README.md

I thought that it would be helpful to mention how one can configure kubectl to access cluster from outside machine.

Added info about accessing cluster from outside

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go

https://github.com/rancher/k3s/issues/93

Actually pass cluster-cidr on to server

---

pkg/daemons/control/server.go

Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>

make the controller-manager and scheduler usable

---

README.md
install.sh
k3s.service
pkg/cli/server/server.go

This reverts commit c73e9187bb5ffcf251cbbdcdb4e11c104eeffc69.

Revert "Enable systemd ready notification for k3s server"

---

README.md
pkg/agent/containerd/containerd.go

- Move the preload images code into a function
- Simplify code
- Enhance logs

refactor: creates preloadImages function.

---

README.md
install.sh

Modify the install script to allow defining arbitrary service names and
commands for k3s.
For rancher/k3s/issues/65

Allow agent install

---

pkg/deploy/controller.go

See issue #222, we need to silently ignore empty yaml objects.

Do not process empty yaml objects (fixes #222)

---

scripts/package-cli

https://github.com/rancher/k3s/issues/203

Fix version for cli

---

install.sh

Set the selinux context during the install

---

docker-compose.yml

Adjust the startup order of node and server, server service should be started at first.

Adjust the startup order of docker-compose

---

pkg/cli/cmds/agent.go
scripts/ci
scripts/package-cli
types/apis/apps/v1/zz_generated_deployment_controller.go
types/apis/apps/v1/zz_generated_deployment_lifecycle_adapter.go
types/apis/batch/v1/zz_generated_job_controller.go
types/apis/batch/v1/zz_generated_job_lifecycle_adapter.go
types/apis/core/v1/zz_generated_config_map_controller.go
types/apis/core/v1/zz_generated_config_map_lifecycle_adapter.go
types/apis/core/v1/zz_generated_endpoints_controller.go
types/apis/core/v1/zz_generated_endpoints_lifecycle_adapter.go
types/apis/core/v1/zz_generated_node_controller.go
types/apis/core/v1/zz_generated_node_lifecycle_adapter.go
types/apis/core/v1/zz_generated_pod_controller.go
types/apis/core/v1/zz_generated_pod_lifecycle_adapter.go
types/apis/core/v1/zz_generated_service_account_controller.go
types/apis/core/v1/zz_generated_service_account_lifecycle_adapter.go
types/apis/core/v1/zz_generated_service_controller.go
types/apis/core/v1/zz_generated_service_lifecycle_adapter.go
types/apis/rbac.authorization.k8s.io/v1/zz_generated_cluster_role_binding_controller.go
types/apis/rbac.authorization.k8s.io/v1/zz_generated_cluster_role_binding_lifecycle_adapter.go

Fix build validation check, move downloads to CI, fix formatting error,
and add generated data for git status check.

Re-enable build validation

---

README.md

Add more details about using HelmChart resource

---

README.md

Add information on /etc/hosts hostname requirement.
For rancher/k3s/issues/138

Update README for hostname req

---

README.md
docker-compose-agent.yml
docker-compose.yml

Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>

update docker image to new version v0.3.0

---

pkg/daemons/control/server.go

https://github.com/rancher/k3s/issues/281

Change address to bind-address for scheduler and controller-manager

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/server/server.go
vendor.conf
vendor/github.com/rancher/norman/pkg/dynamiclistener/server.go
vendor/github.com/rancher/norman/pkg/dynamiclistener/types.go
vendor/github.com/rancher/norman/pkg/resolvehome/home.go

https://github.com/rancher/k3s/issues/214#issuecomment-478015268
Depends on https://github.com/ibuildthecloud/norman/pull/1

Add bind address server config

---

pkg/agent/config/config.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go

https://github.com/rancher/k3s/issues/290

Add extra flags for server and agent components

---

pkg/cli/cmds/server.go

https://github.com/rancher/k3s/pull/289#pullrequestreview-225849971

Fix usage of bind address flag

---

recipes/metrics-server/auth-delegator.yaml
recipes/metrics-server/auth-reader.yaml
recipes/metrics-server/metrics-apiservice.yaml
recipes/metrics-server/metrics-server-deployment.yaml

Use the latest apiVersion in k8s-v1.14.x

Use the latest apiVersion in k8s-v1.14.x

---

pkg/kubelet/apis/config/validation/validation.go

Revert "Fix kubelet --enforce-node-allocatable validation"

---

pkg/daemons/agent/agent.go
trash.lock
vendor.conf
vendor/k8s.io/client-go/pkg/version/base.go
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/pkg/kubelet/client/kubelet_client.go
vendor/k8s.io/kubernetes/pkg/version/base.go

If cgroup pids are not supported add a feature-gates flag
SupportPodPidsLimit=false for kubelet. Also set cgroups-per-qos 
to false and enforce-node-allocatable to none.
For rancher/k3s/issues/335

Check for cgroup pids support

---

pkg/deploy/controller.go

https://github.com/rancher/k3s/issues/280

Skip any file with no yaml yml or json suffix

---

pkg/helm/controller.go

https://github.com/rancher/k3s/issues/308

Add proxy env to helm controller

---

pkg/daemons/config/types.go

https://github.com/rancher/k3s/issues/343

Fix extra argument with multiple =

---

README.md
k3s.service
pkg/agent/syssetup/setup.go

Fix https://github.com/rancher/k3s/issues/364

🔧 modprobe nf_conntrack

---

README.md

https://github.com/rancher/k3s/issues/332

Add extra args documentation

---

install.sh

For https://github.com/rancher/k3s/commit/fa673468cefbf38f3b46ddbae58ebfc7cc60b806#commitcomment-33330902

Fix systemd install not starting

---

README.md
contrib/ansible/roles/k3s/master/templates/k3s.service.j2
contrib/ansible/roles/k3s/node/templates/k3s.service.j2
install.sh
k3s.service

https://github.com/rancher/k3s/issues/367

Change systemd unit file target to network-online.target

---

install.sh

Provides a `k3s-killall.sh` script on install for cleaning up all running k3s services, 
containers, mounts, and network devices.

Add k3s-killall.sh script to installer

---

pkg/agent/config/config.go

https://github.com/rancher/k3s/issues/321

Check if hostname is resolvable before running agent

---

pkg/cli/server/server.go

https://github.com/rancher/k3s/issues/79

Change the stderr threshold for cli

---

pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go

https://github.com/rancher/k3s/issues/255
https://github.com/rancher/k3s/issues/323

Add cni plugin to kubelet if docker is used

---

cmd/k3s/main.go
scripts/download

Use host's mount binary before packaged busybox binary

---

pkg/agent/config/config.go
pkg/agent/run.go

https://github.com/rancher/k3s/issues/321

Add timeout to hostname check

---

pkg/daemons/control/server.go

Force upgrade of token node cert

---

pkg/helm/controller.go
pkg/server/server.go

Add no_proxy env to server 

---

package/Dockerfile
scripts/sonobuoy
scripts/sonobuoy-e2e-tests

Fix issue with killing cleanup on interupt
Use docker cp for copying kubeconfig
Add passed/failed status to log names
Fix docker image path for /bin/aux/mount

 Add e2e enhancements

---

README.md

https://github.com/rancher/k3s/issues/363

Upgrade docs

---

README.md

https://github.com/rancher/k3s/issues/331

Update README with containerd template

---

docker-compose-agent.yml
docker-compose.yml

The sample docker-compose yaml documents should use the latest version
Signed-off-by: Carson Anderson <ca@carsonoid.net>

Update docker-compose files to use 0.5.0

---

pkg/kubectl/main.go
pkg/server/server.go

https://github.com/rancher/k3s/issues/389

change permissions of kubeconfig and issue warning with kubectl wrapper

---

pkg/server/server.go

https://github.com/rancher/k3s/issues/378

Create symlink for kubeconfig when --write-kubeconfig is selected

---

pkg/cli/server/server.go

https://github.com/rancher/k3s/issues/411

Check if server time before 1/1/1970

---

README.md
pkg/agent/config/config.go
pkg/cli/agent/agent.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go

https://github.com/rancher/k3s/issues/379
https://github.com/rancher/k3s/issues/394

Expose node labels and taints and add node roles

---

README.md
contrib/ansible/roles/k3s/master/templates/k3s.service.j2
contrib/ansible/roles/k3s/node/templates/k3s.service.j2
install.sh
k3s.service

https://github.com/rancher/k3s/issues/420

Add Restart=always to systemd unit

---

README.md

Update README for air-gap upgrade

---

install.sh

Quote installer arguments

---

pkg/server/server.go
pkg/servicelb/controller.go

https://github.com/rancher/k3s/issues/542

stop service update when disable svclb flag is passed

---

README.md

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

README.md: fix rootless description

---

pkg/server/server.go
trash.lock
vendor.conf
vendor/github.com/rancher/helm-controller/pkg/helm/controller.go

Add missing ConfigMap cache to helm apply

---

README.md

Update README for Metrics-Server info

---

cmd/ctr/main.go
cmd/k3s/main.go
cmd/server/main.go
pkg/cli/ctr/ctr.go
pkg/ctr/main.go
scripts/build

Build & enable ctr with k3s server

---

pkg/agent/tunnel/tunnel.go
trash.lock
vendor.conf
vendor/github.com/rancher/remotedialer/client.go
vendor/github.com/rancher/remotedialer/peer.go
vendor/github.com/rancher/remotedialer/server.go
vendor/github.com/rancher/remotedialer/session.go

Improve logging and fix stuck ping errors

Cleanup tunnel

---

pkg/cli/agent/agent.go
pkg/cli/server/server.go

Update agent to notify systemd

---

install.sh

Adds INSTALL_K3S_SYMLINK which can be set to 'skip' or 'force',
default is not to symlink if already in path.
For #622 & #521

Install script symlink update

---

pkg/server/server.go

We no longer make dynamiclistener generate CA certs.

Simplify startWrangler a bit

---

pkg/agent/loadbalancer/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
trash.lock
vendor.conf
vendor/github.com/google/tcpproxy/.gitignore
vendor/github.com/google/tcpproxy/.travis.yml
vendor/github.com/google/tcpproxy/CONTRIBUTING.md
vendor/github.com/google/tcpproxy/LICENSE
vendor/github.com/google/tcpproxy/README.md
vendor/github.com/google/tcpproxy/http.go
vendor/github.com/google/tcpproxy/listener.go
vendor/github.com/google/tcpproxy/sni.go
vendor/github.com/google/tcpproxy/tcpproxy.go

Add built-in load balancing proxy for failing over agents to
multiple masters in an HA environment.

Add go load-balancing proxy

---

pkg/node/controller.go

Fix panic in node controller

---

pkg/daemons/control/server.go

Add --kubelet-certificate-authority flag

---

pkg/cli/agent/agent.go
pkg/cli/server/server.go
pkg/server/server.go

https://github.com/rancher/k3s/issues/842
The PR now just adds the master role label on server startup

Add master role label to server node at startup

---

go.mod
go.sum
pkg/daemons/control/server.go
vendor/github.com/rancher/dynamiclistener/cert/io.go
vendor/modules.txt

https://github.com/rancher/k3s/issues/804

Certificate Rotation

---

scripts/build

Separate version flags and build CNI plugins in a temp directory.

Cleanup build script

---

pkg/server/server.go

https://github.com/rancher/k3s/issues/895

Fix Master label in HA setups

---

pkg/agent/config/config.go

Use default kubelet directory

---

pkg/agent/flannel/setup.go

Fallback to /etc/strongswan for config

---

go.mod
pkg/agent/config/config.go
pkg/agent/netpol/network_policy.go
pkg/agent/netpol/network_policy_controller.go
pkg/agent/netpol/utils.go
pkg/agent/run.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/config/types.go

For #640
Needs prometheus metrics reporting for future enhancement?

Add network policy support

---

install.sh

Write proxy settings into FILE_K3S_ENV on install. This should address #627

inherit proxy from ENV on install

---

pkg/agent/templates/templates.go

Remove trailing whitespace trimming from containerd template

---

pkg/servicelb/controller.go
scripts/airgap/image-list.txt

Bump the version of klipper-lb to use the latest that will try to setup ip_forward

Bump klipper-lb version

---

Dockerfile.dapper
Dockerfile.sonobuoy.dapper

Downgrade go to v1.13.2

---

install.sh
pkg/cli/cmds/server.go

Hide the --disable-agent flag

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go

Fix https://github.com/rancher/k3s/issues/784
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

rootless: add kubelet flags automatically

---

Dockerfile.dapper
Dockerfile.sonobuoy.dapper

Downgrade build go to v1.12.12

---

.drone.yml
scripts/sonobuoy
scripts/sonobuoy-e2e-tests

Enable tests for arm

---

docker-compose.yml

Just noticed the versions were not recent  :smile:

update image to v0.10.0 in docker-compose.yml

---

install.sh

Move command with line continuations to bottom of service file to
prevent including systemd directives.
Changes After network-online to Wants network-online for air-gap.

Cleanup systemd service file

---

pkg/cli/server/server.go

The recent setMasterRoleLabel stuff uses it.

Propagate DisableAgent flag

---

go.mod
go.sum
vendor/github.com/containerd/cri/pkg/server/image_pull.go
vendor/modules.txt

Bump cri to include local http registry fix

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/generic/generic.go
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go
vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go
vendor/github.com/rancher/kine/pkg/server/watch.go
vendor/modules.txt

Fix broken mysql and performance issues.

kine v0.1.1

---

pkg/daemons/control/server.go

Work-around issue #970 by waiting for apiserver to be up and running before continuing starting the rest of k3s.

Wait for api-server to report version after starting

---

go.mod
go.sum
pkg/cli/cmds/server.go
pkg/daemons/control/server.go
pkg/server/server.go
vendor/github.com/rancher/dynamiclistener/redirect.go
vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go
vendor/modules.txt

Fix server join issues

---

.drone.yml
Dockerfile.sonobuoy.dapper
scripts/log-upload
scripts/sonobuoy
scripts/sonobuoy-e2e-tests
scripts/test-helpers

On failure provide a link for downloading logs.

Upload logs to gcloud

---

cmd/k3s/main.go
contrib/util/check-config.sh
pkg/cli/cmds/check-config.go
scripts/package-cli
scripts/sonobuoy

Add check-config for system validation

---

install.sh

The install script uses `semanage` which is not present in a default minimal CentOS/RHEL 8 installation. The current check for `semanage` is placed just before the utility is called in `setup_binary`. 
When running the installer a second time -- after installing `semanage` -- the part that adjusts the selinux labels is not executed because the binary was already downloaded and has the correct hash. 
This would resolve #837.

Verify selinux status before downloading

---

docker-compose.yml

Updates the images in the `docker-compose.yml` file to use the `v1.0.0` tags.

Update Docker Compose file to use v1.0.0 image versions

---

Dockerfile.dapper

Addresses https://github.com/rancher/k3s/issues/1155

Bump dqlite to support arm 32-bit

---

pkg/servicelb/controller.go

Allow udp protocol for service-lb ports

---

pkg/cli/cmds/server.go

Cleanup --flannel-backend help text

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/agent/templates/templates.go
pkg/cli/cmds/agent.go
pkg/daemons/agent/agent.go

Allow --pause-image to set docker sandbox image also

---

pkg/agent/flannel/setup.go

Set Wireguard keepalive to 25 seconds

---

scripts/airgap/image-list.txt

Fix https://github.com/rancher/k3s/issues/1232.

Update klipper-helm images to v0.2.2

---

.drone.yml
Dockerfile.manifest
scripts/manifest

Munge + to - for drone tags and manifest publish.

Update manifest publish

---

Dockerfile.dapper
go.mod
go.sum
vendor/github.com/canonical/go-dqlite/.dir-locals.el
vendor/github.com/canonical/go-dqlite/.travis.yml
vendor/github.com/canonical/go-dqlite/client/client.go
vendor/github.com/canonical/go-dqlite/client/constants.go
vendor/github.com/canonical/go-dqlite/client/store.go
vendor/github.com/canonical/go-dqlite/driver/driver.go
vendor/github.com/canonical/go-dqlite/internal/bindings/server.go
vendor/github.com/canonical/go-dqlite/internal/protocol/constants.go
vendor/github.com/canonical/go-dqlite/internal/protocol/message.go
vendor/github.com/canonical/go-dqlite/internal/protocol/request.go
vendor/github.com/canonical/go-dqlite/internal/protocol/response.go
vendor/github.com/canonical/go-dqlite/internal/protocol/schema.go
vendor/github.com/canonical/go-dqlite/internal/protocol/store.go
vendor/modules.txt

Should resolve rancher/k3s#1283

Update dqlite to 1.3.1-r1

---

pkg/daemons/control/tunnel.go

If you want to run a custom kubelet, or something like virtual kubelet, the kubelet will not support the k3s tunnel.  This change makes it so that if we can't find a tunnel session for the kubelet we fall back to the native dialer.

If tunnel session does not exist fallback to default dialer

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/config/types.go
pkg/deploy/controller.go
pkg/deploy/stage.go
pkg/server/server.go

Similar to --no-deploy, but deletes any currently deployed components.

Add --disable flag

---

scripts/vagrant-provision

Remove cgroup provision from dev vagrant script

---

scripts/manifest

Create a latest tag in docker hub for new releases (release-1.17 branch)

---

scripts/manifest

Create a latest tag in docker hub for new releases

---

pkg/agent/config/config.go

Use default kubelet device-plugins path

---

pkg/agent/config/config.go

Use default kubelet device-plugins path (release-1.17 branch) 

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/generic/generic.go
vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go
vendor/modules.txt

In HA the compaction in kine will get stuck.  This change fixes
and also fixes the corrupt data.

Fix kine HA compaction

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/generic/generic.go
vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go
vendor/modules.txt

In HA the compaction in kine will get stuck.  This change fixes
and also fixes the corrupt data.

Fix kine HA compaction (release-1.17 branch)

---

scripts/version.sh

Add 'k3s' to kubernetes version metadata in dev builds

---

.drone.yml
scripts/dispatch

Sorry had to open a new PR with a new branch, I had too many conflicts with the old one
https://github.com/rancher/k3s/issues/1408

Send dispatch event with drone

---

contrib/ansible/roles/k3s/master/templates/k3s.service.j2
contrib/ansible/roles/k3s/node/templates/k3s.service.j2

Add Type/TimeoutStartSec/ExecStartPre to ansible systemd unit files similar to ones created by `install.sh`

Ansible systemd unit file similar to install.sh

---

.drone.yml

Only publish rpm on tag

---

pkg/nodeconfig/nodeconfig.go

https://github.com/rancher/k3s/issues/1524

Add asterisks for omitted values in nodeconfig

---

pkg/nodeconfig/nodeconfig.go

https://github.com/rancher/k3s/issues/1524

[release-1.17] Backport add asterisk

---

go.mod
go.sum
vendor/github.com/containerd/cri/pkg/containerd/opts/spec.go
vendor/modules.txt

Bump cri to 1.3.0-k3s.5

---

install.sh
package/rpm/install.sh

GitHub now returns lowercase:
wget -SqO /dev/null https://github.com/rancher/k3s/releases/latest |& grep -i location
location: https://github.com/rancher/k3s/releases/tag/v1.17.3+k3s1

Fix error when get version using Wget

---

contrib/ansible/reset.yml
contrib/ansible/roles/reset/tasks/main.yml

Signed-off-by: Julien DOCHE <julien.doche@gmail.com>

contrib/ansible: Add reset role and playbook to reset a node

---

install.sh

Check for k3s policy and provide install hints

---

channel.yaml

Add channel yaml to k3s

---

install.sh

Use channel server for install script

---

pkg/deploy/controller.go

Check modification time before deploying manifests

---

pkg/rootlessports/controller_windows.go

Fixes the build caused by rootlessports interface change
related to https://github.com/rancher/k3s/issues/1486

fix build windows v1.18

---

go.mod
go.sum
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/modules.txt

Bump cri to 1.3.0-k3s6

---

pkg/cli/cmds/log.go

This makes it a bit easier to embed k3s into another go program.

Allow InitLogging to be called twice

---

pkg/agent/containerd/containerd.go

In the agent/images folder if a .txt file is found it is assumed to
be a line separated list of image names to pull on start.

Support prepulling images on start

---

pkg/cli/server/server.go

The default CipherSuites need to be set to disable the insecure TLS 1.2 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 Cipher
Issue #1741 
Previous Pull Request #1765 
This request will set the default CipherSuite if it is not set via the CLI.

Feature Request #1741: Update to set default CipherSuites

---

scripts/version.sh

Updating the version of the CNI Plugin to v0.8.6-k3s1.

update CNI to v0.8.6-k3s1

---

pkg/server/server.go

Adding this configmap to expose the cluster dns ip and the cluster domain to be used

Add cluster dns configmap

---

CONTRIBUTING.md

Small fixes to the contributing doc.

Update Contribution Doc

---

pkg/servicelb/controller.go

noderole.kubernetes.io/master -> node-role.kubernetes.io/master

servicelb: fix ineffective toleration

---

pkg/daemons/control/server.go

This PR is for the same purpose of #1896 . I missed it in the first PR though.

add profiling flag with default value of false

---

Dockerfile.test.dapper

This should resolve the warnings described in #1999

Update sonobuoy version for k8s 1.18 support

---

.drone.yml

Fix CI dispatch failure due to incorrect secret name

---

scripts/download

Update k3s-root to pull in updated slirp4netns

---

go.mod
go.sum
pkg/cli/agent/agent.go
pkg/cli/server/server.go
pkg/nodeconfig/nodeconfig.go
vendor/github.com/erikdubbelboer/gspt/.travis.yml
vendor/github.com/erikdubbelboer/gspt/LICENSE
vendor/github.com/erikdubbelboer/gspt/README.md
vendor/github.com/erikdubbelboer/gspt/gspt.go
vendor/github.com/erikdubbelboer/gspt/setproctitle.h
vendor/modules.txt

Call setproctitle to conceal node args in ps output

---

.github/PULL_REQUEST_TEMPLATE.md
BUILDING.md

======
Adds a template for pull request submitters to fill out providing additional insights into the change, and linking to a related issue.
======
New feature for pull requests. 
Verification
======
This PR is in the specified format. Once merged, this template will appear in a new pull request
Linked Issues
======
N/A
======
N/A

add pull request template

---

install.sh

======
Fix /run cleanup 
======
install script
Verification
======
See steps in linked issue 
Linked Issues
======
rancher/k3s#2102
======
Should have caught this before merging rancher/k3s#1614

Fix removal of /run directories

---

Dockerfile.dapper
Dockerfile.manifest
Dockerfile.test.dapper

- https://github.com/golang/go/issues?q=milestone%3AGo1.13.15+label%3ACherryPickApproved

golang: 1.13.15

---

pkg/cli/cmds/config.go

======
Rename flags.conf to config.yaml
======
- cli
Verification
======
`k3s server --help`
Linked Issues
======
Related to https://github.com/rancher/rke2/issues/150

Rename flags.conf to config.yaml

---

pkg/cli/cmds/server.go
pkg/server/server.go
pkg/server/types.go

======
Adjusted arguments to StartupHook functions to not require the k8s dependency which carries in a lot of unnecessary and bloating code.
======
Verification
======
```sk
SKIP_VALIDATE=true make
ls -ltra dist/artifacts/k3s
-rwxr-xr-x  1 bdowns  staff  53428224 Sep  4 09:19 dist/artifacts/k3s
```
Linked Issues
======
#2205 
======
N/A

Remove k8s Import to Shrink Binary

---

pkg/agent/config/config.go
pkg/server/router.go

======
Add node IP to header for inclusion in certificate generation.
======
Update function signatures to pass around node IP to where it's necessary.
Verification
======
Use openssl to view the generated certificate to see the additional IP(s).
Linked Issues
======
https://github.com/rancher/rke2/issues/112
======

add node ip to the request header for cert gen

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the PR template to match the one we adopted for RKE2. This PR uses the new template.
- GH PR Template
N/A
N/A
Credit to @briandowns for the original text.

Update PR template to match RKE2

---

channel.yaml

Add 1.19 to channel.yaml
* Channel
* Install k3s from script using channel option
part of #2264
This will cause 1.19.* releases to be aggregated into a v1.19 channel on https://update.k3s.io/v1-release/channels

Add 1.19 to channel.yaml

---

Dockerfile.dapper
Makefile
scripts/image_scan.sh
scripts/package-image

Add a step in the build process to scan a k3s image by Trivvy to detect any security flaws.
rancher/k3s#2106

Add Trivy Scans for Built Images

---

pkg/agent/config/config.go
pkg/agent/containerd/containerd.go
pkg/agent/flannel/setup.go
pkg/agent/proxy/apiproxy.go
pkg/agent/run.go
pkg/agent/syssetup/setup.go
pkg/agent/tunnel/tunnel.go
pkg/cli/agent/agent.go
pkg/cli/server/server.go
pkg/cloudprovider/instances.go
pkg/cluster/managed.go
pkg/deploy/controller.go
pkg/etcd/etcd.go
pkg/netutil/iface.go
pkg/node/controller.go
pkg/rootlessports/controller.go
pkg/server/auth.go
pkg/server/server.go

This attempts to update logging statements to make them consistent
thoughtout the code base. It also adds additional context to messages
where possible, simplifies messages, and updates level where necessary.
https://github.com/rancher/rke2/issues/317

Initial Logging Output Update

---

cmd/k3s/main.go
pkg/dataverify/dataverify.go
pkg/flock/flock_other.go
pkg/flock/flock_unix.go

Add data directory file lock and verify extracted data
Bugfix
```sh
rm -rf /var/lib/rancher/k3s/data/
for i in $(seq 1 10); do 
k3s check-config >/dev/null & 
done
wait
```
#1938

Fix race condition in data extraction

---

pkg/agent/netpol/network_policy_controller.go
pkg/agent/netpol/utils.go

Add network policy event handlers
Bugfix
Time network policy enforcement
#947
The event handlers were missing when initially importing code from kube-router, this probably won't eliminate a policy enforcement delay but will hopefully help reduce it.

Add event handlers to network policy controller

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/dqlite/dqlite.go
vendor/github.com/rancher/kine/pkg/drivers/dqlite/no_dqlite.go
vendor/github.com/rancher/kine/pkg/drivers/generic/generic.go
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/drivers/pgsql/pgsql.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite_nocgo.go
vendor/github.com/rancher/kine/pkg/endpoint/endpoint.go
vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go
vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go
vendor/github.com/rancher/kine/pkg/server/watch.go
vendor/modules.txt

Updates k3s with the latest version of kine which replaces debug with trace to quiet the k3s log output when in debug.
Run in debug and verify no kine debug output is seen.
#831

Update kine to v0.4.1

---

pkg/etcd/etcd.go

- skip etcd member remove fir the removed node itself
- check for member not found error to handle multiple nodes deleting the same member
bug fix
https://github.com/rancher/rke2/issues/401

skip node delete from removed member

---

.drone.yml

Disable RPM publishing for k3s-server and k3s-agent
Drone pipeline changes
Do multiple releases and see if you run into a race condition
https://github.com/rancher/k3s/issues/2440

Disable RPM publishing 

---

.drone.yml

Backport of https://github.com/rancher/k3s/pull/2441 -- Disable RPM publishing for k3s-server and k3s-agent
Drone pipeline changes
Do multiple releases and see if you run into a race condition
https://github.com/rancher/k3s/issues/2440

[1.17 Backport] Disable RPM publishing

---

.drone.yml

Backport of https://github.com/rancher/k3s/pull/2441 -- Disable RPM publishing for k3s-server and k3s-agent
Drone pipeline changes
Do multiple releases and see if you run into a race condition
https://github.com/rancher/k3s/issues/2440

[1.18 Backport] Disable RPM publishing

---

install.sh
package/rpm/install.sh

Remove duplicate systemd directive in install scripts
Chore, not a bug or feature. This was probably added inadvertently. I discovered this while translating the the unit files for chef cookbook

(chore)remove duplicate systemd directives

---

install.sh

Add additional logic into the install_selinux function to specifically look for `7.x` or `8.x`. This will effectively gate out other operating systems that are not RHEL/CentOS 7 or 8
Additionally, add `$SUDO` in front of all of the `yum` commands to ensure that we are able to execute this script as a non-privileged user.
`install.sh`
Run this iteration of the `install.sh` script on
CentOS 7
CentOS 8
RHEL 7
RHEL 8
Fedora 33
All should work and have auto-installed SELinux RPMs except Fedora.
https://github.com/rancher/k3s/issues/2451
https://github.com/rancher/k3s/issues/2452
https://github.com/rancher/k3s/issues/2454

Support k3s-selinux rpm install more effectively

---

install.sh

Backport of: https://github.com/rancher/k3s/pull/2456
Add additional logic into the install_selinux function to specifically look for `7.x` or `8.x`. This will effectively gate out other operating systems that are not RHEL/CentOS 7 or 8
Additionally, add `$SUDO` in front of all of the `yum` commands to ensure that we are able to execute this script as a non-privileged user.
`install.sh`
Run this iteration of the `install.sh` script on
CentOS 7
CentOS 8
RHEL 7
RHEL 8
Fedora 33
All should work and have auto-installed SELinux RPMs except Fedora.
https://github.com/rancher/k3s/issues/2451
https://github.com/rancher/k3s/issues/2452
https://github.com/rancher/k3s/issues/2454

[1.19 Backport] Support k3s-selinux rpm install more effectively

---

go.mod
go.sum
vendor/github.com/containerd/cri/Makefile
vendor/github.com/containerd/cri/cri.go
vendor/github.com/containerd/cri/pkg/config/config.go
vendor/github.com/containerd/cri/pkg/seccomp/seccomp_linux.go
vendor/github.com/containerd/cri/pkg/seccomp/seccomp_unsupported.go
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_remove.go
vendor/github.com/containerd/cri/pkg/server/events.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/image_pull.go
vendor/github.com/containerd/cri/pkg/server/restart.go
vendor/github.com/containerd/cri/pkg/server/sandbox_remove.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/pkg/server/service.go
vendor/github.com/containerd/cri/pkg/store/container/status.go
vendor/github.com/containerd/cri/vendor.conf
vendor/modules.txt

backport #2478 to 1.18
backport of selinux fix
see #2240 for replication
#2240 
see https://github.com/rancher/cri/pull/7

[1.18 Backport] cri: pull on fix for selinux relabel of /dev/shm

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/drivers/pgsql/pgsql.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite.go
vendor/modules.txt

Update kine to v0.5.1
* kine
See test steps from rancher/kine#62
rancher/kine#61, rancher/kine#62

Update kine to v0.5.1 for compact fix

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/drivers/pgsql/pgsql.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite.go
vendor/modules.txt

Update kine to v0.5.1
* kine
See test steps from rancher/kine#62
rancher/kine#61, rancher/kine#62

[1.18 backport] Update kine to v0.5.1 for compact fix

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/drivers/pgsql/pgsql.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite.go
vendor/modules.txt

Update kine to v0.5.1
* kine
See test steps from rancher/kine#62
rancher/kine#61, rancher/kine#62

[1.17 backport] Update kine to v0.5.1 for compact fix

---

go.mod
go.sum
vendor/github.com/rancher/kine/pkg/drivers/mysql/mysql.go
vendor/github.com/rancher/kine/pkg/drivers/pgsql/pgsql.go
vendor/github.com/rancher/kine/pkg/drivers/sqlite/sqlite.go
vendor/modules.txt

Update kine to v0.5.1
* kine
See test steps from rancher/kine#62
rancher/kine#61, rancher/kine#62

[1.19 backport] Update kine to v0.5.1 for compact fix

---

channel.yaml

Update channel.yaml to mark v1.19.3+k3s3 as the stable release.
Urgent update to channel.yaml (refer to incoming v1.19.3+k3s3 release notes)
simply run `curl -sfL https://get.k3s.io | sh -` as the install.sh script defaults to the stable channel. This should pull down v1.19.3+k3s3. Please note it can take about 15 mins for https://update.k3s.io/v1-release/channels to update.
This PR is for https://github.com/rancher/k3s/issues/2521

Update stable channel to v1.19.3+k3s3

---

install.sh

Enhance install.sh to help with k3s upgrade and uninstall scenarios for k3s-selinux
https://github.com/rancher/k3s/issues/2517
https://github.com/rancher/k3s/issues/2518
Signed-off-by: Chris Kim <oats87g@gmail.com>

Enhance install.sh to help with k3s upgrade and uninstall scenarios

---

MAINTAINERS

Add Chris Kim to the list of maintainers for K3s
`MAINTAINERS`
N/A
N/A

Add Oats87 (Chris Kim) to the list of maintainers for K3s

---

MAINTAINERS

Signed-off-by: David Nuzik <david.nuzik@rancher.com>
Add David Nuzik to the list of maintainers for K3s
`MAINTAINERS`
N/A
N/A

Add davidnuzik (David Nuzik) to the list of maintainers

---

go.mod
go.sum
vendor/modules.txt

rancher/etcd :arrow_right: k3s-io/etcd
Part of https://github.com/rancher/k3s/issues/2189

[migration k3s-io] update etcd replace directive

---

pkg/rootless/rootless.go

Validate sysctl before starting up.
BugFix
```console
$ sudo sysctl kernel.dmesg_restrict=1
$ k3s server --rootless
FATA[2020-11-24T18:51:24.567157326+09:00] expected sysctl value "kernel.dmesg_restrict" to be "0", got "1"; try adding "kernel.dmesg_restrict=0" to /etc/sysctl.conf and running `sudo sysctl --system` 
```
Fix #2420

rootless: validate sysctl before starting up

---

pkg/cli/cmds/root.go

Show go version when executes with --version.
```
k3s version v1.19.4+k3s-95ea0e16 (95ea0e16)
go version go1.15.2
```
Enhancement
```
k3s --version
k3s-agent --version
k3s-server --version
```
https://github.com/rancher/rke2/pull/558#pullrequestreview-544621458

Show go version when executes with --version.

---

.drone.yml

[migration k3s-io] drone: initial move to k3s-io

---

.drone.yml

[migration k3s-io][release-1.19] drone: initial move to k3s-io

---

.drone.yml

[migration k3s-io][release-1.18] drone: initial move to k3s-io

---

.drone.yml

[migration k3s-io][release-1.17] drone: initial move to k3s-io

---

install.sh

Fix alternate bindir logic for #2551
install script
Install from get.k3s.io
#2551
Should have actually tested this community PR as opposed to just looking at it.

Fix alternate bindir logic for install.sh

---

pkg/daemons/agent/agent.go

Backport of https://github.com/k3s-io/k3s/pull/2642
https://github.com/k3s-io/k3s/issues/2548

[Backport 1.19] Set a cgroup if containerized

---

pkg/daemons/agent/agent.go

When there is a defined cgroup for PID 1, assume we are containerized and set a root
Set `--kubelet-cgroups` and `--runtime-cgroups` on the `kubelet` only if we think we are containerized and running with `systemd`.
Bugfix
Run `K3s` on a CentOS 7.8+ system and observe that it starts.
https://github.com/k3s-io/k3s/issues/2548
This specifically examines the cgroup for PID 1, and makes an educated guess as to whether we should set the `--*-cgroups` flags to `/systemd`

Set a cgroup if containerized

---

scripts/test
scripts/test-helpers

Backport test script updates from RKE2
Keep test container cleanup in foreground
Test containers are always removed
n/a

[Release-1.19] Test script cleanup backport from RKE2

---

scripts/test
scripts/test-helpers

Backport test script updates from RKE2
Keep test container cleanup in foreground
Test containers are always removed
n/a

[Release-1.17] Test script cleanup backport from RKE2

---

scripts/test
scripts/test-helpers

Backport test script updates from RKE2
Keep test container cleanup in foreground
Test containers are always removed
n/a

[Release-1.18] Test script cleanup backport from RKE2

---

Dockerfile.dapper
Dockerfile.manifest
Dockerfile.test.dapper

bump Go to version 1.15.5

---

go.mod
go.sum
vendor/go.etcd.io/etcd/etcdserver/api/membership/cluster.go
vendor/go.etcd.io/etcd/etcdserver/errors.go
vendor/modules.txt

https://github.com/k3s-io/k3s/issues/2527

update etcd to fix the panic for etcd tombstone issue

---

go.mod
go.sum
vendor/go.etcd.io/etcd/etcdserver/api/membership/cluster.go
vendor/go.etcd.io/etcd/etcdserver/errors.go
vendor/go.etcd.io/etcd/etcdserver/server.go
vendor/modules.txt

https://github.com/k3s-io/k3s/issues/2527

[Backport 1.19] update etcd to fix the panic for etcd tombstone issue (#2658)

---

CODEOWNERS

Update CODEOWNERS for k3s-io move
Housekeeping
* Open a PR
* Note that k3s-dev group is added as a reviewer
#2189

Update CODEOWNERS for k3s-io move

---

scripts/dispatch

fix the k3s-upgrade dispatch

---

scripts/dispatch

[release-1.19] k3s-upgrage dispatch k3s-io

---

scripts/dispatch

[release-1.18] k3s-upgrage dispatch k3s-io

---

scripts/dispatch

[release-1.17] k3s-upgrage dispatch k3s-io

---

channel.yaml

Updates channel server version.
#2685

update stable version

---

pkg/server/router.go
pkg/server/server.go

Fix HA server initialization
Bugfix
HA server testing matrix (including HA server 1.19 -> 1.20 upgrade with this change)
#2665
Will add HA etcd tests in another PR

Fix HA server initialization

---

scripts/test-helpers

Wait longer for sonobuoy tests to start up
CI
#2713

Wait longer for sonobuoy tests to start up

---

channel.yaml

Change stable version to v1.19.5+k3s2

mark v1.19.5+k3s2 as stable

---

scripts/download

Pull Traefik helm chart from new stable charts repository
* CI
* Packaged components
* Build K3s
* Note that it succeeds
#2734

Pull Traefik helm chart from new stable charts repository

---

scripts/download

Pull Traefik helm chart from new stable charts repository
* CI
* Packaged components
* Build K3s
* Note that it succeeds
#2734

[Release-1.19] Pull Traefik helm chart from new stable charts repository

---

scripts/download

Pull Traefik helm chart from new stable charts repository
* CI
* Packaged components
* Build K3s
* Note that it succeeds
#2734

[Release-1.18] Pull Traefik helm chart from new stable charts repository

---

scripts/download

Pull Traefik helm chart from new stable charts repository
* CI
* Packaged components
* Build K3s
* Note that it succeeds
#2734

[Release-1.17] Pull Traefik helm chart from new stable charts repository

---

channel.yaml

Add v1.20 channel and mark as stable
* Channel server
* Install K3s using install script
* Note that v1.20 is installed
#2707

Add v1.20 channel and mark as stable

---

contrib/util/DIAGNOSTICS.md
contrib/util/diagnostics.sh
contrib/util/fetch-diags.sh

Add script for collecting diagnostics.
New Feature
tbd
#2461

Add diagnostics collection

---

pkg/etcd/etcd.go

change the permission of etcd dir if it exists after upgrades
```
sudo ls -ld /var/lib/rancher/k3s/server/db/etcd
```

change etcd dir permission if it exists

---

pkg/etcd/etcd.go

Fix typo in field tag
Bugfix
N/A (no user facing change)
#2826

Fix typo in field tag

---

scripts/download

Update k3s-root to v0.7.3
* k3s-root
* rootless
Related to #2817 and k3s-io/k3s-root#31

Update k3s-root to v0.7.3

---

go.mod
go.sum
vendor/github.com/containerd/containerd/contrib/apparmor/template.go
vendor/github.com/google/go-cmp/cmp/compare.go
vendor/github.com/google/go-cmp/cmp/export_panic.go
vendor/github.com/google/go-cmp/cmp/export_unsafe.go
vendor/github.com/google/go-cmp/cmp/options.go
vendor/github.com/google/go-cmp/cmp/path.go
vendor/modules.txt

Update containerd to fix AppArmor on SLES
* Bugfix
#2778 
containerd/containerd#4467

[release-1.18] Update containerd to fix AppArmor on SLES

---

Vagrantfile
scripts/provision/generic/opensuse15/vagrant

Add opensuse 15 generic provisioning for vagrant
New Dev Feature
`BOX=generic/opensuse15 NUM_NODES=3 vagrant up .2`
N/A - dev use

Add opensuse 15 vagrant provision

---

go.mod
go.sum
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed/drivers.go
pkg/etcd/controller.go
pkg/etcd/etcd.go
vendor/github.com/rancher/dynamiclistener/storage/memory/memory.go
vendor/modules.txt

- Add the ability to register to etcd only nodes with public IPs (dynamic listener fix)
- add systemd support for etcd only nodes
- remove etcd member from etcd cluster if the --disable-etcd is passed
bugfix
https://github.com/k3s-io/k3s/issues/assigned/galal-hussein

Fix etcd only nodes

---

go.mod
go.sum
pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/proxy/apiproxy.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/apiaddresses/controller.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/etcd.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/etcd/controller.go
pkg/etcd/etcd.go
pkg/etcd/etcdproxy.go
pkg/server/etcd.go
pkg/server/server.go
vendor/github.com/rancher/dynamiclistener/storage/memory/memory.go
vendor/modules.txt

Backport etcd only nodes disable flags to 1.20 and add experimental to the flags
Backport Feature
https://github.com/k3s-io/k3s/issues/2635

[release-1.20] Add disable components flags 

---

pkg/cli/cmds/server.go

This PR will mark disable flags for controller manager, api and etcd as experimental

Mark disable components flags as experimental

---

go.mod
go.sum
pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/proxy/apiproxy.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/apiaddresses/controller.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/etcd.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/etcd/controller.go
pkg/etcd/etcd.go
pkg/etcd/etcdproxy.go
pkg/server/etcd.go
pkg/server/server.go
vendor/github.com/rancher/dynamiclistener/storage/memory/memory.go
vendor/modules.txt

Backport disable components flags to 1.19
Hide disable flags in cli
https://github.com/k3s-io/k3s/issues/2635

[release-1.19] Add disable components flags

---

BUILDING.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
MAINTAINERS
README.md
install.sh

1. Docs updates with minor tweaks for URLs/Emails
2. Update GITHUB_URL in install.sh to avoid redirect
Minor docs changes
Minor install.sh change
I tested each change where a URL was updated and the change I made to install.sh to ensure I didn't break anything.
For https://github.com/k3s-io/k3s/issues/2970
These changes are minor, largely to avoid redirects in documentation (rancher/k3s to k3s-io/k3s). I also updated MAINTAINERS emails to point to new suse.com emails. This PR doesn't encompass all references to rancher/k3s - there are areas in code where we might want to change this later. This PR just touches .md files in the root of the project and a small changes to install.sh

Docs housekeeping

---

pkg/cluster/storage.go
pkg/etcd/etcd.go

- backup etcd data dir when etcd is disabled
- check etcd is learner before 
bug fix
https://github.com/k3s-io/k3s/issues/3055

remove etcd data dir when etcd is disabled

---

go.mod
go.sum
vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
vendor/github.com/containerd/containerd/runtime/v2/binary.go
vendor/github.com/containerd/containerd/runtime/v2/manager.go
vendor/github.com/containerd/containerd/runtime/v2/runc/v2/service.go
vendor/github.com/containerd/containerd/runtime/v2/shim.go
vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
vendor/github.com/containerd/containerd/sys/oom_unix.go
vendor/github.com/containerd/containerd/sys/oom_windows.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go
vendor/github.com/containerd/cri/Makefile
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/vendor.conf
vendor/modules.txt

Addresses k3s-io/k3s#3070 and CVE-2021-21334

[release 1.17] containerd: v1.3.10-k3s1

---

go.mod
go.sum
vendor/github.com/containerd/containerd/contrib/apparmor/template.go
vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
vendor/github.com/containerd/containerd/runtime/v2/binary.go
vendor/github.com/containerd/containerd/runtime/v2/manager.go
vendor/github.com/containerd/containerd/runtime/v2/runc/v2/service.go
vendor/github.com/containerd/containerd/runtime/v2/shim.go
vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
vendor/github.com/containerd/containerd/sys/oom_unix.go
vendor/github.com/containerd/containerd/sys/oom_windows.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go
vendor/github.com/containerd/cri/Makefile
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/vendor.conf
vendor/modules.txt

Addresses k3s-io/k3s#3069 and CVE-2021-21334

[release 1.18] containerd: v1.3.10-k3s1

---

pkg/cluster/cluster.go

Puts the save call for bootstrap data into a Go routine when embedded etcd is in use. This allows for etcd to be ready and not stall there resulting in the context deadline firing.

put etcd bootstrap save call in goroutine and update comment

---

pkg/cluster/cluster.go

Fix bootstrap save in 1.19
bug fix
start 2 or more servers with external db

[release-1.19] Fix bootstrap save

---

go.mod
go.sum
vendor/github.com/containerd/containerd/contrib/apparmor/template.go
vendor/modules.txt

Update containerd to fix AppArmor on SLES
* Bugfix
#2778 
containerd/containerd#4467
k3s-io/containerd#14

[release-1.18] Update containerd to fix AppArmor on SLES (again)

---

install.sh

Remove dependency on which binary, use shell internal equivalent.
install script
#3125

Replace which with command -v (#3125)

---

pkg/agent/tunnel/tunnel.go
pkg/apiaddresses/controller.go
pkg/util/api.go

refactor tunnel.go and controller.go, remove duplicated lines.
fix issue #3036
Signed-off-by: Xiao Deshi <xiaods@gmail.com>

remove duplicated func GetAddresses, fix issue #3036

---

channel.yaml

For https://github.com/k3s-io/k3s/issues/2974
channel.yaml change to mark v1.20.5+k3s1 as stable
non-breaking change
Ensure the [endpoint](https://update.k3s.io/v1-release/channels) gets updated roughly 15 mins after CI finishes.

Make v1.20.5+k3s1 stable

---

pkg/cli/cmds/nocluster.go
pkg/cli/cmds/server.go
pkg/cluster/etcd.go

Unhides cluster flags from server subcommand and removes related unused code.
Unhide server subcommand flags.
https://github.com/rancher/rke2/issues/856

remove hidden attribute from cluster flags and related code

---

pkg/nodeconfig/nodeconfig.go

https://github.com/k3s-io/k3s/pull/3180

[Backport 1.19] - add etcd s3 secret and access key flags to secret data

---

pkg/nodeconfig/nodeconfig.go

https://github.com/k3s-io/k3s/pull/3180

[Backport 1.20] - add etcd s3 secret and access key flags to secret data

---

pkg/cli/cmds/server.go

Add hidden attribute to disable flags.
Make sure that the disable-api-server, disable-controller-manager, and disable-etcd flags aren't shown.
```sh
k3s server -h | grep "disable-*"
```

Add hidden attribute to disable flags

---

pkg/cli/cmds/nocluster.go
pkg/cli/cmds/server.go
pkg/cluster/etcd.go

Backport of hidden flags fix.
https://github.com/k3s-io/k3s/pull/3155
#3176

[Backport 1.19] Hidden Flags Bug Fix

---

pkg/cli/cmds/nocluster.go
pkg/cli/cmds/server.go
pkg/cluster/etcd.go

Backport of hidden flags fix.
#3155
#3176

[Backport 1.20] Hidden Flags Bug Fix

---

channel.yaml

mark v1.20.6+k3s1 as stable in channels.yaml
non-breaking change in channels.yaml
Will verify [endpoint](https://update.k3s.io/v1-release/channels) gets updated as per the linked issue. Will ensure a default install indeed installs 1.20.6+k3s1 successfully on a single-node cluster.
For https://github.com/k3s-io/k3s/issues/3150

Mark v1.20.6+k3s1 as stable

---

pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/data.yaml.d/01-data.yml
pkg/configfilearg/testdata/data.yaml.d/02-data.yaml

If key ends in "+" the value of the key is appended to previous
values found.  If values are string instead of a slice they are
automatically converted to a slice of one string.

Add ability to append to slice during config file merge

---

pkg/agent/containerd/containerd.go

retry on creating etcd proxy load balancer, to avoid errors in rke2 when etcd is disabled after being enabled
bug fix
https://github.com/rancher/rke2/issues/886

Export CriConnection function

---

pkg/etcd/etcd.go

Remove previously added struct field and revert to existing env var ref.

Reference node name when needed

---

pkg/cli/cmds/server.go

change --disable-api-server flag to --disable-apiserver to be consistent with other flags
CLI
`k3s --help`
https://github.com/k3s-io/k3s/issues/3170

change --disable-api-server flag to --disable-apiserver

---

pkg/cli/cmds/server.go

change --disable-api-server flag to --disable-apiserver to be consistent with other flags
CLI
`k3s --help`
https://github.com/k3s-io/k3s/issues/3170

[release-1.19]change --disable-api-server flag to --disable-apiserver

---

pkg/cli/cmds/server.go

change --disable-api-server flag to --disable-apiserver to be consistent with other flags
CLI
`k3s --help`
https://github.com/k3s-io/k3s/issues/3170

[release-1.20] change --disable-api-server flag to --disable-apiserver

---

scripts/download

runc: v1.0.0-rc95

---

scripts/download

[backport 1.20] runc: v1.0.0-rc95

---

scripts/download

[backport 1.18] runc: v1.0.0-rc95

---

scripts/download

[backport 1.19] runc: v1.0.0-rc95

---

install.sh

Fix shell expansion and file permission issues install.sh
install script
#3179
rancherlabs/rancher-security#768

Fix shell expansion and file permission issues install.sh

---

scripts/download

[backport 1.21] runc: v1.0.0-rc95 (#3348)

---

channel.yaml

Bump channel stable version to v1.20.7+k3s1

---

go.mod
go.sum
vendor/github.com/containerd/containerd/go.mod
vendor/github.com/containerd/containerd/go.sum
vendor/github.com/containerd/containerd/oci/spec_opts.go
vendor/github.com/containerd/containerd/oci/spec_opts_linux.go
vendor/github.com/containerd/containerd/oci/spec_opts_nonlinux.go
vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
vendor/github.com/containerd/containerd/oci/utils_unix.go
vendor/github.com/containerd/containerd/pkg/cap/cap_linux.go
vendor/github.com/containerd/cri/pkg/cap/cap_linux.go
vendor/github.com/containerd/cri/pkg/containerd/opts/spec_unix.go
vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
vendor/github.com/containerd/cri/pkg/server/service.go
vendor/github.com/containerd/cri/pkg/server/service_unix.go
vendor/modules.txt

Pull in backport of containerd/containerd#5017
Addresses #3296

containerd: v1.4.4-k3s2

---

go.mod
go.sum
vendor/github.com/containerd/containerd/go.mod
vendor/github.com/containerd/containerd/go.sum
vendor/github.com/containerd/containerd/oci/spec_opts.go
vendor/github.com/containerd/containerd/oci/spec_opts_linux.go
vendor/github.com/containerd/containerd/oci/spec_opts_nonlinux.go
vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
vendor/github.com/containerd/containerd/oci/utils_unix.go
vendor/github.com/containerd/containerd/pkg/cap/cap_linux.go
vendor/github.com/containerd/cri/pkg/cap/cap_linux.go
vendor/github.com/containerd/cri/pkg/containerd/opts/spec_unix.go
vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
vendor/github.com/containerd/cri/pkg/server/service.go
vendor/github.com/containerd/cri/pkg/server/service_unix.go
vendor/modules.txt

Pull in backport of containerd/containerd#5017
Addresses #3296

[backport 1.21] containerd: v1.4.4-k3s2

---

pkg/agent/config/config.go
pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/containerd/containerd.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/utility_windows.go
pkg/agent/loadbalancer/utlity_linux.go
pkg/agent/run.go
pkg/agent/syssetup/setup_windows.go
pkg/cgroups/cgroups_linux.go
pkg/cgroups/cgroups_windows.go
pkg/cli/cmds/root.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/containerd/utility_linux.go
pkg/containerd/utility_windows.go
pkg/daemons/agent/agent.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go
pkg/util/errors.go

These changes allow for k3s agent to support being built on Windows.
This is a new feature adding Windows support for the agent.
Builds succeed.
This is in support of adding Windows support. rancher/windows#52
The minimum about of changes were performed to get a successful build working on Windows. We tried to keep the changes as localized as possible.

Initial windows support for agent.

---

.github/workflows/cgroup2.yaml
k3s-rootless.service
tests/cgroup2/.gitignore
tests/cgroup2/Vagrantfile
tests/testutil/wait-for-coredns.sh

Add rootless tests to cgroup2 CI
Tests
See the result of cgroup2 CI.
Rootless tests are prefixed with `[Rootless]`.
https://github.com/k3s-io/k3s/issues/2845

cgroup2 CI: add rootless

---

channel.yaml

Bump stable version to v1.21.1+k3s1 and add v1.21 channel

---

pkg/cluster/cluster.go

Put channel read in loop that will check again and again until the signal is received rather than a single check and pass.
#3414

fix possible race where bootstrap data might not save

---

pkg/agent/flannel/setup.go

strings has a specific function to replace all matches. We should use that one instead of strings.Replace(string, old, new string, -1)
Fix
By using flannel and k3s (default option)
https://github.com/k3s-io/k3s/issues/3416

Change Replace with ReplaceAll function

---

pkg/agent/containerd/containerd.go

Revert "Change containerd image leases from 24h to permanent"

---

go.mod
go.sum
pkg/cli/server/server.go
pkg/clientaccess/token.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/storage.go
pkg/server/server.go
vendor/github.com/k3s-io/kine/pkg/client/client.go
vendor/modules.txt

Fix saving bootstrap data with empty token
BugFix
Issues:
https://github.com/k3s-io/k3s/issues/3435
https://github.com/rancherlabs/rancher-security/issues/501

Fix storing bootstrap data with empty token string

---

channel.yaml

https://github.com/k3s-io/k3s/issues/3450

Bump stable version to v1.21.2+k3s1

---

pkg/agent/config/config_windows.go

missing build tag for windows

---

go.mod
pkg/agent/netpol/namespace.go
pkg/agent/netpol/netpol.go
pkg/agent/netpol/network_policy_controller.go
pkg/agent/netpol/network_policy_controller_test.go
pkg/agent/netpol/pod.go
pkg/agent/netpol/policy.go
pkg/agent/netpol/utils.go
pkg/agent/netpol/utils/ipset.go
pkg/agent/netpol/utils/ipset_test.go
pkg/agent/netpol/utils/iptables.go
pkg/agent/netpol/utils/node.go
pkg/cluster/encrypt.go
vendor/modules.txt

* Update embedded kube-router to latest commit
https://github.com/k3s-io/k3s/issues/3374
Original Issue: https://github.com/k3s-io/k3s/issues/3373
Original PR: https://github.com/k3s-io/k3s/pull/3557

[Backport 1.21] Update embedded kube-router (#3557)

---

cmd/etcdsnapshot/main.go
cmd/k3s/main.go
cmd/server/main.go
main.go
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/etcd/etcd.go

Backport issue 3414 release 1.20 2

---

go.mod
go.sum
pkg/cli/server/server.go
pkg/clientaccess/token.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/storage.go
pkg/server/server.go
vendor/github.com/k3s-io/kine/pkg/client/client.go
vendor/github.com/k3s-io/kine/pkg/logstructured/sqllog/sql.go
vendor/modules.txt

* https://github.com/rancherlabs/rancher-security/issues/831
* #3629
* #3632

[release-1.21] - Backport Fix storing bootstrap data with empty token string

---

.github/ISSUE_TEMPLATE/cut_release.md

Signed-off-by: cwayne18 <cwayne@ubuntu.com>
Adds an issue template for ensuring release checklist issues are formatted properly
New issue template
Additional issue template when creating a new issue

Add issue template for creating release checklist issues

---

pkg/cli/cmds/server.go
pkg/server/server.go
pkg/server/types.go

This reverts commit 8a81349b2f62b38945c271da48cf4625af45a536.
https://github.com/k3s-io/k3s/pull/3654
```release-note
```

Revert "Adding support for waitgroup to the Startuphooks (#3654)

---

scripts/download

Bump k3s-root to 0.9.1
Linked issue: #3635 

[release-1.19] Upgrade k3s-root version

---

pkg/cli/cmds/server.go
pkg/server/server.go
pkg/server/types.go

move go routines for api server ready beneath wait group

---

pkg/cluster/storage.go

* https://github.com/rancher/rke2/issues/1404

[Release-1.19] Fix multiple bootstrap keys found

---

pkg/cluster/storage.go

* https://github.com/rancher/rke2/issues/1403

[Release-1.20] Fix multiple bootstrap keys found

---

pkg/cluster/storage.go

* https://github.com/rancher/rke2/issues/1402

[Release-1.21] Fix multiple bootstrap keys found

---

channel.yaml

Signed-off-by: David Nuzik <david.nuzik@rancher.com>
change stable channel to v1.21.3+k3s1 we will be releasing.
Post-merge, channel server [endpoint](https://update.k3s.io/v1-release/channels) should automatically update within approximately 15 minutes. When that's done, QA should attempt to install with defaults (uses stable channel) and ensure this works.
https://github.com/k3s-io/k3s/issues/3698 
```release-note
NONE
```
(It does, but is not something that should get release noted)

Update K3S 1.21 stable version

---

contrib/gotests_templates/call.tmpl
contrib/gotests_templates/function.tmpl
contrib/gotests_templates/header.tmpl
contrib/gotests_templates/inline.tmpl
contrib/gotests_templates/inputs.tmpl
contrib/gotests_templates/message.tmpl
contrib/gotests_templates/results.tmpl

Adds gotests templates that make sure all generated tests from gotests are the same with the necessary built-in functions.
#3706 
```release-note
```

add gotests templates

---

pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go
pkg/daemons/config/types_test.go
pkg/daemons/control/server.go

Updated the logic to handle if extra args are passed with existing hyphens in the arg. The test was updated to add the additional case of having pre-existing hyphens. The method name was also refactored based on previous feedback.
* https://github.com/k3s-io/k3s/issues/3642

Added logic to strip any existing hyphens before processing the args.

---

pkg/cli/server/server.go

- https://github.com/rancher/rke2/issues/1485

[Release-1.21] Notify systemd for etcd only node

---

pkg/etcd/etcd.go

Add a context timeout for the etcd remove peer function
bug fix
- create cluster with 3 server nodes and etcd backend
- delete one of the nodes using kubectl delete node
node should be deleted normally from the node list
https://github.com/k3s-io/k3s/issues/2669
The issue is not always reproducible

Fix Node stuck at deletion

---

pkg/etcd/etcd.go

* account for an s3 folder when listing objects
#3809 
```release-note
```

[Backport 1.20] - account for an s3 folder when listing objects (#3807)

---

pkg/etcd/etcd.go

* account for an s3 folder when listing objects
#3808 
```release-note
```

[Backport 1.21]  - account for an s3 folder when listing objects (#3807)

---

CONTRIBUTING.md
tests/TESTING.md

New documentation that describes when and how to write new k3s tests.
Documentation
N/A
https://github.com/k3s-io/k3s/issues/3729
```release-note
NONE
```

Added new testing documentation

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/cli/server/server.go

Backport PR for:
- https://github.com/k3s-io/k3s/issues/3876

[Release-1.19] Reset load balancer state during restoraion

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/cli/server/server.go

Backport PR:
- https://github.com/k3s-io/k3s/issues/3875

[Release-1.20] Reset load balancer state during restoraion

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/cli/server/server.go

Backport PR:
- https://github.com/k3s-io/k3s/issues/3874

[Release-1.21] Reset load balancer state during restoraion

---

go.mod
go.sum
vendor/github.com/gofrs/flock/flock_aix.go
vendor/github.com/google/uuid/uuid.go
vendor/github.com/google/uuid/version4.go
vendor/github.com/rootless-containers/rootlesskit/pkg/api/api.go
vendor/github.com/rootless-containers/rootlesskit/pkg/api/openapi.yaml
vendor/github.com/rootless-containers/rootlesskit/pkg/network/slirp4netns/slirp4netns.go
vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/parent.go
vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/tcp/tcp.go
vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/udp/udp.go
vendor/github.com/rootless-containers/rootlesskit/pkg/version/version.go
vendor/modules.txt

Release notes: https://github.com/rootless-containers/rootlesskit/releases

Update RootlessKit to v0.14.5

---

channel.yaml

Bump stable release in channel server
release
Install from install script
#3778

Bump stable to v1.21.4+k3s1

---

MAINTAINERS

Update maintainers to reflect team changes
housekeeping
n/a
n/a

Update maintainers to reflect team changes

---

pkg/etcd/etcd.go

* https://github.com/k3s-io/k3s/issues/3982

Migrate sqlite data to etcd when initializing the cluster

---

pkg/etcd/member_controller.go

Backport of: https://github.com/k3s-io/k3s/pull/4014
https://github.com/k3s-io/k3s/issues/4002

[release-1.21] Use existing name for etcd controller

---

pkg/etcd/member_controller.go

Backport of: https://github.com/k3s-io/k3s/pull/4014
Sync of: https://github.com/k3s-io/k3s/pull/4015
https://github.com/k3s-io/k3s/issues/4002

[engine-1.21] Use existing name for etcd controller

---

pkg/etcd/member_controller.go

This is an extremely minor fix to ensure upgrade scenarios still work.
Please see https://github.com/k3s-io/k3s/pull/4001 for more information on testing this PR.

[master] Use existing name for etcd controller

---

pkg/etcd/etcd.go

Fix regression introduced in https://github.com/k3s-io/k3s/pull/3975 - the context used to start the member is wrapped in a timeout that was intended to only be used for the AddMember calls, but was inadvertently also passed into the embedded etcd server context. Now that we properly stop the embedded etcd instance when the context is cancelled, use of the wrong context caused the joining member to stop prematurely.
bugfix
Join a second member to an embedded etcd cluster
* #4017
```release-note
```

Fix premature etcd shutdown when joining an existing cluster

---

Dockerfile.dapper
Dockerfile.test.dapper

ci; bugfix
Check CI
* TBD
```release-note
NONE
```

Update build images to python3 for compat with recent gsutil change

---

Dockerfile.dapper
Dockerfile.test.dapper

ci; bugfix
Check CI
* TBD
```release-note
NONE
```

[release-1.22] Update build images to python3 for compat with recent gsutil change

---

channel.yaml

Add 1.22 channel
channel server
Install with INSTALL_K3S_CHANNEL=1.22
* #3781 
```release-note
NONE
```

Add 1.22 channel

---

Dockerfile.dapper
Dockerfile.test.dapper

ci; bugfix
Check CI
* TBD
```release-note
NONE
```

[release-1.21] Update build images to python3 for compat with recent gsutil change

---

Dockerfile.dapper
Dockerfile.test.dapper

ci; bugfix
Check CI
* TBD
```release-note
NONE
```

[release-1.20] Update build images to python3 for compat with recent gsutil change

---

.drone.yml
Dockerfile.dapper
scripts/fossa.sh

This adds a fossa analyze and test to the amd64 pipeline.

Adding fossa anaylze/test drone step

---

pkg/agent/syssetup/setup.go

As explained in https://www.kernel.org/doc/html/latest/admin-guide/sysctl/net.html#devconf-inherit-init-net, this parameter controls how sysctl net settings are inherited by network namespaces. By default, the value is 0 which means that ipv4 settings are inherited but ipv6 are not. Setting this to 1 changes that behaviour and both ipv4 and ipv6 settings are inherited.
Bug fix
Create a dual-stack cluster and verify inside the pods that the config is the same as in the root namespace (e.g. /proc/sys/net/ipv6/conf/all/forwarding)
https://github.com/k3s-io/k3s/issues/4021
```release-note
```

Enable the inheritance of sysctl network settings for ipv6

---

channel.yaml

Bump K3s stable to `v1.21.5+k3s1`
Stable version bump
https://github.com/k3s-io/k3s/issues/4004
```release-note
```

Bump stable to v1.21.5+k3s1

---

pkg/etcd/s3.go

https://github.com/rancher/rke2/issues/1870
```release-note
```

set transport to skip verify if se skip flag passed

---

scripts/test-helpers
scripts/test-run-compat

ci
* #4117 
```release-note
```

[release-1.20] Skip tests that violate version skew policy

---

scripts/test-helpers
scripts/test-run-compat

ci
* (forward port since this will also affect other branches over time)
#4118
* #4117
```release-note
```

[release-1.21] Skip tests that violate version skew policy 

---

scripts/test-helpers
scripts/test-run-compat

ci
* (forward port since this will also affect other branches over time)
#4118
* #4117
```release-note
```

[engine-1.21] Skip tests that violate version skew policy

---

scripts/test-helpers

ci
* (forward port since this will also affect other branches over time)
#4118
* #4117
```release-note
```

[release-1.22] Skip tests that violate version skew policy

---

scripts/test-helpers

ci
* (forward port since this will also affect other branches over time)
#4118
* #4117
```release-note
```

Skip tests that violate version skew policy

---

.github/workflows/epic.yaml

Adds a new workflow to check against a known epic and automagically check off child issues
Workflow
Land and then create an epic issue with a list of smaller issues, when a child issue is closed the epic should automatically be updated
```release-note
```

Enable Epics Action to automatically check off child issues in an epic

---

pkg/servicelb/controller.go
scripts/airgap/image-list.txt

Bump klipper-lb image for arm fix
bugfix arm
start k3s on arm7l
* #4384
```release-note
```

Bump klipper-lb image for arm fix

---

go.mod
go.sum
vendor/github.com/containerd/containerd/pkg/cri/opts/spec_linux.go
vendor/github.com/containerd/containerd/pkg/cri/server/container_create_linux.go
vendor/modules.txt

containerd: v1.5.7-k3s2

---

pkg/servicelb/controller.go
scripts/airgap/image-list.txt

Bump klipper-lb image for arm fix
bugfix arm
start k3s on arm7l
* #4384
```release-note
```

[release-1.22] Bump klipper-lb image for arm fix

---

go.mod
go.sum
vendor/github.com/containerd/containerd/pkg/cri/opts/spec_linux.go
vendor/github.com/containerd/containerd/pkg/cri/server/container_create_linux.go
vendor/modules.txt

Upgrade containerd

---

go.mod
go.sum
pkg/agent/containerd/containerd.go
pkg/cli/agent/agent.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_apply.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_compare.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_process.go
vendor/github.com/rancher/wrangler/pkg/signals/signal.go
vendor/modules.txt

Updates to using wrangler v0.8.8 which includes fixes to the signal handler to give a exported func to cancel the the context by hand. this is useful in windows services and gives us a way to cancel context to kill all sub-processes and exit gracefully when using windows service manager.
vendor update, small code change to align k3s to use library slight different and pass in context to containerd
this will ultimately be used in rke2 windows services, this will be tested by QA when we work on closing the linked issue.
https://github.com/rancher/rke2/issues/1755
none

[master] updating to new signals package in wrangler

---

go.mod
go.sum
pkg/agent/containerd/containerd.go
pkg/cli/agent/agent.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_apply.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_compare.go
vendor/github.com/rancher/wrangler/pkg/apply/desiredset_process.go
vendor/github.com/rancher/wrangler/pkg/signals/signal.go
vendor/modules.txt

Updates to using wrangler v0.8.8 which includes fixes to the signal handler to give a exported func to cancel the the context by hand. this is useful in windows services and gives us a way to cancel context to kill all sub-processes and exit gracefully when using windows service manager.
vendor update, small code change to align k3s to use library slight different and pass in context to containerd
this will ultimately be used in rke2 windows services, this will be tested by QA when we work on closing the linked issue.
https://github.com/rancher/rke2/issues/1755
none

[release-1.22] updating to new signals package in wrangler

---

scripts/test

Remove unit tests from Drone CI, we still run them via Github. Prevents failures on Drone CI with the etcd unit tests.
Bugfix
https://github.com/k3s-io/k3s/issues/4425
```release-note
```

Remove unit tests from drone CI

---

pkg/bootstrap/bootstrap.go
pkg/bootstrap/bootstrap_test.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
pkg/clientaccess/kubeconfig.go
pkg/clientaccess/token.go
pkg/clientaccess/token_test.go
pkg/cluster/bootstrap.go
pkg/cluster/bootstrap_test.go
pkg/cluster/cluster.go
pkg/cluster/https.go
pkg/cluster/storage.go
pkg/daemons/control/deps/deps.go
pkg/daemons/control/server.go
pkg/daemons/executor/etcd.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
tests/util/runtime.go

[Release-1.22] All bootstrap backport

---

cmd/agent/main.go
cmd/etcdsnapshot/main.go
cmd/k3s/main.go
cmd/server/main.go
go.mod
go.sum
main.go
pkg/agent/flannel/setup.go
pkg/cluster/https.go
pkg/daemons/agent/agent.go
pkg/daemons/control/server.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/executor.go
pkg/server/server.go
vendor/k8s.io/klog/klog.go
vendor/k8s.io/klog/klog_file.go
vendor/k8s.io/klog/v2/klog.go
vendor/modules.txt

Backport the context pass-through changes from master that were part of the klog/exit handling PR.
backport
normal CI
* rancher/rke2#1755
```release-note
```

[engine-1.21] Backport klog+executor context changes

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_int_test.go
tests/TESTING.md
tests/integration/custometcdargs/custometcdargs_int_test.go
tests/integration/localstorage_int_test.go
tests/util/cmd.go

Backport https://github.com/k3s-io/k3s/pull/4463

[engine-1.21] Add etcd extra args support for K3s

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
tests/integration/custometcdargs/custometcdargs_int_test.go

Backport: https://github.com/k3s-io/k3s/pull/4463

[release-1.22] Add etcd extra args support for K3s

---

pkg/cli/server/server.go

We forgot to remove the check to allow dual-stack and flannel
Without this PR, k3s will fail to start when detecting flannel and dual-stack config
Bugfix
https://github.com/k3s-io/k3s/issues/1405
```release-note
```

[Release 1.21] Fix bug in dual-stack

---

pkg/servicelb/controller.go
scripts/airgap/image-list.txt

This PR backports: https://github.com/k3s-io/k3s/pull/4114
Issue: https://github.com/k3s-io/k3s/issues/1405

[Release 1.21] Backport dual stack

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/config/types.go
pkg/servicelb/controller.go

Backport: https://github.com/k3s-io/k3s/pull/4437
Issue: https://github.com/k3s-io/k3s/issues/4516

[Release 1.22] Allow svclb pod to enable ipv6 forwarding

---

scripts/test-helpers

Bump timeout to 60m (missed this)
CI/testing
```release-note
```

[release-1.22] Backport bump timeout to 60m

---

pkg/configfilearg/defaultparser.go
pkg/configfilearg/defaultparser_test.go

Enable downstream programs to modify the default parser.
Bugfix
Local testing
https://github.com/rancher/rke2/issues/2194
```release-note
```

[Release-1.22] Expose default parser

---

pkg/agent/config/config.go
pkg/agent/flannel/setup.go
pkg/agent/flannel/setup_test.go
pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/4550
Issue: https://github.com/k3s-io/k3s/issues/4612

[Release 1.22] Improve flannel logging

---

pkg/agent/config/config.go
pkg/agent/flannel/setup.go
pkg/daemons/config/types.go

Backport:  #4550
Issue: https://github.com/k3s-io/k3s/issues/4615

[Release 1.21] Improve flannel logging

---

channel.yaml

Bump stable version
Version change
Check channel server
https://github.com/k3s-io/k3s/issues/4441
```release-note
```

Bump stable to v1.21.7+k3s1

---

pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/etcd/etcd_test.go

Backport: https://github.com/k3s-io/k3s/pull/4581
Issue: https://github.com/k3s-io/k3s/issues/4674

[Release 1.22] Verify new control plane nodes joining the cluster share the same config as cluster members

---

pkg/cluster/bootstrap.go
pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/4581
Issue: https://github.com/k3s-io/k3s/issues/4675

[Release 1.21] Verify new control plane nodes joining the cluster share the same config as cluster members

---

pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/etcd/etcd_test.go

Backport: https://github.com/k3s-io/k3s/pull/4581
Issue: https://github.com/k3s-io/k3s/issues/4677

[k3s-engine] Verify new control plane nodes joining the cluster share the same config as cluster members

---

pkg/cluster/bootstrap.go
pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/4581
Issue: https://github.com/k3s-io/k3s/issues/4676

[Release 1.20] Verify new control plane nodes joining the cluster share the same config as cluster members

---

pkg/cli/cert/cert.go

[Release-1.20] Add validation to certificate rotation

---

pkg/agent/containerd/config_windows.go

Fix https://github.com/k3s-io/k3s/pull/4671 for windows. We don't test or build any of the Windows code that's present in k3s until it's pulled through into RKE2, so this was missed.
bugfix
update k3s in rke2; notice build failure.
* https://github.com/k3s-io/k3s/issues/4663

[engine-1.21] Update wharfie usage in windows code path

---

pkg/bootstrap/bootstrap.go
pkg/cluster/bootstrap.go
pkg/etcd/etcd.go

[ Release-1.22 ] - Resolve restore bootstrap (#4704)

---

pkg/bootstrap/bootstrap.go
pkg/cluster/bootstrap.go
pkg/etcd/etcd.go

[ Release-1.21 ] - Resolve restore bootstrap (#4704)

---

pkg/bootstrap/bootstrap.go
pkg/cluster/bootstrap.go
pkg/etcd/etcd.go

[ Engine-1.21 ] - Resolve restore bootstrap (#4704)

---

pkg/bootstrap/bootstrap.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/etcd/etcd.go

Resolve Bootstrap Migration Edge Case (#4730)

---

pkg/cluster/bootstrap.go

Backport of https://github.com/k3s-io/k3s/pull/4747
https://github.com/k3s-io/k3s/issues/4752

[Release-1.21] Fix cold boot and reconcilation on secondary servers

---

pkg/cluster/bootstrap.go

Backport of https://github.com/k3s-io/k3s/pull/4747
https://github.com/k3s-io/k3s/issues/4751

[Release-1.22] Fix cold boot and reconcilation on secondary servers

---

pkg/cluster/bootstrap.go

Backport of https://github.com/k3s-io/k3s/pull/4747
https://github.com/k3s-io/k3s/issues/4750

[Engine-1.21] Fix cold boot and reconcilation on secondary servers

---

pkg/cluster/bootstrap.go

Signed-off-by: manuelbuil <mbuil@suse.com>
Moves all IPs to 16-byte representation to be able to properly compare with the config we get from the server
Bugfix
https://github.com/k3s-io/k3s/issues/4768
```release-note
```

[Release 1-20] Fix joining ha problems

---

ADOPTERS.md

Add new .md to capture users/use cases of k3s
Docs
Check that ADOPTERS.md is there and well-formatted
```release-note
```

Add initial skeleton ADOPTERS.md to better track large use cases

---

pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/4774
Issue: https://github.com/k3s-io/k3s/issues/4777

[Release-1.21] Remove Disables, Skips and DisableKubeProxy from the comparing configs

---

pkg/daemons/config/types.go

Backporting: https://github.com/k3s-io/k3s/pull/4781

[Release-1.22] Remove Disables, Skips and DisableKubeProxy from the comparing configs

---

pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/4774/commits/5d673f4cddbb20cd5f494c5a79029d63cbd71a89
Issue: https://github.com/k3s-io/k3s/issues/4775

[Release 1.20] Remove Disables, Skips and DisableKubeProxy from the comparing configs

---

pkg/cluster/bootstrap.go

[release-1.21] Update bootstrap logic to output all changed files on disk (#4800)

---

pkg/cluster/bootstrap.go

[release-1.22] Update bootstrap logic to output all changed files on disk (#4800)

---

pkg/cluster/bootstrap.go

[engine-1.21] Update bootstrap logic to output all changed files on disk (#4800)

---

pkg/etcd/etcd.go

Fix panic checking name of uninitialized etcd member
bugfix
* #4803 
```release-note
```

Fix panic checking name of uninitialized etcd member

---

pkg/etcd/etcd.go

Fix panic checking name of uninitialized etcd member
bugfix
#4802 
```release-note
```

[release-1.22] Fix panic checking name of uninitialized etcd member

---

pkg/agent/flannel/flannel.go

Use logrus for all the flannel logs. Logrus is used by k3s and it makes sense to use it for everything that is part of k3s.
I also improved some of the logs
Log fixing
Just check that the new logs appear
https://github.com/k3s-io/k3s/issues/4756

Move flannel logs to logrus

---

channel.yaml

Bump stable to v1.22.5+k3s1

---

scripts/build
scripts/build-tests-sonobuoy
scripts/package-cli

in the previous pr i accidently renamed the package in the scripts dir as a find/replace snuck into my commit some how.

Backout accidental package renaming

---

pkg/configfilearg/defaultparser.go
pkg/configfilearg/defaultparser_test.go

Enable downstream programs to modify the default parser.
Bugfix
Local testing
https://github.com/rancher/rke2/issues/2194
```release-note
```

Export default parser

---

channel.yaml

Add 1.23 to channels.yaml
Channel server
Install from v1.23 channel
* https://github.com/k3s-io/k3s/issues/4689
```release-note
```

Update channel.yaml for 1.23

---

.github/workflows/integration.yaml
tests/TESTING.md
tests/integration/Dockerfile.test
tests/integration/secretsencryption/secretsencryption_int_test.go
tests/util/cmd.go

Backport of https://github.com/k3s-io/k3s/pull/4824

[Release-1.22] Require integration test to be run as sudo/root

---

pkg/daemons/agent/agent_windows.go

linter doesn't actually run on a windows machine so while getting it working locally i found these two simple fixes.

[master] Fix small windows lint issues

---

pkg/cli/server/server.go

Just a typo fixed in k3s/pkg/cli/server/server.go
Typo fixed in comment.
Peer review, as it is a one word change in comment.

Fix a typo: advertise-up -> advertise-ip

---

pkg/cluster/bootstrap.go
scripts/test
scripts/test-run-etcd

Fix handling of agent-token fallback to token
bugfix
```release-note
none
```

Fix handling of agent-token fallback to token

---

pkg/cluster/bootstrap.go
scripts/test
scripts/test-run-etcd

Fix handling of agent-token fallback to token
bugfix
```release-note
none
```

[release-1.22] Fix handling of agent-token fallback to token

---

pkg/cluster/bootstrap.go
scripts/test
scripts/test-run-etcd

Fix handling of agent-token fallback to token
bugfix
```release-note
none
```

[engine-1.21] Fix handling of agent-token fallback to token

---

pkg/cluster/bootstrap.go
scripts/test
scripts/test-run-etcd

Fix handling of agent-token fallback to token
bugfix
```release-note
none
```

[release-1.21] Fix handling of agent-token fallback to token

---

pkg/cli/server/server.go

Fix cluster-reset not closing the agentReady channel on K3s so the LB never comes up.
bugfix
* https://github.com/k3s-io/k3s/issues/4914
```release-note
Fixed an issue that prevented cluster-reset restore from working on some nodes in a multi-node etcd cluster.
```

[release-1.21] Move ClusterResetRestore handling after ControlConfig setup

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/log.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go

Backport of https://github.com/k3s-io/k3s/pull/4921
https://github.com/k3s-io/k3s/issues/4929
```release-note
```

[Release-1.22] Enable debug logging on all k3s subcommands with debug flag

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/log.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go

Backport of https://github.com/k3s-io/k3s/pull/4921
https://github.com/k3s-io/k3s/issues/4930
```release-note
```

 [Release-1.21] Enable debug logging on all k3s subcommands with debug flag

---

pkg/cli/cmds/agent.go
pkg/cli/cmds/log.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go

Backport of https://github.com/k3s-io/k3s/pull/4921
https://github.com/rancher/rke2/issues/2343
```release-note
```

[Engine-1.21] Enable debug logging on all k3s subcommands with debug flag

---

.golangci.json
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/daemons/config/types.go
pkg/etcd/etcd.go
pkg/etcd/s3.go

[Release-1.22] Adds the ability to compress etcd snapshots (#4866)

---

.golangci.json
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/daemons/config/types.go
pkg/etcd/etcd.go
pkg/etcd/s3.go
scripts/validate

[Release-1.21] Adds the ability to compress etcd snapshots (#4866)

---

.golangci.json
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/daemons/config/types.go
pkg/etcd/etcd.go
pkg/etcd/s3.go
scripts/validate

[Engine-1.21] Adds the ability to compress etcd snapshots (#4866)

---

pkg/agent/config/config.go
pkg/agent/flannel/flannel.go
pkg/agent/flannel/setup.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/config/types.go

[Release 1.21] Add IPv6 NAT

---

install.sh
package/rpm/install.sh

Backport: https://github.com/k3s-io/k3s/pull/4973
Issue: https://github.com/k3s-io/k3s/issues/4974

[Release 1.22] Remove ip6table rules when cleaning up k3s

---

install.sh
package/rpm/install.sh

Backport: https://github.com/k3s-io/k3s/pull/4973
Issue: https://github.com/k3s-io/k3s/issues/4975

[Release 1.21] Remove ip6table rules when cleaning up k3s

---

pkg/agent/containerd/containerd.go

Move containerd wait into exported function
RKE2 needs to do the same thing when starting up the temporary kubelet and containerd; make this code reusable so that we don't have to copypasta it over there.
D.R.Y.
No change to K3s - existing code just moved into a function
* https://github.com/rancher/rke2/issues/2083#issuecomment-977563685
* https://github.com/rancher/rke2/pull/2391
```release-note
NONE
```

[release-1.21] Move containerd wait into exported function

---

ADOPTERS.md

Add Rocket.Chat to list of adopters.  We utilize k3s under our services including our SaaS offering
Doc update
```release-note
```

Add Rocket.Chat to list of adopters

---

channel.yaml

Bump K3s Stable
Release
https://github.com/k3s-io/k3s/issues/4891
```release-note
```

Bump K3s stable to v1.22.6

---

scripts/test
scripts/test-helpers
scripts/test-run-compat
scripts/test-run-etcd
scripts/test-setup-sonobuoy
scripts/test-setup-sonobuoy-etcd
scripts/test-setup-sonobuoy-mysql
scripts/test-setup-sonobuoy-postgres

* Do serial only first
* Add test-post-hook for extremely flaky tests, enable parallel
Backport of https://github.com/k3s-io/k3s/pull/4897 to release-1.22
https://github.com/k3s-io/k3s/issues/4883
```release-note
```

[Release-1.22] Fixes to Drone CI Stability

---

tests/e2e/Dockerfile.build
tests/e2e/amd64_resource_files/ingress.yaml
tests/e2e/testutils.go
tests/e2e/upgradecluster/upgradecluster_test.go

Fix cluster validation and add upgrade cluster test

---

install.sh
package/rpm/install.sh

flannel creates ipmasq rules in iptables that don't get removed. Using the new version of flannel, those rules contain a comment that has flannel in it
Bug fix
Remove k3s and verify that all iptable rules are removed 
https://github.com/k3s-io/k3s/issues/5001
https://github.com/k3s-io/k3s/issues/5010
```release-note
Remove all iptables rules when destroying k3s cluster
```

Remove the iptables rules from ipmasq flannel

---

tests/e2e/scripts/latest_commit.sh
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile

Fixed potentially infinite while loop
Cleaned up Upgradecluster test checks
Consolidated common Vagrant code
E2E Testing Improvements
`go test -v -timeout=15m ./tests/e2e/... -run E2E`
N/A internal testing change only
```release-note
```

E2E Test Improvements

---

pkg/daemons/control/deps/deps.go

Check and make sure the `encryption-hash.json` file exists when generating secrets-encryption files.
This was breaking upgrades because previously we only had one relevant encryption-config.json file.
Bugfix
- Install pre encryptions rotation version of K3s: v1.22.4+k3s1
- Start K3s `k3s server --secrets-encryption`
- Stop K3s
- Upgrade to this PR
- Start K3s `k3s server --secrets-encryption`
- Run `k3s secrets-encrypt status` and note that it does not fail with 500 Internal Server Error
https://github.com/k3s-io/k3s/issues/5139
```release-note
Fixed a bug that prevented users from using k3s secrets-encryption rotation after upgrading from older K3s versions.
```

Create encryption-hash.json file if it doesn't exist

---

pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/daemons/config/types.go

Adds the ability to specifiy the output format of the etcd snapshot list command.
* rancher/rke2#2490
```release-note
```

add ability to specify etcd snapshot list output format

---

pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/daemons/config/types.go

add ability to specify etcd snapshot list output format (#5132)

---

go.mod
go.sum
pkg/flock/flock_int_test.go
tests/TESTING.md
tests/e2e/Dockerfile.build
tests/e2e/amd64_resource_files/ingress.yaml
tests/e2e/go.mod
tests/e2e/go.sum
tests/e2e/scripts/latest_commit.sh
tests/e2e/testutils.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go
tests/integration/custometcdargs/custometcdargs_int_test.go
tests/integration/dualstack/dualstack_int_test.go
tests/integration/etcdrestore/etcd_restore_int_test.go
tests/integration/etcdsnapshot/etcdsnapshot_int_test.go
tests/integration/localstorage/localstorage_int_test.go
tests/integration/secretsencryption/secretsencryption_int_test.go

Backports several PRs around tests:
https://github.com/k3s-io/k3s/pull/5020
https://github.com/k3s-io/k3s/pull/5097
https://github.com/k3s-io/k3s/pull/5102
Testing Improvments
N/A internal testing change only
```release-note
```

[Release-1.22] Backport E2E Testing Improvements

---

.drone.yml

Switch to rancher drone-fossa plugin instead of installing from scratch every time
merge CI bugfix
Check merge CI logs.
* https://github.com/k3s-io/k3s/issues/5203
```release-note
NONE
```

Switch to drone-fossa plugin

---

channel.yaml

Mark 1.22.7 as stable

---

tests/e2e/amd64_resource_files/secrets.yaml
tests/e2e/scripts/latest_commit.sh
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/secretsencryption/secretsencryption_test.go
tests/e2e/testutils.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go
tests/util/cmd.go

Backport The following PRs:
- Secrets encryption test: https://github.com/k3s-io/k3s/pull/5144
- External DB validate test option: https://github.com/k3s-io/k3s/pull/5157
- Fix to Integration tests when killing K3s server (test only changes): https://github.com/k3s-io/k3s/pull/5158
`go test -v ./tests/e2e/... -run E2E`
`go test -v ./tests/integration/... -run Integration`
N/A Internal testing change only
```release-note
```

[Release-1.22] Backport new E2E tests

---

pkg/daemons/agent/agent_windows.go

fix function arg call

---

go.mod
go.sum
pkg/agent/flannel/flannel.go

Update flannel to v0.17
Version update
#5214 
```release-note
```

Flannel 0.17

---

pkg/daemons/agent/agent_windows.go

[release 1.22] - fix function arg call (#5234)

---

pkg/daemons/agent/agent_windows.go

[engine 1.21] - fix function arg call (#5234)

---

pkg/util/net.go

add net util funcs

---

pkg/daemons/agent/agent_windows.go

Release 1.22 fix 700

---

pkg/daemons/agent/agent_windows.go

remove unused code

---

go.mod
go.sum
pkg/agent/config/config.go
pkg/agent/flannel/flannel.go
pkg/agent/flannel/setup.go
pkg/agent/run.go
pkg/cli/server/server.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go

Backport for PR #5238 #5215 #4450 
Ipv6 only support
#5262
```release-note
```

[release 1.22] ipv6 only

---

.github/workflows/install.yaml
tests/TESTING.md
tests/install/rocky-8/Vagrantfile

Drop in replacement of CentOS 8 with rocky 8 in the install vagrant testing.
Testing
Smoke test on this PR
https://github.com/k3s-io/k3s/issues/5091
```release-note
```

Replace CentOS 8 with Rocky Linux 8 for install testing

---

Vagrantfile
scripts/provision/vagrant

This PR brings two improvements to Vagrantfile:
* Enabling IPv6 and IP forwarding for all families, to make using dual-stack possible.
* Setting NFS options, necessary to make NFS under vagrant-libvirt work.
minor changes in Vagrantfile
VMs should have the following sysctls:
```
net.ipv4.ip_forward = 1
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
```
And setting up Vagrant with the following options should work (it doesn't outside this PR):
```
export MOUNT_TYPE=nfs
vagrant up
```
```release-note
NONE
```

vagrant: Enable IPv6 and IP forwarding, set NFS options

---

pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/proxy/apiproxy.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/apiaddresses/controller.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/https.go
pkg/daemons/control/deps/deps.go
pkg/daemons/control/server.go
pkg/etcd/etcd.go
pkg/etcd/etcdproxy.go
pkg/server/server.go

Signed-off-by: Roberto Bonafiglia <roberto.bonafiglia@suse.com>
Fix the etcd URL in case of IPv6 address
Bugfix
#5237
```release-note
```

Fixed etcd URL in case of IPv6 address

---

go.mod
go.sum
scripts/airgap/image-list.txt

Update version to support ipv6-only
Version bump
Deploy k3s and verify that the klipper-helm image has now tag v0.7.1-build20220407
https://github.com/k3s-io/k3s/issues/5237
```release-note
Update helm-controller version
```

Update helm-controller version

---

go.mod
go.sum
scripts/airgap/image-list.txt

Issue: https://github.com/k3s-io/k3s/issues/5262
Backport: https://github.com/k3s-io/k3s/pull/5398

[Release 1.22] Update helm-controller version

---

tests/integration/certrotation/certrotation_int_test.go

Add certificate rotation integration tests

---

tests/terraform/Dockerfile.build
tests/terraform/createcluster.go
tests/terraform/jenkinsfile
tests/terraform/testutils.go

fix typo in Dockerfile

---

Dockerfile.dapper

[Release 1.22] update trivy to 0.25.3

---

Dockerfile.dapper

[Release 1.21] update trivy to 0.25.3

---

pkg/cli/cmds/server.go

Signed-off-by: Roberto Bonafiglia <roberto.bonafiglia@suse.com>
Removed (default: vxlan) duplicate on cmd helper
#5421
```release-note
```

Fixed flannel backend helper text

---

go.mod
go.sum
pkg/agent/flannel/flannel.go
pkg/agent/flannel/setup.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Issue: #5408
Backport: #5377 #5391

[Release 1.22] Wireguard native flannel support

---

go.mod
go.sum
pkg/agent/flannel/flannel.go
pkg/agent/flannel/setup.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Issue: #5410
Backport: #5377 #5391

[Release 1.21] Wireguard native flannel support

---

pkg/etcd/etcd.go
pkg/etcd/etcd_test.go

Signed-off-by: Roberto Bonafiglia <roberto.bonafiglia@suse.com>
Add the default endpoint for ETCD client in case of IPv6 only setup
Bugfix
#5237
```release-note
```

Added default endpoint for IPv6

---

Dockerfile.test.dapper
conformance/Dockerfile
conformance/run-test.sh

This appears to be fixing the CI testing in local testing.
Update sonobuoy to latest release
Bugfix
CI verifies it.
```release-note
NONE
```

update sonobuoy to 0.56.4

---

go.mod
go.sum
pkg/agent/netpol/netpol.go
pkg/cli/server/server.go

[Release 1.22] netpol: Add dual-stack support

---

go.mod
go.sum
pkg/agent/netpol/netpol.go
pkg/cli/server/server.go

Issue: https://github.com/k3s-io/k3s/issues/5386
Backport: https://github.com/k3s-io/k3s/pull/5387

[Release 1.21] netpol: Add dual-stack support

---

pkg/etcd/apiaddresses_controller.go

Use ListWatch helpers to retry when the watch channel is closed.
bugfix
Leave k3s running for ~30 minutes, note no spamming errors:
```
ERRO[2110] Failed to watch apiserver addresses: could not convert event object to endpoint: { <nil>}
```
* https://github.com/k3s-io/k3s/issues/5484
```release-note
NONE
```

[release-1.21] Fix issue with long-running apiserver endpoints watch

---

pkg/etcd/apiaddresses_controller.go

Use ListWatch helpers to retry when the watch channel is closed.
bugfix
Leave k3s running for ~30 minutes, note no spamming errors:
```
ERRO[2110] Failed to watch apiserver addresses: could not convert event object to endpoint: { <nil>}
```
* https://github.com/k3s-io/k3s/issues/5484
```release-note
NONE
```

[engine-1.21] Fix issue with long-running apiserver endpoints watch

---

pkg/etcd/apiaddresses_controller.go

Use ListWatch helpers to retry when the watch channel is closed.
bugfix
Leave k3s running for ~30 minutes, note no spamming errors:
```
ERRO[2110] Failed to watch apiserver addresses: could not convert event object to endpoint: { <nil>}
```
* https://github.com/k3s-io/k3s/issues/5483
```release-note
NONE
```

[release-1.22] Fix issue with long-running apiserver endpoints watch

---

go.mod
go.sum

Bump containerd for selinux fix:
* https://github.com/opencontainers/selinux/issues/172
version bump
* https://github.com/k3s-io/k3s/issues/5493
```release-note
NONE
```

Bump containerd for selinux fix

---

pkg/etcd/etcd.go
pkg/etcd/etcd_test.go

Backport for #5420 
Issue #5509

[Release 1.22] Added default endpoint for IPv6

---

channel.yaml

Mark v1.23.6+k3s1 stable
channel server
Install k3s from install script
* https://github.com/k3s-io/k3s/issues/5476
```release-note
NONE
```

Mark v1.23.6+k3s1 stable

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/templates/templates.go
pkg/agent/templates/templates_linux.go
pkg/cgroups/cgroups_linux.go
pkg/cgroups/cgroups_windows.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/config/types.go

[Release-1.22] Add systemd cgroup controller support 

---

pkg/deploy/controller.go

If a user puts a file in /var/lib/rancher/k3s/server/manifests/ then the
objects contained therein are deployed to the cluster. If the objects
are removed from that file, they are not removed from the cluster.
This change tracks the GVKs in the files and will remove objects when
there are removed from the cluster.
Signed-off-by: Donnie Adams <donnie.adams@suse.com>
Deploy a K3S cluster and put a file in the /var/lib/rancher/k3s/server/manifests/ directory. Once the objects have been deployed to the cluster, clear the contents of the file in the directory. The objects should be removed from the cluster.
https://github.com/k3s-io/k3s/issues/5559
```release-note
Objects will be removed from Kubernetes when they are removed from manifest files.
```

Remove objects when removed from manifests

---

MAINTAINERS

remove dweomer from maintainers

---

go.mod
go.sum

Bump dynamiclistener to v0.3.3
version bump
Normal CI / QA tests
* https://github.com/k3s-io/k3s/issues/5591
```release-note
NONE
```

Bump dynamiclistener to v0.3.3

---

tests/e2e/README.md
tests/e2e/amd64_resource_files/dualstack_clusterip.yaml
tests/e2e/amd64_resource_files/dualstack_ingress.yaml
tests/e2e/amd64_resource_files/dualstack_nodeport.yaml
tests/e2e/dualstack/Vagrantfile
tests/e2e/dualstack/dualstack_test.go
tests/e2e/scripts/ipv6.sh
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/splitserver/Vagrantfile
tests/e2e/splitserver/splitserver_test.go
tests/e2e/testutils.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go

A new E2E test for dualstack configuration (finally fully supported in K3s).
Consolidate duplicate Vagrant code.
New E2E Test
`go test -v -timeout=20m ./tests/e2e/dualstack/dualstack_test.go`
N/A Internal testing change only
```release-note
```

E2E: Dualstack test

---

.github/PULL_REQUEST_TEMPLATE.md
tests/e2e/README.md
tests/e2e/amd64_resource_files/dualstack_clusterip.yaml
tests/e2e/amd64_resource_files/dualstack_ingress.yaml
tests/e2e/amd64_resource_files/dualstack_nodeport.yaml
tests/e2e/dualstack/Vagrantfile
tests/e2e/dualstack/dualstack_test.go
tests/e2e/scripts/ipv6.sh
tests/e2e/scripts/rancher.sh
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/splitserver/Vagrantfile
tests/e2e/splitserver/splitserver_test.go
tests/e2e/testutils.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go
tests/integration/certrotation/certrotation_int_test.go
tests/integration/dualstack/dualstack_int_test.go
tests/integration/etcdrestore/etcd_restore_int_test.go
tests/integration/etcdsnapshot/etcdsnapshot_int_test.go
tests/integration/integration.go
tests/integration/localstorage/localstorage_int_test.go
tests/integration/secretsencryption/secretsencryption_int_test.go
tests/integration/startup/startup_int_test.go

Backport of the following PRs:
https://github.com/k3s-io/k3s/pull/5593
https://github.com/k3s-io/k3s/pull/5617
https://github.com/k3s-io/k3s/pull/5630
E2E and Integration test improvements

[Release-1.23] Integration and E2E test improvements

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/https.go
pkg/daemons/config/types.go

Signed-off-by: igor <igor@igor.io>
Backport of https://github.com/k3s-io/k3s/pull/5527
https://github.com/k3s-io/k3s/issues/5688

[Release-1.22] add support for pprof server

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/https.go
pkg/daemons/config/types.go

Signed-off-by: igor <igor@igor.io>
Backport of https://github.com/k3s-io/k3s/pull/5527
https://github.com/k3s-io/k3s/issues/5687

[Release-1.23] add support for pprof server

---

.github/PULL_REQUEST_TEMPLATE.md
tests/e2e/README.md
tests/e2e/amd64_resource_files/dualstack_clusterip.yaml
tests/e2e/amd64_resource_files/dualstack_ingress.yaml
tests/e2e/amd64_resource_files/dualstack_nodeport.yaml
tests/e2e/dualstack/Vagrantfile
tests/e2e/dualstack/dualstack_test.go
tests/e2e/scripts/ipv6.sh
tests/e2e/scripts/rancher.sh
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/splitserver/Vagrantfile
tests/e2e/splitserver/splitserver_test.go
tests/e2e/testutils.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/validatecluster/validatecluster_test.go
tests/integration/dualstack/dualstack_int_test.go
tests/integration/etcdrestore/etcd_restore_int_test.go
tests/integration/etcdsnapshot/etcdsnapshot_int_test.go
tests/integration/localstorage/localstorage_int_test.go
tests/integration/secretsencryption/secretsencryption_int_test.go
tests/integration/startup/startup_int_test.go
tests/util/cmd.go

Backport of the following PRs:
https://github.com/k3s-io/k3s/pull/5593
https://github.com/k3s-io/k3s/pull/5617
https://github.com/k3s-io/k3s/pull/5630
E2E and Integration test improvements

[Release-1.22] Integration and E2E test improvements

---

install.sh
package/rpm/install.sh

Issue: https://github.com/k3s-io/k3s/issues/5676
Backport: https://github.com/k3s-io/k3s/pull/5644

[Release 1.23] Remove kube-ipvs0 interface when cleaning up

---

pkg/agent/config/config.go
pkg/agent/flannel/setup.go
pkg/agent/util/file.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/5656
Issue: https://github.com/k3s-io/k3s/issues/5683

[Release 1.22] Add FlannelConfCNI flag

---

pkg/agent/config/config.go
pkg/agent/flannel/setup.go
pkg/agent/util/file.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Backport: https://github.com/k3s-io/k3s/pull/5656
Issue: https://github.com/k3s-io/k3s/issues/5681

[Release 1.23] Add FlannelConfCNI flag

---

pkg/etcd/etcd.go

If the user points S3 backups at a bucket containing other files, those
file names may not be valid configmap keys.
For example, RKE1 generates backup files with names like
`s3-c-zrjnb-rs-6hxpk_2022-05-05T12:05:15Z.zip`; the semicolons in the
timestamp portion of the name are not allowed for use in configmap keys.
bugfix
n/a
* https://github.com/rancher/rancher/issues/37904#issuecomment-1155731449
```release-note
The embedded etcd snapshot controller will no longer fail to process snapshot files containing characters that are invalid for use in ConfigMap keys.
```

[release-1.21] Sanitize filenames for use in configmap keys

---

go.mod
go.sum
pkg/agent/flannel/setup.go
pkg/cli/cmds/server.go

Backport for  #5552
#5719
```release-note
```

[Release 1.23] Flannel version update to 0.18.1 and added the ability to configure additional options for wireguard backend

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump helm-controller
version bump
* https://github.com/k3s-io/k3s/issues/5534
```release-note
The embedded Helm controller now properly updates Chart deployments when HelmChartConfig resources are updated or deleted.
```

Bump helm-controller

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump helm-controller
version bump
* https://github.com/k3s-io/k3s/issues/5733
```release-note
The embedded Helm controller now properly updates Chart deployments when HelmChartConfig resources are updated or deleted.
```

[release-1.23] Bump helm-controller

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump helm-controller
version bump
* https://github.com/k3s-io/k3s/issues/5732
```release-note
The embedded Helm controller now properly updates Chart deployments when HelmChartConfig resources are updated or deleted.
```

[release-1.22] Bump helm-controller

---

channel.yaml

Add 1.24 release channel

---

channel.yaml

Signed-off-by: Nikolai Shields <nikolai@nikolaishields.com>
```release-note
```

Mark v1.23.8+k3s1 to stable

---

go.mod

We don't use this dependency and it is a legacy from the transition from rancher to k3s-io
go.mod cleanup
`make`
https://github.com/k3s-io/k3s/issues/5775
```release-note
```

[Release-1.22] Remove go-powershell dead dependency

---

go.mod

We don't use this dependency and it is a legacy from the transition from rancher to k3s-io
go.mod cleanup
`make`
https://github.com/k3s-io/k3s/issues/5775
```release-note
```

[Release-1.23] Remove go-powershell dead dependency

---

go.mod
go.sum
pkg/agent/tunnel/tunnel.go
pkg/daemons/control/tunnel.go

Bump remotedialer
Includes fix for recently identified memory leak (https://github.com/rancher/remotedialer/pull/46), and adapts the code to track changes to remotedialer API changes.
version bump
I don't believe we've had any complaints of memory leaks yet, but since we don't use remotedialer as extensively as rancher they've probably just not been bad enough to create problems.
N/A
* TBD
```release-note
Updated rancher/remotedialer to address a potential memory leak.
```

Bump remotedialer

---

channel.yaml

Promote v1.23.8+k3s2 to stable
channel server
Install K3s from channel server
n/a
* n/a
```release-note
NONE
```

Promote v1.23.8+k3s2 to stable

---

pkg/secretsencrypt/controller.go

The root cause is that using the `pager.EachListItem` on 10K secrets takes too long and request is expired. This is described in the [K8s code]( https://github.com/kubernetes/client-go/blob/v0.24.3/tools/pager/pager.go#L154.
Instead, we use the `pager.List` to get 1 single list all at once (the list request is still broken into chunked requests of 500 items to the apiserver) and then process each secret without running up against an expiration. 
Bugfix
See the linked issue, TLDR:
- Make a K3s cluster
- Add 10K secrets to the cluster
`kubectl create namespace test-encryption-key-rotation && for i in {1..10000}; do kubectl create secret generic test$i -n test-encryption-key-rotation --from-literal=key$1=value$i; done`
- Follow [the …

Fix secrets reencryption for clusters with 8K+ secrets

---

pkg/secretsencrypt/controller.go

Backport of https://github.com/k3s-io/k3s/pull/5936
https://github.com/k3s-io/k3s/issues/5934
```release-note
```

[Release-1.23] Fix secrets reencryption for 8K+ secrets

---

pkg/secretsencrypt/controller.go

Backport of https://github.com/k3s-io/k3s/pull/5936
https://github.com/k3s-io/k3s/issues/5935
```release-note
```

[Release-1.22] Fix secrets reencryption for 8K+ secrets

---

go.mod
go.sum
pkg/agent/flannel/flannel.go

Update flannel version to v0.19.1
CNI version update
#5961
```release-note
```

Updated flannel to v0.19.1

---

go.mod
go.sum
pkg/agent/flannel/flannel.go

[Release 1.23] Updated flannel to v0.19.1

---

go.mod
go.sum
pkg/agent/flannel/flannel.go

[Release 1.22] Updated flannel to v0.19.1

---

tests/e2e/scripts/Jenkinsfile
tests/e2e/scripts/run_tests.sh

Signed-off-by: Shylaja Devadiga <shylaja@rancher.com>
Adding jenkins credentials variable
Running more tests
NA Internal testing

Update run scripts

---

tests/cgroup/unified/fedora-34/Vagrantfile
tests/install/centos-7/Vagrantfile
tests/install/fedora-coreos/Vagrantfile
tests/install/opensuse-leap/Vagrantfile
tests/install/opensuse-microos/Vagrantfile
tests/install/rocky-8/Vagrantfile
tests/install/ubuntu-focal/Vagrantfile
tests/snapshotter/btrfs/opensuse-leap/Vagrantfile

The vagrant-k3s plugin supports configuring K3s alot of ways. This eliminates one, the ruby hash based config. This configuration was confusing and not portable (couldn't just copy paste to config.yaml file). This brings tests all in line with using string YAML configuration.
Testing Changes
GH actions still pass
N/A
```release-note
```

Convert install/cgroup tests to yaml based config

---

.github/workflows/nightly-install.yaml

Add nightly install tests in Github
Automation/CI
See Github Actions -- this should run at midnight every night Monday through Friday. It should install k3s using the vagrant scripts on multiple different OSes, using the latest commit from master branch.
N/A
N/A

Add nightly install github action

---

channel.yaml

mark v1.24.4+k3s1 as stable

---

.github/workflows/install.yaml
install.sh
tests/install/opensuse-leap/Vagrantfile

- Install tests will now build the commit of the PR being tested. This build will then be deployed across all OS install tests.
Testing change
Github CI Passes
N/A internal testing change
```release-note
```

Convert install tests to run PR build of k3s

---

.github/workflows/cgroup.yaml
tests/TESTING.md
tests/cgroup/unified/fedora-35/Vagrantfile

Update Fedora 34 to 35.
Fedora 34 has reached EOL on 2022-06-07 
https://docs.fedoraproject.org/en-US/releases/eol/
CI
Observe the CI result
Observe the CI result
🚫 
🚫 
Alternative to
- https://github.com/k3s-io/k3s/pull/5954 (CI failing currently)

CI: update Fedora 34 -> 35

---

tests/e2e/testutils.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/vagrantdefaults.rb

Signed-off-by: Shylaja Devadiga <shylaja@rancher.com>
Proposed Changes
Update Vagrantfile for upgrade cluster tests
Fix OpenSuse test fails with apparmor
Verification
All tests should pass on OpenSuse
Linked Issues
N/A internal testing change

Fix e2e tests

---

install.sh
package/rpm/install.sh

This PR includes the deletion of the wireguard interfaces when destroying the cluster. Those interfaces are created when we choose `flannel-backend: wireguard-native`
Bugfix
Deploy k3s with `flannel-backend: wireguard-native` and then destroy the cluster. You should see those interfaces disappear.
Note that flannel-wg-v6 only appears in dual-stack or ipv6-only
https://github.com/k3s-io/k3s/issues/6053
```release-note
```

Remove wireguard interfaces when deleting the cluster

---

go.mod
go.sum

[Release 1.23] Update Flannel to v0.19.2 to fix older iptables issue

---

go.mod
go.sum

[Release 1.22] Update Flannel to v0.19.2 to fix older iptables issue
