- cmd/k3s/main.go
Return the directory name if assets are located in HOME, so we can
properly set the PATH for binary lookup.
For rancher/k3s/issues/38 and rancher/k3s/issues/21
> Fix asset lookup of HOME directory

- package/Dockerfile
The kubernetes e2e tests will mount /tmp and verify permissions, fix
to match the expectations of the test for our image.
For rancher/k3s/issues/45
> Chmod /tmp to 1777 for e2e tests

- pkg/agent/flannel/setup.go
It seems like a lot of users are getting issues with flannel initially. This will help them get the 'right' error message 👍
> fix 'fannel' typo.

- staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
To properly notify systemd that the k3s server is ready we need to
prevent the current k8s notification and add one to the k3s cli.
For rancher/k3s/issues/57
> Make systemd notify optional in generic api server

- install.sh
Check for latest release of k3s or pass a desired version as an
argument. Adds curl as a requirement and early exits if not available.
Fixes silent abort when wget is not available and `which` returns
non-zero exit code.
For rancher/k3s/issues/47 and rancher/k3s/issues/48
> Download latest release for install script

- pkg/agent/config/config.go
- pkg/agent/containerd/containerd.go
- pkg/daemons/config/types.go
This PR adds preloading existing container images ( `docker save` format ) from `/var/lib/rancher/k3s/agent/images`
Fixes #92
> preload a docker image on the k3s node agents

- pkg/agent/config/config.go
This enforces that node names are lower case, due to constraint in kubernetes. For more detail, see https://github.com/rancher/k3s/issues/160
> Enforce lower case hostname for node

- README.md
Adds information about uninstall script, CRD for Helm Charts and Traefik integration / disabling to README.md. For more please see the respective issues #86, #96, #97.
> Document uninstall and Traefik, Helm integration (references #86, #96, #97)

- scripts/dev-agent.sh
- scripts/dev-docker-agent.sh
- scripts/setup-rancher-path.sh
After running the steps in https://github.com/rancher/k3s#building-from-source up to running ```dev-agent.sh```, the node token was in:
```/var/lib/rancher/k3s/server/node-token``` (this VM has never had binary release installed on it)
So changed ```dev-agent.sh``` to reflect this.
Note: I haven't tested change to ```dev-docker-agent.sh``` separately yet and out of time for this evening
> Fix node token path

- pkg/cli/server/server.go
Disables k8s generic api server systemd ready notification and send
our own ready notification after server available and kubeconfig
available.
Make sure we unset the NOTIFY_SOCKET environment variable by passing
`true` to SdNotify so the agent can start containers.
For rancher/k3s/issues/57
> Enable systemd ready notification for k3s server

- pkg/servicelb/controller.go
If a port name is longer than 15 characters we are unable to create
the associated service load balancer containers. Use our own short
name of `lb-port-{port}` to avoid naming issues.
For rancher/k3s/issues/90
> Short port names for service load balancer

- README.md
Flannel uses port 8472 for VXLAN: https://github.com/coreos/flannel/blame/e63a71b4de14407d0bee999ffa2f0f68758c34a1/Documentation/backends.md#L23
```
ip -d l show flannel.1
... dstport 8472 ...
```
> Update README for correct VXLAN port

- pkg/helm/controller.go
- scripts/airgap/generate-list.sh
- scripts/airgap/image-list.txt
- scripts/package
- scripts/package-airgap
Create artifacts for air-gap images and tools for generating new image lists.
Updates klipper-helm for air-gap compatibility.
For rancher/k3s/issues/166
> Generate air-gap image artifacts

- Dockerfile.dapper
Change-Id: I60c92d0127cfc503c46b26fe7b2e3ad2f957dfa3
We are not able to go get golang.org/x/* packages from China. So I replace it with GitHub mirrors.
> Fix go get golang.org/x/* packages timed out issue.

- pkg/deploy/controller.go
- pkg/deploy/stage.go
- pkg/server/server.go
Instead of skipping the manifest when listing the directory, we now skip
creating it in the first place. This allows users to deploy manifests
that replaces the ones bundled, without having to come up with a new
name.
Fixes #230.
> Skip writing manifest when using `--no-deploy`

- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
In NAT or LB environment,
we need not just the certs for local ip, but also additional ips.
advertise-address flag enables to add optional ips.
Related: #214
> Add tls-san flag

- install.sh
Airgap image checksums may accidentaly be used by the installer, be
more specific to grep only for the downloaded executable.
> Fix installer shasum check

- README.md
> Update README for airgap documentation

- README.md
- install.sh
- k3s.service
Cert generation may cause slow startup times for some systems such as
the Raspberry Pi, set the systemd service TimeoutStartSec to Infinity to
avoid startup timeouts.
From rancher/k3s/pull/226
> Extend systemd start timeout for slow systems

- pkg/kubelet/apis/config/validation/validation.go
If --cgroups-per-qos is false and --enforce-node-allocatable is "none"
then validation should pass. Needed if cgroup pids is disabled.
> Fix kubelet --enforce-node-allocatable validation

- pkg/agent/config/config.go
- pkg/agent/flannel/flannel.go
- pkg/agent/flannel/setup.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/config/types.go
This should fix #200 and #72.
I am having issues building this on my local system to test properly as dapper keeps flaking out. I am hoping someone can review this while I try and fix dapper.
> Allow flannel interface to be specified on the command line

- cmd/kube-apiserver/app/server.go
- pkg/kubelet/client/kubelet_client.go
Proxy settings may interfere with a kubelet client communicating with
the API server, so set the proxy to nil.
> Ignore proxy settings for kubelet client

- README.md
Follow-up to #252: mention that Metrics API can now be used and how to do so.
> #252 mention how to deploy metrics-server

- README.md
- install.sh
- k3s.service
Set TimeoutStartSec to 0 instead of infinity for systemd versions older
than 229.
For #361, #360, #347
> Fix systemd TimeoutStartSec

- pkg/agent/config/config.go
- pkg/agent/containerd/containerd.go
- pkg/agent/templates/templates.go
- pkg/daemons/config/types.go
https://github.com/rancher/k3s/issues/331
The PR works by passing Node config to a go template, the user will have the ability to override the template by creating a file with path:
```
<data-dir>/etc/containerd/config.toml.tmpl
```
> Add containerd config go template

- Vagrantfile
- scripts/vagrant-provision
Provides Vagrantfile for multi-machine development. Uses NFS mounts for 
very fast volume access at the cost of increased memory consumption.
> Add Vagrantfile for development use

- install.sh
The ARCH env var can be set by the install.sh caller.  This is
specifically important if you want to install arm on arm64.
> Add ability to set architecture

- pkg/agent/syssetup/setup.go
Fix `/proc/sys/net/bridge/bridge-nf-call-iptables` and `/proc/sys/net/ipv4/ip_forward` not set to `1` when `br_netfilter` kernel module is compiled into the kernel, caused by #371
Signed-off-by: Wenxuan Zhao <viz@linux.com>
> Allow using built-in kernel modules

- contrib/ansible/README.md
- contrib/ansible/roles/k3s/master/tasks/main.yml
I've enhance some Ansible display informations, and add the automatic copy of kubeconfig file to user home directory in ~/.kube/config. In addition https://localhost:6443 is replace by https://master_ip:6443 in order to easily make an scp on your laptop.
> Fix typo and add kubeconfig copy to user homedir

- pkg/rootless/mounts.go
- pkg/rootless/rootless.go
k3s was unable to start up when /var/lib/cni is missing on the host.
Fix https://github.com/rancher/k3s/issues/470
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> rootless: fix mounting /var/lib/cni

- contrib/ansible/roles/download/tasks/main.yml
existing usage produced an error under ansible 2.6.1
> contrib/ansible: Fixes 'search' test usage syntax

- contrib/ansible/roles/k3s/node/tasks/main.yml
Instead of using a common filename for the systemd unit file in two different ansible roles, this PR separates the unit file name into two unique filenames:
- one for the `server` role (`/etc/systemd/system/k3s.service`)
- one for the `node` role (`/etc/systemd/system/k3s-node.service`)
Currently, when attempting to install both the `server` and `node` ansible roles on the same host, the `node` role would overwrite the `server` role's systemd file because it was installed to the same path.
> contrib/ansible: Allow 'server' and 'node' roles to co-exist on a single host

- contrib/ansible/roles/raspbian/tasks/main.yml
Adds a test for the Raspbian OS -specific file before assuming file can be modified.
Currently the role assumes `/boot/cmdline.txt` file exists.
On other ARM OS's (Armbian) it does not, nor does it need editing.
> Ansible: Test for Raspbian before assuming

- contrib/ansible/README.md
The example inventory uses the group `kube-cluster`, but the playbooks reference `k3s-cluster`. This resolves the inconsistency.
> Fix an inconsistency in contrib/ansible/README.md

- pkg/agent/tunnel/tunnel.go
- trash.lock
- vendor.conf
- vendor/github.com/rancher/remotedialer/client.go
1. ✓ (certs refactor pr) k8s addressable advertise endpoint
1. ✆ (future work planned for HAv2) local proxy load balancing as endpoints change (nginx?)
- save last known ips for failover
1. ✓ (this pr) Peer manager (tunnel server)
- remotedialer update to use k8s advertised addresses
- refactor watcher code for use by proxy
1. ✓ (bootstrap pr) Server join get cluster info
- what is needed & what can be stored in k8s
✓ - Initial Implementation, ☆ - Exploration / In Progress, ✆ - Planning
> Initial HA support

- .drone.yml
- Makefile
This will add support for building k3s w/ dapper using buildkit.
Related: https://github.com/rancher/k3s/issues/504
> Update to dapper v0.4.2

- contrib/ansible/roles/k3s/master/tasks/main.yml
Running the ansible playbook on a raspberry pi cluster causes the following error:
```bash
PLAY [master] *********************************************************************************************************************************************************************************
TASK [Gathering Facts] ************************************************************************************************************************************************************************
Sunday 07 July 2019  11:50:54 +0000 (0:00:01.347)       0:02:33.074 ***********
ok: [192.168.1.110]
TASK [k3s/master : Copy K3s service file] *****************************************************************************************************************************************************
Sunday 07 July 2019  11:50:59 …
```
> Add wait for node-token file

- pkg/daemons/control/bootstrap.go
Force error if bootstrap mode is read but nothing exists in etcd,
always write if bootstrap mode is write.
> Enforce explicit read or write for bootstrap

- contrib/ansible/roles/k3s/master/tasks/main.yml
Create symlinks for kubectl and crictl.
This avoids you having to use k3s kubectl or k3s crictl.
> Create symlinks for kubectl and crictl

- pkg/daemons/control/bootstrap.go
Fixes a tls error when starting k3s agents and using a round robin load balancer to masters:
`tls: private key does not match public key`.
> Bootstrap node key files & fix permissions

- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
If the k8s endpoint changes (eg 127.0.0.1 -> node ip) and we start
an agent during that time, the agent will get stuck waiting to connect
the tunnel to the old ip.  If the agent service is restarted the original
process never exits as it is still waiting to connect, but a new agent
process is created, resulting in multiple agents.
To fix we start waiting after watching for endpoint changes, when the
old ip is removed we also stop waiting for that connection attempt.
Additionally we pass in the context for tunnel connection, so if the
service is terminated we exit immediately instead of continuing to wait
for connections to be established.
> Fix tunnel endpoint upgrade

- contrib/ansible/roles/k3s/master/templates/k3s.service.j2
- contrib/ansible/roles/k3s/node/templates/k3s.service.j2
- install.sh
- k3s.service
This extra delay prevents systemd from determining that the service is restarting "too quickly".
At least on the RPi 4, with a wireless connection, it can take a bit longer after the network-online.target is reached before networking is actually ready.  If k3s attempts to start during this time, it exits with the following error:
```
Jul 22 22:57:40 k3s-node01 k3s[476]: time="2019-07-22T22:57:40.220062513+01:00" level=fatal msg="apiserver exited: unable to find suitable network address.error='no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this"
```
Adding a little extra delay prevents the k3s service from hitting the "5 restarts in 10 seconds" and allows systemd to continue to …
> Add a little extra delay between restart attempts

- install.sh
Fix logging for Alpine 3.10, openrc --version
openrc (OpenRC) 0.41.2.6fc2696f3e
> Fix logging for openrc

- pkg/daemons/agent/agent.go
On my environment, the name=systemd entry in /proc/self/cgroup
looks like:
13:name=systemd:/docker/917b388b40c70b17a3283d852d38bfcdc84d1bf8242e32a779eacd98a610e499
Kubelet periodically complains like:
E0802 06:42:52.667123       1 summary_sys_containers.go:47] Failed to get system container stats for "/docker/917b388b40c70b17a3283d852d38bfcdc84d1bf8242e32a779eacd98a610e499/kube-proxy": failed to get cgroup stats for "/docker/917b388b40c70b17a3283d852d38bfcdc84d1bf8242e32a779eacd98a610e499/kube-proxy": failed to get container info for "/docker/917b388b40c70b17a3283d852d38bfcdc84d1bf8242e32a779eacd98a610e499/kube-proxy": unknown container "/docker/917b388b40c70b17a3283d852d38bfcdc84d1bf8242e32a779eacd98a610e499/kube-proxy"
> Appease kubelet warnings on docker for mac

- pkg/agent/config/config.go
- pkg/agent/run.go
- pkg/agent/templates/templates.go
- pkg/cli/server/server.go
- pkg/daemons/control/server.go
- pkg/server/server.go
Fixes #60
Closes #91 
Resolves #193 
Resolves #299
> Remove hostname requirement in `/etc/hosts`

- install.sh
If the install errors out on semanage not found, an error is
thrown as a 'file not found' for `error`. Updating to 'fatal' resolves
this as the script then exits as intended and throws an 'error'.
Actual output (before):
`sh: line 347: error: command not found`
Output (after):
`[ERROR] SELinux is enabled but semanage is not found`
> Changed SELinux/semanage error to fatal

- pkg/cli/server/server.go
- vendor/k8s.io/client-go/pkg/version/base.go
- vendor/k8s.io/kubernetes/pkg/version/base.go
- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
- vendor/k8s.io/kubernetes/pkg/volume/plugins.go
Due to a bug in trash the wrong commit was pulled in for k8s.  Luckily
we are switching to go modules and this type of issue won't happen again.
> Fix CSI and update vendor

- pkg/daemons/control/server.go
It has been removed as a part of #764 for no obvious reasons.
Fix #791
> Add back NodeRestriction

- install.sh
This change sets up the correct dependency on the `network-online` service provided by openrc.
See:
- https://github.com/OpenRC/openrc/blob/0.39.2/service-script-guide.md#be-wary-of-need-net-dependencies
- https://github.com/OpenRC/openrc/blob/0.39.2/init.d/net-online.in#L18
> install.sh: fix openrc service depend in heredoc

- pkg/cli/server/server.go
This allows no-deploy values to be either specified as multiple `--no-deploy` invocations, or a single invocation with comma-separated values.
> Add comma-separated no-deploy values

- pkg/deploy/controller.go
This PR makes the deploy controller scan the `manifests` directory recursively, i.e. also `yaml` files living in subdirectories will be deployed upon k3s start.
In k3d, we can mount volumes into the k3s server container. To get custom manifests into the auto-deploy folder inside the k3s container, we have three options:
1. we mount every file separately -> this should work
2. we mount a whole directory into this path -> manifests created by k3s may overwrite what we put there and also write back to the host system (`ro` won't work, since k3s will fail to write and error out)
3. we mount a whole directory into a subdirectory -> this works around the problems of (1) and (2), but only works, if the deploy controller also scans subdirectories
Fix: https://github.com/rancher/k3d/issues/122
> [Enhancement] include subdirectories for auto-deploy manifests

- contrib/ansible/README.md
- contrib/ansible/roles/prereq/tasks/main.yml
- contrib/ansible/site.yml
- Setting IPv4 & IPv6 forwarding
- Setting `sysctl:net.bridge.bridge-nf-call-iptables` and `bridge-nf-call-ip6tables` to enabled since it is disabled by default on some CentOS systems
> CentOS/RHEL compatibility for Ansible roles

- contrib/ansible/roles/prereq/tasks/main.yml
This PR fixes an issue with indentation in the contrib Ansible role `prereq`
Error this fixes:
```
ERROR! Syntax Error while loading YAML.
did not find expected '-' indicator
The error appears to have been in 'k3s/contrib/ansible/roles/prereq/tasks/main.yml': line 7, column 2, but may
be elsewhere in the file depending on the exact syntax problem.
```
> Fix Ansible indentation

- Dockerfile.dapper
- go.mod
- go.sum
- pkg/cli/cmds/root.go
- scripts/build
- scripts/package-cli
- scripts/sonobuoy
- vendor/github.com/canonical/go-dqlite/internal/bindings/server.go
- vendor/github.com/mattn/go-sqlite3/.travis.yml
- vendor/github.com/mattn/go-sqlite3/README.md
- vendor/github.com/mattn/go-sqlite3/callback.go
- vendor/github.com/mattn/go-sqlite3/sqlite3-binding.h
- vendor/github.com/mattn/go-sqlite3/sqlite3.go
- vendor/github.com/mattn/go-sqlite3/sqlite3_func_crypt.go
- vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go
- vendor/github.com/mattn/go-sqlite3/sqlite3ext.h
- vendor/modules.txt
This enables full embedded HA support by using [dqlite](https://github.com/canonical/dqlite)
```sh
./k3s server --cluster-init --token SECRET
./k3s server -t SECRET -s https://server1:6443
./k3s server -t SECRET -s https://server1:6443
```
And you now have full HA.
Before you get too excited this is going to take a bit of time to bake to iron out the bugs and what not.  We will merge this as an experimental feature for a while so people can test it out.
> dqlite support

- pkg/agent/config/config.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
- pkg/passwd/passwd.go
Sets `--hostname-override` flag for kube-proxy.
Store node password in `/etc/rancher/node/password`, so it will survive an 
uninstall and less likely for server to reject node on re-install.
Provide a `--with-node-id` flag to append random id to node name.
> Node password cleanup

- pkg/daemons/control/server.go
Kubernetes componentstatus check is hardcoded to 10252 and 10251
so we should never change these ports.  If you do componentstatus
will return error.
> Don't ever change 10252/10251 ports

- BUILDING.md
- We migrated "Building from Source" on k3s docs to this GH file.
- Make some small tweaks
Related to https://github.com/rancher/k3s/issues/859
> Add new BUILDING.md with "Building from Source" content from k3s docs

- contrib/util/check-config.sh
This reverts commit 8edbe30c8c3a516a2febc7e4c6edb34867aab435.
> Revert check-config's "Silence modprobe warnings"

- pkg/agent/templates/templates.go
- scripts/airgap/image-list.txt
**Problem:**
base pause image `gcr.io/pause:3.1` can not be accessed with the block of GFW.
**Solution:**
set the default pause image to `docker.io/rancher/pause:3.1`
**Related Issue:**
https://github.com/rancher/k3s/issues/1128
> Update base pause image to rancher repo

- README.md
In the past, yes k3s did exclude all those legacy, alpha, non-default features from Kubernetes source as you can see in https://github.com/rancher/k3s/pull/113. But not anymore.
As you can see in the source code, most of legacy/alpha/non-default features is available in k3s, and misleading README should be updated.
But please, don't get me wrong. I'm actually glad to see those features enabled in k3s. :)
- https://github.com/kubernetes/kubernetes/compare/v1.16.3...rancher:v1.16.3-k3s.1
> Update README.md: k3s does not exclude legacy/alpha/non-default features anymore

- pkg/agent/run.go
- pkg/cli/cmds/agent.go
Values passed in via the server/agent `--node-label` flag are treated as mutable. They are passed through to the kubelet just as before (registration-time) but after the kubelet comes up they are applied again. This allows for passing labels a k3s start-time that may be necessary for scheduling but may change from boot to boot, e.g. `k3os.io/version` after an upgrade.
Tested locally on my amd64 workstation with the docker container.
Addresses #1119.
> Mutable --node-label values for server/agent sub-commands.

- pkg/agent/syssetup/setup.go
Currently servicelb uses klipper-lb as the container which requires ip_forward to be enabled.  The pod does not have a security context set to enable and set this.   This patch will insure that the security context enables this, unfortunately net.ipv4.ip_forward is namespaced but still unsafe which means kublet needs to allow it.
Prior to this patch the host would have ip_foward set to 1, but the containers would have it set to 0 preventing the service load balancer containers from starting.   With this patch, traefik is able to start, but requires passing `--kubelet-arg="allowed-unsafe-sysctls=net.ipv4.ip_forward"` to the server.
In some configurations the containers must already have ip_forward=1 (which does not sound correct from a security standpoint), and I am worried that applying …
> Enable ip forwarding on both all and default net config

- pkg/agent/flannel/setup.go
This reverts commit e712cdf7e8fcc00dfb9786e745efcafb5366ca45, reversing
changes made to d5929bc8c873a33ecf0c187699dbe6de1d6f2f97.
Wireguard docs fail to describe that persistent-keepalive is only valid
when peer is set.
> Revert "Merge pull request #1190 from erikwilson/wireguard-keepalive"

- pkg/agent/flannel/setup.go
> Set wireguard persistent-keepalive on wg set peer

- pkg/agent/tunnel/tunnel.go
I've noticed the following error in k3s logs when running k3s-server on a dual-stack PI cluster:
```
Dec 14 20:46:19 pi-1 k3s[25744]: time="2019-12-14T20:46:19.558820515+01:00" level=info msg="Connecting to proxy" url="wss://192.168.10.14:6443/v1-k3s/connect"
Dec 14 20:46:19 pi-1 k3s[25744]: time="2019-12-14T20:46:19.558829570+01:00" level=info msg="Connecting to proxy" url="wss://2a02:8109:9ac0:36b5:e81b:0:c0a8:a0e:6443/v1-k3s/connect"
Dec 14 20:46:19 pi-1 k3s[25744]: time="2019-12-14T20:46:19.560311466+01:00" level=error msg="Failed to connect to proxy" error="dial tcp: address 2a02:8109:9ac0:36b5:e81b:0:c0a8:a0e:6443: too many colons in address"
Dec 14 20:46:19 pi-1 k3s[25744]: time="2019-12-14T20:46:19.560364280+01:00" level=error msg="Remotedialer proxy error" error="dial tcp: …
```
> Respect IPv6 when building proxy address

- pkg/daemons/agent/agent.go
The containerd flag was accidentally added to kubelet and is
deprecated, but needed for cadvisor to properly connect with
the k3s containerd socket, so adding for now.
For #473
> Run kubelet with containerd flag

- install.sh
cgroups init script is present in Alpine Linux since 3.8.
Fixes #660
> Start cgroups service in OpenRC script

- pkg/agent/run.go
- pkg/nodeconfig/nodeconfig.go
- pkg/nodeconfig/nodeconfig_test.go
https://github.com/rancher/k3s/issues/1342
~The PR injects cli config for server and agents to the node on startup. example:~
The PR adds node args and env annotations on startup
> Inject node config on startup

- pkg/passwd/passwd.go
Renaming files that are open does not work on windows depending on how file is opened. 
Add a scope to ensure that the defer close occurs before rename.
> do not rename inuse files

- contrib/ansible/roles/k3s/master/tasks/main.yml
Sometimes https://127.0.0.1:6443 can be written in the conf by default instead of https://localhost:6443, using `kubectl config set-cluster default` solves the issue.
Home directory is not always in `/home` using `~user` expands the correct path.
> contrib/ansible: Fix home path and use kubectl to set the server url in conf

- .dockerignore
- .drone.yml
- install.sh
- package/k3s.spec
- scripts/package-rpm
- scripts/provision/generic/centos7/gen-gpg-keys
- scripts/provision/generic/centos7/yum-install-rpm-tools
- scripts/provision/vagrant
- scripts/version.sh
> Publish RPMs

- .github/ISSUE_TEMPLATE/bug_report.md
In the bug report template, more clearly ask the user for K3s arguments and logs
> Ask more clearly for K3s args and logs

- pkg/cli/agent/agent.go
This enables agent to start on windows.
I tested connecting to a server running on another windows node, things seemingly worked. Currently I am hand configuring flannel and passing in a few flags to enable startup.
> enable agent to start on windows

- pkg/agent/flannel/setup.go
- pkg/daemons/control/server.go
Windows volume guid paths (ex: "\\?\Volume{26a21bda-a627-11d7-9931-806e6f6e6963}\tmp\k3s") can get tripped up if you mix slash and backslash.
When dealing with files, filepath should be used.
> fix usage of path instead of filepath

- scripts/package-cli
The command rm -f will succeed even if run for a file that does not
exist. Hence it is superfluous to existence check a file that we want
to purge with rm -f, which makes the script a bit simpler to read.
> package-cli: Remove superfluous file exist check

- install.sh
Fix rancher/k3s#1630 by properly checking configuration file.
Without this change, commented-out parameter is incorrectly detected as enabled selinux.
> install: Properly detect enabled selinux

- contrib/ansible/README.md
When I was setting up my cluster, I got to the point where the Ansible README recommends copying down the kubeconfig file from the master server, but the command fails because the path is incorrect. It should be ~/.kube/config and not ~/kube/config (note the missing '.').﻿
> Fix typo in Ansible README file scp command.

- contrib/ansible/roles/raspbian/tasks/main.yml
Closes #1729.
This PR is necessary to make the 'Rebooting on Raspbian' task work at all; without the change the task silently fails on every run, regardless of architecture.﻿
> Fixes #1729: Use 'is changed' instead of non-existent changed filter.

- scripts/package-cli
Moving symlinks to containerd to a for loop makes maintenance easier.
It also reveals a duplicate, redundant, rm -rf build/data and one
duplicate, redundant, rm -rf bin/kubectl, that can be both be purged.
> package-cli: Remove redundant rm -rf build/data

- pkg/agent/templates/templates.go
> Correctly quote auth strings in containerd config. For #1610

- pkg/agent/config/config.go
Right now we require host-local binary to exist always.  This is always there because we include it, but we are working towards variants of k3s that don't include CNI or many other components. This change will require host-local only if k3s' embedded flannel is enabled.
> Only need to resolve the path of host-local if Flannel is enabled

- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
This also help when embedding k3s because we can programmitically know all
the components to disable.
> Move disabled items to a const to keep more consistency

- install.sh
The option `--no-deploy` was deprecated by https://github.com/rancher/k3s/commit/0374c4f63d056df01c3e9e8cf4d77a6461169070 and is replaced with `--disable` in the `install.sh` documentation.
> Replace deprecated option

- pkg/cli/cmds/server.go
Remove redundant Sprintf in [pkg/cli/cmds/server.go](pkg/cli/cmds/server.go)
> remove redundant Sprintf

- pkg/agent/config/config.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
By default now the kubelet will look for ${datadir}/agent/staticpods
to autodeploy as pods. This is for static pods and is different
from the ${datadir}/server/manifests folder which will deploy
any k8s type.
> Suppport static pods at ${datadir}/agent/staticpods

- pkg/daemons/agent/agent.go
- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/executor.go
This moves all the calls to cobra root commands to one package
so that we can change the behavior of running components as embedded
or external.
> Encapsulate execution logic

- pkg/agent/run.go
Don't print a message every second while we are waiting for the
kubelet to report Ready.
> Only echo Waiting for kubelet every 30 seconds

- contrib/ansible/roles/k3s/master/templates/k3s.service.j2
- contrib/ansible/roles/k3s/node/templates/k3s.service.j2
- install.sh
- k3s.service
- package/rpm/install.sh
When k3s is installed on an OS with default high ulimits, performance
issues can be observed. This was discovered on CoreOS where the default
value is 1073741816. Symptoms include very slow file operations such
as installing a Rook/Ceph cluster will take ~6 hours instead of ~10 minutes.
A google search for 'container LimitNOFILE' will show that most major
projects set this already, including the (unused) containerd systemd unit
found in this repository at /vendor/github.com/containerd/containerd/containerd.service
k3OS is not affected becuasse the default there is already 1048576.
See description in coreos/fedora-coreos-tracker#329
> [systemd] Add value to LimitNOFILE due to performance problems

- pkg/agent/config/config.go
- pkg/agent/loadbalancer/loadbalancer.go
- pkg/agent/loadbalancer/loadbalancer_test.go
- pkg/agent/proxy/apiproxy.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/clientaccess/clientaccess.go
- pkg/cluster/https.go
- pkg/daemons/config/types.go
- pkg/daemons/control/server.go
- pkg/server/server.go
- pkg/server/types.go
In k3s today the kubernetes API and the /v1-k3s API are combined into
one http server.  In rke2 we are running unmodified, non-embedded Kubernetes
and as such it is preferred to run k8s and the /v1-k3s API on different
ports.  The /v1-k3s API port is called the SupervisorPort in the code.
To support this separation of ports a new shim was added on the client in
then pkg/agent/proxy package that will launch two load balancers instead
of just one load balancer.  One load balancer for 6443 and the other
for 9345 (which is the supervisor port).
> Add supervisor port

- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/executor.go
- pkg/server/server.go
In rke2 everything is a static pod so this causes a chicken and egg situation
in which we need the kubelet running before the kube-apiserver can be
launched.  By starting the apiserver in the background this allows us to
do this odd bootstrapping.
> Start kube-apiserver in the background

- pkg/cli/server/server.go
- pkg/cluster/https.go
- pkg/daemons/config/types.go
Adding support for TLS MinVersion and CipherSuites and set to VersionTLS12 by default
This will watch for the following kube-apiserver-arg variables and apply them to the k3s kube-apiserver https listener.
--kube-apiserver-arg=tls-cipher-suites=XXXXXXX
--kube-apiserver-arg=tls-min-version=XXXXXXX
Closes #1741 #768
This allows the kubeapi server to run with a secure version of TLS.  Without this change there is no way to disable the insecure versions of TLS. 
The default version can be changed to VersionTLS10 if there is a desire to continue with the current insecure default.
> Feature Request #1741: Adding support for tls minimum version

- channel.yaml
* Updates channel.yaml - replaces v1.17.4 with v1.18.2 which is now stable.
> Bump stable version from v1.17.4 to v1.18.2

- channel.yaml
* This version of k3s addresses two CVEs -- Please reference the release notes
> Update stable channel to v1.18.3+k3s1

- pkg/daemons/control/server.go
Resolves CIS 1.5 issues in regards to profiling of controller manager, api server, and scheduler.
> added profiling = false args to api, controllerManager, and scheduler

- install.sh
When for some reason, k3s crashes, and can't startup again, e.g. when
the data backend is not available (dqlite crashed, database server is
offline, ...), on openrc systems, supervise-daemon will try to restart
it, as per supervise-daemon(8):
respawn-max:
Sets the maximum number of times a daemon will be respawned during
a respawn period. If a daemon dies more than this number of times
during a respawn period, will give up trying to respawn it and exit.
The default is 10, and 0 means unlimited.
Setting respawn-max to 0, makes sure a k3s process on openrc systems will
keep trying to come online, even if the database backend is offline for a
longer period of time.
This aligns the openrc service configuration with the systemd
configuration, which has
Restart=always
RestartSec=5s
> Always keep restarting k3s process by openrc

- cmd/k3s/main.go
- pkg/agent/run.go
This pull request fixes an issue brought to light in #1582 . We're creating a config file for crictl and populating it with either the default containerd sock file path or if the docker flag is issued, we update it to use the dockershim socket path.
> Make packaged crictl work when using Docker

- .github/ISSUE_TEMPLATE/bug_report.md
- Does away with "K3s arguments" section, instead ask for it in repro steps
- Updates repro section to be more clear (maybe we need even more clarity?)
- Small tweaks throughout
> Update GitHub bug_report template

- pkg/agent/netpol/network_policy.go
This network-policy controller runs in the k3s agent, it needs the `system:k3s-controller` user to list pods, namespaces, and network-policies. We can get the RABC info in the `/var/lib/rancher/k3s/server/manifests`. 
There is a race-condition that the network-policy controller should run after the clusterrolebinding. When using containerd, the agent waits for containerd to start, which gives the server time to load clusterrolebinding. If using docker, the agent will start faster. At that moment, it is likely that the server has not loaded clusterrolebinding.
Related issues:
- https://github.com/rancher/k3s/issues/1792
- https://github.com/rancher/k3s/issues/1551
> Add retry backoff for starting network-policy controller

- pkg/agent/netpol/network_policy_controller.go
reopened #1883 - i have singed commit.
I have rebooted a newly created k3s etcd cluster and this panic was triggered:
```
k3s[948]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x45f2945]
k3s[948]: goroutine 1 [running]:
k3s[948]: github.com/rancher/k3s/pkg/agent/netpol.NewNetworkPolicyController(0xc00159e180, 0x61b4a60, 0xc006294000, 0xdf8475800, 0xc011d9a360, 0xc, 0x0, 0xc00bf545b8, 0x2b2edbc)
k3s[948]:         /home/x/git/k3s/pkg/agent/netpol/network_policy_controller.go:1698 +0x275
```
> fixed panic in network_policy_controller

- scripts/download
`k3s-root` v0.5.0 implements the new iptables-detect script. This PR changes the `scripts/download` file to better consume `k3s-root` as the various symbolic link creation commands were moved into the `k3s-root` build process.
> Implement new k3s-root changes

- pkg/daemons/control/server.go
Certificates issued by the signer controller should be issued by the k3s ClientCA instead of the ServerCA so that they are trusted by kube-apiserver, as guaranteed by [the documentation](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers). 
Fixes rancher/k3s#1764
~~While this fixes the reported issue and allows proper issuance of client certificates, I'm not 100% sure that this is the right way to resolve the issue, as it makes the signer controller unable to issue certs that are trusted as servers.~~
~~The correct fix (as mentioned in the issue) is probably to have a master Root CA that issues the ClientCA, ServerCA, and (new) SignerCA keys. This would provide a single trust anchor between all components.~~
> Configure default signer implementation to use ClientCA instead of ServerCA

- pkg/version/version.go
This PR removes the hard coded value that was being passed in to ProgramUpper in favor of the Program variable. This is needed to resolve an issue with environment variable use in RKE2.
> remove hard coded value from ProgramUpper

- install.sh
**This is #1933 backported from master to `release-1.18`**
When for some reason, k3s crashes, and can't startup again, e.g. when
the data backend is not available (dqlite crashed, database server is
offline, ...), on openrc systems, supervise-daemon will try to restart
it, as per supervise-daemon(8):
respawn-max:
Sets the maximum number of times a daemon will be respawned during
a respawn period. If a daemon dies more than this number of times
during a respawn period, will give up trying to respawn it and exit.
The default is 10, and 0 means unlimited.
Setting respawn-max to 0, makes sure a k3s process on openrc systems will
keep trying to come online, even if the database backend is offline for a
longer period of time.
This aligns the openrc service configuration with the systemd …
> backport 1.18 : Always keep restarting k3s process by openrc

- install.sh
**This is #1933 backported from master to `release-1.17`**
When for some reason, k3s crashes, and can't startup again, e.g. when
the data backend is not available (dqlite crashed, database server is
offline, ...), on openrc systems, supervise-daemon will try to restart
it, as per supervise-daemon(8):
respawn-max:
Sets the maximum number of times a daemon will be respawned during
a respawn period. If a daemon dies more than this number of times
during a respawn period, will give up trying to respawn it and exit.
The default is 10, and 0 means unlimited.
Setting respawn-max to 0, makes sure a k3s process on openrc systems will
keep trying to come online, even if the database backend is offline for a
longer period of time.
This aligns the openrc service configuration with the systemd …
> backport 1.17 : Always keep restarting k3s process by openrc

- install.sh
This allows us to fail quickly if we're handed a schemeless or plain
HTTP URI, rather than having the agent barf when the systemd unit
starts. For an operator, this makes for a cleaner error up front and
clear messaging for how to fix the situation.
Addresses #1964 
Signed-off-by: Josh McSavaney <mcsaucy@csh.rit.edu>
> Perform basic validation on K3S_URL in install.sh

- pkg/cli/agent/agent.go
- pkg/cli/cmds/agent.go
Adds the `--protect-kernel-defaults` flag and sets the value to true. This is needed by RKE2 which will set the value to false as part of CIS requirements.
> add protect-kernel-defaults to kubelet

- channel.yaml
Update channel.yaml so v1.18.6 is now our stable version in the channel server.
Is for https://github.com/rancher/k3s/issues/2021
> Set v1.18.6 as stable in channel server

- pkg/agent/config/config.go
- pkg/agent/templates/templates.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/config/types.go
rancher/k3s#924
In some scenarios, we need to change the Snapshotter for Containerd(such as Running K3s in Kata-Containers(9pfs)).
```
--snapshotter value                 (agent/runtime) Customized containerd snapshotter (default: "overlayfs")
k3s server --snapshotter=native
k3s agent --snapshotter=natvie
```
Signed-off-by: Jason-ZW <zhenyang@rancher.com>
> Add containerd snapshotter flag

- pkg/agent/config/config.go
- pkg/cli/agent/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
Adds necessary linkage to get the flag set to the correct value and passed all the way through to kubelet.
> update cis flag implementation to propogate the rest of the way 

- scripts/download
This PR bumps k3s-root to v0.6.0-rc3 in order to support RHEL 7 and 8 operating systems which have VERSION_ID's in /etc/os-release that are of the format X.Y where X is major and Y is minor. This is different than CentOS where the VERSION_ID is simply 7 or 8.
This is work for: https://github.com/rancher/k3s/issues/1812
Signed-off-by: Chris Kim <oats87g@gmail.com>
> Bump k3s-root to v0.6.0-rc3

- install.sh
Also move K3S_URL validation to its own function. This should fix rancher/k3s#1964 
Signed-off-by: Josh McSavaney <mcsaucy@csh.rit.edu>
> Always validate K3S_URL if running agent.

- pkg/server/server.go
As seen in issues such as #15 #155 #518 #570 there are situations where
k3s will fail to write the kubeconfig file, but reports that it wrote it
anyway as the success message is printed unconditionally. Also, secondary
actions like setting file mode and creating a symlink are also attempted
even if the file was not created.
This change skips attempting additional actions, and propagates the
failure back upwards.
> Correctly report and propagate kubeconfig write failures

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
- package/Dockerfile
Should hopefully fix issues that cropped up with arm builds failing due
to the sqlite libs from alpine 3.10 no longer being compatible with
alpine edge, which was probably never a safe assumption to begin with.
> Update base image version in Dockerfiles

- pkg/cluster/managed.go
- pkg/cluster/managed/drivers.go
- pkg/etcd/etcd.go
The PR uses the learner features to add members to the cluster to avoid downtime while adding a second node.
https://github.com/rancher/rke2/issues/53
> Add etcd members as learners

- pkg/daemons/control/server.go
Before this change, k3s configured the scheduler and controller's
insecure ports to listen on 0.0.0.0. Those ports include pprof, which
provides a minor DoS vector.
These ports are only enabled for componentstatus checks in the first
place, and componentstatus is hardcoded to only do the check on
localhost anyway (see
https://github.com/kubernetes/kubernetes/blob/v1.18.2/pkg/registry/core/rest/storage_core.go#L341-L344),
so there shouldn't be any downside to switching them to listen only on
localhost.
> Listen insecurely on localhost only

- install.sh
Fix for issue 1326, added lines to delete /run/k3s and /run/flannel in create_uninstall() function.
> install.sh: cleanup /run on uninstall

- pkg/agent/config/config.go
- pkg/agent/containerd/containerd.go
- pkg/agent/templates/templates.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/config/types.go
Introduces --selinux flag to affirmatively enable SELinux in containerd.
Deprecates --disable-selinux flag which now defaults to true which means auto-detection of SELinux configuration for containerd is no longer supported.
Specifying both --selinux and --disable-selinux will result in an error message encouraging you to pick a side.
> cli: add --selinux flag to agent/server sub-cmds

- cmd/k3s/main.go
Hi,
This PR creates a symbolic link named `current` to the active k3s version artifact dir in `DataDir`. It renames the previous one if it exists.
This is useful for example to install multus CNI that relies on CNI binaries, and look for them by default in `/opt/cni/bin`. Even if we can override this, we would need to know the artifcat dir name at install, and it would not work after a k3s upgrade.
With the current artefact dir symlink, we can either point to `/var/lib/rancher/k3s/data/current/bin`, or create binaries symlinks in `/opt/cni/bin` to the required binaries in `/var/lib/rancher/k3s/data/current/bin`.
Regards,
Ben.
> Create a "current" symlink to artifact dir in DataDir

- pkg/cli/server/server.go
- pkg/rootless/rootless.go
======
Fix handling of `--kube-apiserver-arg` `tls-min-version` and `tls-cipher-suites` options applied to dynamiclistener TLS config.
======
- bugfix
Verification
======
QA to test as per #768
Linked Issues
======
See above
======
Also fixed a minor nit in the rootless fatal exit message that I noticed while testing
> Fix handling of TLS configuration args

- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/server/server.go
- pkg/server/types.go
======
This PR adds the ability to add hooks to be run in bootstrapping in k3s that will ultimately be used during rke2 startup.
======
Adds a slice to a struct field and referenced during k3s start up.
Verification
======
Verification will be had through it's use in this RKE2 pull request. https://github.com/rancher/rke2/pull/199
Linked Issues
======
N/A
======
N/A
> add setup hook capabilities for rke2

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/rancher/helm-controller/pkg/apis/helm.cattle.io/v1/types.go
- vendor/github.com/rancher/helm-controller/pkg/generated/controllers/helm.cattle.io/factory.go
- vendor/github.com/rancher/helm-controller/pkg/generated/controllers/helm.cattle.io/v1/helmchart.go
- vendor/github.com/rancher/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
======
Backport for release-1.18:
Update helm-controller to v0.6.5 to add helm job toleration for node.cloudprovider.kubernetes.io/uninitialized
======
- vendor update
- airgap images
Verification
======
1. Add `bootstrap: true` to HelmChart spec
1. Check for new toleration on helm job allowing job to run on uninitialized node
Linked Issues
======
#2140
> Update helm-controller to v0.6.5 to add helm job toleration

- install.sh
This will fix the issue to allow setting `K3S_TOKEN_FILE` as an acceptable pre-check criteria.
> update install.sh to respect K3S_TOKEN_FILE

- pkg/agent/templates/registry.go
- pkg/agent/templates/templates.go
This PR adds the option for `insecure_skip_verify` to the containerd registry template.
It can be found in containerd code over here: https://github.com/containerd/cri/blob/63400c769422618e2998823ec548671cf3e150b1/pkg/config/config.go#L139
> Feature: add insecure_skip_verify field to registry config template

- install.sh
- package/rpm/install.sh
Signed-off-by: Patrick Force <patrickforce@gmail.com>
======
* Fixing issue where the install.sh script umount calls end up with an arg list that's too long. Just split up the calls.
======
* Bugfix
Verification
======
Testing the `do_unmount` method continues to operate as expected in all cases. The updated function(s) were tested in isolation to make sure they still work correctly.
Linked Issues
======
* https://github.com/rancher/k3s/issues/2120
> 2120: fix issue with umount arg list too long on uninstall

- pkg/configfilearg/parser.go
- pkg/configfilearg/parser_test.go
- pkg/configfilearg/testdata/data.yaml
Previously a bool flag would be rendered as `--flag false` for `flag: false`
which is invalid and results in the opposite of what you'd expect.
> All arguments should be of the form --k=v so that bool flags will work

- CONTRIBUTING.md
- README.md
======
Fix missing article in
> The memory footprint is reduced primarily by running many components inside of `a` single process.
And typo in 
> The DCO is a simple statement that you, as a contributor, have the legal ~rite~ `right` to make the contribution.
======
Typo fixes
> Typo fixes

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
- go.mod
- vendor/modules.txt
Update golang to track with upstream
* golang version
* Check build logs or Dockerfile (go minor version is not reported by `kubectl version`)
For #2230
> Update golang to 1.15.2

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
We need to make the expectations around git commits and the process for
pull requests more clear to contributors.
> Add guidance on PRs and git commits

- go.mod
- go.sum
- vendor/go.etcd.io/etcd/etcdserver/raft.go
- vendor/modules.txt
Update etcd in go mod to use the rancher fork with the latest fix for the panic issue
go mod change
we want to make sure that --cluster-reset works in HA mode
https://github.com/rancher/k3s/issues/2131
https://github.com/rancher/k3s/issues/2227
The issue is a bug in etcd, and there is an issue opened in upstream and associated pr as well
https://github.com/etcd-io/etcd/issues/12285
https://github.com/etcd-io/etcd/pull/12288
> update etcd to use rancher fork

- pkg/clientaccess/clientaccess.go
- pkg/cluster/https.go
- ##### Problem : #####
GetCACerts function initial check was to try and get the Certificates with https.DefaultClient, which resulted in tls handshake error when http request is sent in client.Do(req) https://github.com/rancher/k3s/blob/7f32e50bf795af0dff5ce9b14968d9b4ca7fbe51/pkg/clientaccess/clientaccess.go#L261
- ##### Proposed fix #####  
Remove the initial check that's causing bad certificates error and validate if the certificates exist using insecureClient 
Bugfix 
run k3s/rke2 multinode cluster and check the server logs, tls handshake errors presented in the issue below will not appear
https://github.com/rancher/rke2/issues/48
> Add error logger to http server

- pkg/codegen/main.go
- pkg/deploy/nostage.go
- pkg/deploy/stage.go
- pkg/deploy/zz_generated_bindata.go
- pkg/static/nostage.go
- pkg/static/stage.go
- pkg/static/zz_generated_bindata.go
Put the k3s manifests and static content inside a build tag so that we can disable them when compiling for rke2
* build tag
1. Add no_stage to TAGS in scripts/build
1. Build k3s
1. Start k3s on clean system
1. Note that /var/lib/rancher/k3s/server/manifests and /var/lib/rancher/k3s/server/static are not created
Related to https://github.com/rancher/rke2/issues/232
This breaks k3s unless the user provides their own copy of all the core manifests (role bindings, coredns, etc), but this is the desired behavior for RKE2 which provides its own content.
> Add support for disabling all staged content at build time

- pkg/agent/containerd/containerd.go
Set WithAllPlatforms option on containerd image import.
* airgap image load
1. Perform airgap install on arm64
1. Run `k3s ctr images check`; verify all image layers present
1. Run `k3s kubectl get pods -A`; verify all pods running or completed
Related to #1285
Some of the images contain configs that indicate they are amd64 despite actually being arm64. This causes the containerd import process to skip their layers since it filters out mismatched architectures by default. Setting the option to import layers for all platforms allows us to use these images anyways, until the upstreams are fixed.
> Import containerd images with all platforms

- pkg/agent/netpol/network_policy.go
- pkg/daemons/control/server.go
Since we're replacing the k3s rolebindings.yaml in rke2, we should allow changing the CN on the agent tunnel controller cert so that we can use the white-labeled name downstream.
Note that this doesn't affect anything within the agent tunnel controller itself, it just needs to match the subject that we target with the rolebinding at https://github.com/rancher/k3s/blob/master/manifests/rolebindings.yaml#L62
* k3s tunnel controller
* RBAC
* No change for k3s
This will be needed as part of the fix for https://github.com/rancher/rke2/issues/324
Since we're finally dropping all the k3s manifests in rke2, we no longer need to keep the subject static to work with rolebindings.yaml.
> Set tunnel controller certificate CN from build-time program name

- scripts/package-airgap
Only create k3s-images.txt on amd64
* CI
* Tag a release
* No more failed builds!
#2271
The list is the same across architectures, and is validated against the
list in git as part of CI... so there's no reason to be pushing it from
every pipeline. It's also causing conflicts when multiple pipelines try
to upload it at the same time.
> Only create k3s-images.txt on amd64

- scripts/package-airgap
Backport of #2273 - Only create k3s-images.txt on amd64
* CI
* Tag a release
* No more failed builds!
#2271
The list is the same across architectures, and is validated against the
list in git as part of CI... so there's no reason to be pushing it from
every pipeline. It's also causing conflicts when multiple pipelines try
to upload it at the same time.
> [1.19 Backport] Only create k3s-images.txt on amd64

- scripts/package-airgap
Backport of #2273 - Only create k3s-images.txt on amd64
* CI
* Tag a release
* No more failed builds!
#2271
The list is the same across architectures, and is validated against the
list in git as part of CI... so there's no reason to be pushing it from
every pipeline. It's also causing conflicts when multiple pipelines try
to upload it at the same time.
> [1.18 Backport] Only create k3s-images.txt on amd64

- scripts/package-airgap
Backport of #2273 - Only create k3s-images.txt on amd64
* CI
* Tag a release
* No more failed builds!
#2271
The list is the same across architectures, and is validated against the
list in git as part of CI... so there's no reason to be pushing it from
every pipeline. It's also causing conflicts when multiple pipelines try
to upload it at the same time.
> [1.17 Backport] Only create k3s-images.txt on amd64

- Dockerfile.dapper
Adds Docker volume to cache the Trivy database, similar to how we mount a volume to cache go libraries.
* Dapper
* CI
* Run CI build
* Note that it only downloads the Trivy DB once every 12 hours
@cjellick do you have an issue for this?
If this works we'll need to do the same for other projects using Trivy to prevent rate-limiting
> Add trivy cache volume to build

- pkg/etcd/etcd.go
Don't take snapshots if the local endpoint is still a learner
Also added doc comments where missing or incorrect
* etcd
* start k3s with short snapshot interval (cron expression for every minute)
* note snapshots are skipped until node is no longer a learner
Related to https://github.com/rancher/rke2/issues/292
We still need to properly handle nodes that join the etcd cluster but not k8s cluster, but this should fix the issue @rancher-max turned up when testing with very short snapshot invervals.
> Skip etcd snapshots if the local endpoint is still a learner

- channel.yaml
Mark k3s v1.18.9+k3s1 as stable in public channelserver
https://github.com/rancher/k3s/issues/2225
> Mark k3s v1.18.9+k3s1 as stable

- install.sh
- package/rpm/install.sh
======
Adds the line `After=network-online.target` to the k3s systemd service
file. This applies the fix mentioned in
[this GH comment](https://github.com/rancher/k3s/issues/1626#issuecomment-642253812)
which I can confirm makes k3s networking survive reboot in Raspbian
Buster.
======
- Bugfix
Verification
======
Testing steps:
1. You can confirm that networking doesn't adequately restore before applying this fix by using a Raspi 3 running a recent, clean install of Raspbian Buster and installing k3s on it using all the defaults. If you reboot this Pi set up this way, pods such as a deployed Dashboard enter the CrashLoopBackoff state.
2. After applying this fix [you can even edit the service file in-place to add this line] rebooting the pi now cleanly …
> Add network dependency to installed service file

- install.sh
- k3s.service
- package/rpm/install.sh
`Wants=` is required to actually set the dependency on `network-online.service`
`After=` is required or `k3s.service` will be started at the same time as `network-online.service`
In network environments with slow DHCP, both are required to ensure valid network configuration for k3s
**Before:**
```
-- Logs begin at Tue 2020-04-22 01:02:36 CEST, end at Wed 2020-04-22 01:04:01 CEST. --
Apr 22 01:03:48 localhost systemd[1]: Starting Lightweight Kubernetes...
Apr 22 01:03:48 localhost k3s[860]: time="2020-04-22T01:03:48Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/44b43856accd3b248b71bf2f479f3513c942559af34c7b91b2ed3795f107c815"
Apr 22 01:03:50 localhost k3s[860]: time="2020-04-22T01:03:50.989048441Z" level=info msg="Starting k3s v1.18.2-rc1+k3s1 (553517e1)"
Apr 22 01:03:50 …
```
> [systemd] really wait for network to come online

- install.sh
It's a bad practice to install packages via rpm directly. It's better to install all packages with Yum/Dnf. It's also possible to install packages directly via an URL, which is the purpose of this PR.
> feat(install): replace rpm by yum for setup_selinux

- pkg/agent/config/config.go
- pkg/agent/run.go
- pkg/clientaccess/clientaccess.go
- pkg/clientaccess/kubeconfig.go
- pkg/clientaccess/token.go
- pkg/cluster/bootstrap.go
- pkg/cluster/cluster.go
- pkg/cluster/encrypt.go
- pkg/cluster/https.go
- pkg/cluster/managed.go
- pkg/cluster/managed/drivers.go
- pkg/cluster/router.go
- pkg/cluster/storage.go
- pkg/etcd/etcd.go
* Ignore --token and --server if the managed database is initialized, just like we ignore --cluster-init. If the user wants to join a new cluster, or rejoin a cluster after --cluster-reset, they need to delete the database.
* Refactor clientaccess token handling for improved readability and to reduce the number of http requests necessary to bootstrap.
* Add doc comments to clientaccess and cluster startup code.
* Remove unused code from cluster managedDB setup.
* Fix etcd directory permissions warning
* embedded etcd
* token handling
* doc comments
1. Follow reproduction steps in linked issue
1. Cluster starts up successfully from quorum-loss state.
Should see a warning when starting the second node: `Ignoring bootstrap token validation error on initialized member due to cluster quorum …
> Fix managed etcd cold startup deadlock issue #2249

- pkg/cluster/managed.go
* Revert commit that broke rke2 etcd.
* Add comments explaining what code is for
* Managed DB
* Build RKE2 with this branch
* Note that etcd pod is started and cluster functions properly, instead of starting kine+sqlite and then crashing
N/A - @galal-hussein reported an inability to start RKE2 after updating to k3s@master and this was the result of the investigation.
I called out this block in code review and nobody could think of a reason to keep it.
I still don't know what the first bit is doing with checking for an etcd:// prefix on the endpoint string, but I'll leave it there without a comment until I can figure it out.
> Revert removal of EndpointName hooks

- pkg/cluster/managed.go
- pkg/etcd/etcd.go
Allow for multiple restoration
enhancement to snapshot restore
- start k3s with cluster-init and snapshot schedule
- pass --cluster-reset and --cluster-reset-restore-path <snapshot>
- when k3s exits with message `INFO[0075] Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes` run again with same flags
k3s should restore again the same snapshot, two etcd-old-<date> directory should be created in /var/lib/rancher/k3s/server/db/
https://github.com/rancher/rke2/issues/353
> Allow for multiple etcd snapshot restoration

- pkg/cluster/bootstrap.go
If available, store clientAccessInfo even if the managed database is already initialized. There is a timing issue with etcd startup - if the process is killed after the new node is joined to the etcd cluster, but before it is promoted to learner, it will need the info again on next startup to finish promoting itself.
* Managed etcd
* Follow instructions in the linked issue. Should be possible to replicate by terminating any k3s or rke2 server just just after it joins the etcd cluster for the first time.
This is a minimal fix for https://github.com/rancher/rke2/issues/392
> Add temporary fix for issue with interrupted etcd promote

- pkg/clientaccess/clientaccess.go
Use `/cacerts` for clientaccess instead of `/apis` to follow 1.19 supervisor port change. 
https://github.com/rancher/k3s/commit/e5fe184a441ec5a61420a30aaf3d5e6524ebc08e#diff-fc9e094a7966f92b19b6a2a56eb78cd9L151
Bugfix
Join 1.18 agent to 1.19 server
#2311
> Backport 1.18 agent cacerts clientaccess

- pkg/clientaccess/clientaccess.go
Use `/cacerts` for clientaccess instead of `/apis` to follow 1.19 supervisor port change. 
https://github.com/rancher/k3s/commit/e5fe184a441ec5a61420a30aaf3d5e6524ebc08e#diff-fc9e094a7966f92b19b6a2a56eb78cd9L151
Bugfix
Join 1.17 agent to 1.19 server
#2311
> Backport 1.17 agent cacerts clientaccess

- pkg/server/server.go
When building a default `NO_PROXY` environment variable we should include the lowercase `no_proxy` environment variable, and include the `.svc` and cluster domains.
Bugfix
See #2176
#2176
> Use no_proxy env, add .svc and cluster domains

- .github/SECURITY.md
- README.md
Signed-off-by: Jeremy Katz <jeremy@tidelift.com>
This adds information on how to report security issues in k3s to the readme and the github format SECURITY.md
Documentation
Simple documentation
https://github.com/rancher/k3s/issues/2070
Trivial
> Add information on reporting security issues

- pkg/cluster/managed.go
- pkg/cluster/managed/drivers.go
- pkg/daemons/executor/etcd.go
- pkg/daemons/executor/executor.go
- pkg/etcd/etcd.go
* Make etcd voting members responsible for managing learners
* Fix warnings from #2303
* managed etcd
1. `k3s server --cluster-init --token token`on node 1
1. `k3s server --server https://node1:6443 --token token` on node 2; hit control-C to kill k3s immediately after you see log lines from etcd
1. Wait 2 minutes
1. `k3s server --server https://node1:6443 --token token` on node 3; note that node 3 can join because node 2's failed promotion has been automatically cleaned up
1. Start k3s on node 2 again; note error message with instructions to remove old etcd db directory
1. Follow instructions to remove directory on node 2
1. Start k3s on node 2 again; note that it successfully joins the cluster.
#2329
> Make etcd voting members responsible for managing learners

- install.sh
- pkg/agent/syssetup/setup.go
Signed-off-by: Chris Kim <oats87g@gmail.com>
This adds logic to auto-install the `k3s-selinux` and corresponding repositories on el7/el8 systems. This is an improvement over the existing logic today which simply has the user run a `yum` command as a workaround.
Install script changes
This can be verified by attempting to install `K3s` on an EL7/EL8 system that falls into the following:
RHEL 7
RHEL 8
CentOS 7
CentOS 8
Oracle Linux 7
Oracle Linux 8
This should be checked through:
`INSTALL_K3S_CHANNEL=testing ./install.sh` which will install K3s using the testing channel
`INSTALL_K3S_CHANNEL=testing INSTALL_K3S_SKIP_SELINUX_RPM=true ./install.sh` which will install K3s but fail out because the K3s selinux RPM needs to be "manually" installed". Can be useful for things like airgap. 
For now, …
> Add auto-install capability to install.sh for k3s-selinux

- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/etcd/etcd.go
Etcd now uses advertised ip, which is the node external ip if it was passed to the cli, this change makes etcd use node private ip by default 
Bugfix
run k3s server with --cluster-init and --node-external-ip <node-ip> and make sure k3s is up and running
https://github.com/rancher/k3s/issues/2345
> Make etcd use node private ip

- main.go
/bin/rm is less portable. On some distros, like nixos, it doesn't exist
at all.
Right now, [nixpkgs carries this patch](https://github.com/NixOS/nixpkgs/blob/a948654086898aa95541bcd2ab39325588dc3332/pkgs/applications/networking/cluster/k3s/patches/0001-Use-rm-from-path-in-go-generate.patch) in order to compile the k3s there, but this seems like a reasonable thing to just merge in upstream.
> Use 'rm' from path in go generate

- pkg/cli/cmds/nostage.go
- pkg/cli/cmds/server.go
- pkg/cli/cmds/stage.go
The --disable/--no-deploy flags actually turn off some built-in controllers, in addition to preventing manifests from getting loaded. Make it clear which controllers can still be disabled even when the packaged components are ommited by the no_stage build tag.
* CLI
* Build k3s with no_stage tag
* Check `k3s --help | grep disable`
Related to https://github.com/rancher/rke2/issues/376
I wasn't thinking about the controller-disabling side effect of the --disable flag when I committed https://github.com/rancher/rke2/pull/361 - so I will need to partially revert that after this is pulled in.
> Update disables list when building with no_stage

- Dockerfile.test.dapper
- e2e/Dockerfile
- e2e/run-test.sh
- scripts/test-helpers
- scripts/version.sh
Update sonobuoy version and move to rancher-mirrored image
* CI
* Check CI logs, confirm that sonobuoy tests are using rancher/sonobuoy-sonobuoy instead of sonobuoy/sonobuoy
Related to #2479
> Update sonobuoy version and use rancher mirrored image

- channel.yaml
Mark the latest v1.19.x release as stable - final task from 2020-10-30 release checklist
* Channel
* Install k3s from latest channel
* Check version with k3s --version
Related to #2460
> Mark the latest v1.19.x release as stable

- .drone.yml
- Dockerfile.dapper
* Add unprivileged GitHub token to work around rate-limiting when downloading Trivy DB from GH
* CI
Check CI logs, look for message: `Use your github token` when Trivy is downloading the DB
Related to rancherlabs/eio/#296
> Add GH auth for Trivy

- pkg/agent/config/config.go
Removing the cfg.DataDir mutation in 3e4fd7b did not break anything, but did change some paths in unwanted ways. Rather than mutating the user-supplied command-line flags (which we generally try to avoid doing), explicitly specify the agent subdirectory as needed.
Regression fix
* Start k3s with `k3s server --data-dir=/opt/k3s`
* Confirm all items are correctly located: `find /opt/k3s/agent/ -maxdepth 3`:
```
/opt/k3s/agent/
/opt/k3s/agent/client-ca.crt
/opt/k3s/agent/server-ca.crt
/opt/k3s/agent/serving-kubelet.crt
/opt/k3s/agent/serving-kubelet.key
/opt/k3s/agent/client-kubelet.crt
/opt/k3s/agent/client-kubelet.key
/opt/k3s/agent/kubelet.kubeconfig
/opt/k3s/agent/client-kube-proxy.crt
/opt/k3s/agent/client-kube-proxy.key
/opt/k3s/agent/kubeproxy.kubeconfig …
```
> Explicitly set agent paths within --data-dir

- .drone.yml
- Dockerfile.dapper
* Add unprivileged GitHub token to work around rate-limiting when downloading Trivy DB from GH
* CI
Check CI logs, look for message: `Use your github token` when Trivy is downloading the DB
Related to rancherlabs/eio/#296
> [1.19 Backport] Add GH auth for Trivy

- go.mod
- go.sum
- vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
- vendor/modules.txt
Do not relabel container /dev/shm when it is host /dev/shm.
bugfix
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
Additionally, with HostIPC=true:
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1 --overrides='{ "apiVersion": "v1", "spec": { "hostIPC" : true} }'
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
And a directory listing of `/dev/shm` should look like:
```shell
ls -alZ /dev/shm/
drwxrwxrwt. root root system_u:object_r:tmpfs_t:s0     .
drwxr-xr-x. root root system_u:object_r:device_t:s0    ..
-rw-------. root root system_u:object_r:container_file_t:s0 …
```
> cri: pull in updated /dev/shm fix

- go.mod
- go.sum
- vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
- vendor/modules.txt
Do not relabel container /dev/shm when it is host /dev/shm.
bugfix
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
Additionally, with HostIPC=true:
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1 --overrides='{ "apiVersion": "v1", "spec": { "hostIPC" : true} }'
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
And a directory listing of `/dev/shm` should look like:
```shell
ls -alZ /dev/shm/
drwxrwxrwt. root root system_u:object_r:tmpfs_t:s0     .
drwxr-xr-x. root root system_u:object_r:device_t:s0    ..
-rw-------. root root system_u:object_r:container_file_t:s0 …
```
> [backport 1.19] cri: pull in updated /dev/shm fix

- go.mod
- go.sum
- vendor/github.com/containerd/cri/pkg/server/container_create.go
- vendor/modules.txt
Do not relabel container /dev/shm when it is host /dev/shm.
bugfix
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
Additionally, with HostIPC=true:
```shell
kubectl run envoy --image=envoyproxy/envoy:v1.14.1 --overrides='{ "apiVersion": "v1", "spec": { "hostIPC" : true} }'
pod/envoy created
kubectl get pod
NAME    READY   STATUS    RESTARTS   AGE
envoy   1/1     Running   0          18s
```
And a directory listing of `/dev/shm` should look like:
```shell
ls -alZ /dev/shm/
drwxrwxrwt. root root system_u:object_r:tmpfs_t:s0     .
drwxr-xr-x. root root system_u:object_r:device_t:s0    ..
-rw-------. root root system_u:object_r:container_file_t:s0 …
```
> [backport 1.18] cri: pull in updated /dev/shm fix

- go.mod
- go.sum
- scripts/build
- vendor/modules.txt
- rancher/cri :arrow_right: k3s-io/cri
- rancher/cri-tools :arrow_right: k3s-io/cri-tools
- rancher/containerd :arrow_right: k3s-io/containerd
Part of https://github.com/rancher/k3s/issues/2189
> [migration k3s-io] update containerd, cri, and cri-tools replace directives

- channel.yaml
Mark v1.19.4+k3s1 as stable
channelsever
install k3s via the curl command(without passing a channel or setting channel to stable) the installed version should be v1.19.4+k3s1 
https://github.com/rancher/k3s/issues/2574
> Mark v1.19.4+k3s1 as stable

- go.mod
- pkg/agent/run.go
- vendor/modules.txt
Support cgroup v2.
This PR does not add support for rootless cgroup yet. Rootless cgroup will be supported in a separate PR soon.
New Feature (?)
- Boot Ubuntu 20.10 with kernel cmdline `systemd.unified_cgroup_hierarchy=1`
- Run `sudo k3s server`
- Run `sudo k3s kubectl get pods -A`, and confirm that no error is happening
> Support cgroup v2

- pkg/rootless/mounts.go
Fix "stat /run/user/1000: no such file or directory" error that happend on `kubectl run` because
k3s was mounting a tmpfs on `/run` by itself and hiding RootlessKit's `/run`.
Bugfix
```console
$ k3s server --rootless
```
```console
$ KUBECONFIG=~/.kube/k3s.yaml kubectl run -it --rm --image=alpine --restart=Never foo
If you don't see a command prompt, try pressing enter.
/ # 
```
Fix #2421
> rootless: fix "stat /run/user/1000: no such file or directory" on `kubectl run`

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/.travis.yml
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/cmd/containerd-shim/main_unix.go
- vendor/github.com/containerd/containerd/cmd/containerd/command/service_windows.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/shim/shim.go
- vendor/github.com/containerd/containerd/container_restore_opts.go
- vendor/github.com/containerd/containerd/content/helpers.go
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
- vendor/github.com/containerd/containerd/go.mod
- vendor/github.com/containerd/containerd/go.sum
- vendor/github.com/containerd/containerd/runtime/v1/linux/bundle.go
- vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
- vendor/github.com/containerd/containerd/runtime/v2/runc/v2/service.go
- vendor/github.com/containerd/containerd/runtime/v2/shim.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/shim_unix.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Bump **`containerd`** to **`v1.4.3-k3s1`**
Dependency bump.
Start up k3s, making sure that everything runs, then:
```bash
kubectl get node,all -A -o wide
```
For the resulting output the version for the container runtime should report as containerd v1.4.3-k3s1
https://github.com/k3s-io/k3s/issues/2618
n/a
> [release-1.19] containerd: v1.4.3-k3s1

- install.sh
a couple of tests for the k3s installer to enable flatcar install with fewer (no) parameters.
checks inside the installer
on a Flatcar host: `bash ./install.sh`
one thing this does not address yet is the `/usr/libexec/kubernetes` path for plugins. 
As an example, a user can make an overlay mount before running the k3s installer: https://gist.github.com/vbatts/705c2542df39495319c8601c01b658e8#file-cloud-config-yaml-L17
But this seems a bit in the weeds for this installer to do, unless the maintainers say so, and then I'll add this. Because it's just a `mkdir` and a systemd unit
> install.sh: support install on Flatcar with no args

- install.sh
This addresses #2435 by adding an `rm` call to the uninstall script after the given resource is unmounted.
The directories listed below shouldn't exist.
```sh
ls '/run/k3s'
ls '/var/lib/rancher/k3s'
ls '/var/lib/kubelet/pods'
ls '/run/netns/cni-*'
```
#2435
> Update uninstall script to remove mount point path after umount

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/.travis.yml
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/cmd/containerd-shim/main_unix.go
- vendor/github.com/containerd/containerd/cmd/containerd/command/service_windows.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/shim/shim.go
- vendor/github.com/containerd/containerd/container_restore_opts.go
- vendor/github.com/containerd/containerd/content/helpers.go
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
- vendor/github.com/containerd/containerd/go.mod
- vendor/github.com/containerd/containerd/go.sum
- vendor/github.com/containerd/containerd/runtime/v1/linux/bundle.go
- vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
- vendor/github.com/containerd/containerd/runtime/v2/runc/v2/service.go
- vendor/github.com/containerd/containerd/runtime/v2/shim.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/shim_unix.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
- vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Bump **`containerd`** to **`v1.4.3-k3s1`**
Dependency bump.
Start up k3s, making sure that everything runs, then:
```bash
kubectl get node,all -A -o wide
```
For the resulting output the version for the container runtime should report as containerd v1.4.3-k3s1
https://github.com/k3s-io/k3s/issues/2618
n/a
> containerd: v1.4.3-k3s1

- channel.yaml
Limit the `testing` channel(s) to alpha, beta, and rc pre-releases.
> channels: tweak testing channel config(s)

- pkg/daemons/agent/agent.go
Add detection of `/init.scope` (in addition to `/` for `systemd`
Bugfix
https://github.com/rancher/k3s/issues/2548
Follow up to: https://github.com/k3s-io/k3s/pull/2642
> Add check for `/init.scope` for cgroup

- pkg/daemons/agent/agent.go
Backport of: https://github.com/k3s-io/k3s/pull/2654
Add detection of `/init.scope` (in addition to `/` for `systemd`
Bugfix
https://github.com/rancher/k3s/issues/2548
Follow up to: https://github.com/k3s-io/k3s/pull/2646
> [Backport 1.19] Add check for `/init.scope` for cgroup

- pkg/agent/loadbalancer/loadbalancer_test.go
- pkg/authenticator/hash/hash.go
- pkg/authenticator/hash/scrypt.go
- pkg/authenticator/hash/scrypt_test.go
- pkg/node/controller.go
- pkg/nodepassword/nodepassword.go
- pkg/nodepassword/nodepassword_test.go
- pkg/passwd/passwd.go
- pkg/server/router.go
- pkg/server/server.go
- scripts/generate
- scripts/validate
- vendor/golang.org/x/crypto/scrypt/scrypt.go
- vendor/modules.txt
Store node passwords as hashed secrets and remove on node delete.
Bugfix
For #802
>  Use secrets for node-passwd entries

- pkg/daemons/agent/agent.go
Set the `kubelet-cgroups` and `runtime-cgroups` flags depending on conditions.
Bugfix
Run K3s from shell, using `K3d`, and as a `systemd` controlled daemon and observe no cgroup complaints.
https://github.com/k3s-io/k3s/issues/2548
> Set kubelet-cgroups if we detect we are running under a `.scope`

- pkg/daemons/agent/agent.go
Backport of https://github.com/k3s-io/k3s/pull/2668
Set the `kubelet-cgroups` and `runtime-cgroups` flags depending on conditions.
Bugfix
Run K3s from shell, using `K3d`, and as a `systemd` controlled daemon and observe no cgroup complaints.
https://github.com/k3s-io/k3s/issues/2548
> [Backport 1.19] Set kubelet-cgroups if we detect we are running under a `.scope`

- package/Dockerfile
- scripts/test-helpers
Fix warnings and a common flake in CI scripts
* CI
* Run CI tests or open PR and check CI logs
* Note lack of errors and warnings from linked PR
k3s-io/k3s#2656 
The port-used check was only finding used ports if they were listening on 127.0.0.1 (or 0.0.0.0), which occasionally resulted in choosing a port that was actually already in use.
> Clean up CI warnings/errors

- pkg/etcd/controller.go
63f2211b314d5e2e8c7b7cef027ffe369b5955f5 replaced the master role with control-plane for etcd nodes, when it should have added it instead. The old role cannot go away until after the transition period.
Bugfix
* Create multi-node cluster with embedded etcd
* Note correct labels (control-plane, master, etcd) on all nodes
k3s-io/k3s#2385
Thanks @erikwilson!
> Restore legacy master role for etcd nodes

- Dockerfile.manifest
Fix manifest CI step by installing bash, as we do in other Dockerfiles.
I broke this in 50ea2d816421d371cbbee7094310c0b8d3786113 when I standardized on bash for all the CI scripts. Unfortunately I didn't notice that the manifest step Dockerfile is missing bash.
CI
* Tag release
* Note that deploy succeeds
k3s-io/k3s#2556
> Fix manifest CI step

- cmd/k3s/main.go
- pkg/cli/cmds/root.go
- pkg/configfilearg/defaultparser.go
- pkg/configfilearg/parser.go
Add support for both config-file and data-dir at a global level in the self-extracting wrapper for K3s
Adds `data-dir` and `config-file` parsing to the K3s self-extracting wrapper to ensure that we always use our desired `data-dir`.
Enhancement
Run the various `k3s` CLI commands with `--data-dir` or create a config file (`/etc/rancher/k3s/config.yaml`) with `data-dir: ` defined in it and observe `K3s` should always use this.
https://github.com/rancher/k3s/issues/2593
https://github.com/rancher/k3s/issues/2563
> Add support for both config-file and data-dir at a global level in the self-extracting wrapper for K3s

- .drone.yml
Same as #2716 - missed another step, this one a direct invocation from Drone.
Fix by updating curl image (clean as you go) and installing bash before running the script.
* CI
* Tag release
* Note that deploy succeeds
k3s-io/k3s#2556
mea culpa @briandowns, you tried to warn me :/
> Add bash to curl image before running dispatch script

- Dockerfile.test.dapper
- install.sh
- package/rpm/install.sh
- pkg/agent/netpol/network_policy_controller.go
- pkg/agent/netpol/utils.go
- pkg/agent/run.go
- pkg/cluster/bootstrap.go
- pkg/cluster/https.go
- pkg/cluster/managed.go
- scripts/codespell.sh
- scripts/test
Fix the code spell error reported from https://github.com/codespell-project/codespell.
- Add a code spell test in CI `./scripts/codespell.sh`
- Correct code spelling
None
None
Not sure what's the `ba` means in https://github.com/k3s-io/k3s/blob/4317a91/scripts/provision/vagrant#L54
So I add ignore `ba` in https://github.com/k3s-io/k3s/blob/d64b687223aeaa8ca91b6b3a38595f12ec45f68b/scripts/codespell.sh#L5-L6
> Add codespell CI test and fix codespell error

- cmd/k3s/main.go
If the user is the root, use default data-dir `/var/lib/rancher/k3s`.
Otherwise, use default home data-dir `$HOME/.rancher/k3s`.
Bugfix
Use the normal user account (non-root), start the server passing either `--rootless` or `--disable-agent`
```
k3s server --cluster-init --rootless
k3s server --cluster-init --disable-agent
```
#2780
> Fix normal user with --rootless or --disable-agent have no permission to start

- pkg/agent/config/config.go
- pkg/server/router.go
- pkg/server/server.go
Allow a local server to bootstrap kubelet certs if the api-server is not yet up by verifying cert request against saved password on disk and adding node password to secrets when it becomes available.
Needed for rke2 moving node passwords to secrets
In RKE2, starting server instance using head of k3s main branch
https://github.com/rancher/rke2/issues/616
> Bootstrap node password with local file

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Update helm-controller to v0.8.3
* helm controller
* Taint nodes with "CriticalAddonsOnly=true:NoExecute"; note that helm jobs don't fail to run.
* Install helm v2 chart from stable repo (see example from https://github.com/k3s-io/helm-controller/blob/master/test/suite/helm_test.go#L176); note that chart is installed successfully
#2777
rancher/rke2#487
k3s-io/klipper-helm#25
> Update helm-controller to v0.8.3

- pkg/etcd/etcd.go
Signed-off-by: MonzElmasry <menna.elmasry@rancher.com>
change the permission of etcd dir if it exists after upgrades
backport
```
sudo ls -ld /var/lib/rancher/k3s/server/db/etcd
```
https://github.com/k3s-io/k3s/pull/2784
> [release-1.19 ]change etcd dir permission if it exists

- pkg/agent/config/config.go
Problem:
While using ZFS on debian and K3s with docker, I am unable to get k3s working as the snapshotter value is being validated and the validation fails.
Solution:
We should not validate snapshotter value if we are using docker as it's a no-op in that case.
Signed-off-by: Waqar Ahmed <waqarahmedjoyia@live.com>
Bug Fix
> Do not validate snapshotter argument if docker is enabled

- channel.yaml
mark k3s v1.20.2 as stable
channelserver
install k3s with no passed channels, should pull v1.20.2 as default from stable channel
https://github.com/k3s-io/k3s/issues/2794
> mark k3s v1.20.2 as stable

- Dockerfile.test.dapper
- scripts/test-helpers
Update sonobuoy version for v1.20.0
Also drop the rancher-mirrored sonobuoy image since CI has a pull-through image cache now.
CI
See CI warnings in linked issue
Related to #2840
> Update sonobuoy version for v1.20.0

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/instances.go
Replace k3s cloud provider wrangler controller with core node informer
Upstream k8s has exposed an interface for cloud providers to access the
cloud controller manager's node cache and shared informer since
Kubernetes 1.9. This is [used by](https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go#L801) all the other in-tree cloud providers;
we should use it too instead of running a dedicated wrangler controller.
Doing so also appears to fix an intermittent issue with the uninitialized
taint not getting cleared on nodes in CI.
* bugfix
* cloud-provider
See CI failures in linked issue
Related to #2841
> Replace k3s cloud provider wrangler controller with core node informer

- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/etcd/etcd.go
k3s doesn't allow users to scrape metrics for etcd because it's bonded to localhost 
Added to cli flag to change bind address for etcd metrics
```
k3s server --etcd-expose-metrics true
```
> Add functionality to bind custom IP address for Etcd metrics endpoint

- pkg/agent/config/config.go
- pkg/daemons/agent/agent.go
Only container-runtime-endpoint wants RuntimeSocket path as URI
The fix in 5b318d0 set it too early; this field is used by multiple flags and only one of them wants a URI.
Bugfix
#2831
> Only container-runtime-endpoint wants RuntimeSocket path as URI

- pkg/rootless/mounts.go
- pkg/rootless/rootless.go
Since a recent commit, rootless mode was failing with the following errors:
```
E0122 22:59:47.615567      21 kuberuntime_manager.go:755] createPodSandbox for pod "helm-install-traefik-wf8lc_kube-system(9de0a1b2-e2a2-4ea5-8fb6-22c9272a182f)" failed: rpc error: code = Unknown desc = failed to create network namespace for sandbox "285ab835609387f82d304bac1fefa5fb2a6c49a542a9921995d0c35d33c683d5": failed to setup netns: open /var/run/netns/cni-c628a228-651e-e03e-d27d-bb5e87281846: permission denied
...
E0122 23:31:34.027814      21 pod_workers.go:191] Error syncing pod 1a77d21f-ff3d-4475-9749-224229ddc31a ("coredns-854c77959c-w4d7g_kube-system(1a77d21f-ff3d-4475-9749-224229ddc31a)"), skipping: failed to "CreatePodSandbox" for "coredns-854c77959c-w4d7g_kube-system(1a77d21f-ff3d-4475-9749-22422 …
```
> rootless: remove rootful /run/{netns,containerd} symlinks

- pkg/daemons/agent/agent.go
cgroup2 support was introduced in #2584, but got broken in f3de60ff3191dc3a0ae7ce8393e388700f48ed88
It was failing with "F1210 19:13:37.305388    4955 server.go:181] cannot set feature gate SupportPodPidsLimit to false, feature is locked to true"
BugFix
`sudo k3s server` on Ubuntu 20.10 with cgroup2
Fix #900
> fix cgroup2 support

- scripts/download
Bump k3s-root to v0.8.0 - buildroot 2020.02.2 → 2020.11.1
https://git.buildroot.net/buildroot/plain/CHANGES?id=2020.11.1
Check versions in `/var/lib/rancher/k3s/data/current/bin/`
Related to #2783
```
[root@centos01 ~]# k3s --version
k3s version v1.20.2+k3s-1bcaaffe (1bcaaffe)
go version go1.15.5
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/busybox
BusyBox v1.32.0 (2021-01-26 21:37:43 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/coreutils --version
coreutils (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later …
```
> Bump k3s-root to v0.8.0

- scripts/download
Bump k3s-root to v0.8.0 - buildroot 2020.02.2 → 2020.11.1
https://git.buildroot.net/buildroot/plain/CHANGES?id=2020.11.1
Check versions in `/var/lib/rancher/k3s/data/current/bin/`
Related to #2783
```
[root@centos01 ~]# k3s --version
k3s version v1.20.2+k3s-1bcaaffe (1bcaaffe)
go version go1.15.5
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/busybox
BusyBox v1.32.0 (2021-01-26 21:37:43 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/coreutils --version
coreutils (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later …
```
> [release-1.19] Bump k3s-root to v0.8.0

- scripts/download
Bump k3s-root to v0.8.0 - buildroot 2020.02.2 → 2020.11.1
https://git.buildroot.net/buildroot/plain/CHANGES?id=2020.11.1
Check versions in `/var/lib/rancher/k3s/data/current/bin/`
Related to #2783
```
[root@centos01 ~]# k3s --version
k3s version v1.20.2+k3s-1bcaaffe (1bcaaffe)
go version go1.15.5
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/busybox
BusyBox v1.32.0 (2021-01-26 21:37:43 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
[root@centos01 ~]# /var/lib/rancher/k3s/data/current/bin/coreutils --version
coreutils (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later …
```
> [release-1.18] Bump k3s-root to v0.8.0

- k3s.service
Make `EnvironmentFile` optional.
Previously, `k3s.service` was failing when the `EnvironmentFile` does not exist:
```
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed to load environment files: No such file or directory
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed to run 'start' task: No such file or directory
Feb 02 17:17:30 suda-ws01 systemd[1]: k3s.service: Failed with result 'resources'.
Feb 02 17:17:30 suda-ws01 systemd[1]: Failed to start Lightweight Kubernetes.
```
ref: https://unix.stackexchange.com/questions/404199/documentation-of-equals-minus-in-systemd-unit-files
BugFix
`systemctl status k3s.service` without `/etc/systemd/system/k3s.service.env`.
> systemd unit: make EnvironmentFile optional

- cmd/k3s/main.go
* Fix use of literal ${HOME} in default data-dir path when running as non-root
* Fix not using system crictl.yaml when running as non-root
* Fix not setting CRI_CONFIG_FILE when crictl run as `k3s crictl`
* Fix potential cause of `level=fatal msg="exec: \"k3s-server\": executable file not found in $PATH"`
* bugfix
* Install K3s via install script; note that kubectl and crictl can both be used if the user has read access to the correct files
* Install K3s and run rootless; note that kubectl and crictl place things in ~/.rancher
#2891
#2854
> Fix multiple issues with CLI wrapper data-dir handling

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
Bump golang to 1.15.8
go version
`k3s --version`
kubernetes/release#1895
> Bump golang to 1.15.8

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
Bump golang to 1.15.8
go version
`k3s --version`
kubernetes/release#1895
> [release-1.19] Bump golang to 1.15.8

- pkg/clientaccess/token.go
- pkg/clientaccess/token_test.go
Allow joining clusters when the server CA is trusted by the OS CA bundle
* Join token
* CI
#2731
> Allow joining clusters when the server CA is trusted by the OS CA bundle

- pkg/daemons/agent/agent.go
Fix handling of comounted v1 controllers.
As noted at https://github.com/rancher/rke2/issues/689#issuecomment-773751230 the order of the comounted controllers in /proc/self/cgroup doesn't always match the order in /sys/fs/cgroup - but we can count on there being an alias in there for each controller that points to the comounted hierarchy.
- bugfix
- cgroupv1
rancher/rke2#689
Also tidied up the code that iterates across the controller lists to be more unified in variable naming, and added some comments explaining whats going on.
> Improve handling of comounted cpu,cpuacct controllers

- pkg/servicelb/controller.go
@Taloth correctly noted that the code that iterates over ServiceLB pods to collect IP addresses was failing to add internal IPs once  the map contained ANY entry from a previous node. This may date back to when ServiceLB used a Deployment instead of a DaemonSet, so there was only ever a single pod.
The new behavior is to collect all internal and external IPs, and then construct the address list of a single type - external if there are any, otherwise internal.
- Bugfix
- ServiceLB
* Set up multi-node cluster (1 server, 1 agent is fine) with ServiceLB; do not specify ExternalIP addresses for nodes
* Note that the Traefik service lists the IPs of both nodes
https://github.com/k3s-io/k3s/issues/1652#issuecomment-774497788
Before - single ExternalIP for traefik service:
```
[root@centos01 ~]# …
```
> Collect IPs from all pods before deciding to use internal or external addresses

- pkg/server/auth.go
Use appropriate response codes for authn/authz failures
- bugfix
#2310
> Use appropriate response codes for authn/authz failures

- pkg/cli/cmds/server.go
Small update to the `--cluster-init` usage flag to indicate it's for Etcd.
Verify new text is seen in output.
```sh
k3s server -h | grep cluster-init
```
> update usage text

- pkg/agent/config/config.go
- pkg/agent/loadbalancer/loadbalancer.go
- pkg/agent/loadbalancer/loadbalancer_test.go
- pkg/agent/proxy/apiproxy.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/apiaddresses/controller.go
- pkg/cli/agent/agent.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/etcd.go
- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/cluster/cluster.go
- pkg/cluster/managed.go
- pkg/cluster/managed/drivers.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
- pkg/daemons/control/server.go
- pkg/etcd/controller.go
- pkg/etcd/etcd.go
- pkg/etcd/etcdproxy.go
- pkg/server/etcd.go
- pkg/server/server.go
- Add 3 more disable flags for api server, controller manager, and etcd:
- `--disable-api-server`
- `--disable-controller-manager`
- `--disable-etcd`
- a controller for the server to synchronize the k3s/etcd/apiaddresses etcd key with the default:kubernetes endpoints
- In case of disable api server, etcd will only start and will try to get k3s/etcd/apiaddresses list from etcd to connect to the api, once an api joins a cluster it will set this IP
- also in case of disabling the api, the agent internal load balancer will start and will connect with the apis
- in case of disabling etcd a special load balancer (etcd proxy) will start and proxy requests to all etcd servers
New Feature
- to disable any of the components in the server process you should just pass the argument: …
> Add disable flags for control components

- pkg/agent/config/config.go
- pkg/agent/containerd/containerd.go
- pkg/agent/util/strings.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/daemons/config/types.go
- pkg/deploy/controller.go
- pkg/untar/untar.go
- scripts/package-cli
Adds support for retagging images to appear to have been sourced from one or more additional registries as they are imported from the tarball. This is intended to support RKE2 use cases with system-default-registry where the images need to appear to have been pulled from a registry other than docker.io.
This also extends our use of zstd to support loading airgap images from zstd compressed tarballs, and more reliably ensures that files and decompressors are closed at the end of the image load cycle.
- Airgap
```
[root@centos01 ~]# k3s --debug server --airgap-extra-registry=registry.lan.khaus:5000
[root@centos01 ~]# k3s crictl image ls
IMAGE                                                    TAG                 IMAGE ID            SIZE
docker.io/rancher/coredns-coredns …
```
> Add support for retagging images on load from tarball

- scripts/download
Bump k3s-root to v0.8.1
* Confirm that k3s works on EL8 on AWS
* Check for `/var/lib/rancher/k3s/data/current/bin/aux/xtables-nft-multi`
Related to #2940
```
[root@centos8 ~]# /var/lib/rancher/k3s/data/current/bin/aux/iptables-nft --version
iptables v1.8.5 (nf_tables)
```
> Update k3s-root to v0.8.1

- scripts/download
Bump k3s-root to v0.8.1
* Confirm that k3s works on EL8 on AWS
* Check for `/var/lib/rancher/k3s/data/current/bin/aux/xtables-nft-multi`
Related to #2940
```
[root@centos8 ~]# /var/lib/rancher/k3s/data/current/bin/aux/iptables-nft --version
iptables v1.8.5 (nf_tables)
```
> [release-1.20] Update k3s-root to v0.8.1

- scripts/download
Bump k3s-root to v0.8.1
* Confirm that k3s works on EL8 on AWS
* Check for `/var/lib/rancher/k3s/data/current/bin/aux/xtables-nft-multi`
Related to #2940
```
[root@centos8 ~]# /var/lib/rancher/k3s/data/current/bin/aux/iptables-nft --version
iptables v1.8.5 (nf_tables)
```
> [release-1.19] Update k3s-root to v0.8.1

- pkg/agent/syssetup/setup.go
- scripts/download
Bump k3s-root to v0.8.1
* Confirm that k3s works on EL8 on AWS
* Check for `/var/lib/rancher/k3s/data/*/bin/aux/xtables-nft-multi`
Related to #2940
```
[root@centos8 ~]# /var/lib/rancher/k3s/data/current/bin/aux/iptables-nft --version
iptables v1.8.5 (nf_tables)
```
> [release-1.18] Update k3s-root to v0.8.1

- pkg/cli/cmds/agent.go
Hide the airgap-extra-registry flag.
As per design review on rancher/rke2#715 it was decided that this is advanced functionality that we don't need to expose directly.
*CLI
* `k3s agent --help | grep airgap-extra-registry`  # flag not listed
* `k3s agent --airgap-extra-registry=my.local.registry`  # flag is accepted
> Hide the airgap-extra-registry flag

- pkg/agent/run.go
It is possible that the apiserver may serve read requests but not allow writes yet, in which case flannel will crash on startup when trying to configure the subnet manager. 
The kubelet itself will keep retrying the node registration if the apiserver isn't writable yet, but flannel exits immediately if a write fails so we need to fix this by waiting for the apiserver to become fully ready before starting flannel and the network policy controller.
* agent startup
Not sure how to reproduce this on demand; seems to happen occasionally on systems with slow IO (such as raspberry pi) where the apiserver serves reads but does not become fully healthy until a few seconds after startup?
#2989
Possibly #2509
> Wait for apiserver to become healthy before starting agent controllers

- pkg/agent/config/config.go
- scripts/test
- scripts/test-helpers
- scripts/test-run-compat
* Add CI script to test server/agent version compatibility against the latest, stable, and previous minor release channels.
* Log error on startup and disable NPC if server has not been upgraded.
* bugfix
* CI
* Start k3s agent with v1.20.2+k3s1 server
#2996
> Allow agent to start up successfully if server has not yet been upgraded to v1.20.4+k3s1

- go.mod
- go.sum
- pkg/agent/config/config.go
- pkg/agent/loadbalancer/loadbalancer.go
- pkg/agent/proxy/apiproxy.go
- pkg/agent/run.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/clientaccess/token.go
- pkg/clientaccess/token_test.go
- pkg/cluster/bootstrap.go
- pkg/cluster/managed.go
- pkg/etcd/etcd.go
- pkg/etcd/etcdproxy.go
- pkg/server/etcd.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
This fixes an issue where RKE2 kube-proxy daemonset pods were failing to communicate with the apiserver after RKE2 was restarted because the load-balancer used a different port every time it started up.
This also changes the apiserver load-balancer port to be 1 below the supervisor port instead of 1 above it. This makes the apiserver port consistent at 6443 across servers and agents on RKE2.
I also had to pull in a few other fixes to etcd-only mode as well - the new CLI flag wasn't actually being used which caused problems for the load-balancer port fix, and the server would crash or fail to connect to other servers under certain circumstances.
* load-balancer ports
* misc etcd-only stuff
rancher/rke2#573
Comparison of port usage before/after this change: …
> Always use static ports for client load-balancers

- pkg/agent/config/config.go
- pkg/agent/loadbalancer/loadbalancer.go
- pkg/agent/loadbalancer/loadbalancer_test.go
- pkg/agent/proxy/apiproxy.go
- pkg/agent/run.go
- pkg/cluster/cluster.go
- pkg/etcd/etcdproxy.go
* If the port wanted by the client load balancer is in TIME_WAIT, startup will fail. Set SO_REUSEPORT so that it can be listened on again immediately.
* Also handle another error case where we were leaking load balancers if the apiserver load-balancer attempts to connect to the server before it is up. This was always an issue, but was previously masked by the fact that we did not attempt to reuse the same port.
The configurable Listen call wants a context, so plumb that through as well.
client load balancer
I have not been able to reproduce this locally, but RKE2 CI has been flaking on it: https://drone-pr.rancher.io/rancher/rke2/997/1/4
Related to rancher/rke2#573
> Handle loadbalancer port in TIME_WAIT 

- pkg/cli/server/server.go
- pkg/server/server.go
- pkg/server/types.go
This adds trickle-down scaffolding to define `Controllers` and `LeaderControllers` from RKE2. This is being set up to allow RKE2 to define its own controllers to run, and is set up in such a manner to allow controllers to be defined that either only run on a leader, or run on all "server" nodes.
Scaffolding changes.
This should not functionally change K3s.
https://github.com/k3s-io/k3s/issues/3034
https://github.com/rancher/rke2/issues/745
> Define a Controllers and LeaderControllers on the server config

- pkg/cluster/bootstrap.go
- pkg/cluster/cluster.go
- pkg/cluster/managed.go
- pkg/cluster/managed/drivers.go
- pkg/cluster/storage.go
- pkg/etcd/etcd.go
* Add ability to save bootstrap data to etcd  when using managed etcd.
* Remove unneeded code that cleaned up certificates.
```sh
k3s etcd-snapshot
k3s server --cluster-reset --cluster-reset-restore-path=/home/bdowns/on-demand-<TIMESTAMP>
```
#3040
> Have Bootstrap Data Stored in etcd at Completed Start

- pkg/agent/config/config.go
- scripts/test
- scripts/test-helpers
- scripts/test-run-compat
* Add CI script to test server/agent version compatibility against the latest, stable, and previous minor release channels.
* Log clearer error on startup if NPC cannot be started due to down-level server.
* bugfix
* CI
* Start k3s agent with v1.20.2+k3s1 server
#2996
> [release-1.20] Log clearer error on startup if NPC cannot be started due to server not yet upgraded to v1.20.4+k3s1

- pkg/cli/server/server.go
- pkg/server/server.go
- pkg/server/types.go
Backport to release 1.20
This adds trickle-down scaffolding to define `Controllers` and `LeaderControllers` from RKE2. This is being set up to allow RKE2 to define its own controllers to run, and is set up in such a manner to allow controllers to be defined that either only run on a leader, or run on all "server" nodes.
Scaffolding changes.
This should not functionally change K3s.
https://github.com/k3s-io/k3s/issues/3034
https://github.com/rancher/rke2/issues/745
> [release-1.20] Define a Controllers and LeaderControllers on the server config

- pkg/cli/server/server.go
- pkg/server/server.go
- pkg/server/types.go
Backport to release 1.19
This adds trickle-down scaffolding to define `Controllers` and `LeaderControllers` from RKE2. This is being set up to allow RKE2 to define its own controllers to run, and is set up in such a manner to allow controllers to be defined that either only run on a leader, or run on all "server" nodes.
Scaffolding changes.
This should not functionally change K3s.
https://github.com/k3s-io/k3s/issues/3034
https://github.com/rancher/rke2/issues/745
> [release-1.19] Define a Controllers and LeaderControllers on the server config

- install.sh
Signed-off-by: Martin Norrsken <martin.norrsken@gmail.com>
Disable k3s service before removing unit files, otherwise systemd removes some cgroup info. This should be the logical order of doing cleanup (reverse order compared to installing and enabling service).
Bugfix
Installing k3s by script should not make cAdvisor info go stale anymore nor cause systemd to log warnings.
#3035
> Remove unit files after disabling, instead of before

- pkg/rootless/mounts.go
- pkg/rootless/rootless.go
When `/dev/kmsg` is unreadable due to sysctl value `kernel.dmesg_restrict=1`, bind-mount `/dev/null` into `/dev/kmsg`
Enhancement
- Run`sudo sysctl -w kernel.dmesg_restrict=1`
- Run `k3s server --rootless` and make sure kubelet starts up.
Related to #3011
> rootless: allow kernel.dmesg_restrict=1

- scripts/package-airgap
Add gz and zst airgap artifacts
Add zst for direct import
Add gzip for folks using docker to load images into a private registry
Keep plain tar for folks that still expect that
* Download .gz or .zst artifact to agent/images folder; note that k3s loads images on startup
Relatd to #2941
> Add gz and zst airgap artifacts

- pkg/nodeconfig/nodeconfig.go
Adds the etcd S3 access key and secret key flags to the secret data slice to be obfuscated in the node data.
Make sure that if the flags are issued, their values are represented with "*"'s. 
```sh
kubectl describe nodes | grep s3
```
https://github.com/rancherlabs/rancher-security/issues/584
> add etcd s3 secret and access key flags to secret data

- pkg/etcd/etcd.go
Remove early return preventing local retention policy to be enforced
resulting in N number of snapshots being stored.
Run the command below and verify that there are only 2 snapshots stored locally.
```sh
k3s server --cluster-init --etcd-s3 --etcd-s3-bucket=<bucket name> --etcd-s3-access-key=<key> --etcd-s3-secret-key=<secret>  --etcd-snapshot-schedule-cron='* * * * *' --etcd-snapshot-retention=2
```
#3178
> Resolve local retention issue when S3 in use.

- pkg/etcd/etcd.go
Remove early return preventing local retention policy to be enforced
resulting in N number of snapshots being stored.
> [Backport 1.19] - Resolve local retention issue when S3 in use.

- pkg/etcd/etcd.go
Remove early return preventing local retention policy to be enforced
resulting in N number of snapshots being stored.
> [Backport 1.20] - Resolve local retention issue when S3 in use.

- go.mod
- pkg/agent/config/config.go
- pkg/agent/netpol/network_policy_controller.go
- pkg/agent/netpol/network_policy_controller_test.go
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/cli/agent/agent.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/cloudprovider/instances.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
- pkg/daemons/control/server.go
- pkg/server/router.go
- pkg/server/server.go
- pkg/util/net.go
- vendor/modules.txt
* Add support for dual-stack cluster/service CIDRs and node addresses
* Begin transitioning the ip/externalip/hostname handoff (used by the K3s cloud provider) from labels to annotations, as labels do not allow the character-set necessary to pass through IPv6 addresses.
* If a node has labels they will be maintained, but new nodes will use only annotations. The cloud provider will continue to check both, with annotations taking precedence.
* Dual-stack node addresses are not autodetected; if desired a dual-stack address list must be passed to --node-ip (and --node-external-ip as necessary). Kubeadm is taking the same approach: https://github.com/kubernetes/kubeadm/issues/1612#issuecomment-786540060
This opens the door to dual-stack operation, even if flannel and the kube-router NPC don't …
> Add support for dual-stack Pod/Service CIDRs and node IP addresses

- install.sh
Add an option to the install script (`INSTALL_K3S_FORCE_RESTART`) to force a restart of the K3s service even if there are no binary/service/environment variable changes.
Install script changes
Install K3s using the install script, perform a reinstall (simply run the script again) and observe that it does not restart the K3s service. Run the install script a third time, but this time with `INSTALL_K3S_FORCE_RESTART=true` and observe that K3s is restarted when the script is run.
https://github.com/k3s-io/k3s/issues/3232
> Add install script option to force a restart of the K3s service

- pkg/daemons/control/deps/deps.go
- pkg/daemons/control/server.go
Add cluster DNS domain to ServingKubeAPICert to match SANs on serving cert at
https://github.com/k3s-io/k3s/blob/master/pkg/cluster/https.go#L41
* Certificates
Pull through in to RKE2; run Kubernetes conformance tests for 1.21.0 - note that it passes
rancher/rke2#845
Fixes error in v1.21.0 conformance tests:
```
[Fail] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
[It] ServiceAccountIssuerDiscovery
should support OIDC discovery of service account issuer [Conformance] \ /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
Apr 27 23:16:58.906: INFO: created pod
Apr 27 23:16:58.906: INFO: Waiting up to 5m0s for pod \“oidc-discovery-validator\” in …
```
> Add cluster DNS domain to ServingKubeAPICert

- install.sh
Unmount kubelet plugin folder on k3s-uninstall.sh. This is required to prevent data lost as seen in #3264 
Bugfix
Real test described in #3264 
Dummy test would be just doing a manual mount in /var/lib/kubelet/plugins and ensure is unmounted by k3s-killall.sh.
#3264 
You might consider unmounting any mount points under /var/lib/kubelet instead to catch any potential new future new folders.
> fixes #3264 - unmount CSI plugins on k3s-killall.sh

- pkg/agent/run.go
- pkg/cli/cmds/agent.go
- pkg/cli/server/server.go
- pkg/cluster/managed.go
The PR does two things:
- Fixes the calling of Reset() function, which only has been called if cluster-reset-restore-path is passed along with cluster-reset
- Makes sure kubelet starts first in clusterReset situation to be able to start etcd with the ForceNewCluster: true config and reset the cluster membership
bug fix
https://github.com/rancher/rke2/issues/934
> Invoke cluster reset function when only reset flag is passed

- .github/workflows/cgroup2.yaml
- tests/cgroup2/.gitignore
- tests/cgroup2/Vagrantfile
Add `.github/workflows/cgroup2.yaml` for running Fedora on Vagrant on GitHub Actions to test cgroup2 environment.
Only very basic smoke tests are executed, as Vagrant is too slow to run the entire sonobuoy.
Relevant:
- kubernetes-sigs/kind#2017
- https://github.com/rootless-containers/usernetes/blob/v20210201.0/.github/workflows/main.yaml
CI
CI logs can be observed on https://github.com/AkihiroSuda/k3s/actions?query=workflow%3Acgroup2 until this PR gets merged.
Close https://github.com/k3s-io/k3s/issues/2845 (`Request: cgroup v2 CI`)
Feel free to close this PR if we can get Drone instances for cgroup2.
> Add cgroup2 CI (Fedora on Vagrant on GHA)

- pkg/daemons/control/server.go
Problem:
Only the client CA is passed to the kube-controller-manager and
therefore CSRs with the signer name "kubernetes.io/kubelet-serving" are
signed with the client CA. Serving certificates must be signed with the
server CA otherwise e.g. "kubectl logs" fails with the error message
"x509: certificate signed by unknown authority".
Solution:
Instead of providing only one CA via the kube-controller-manager
parameter "--cluster-signing-cert-file", the corresponding CA for every
signer is set with the parameters
"--cluster-signing-kube-apiserver-client-cert-file",
"--cluster-signing-kubelet-client-cert-file",
"--cluster-signing-kubelet-serving-cert-file", and
"--cluster-signing-legacy-unknown-cert-file".
Signed-off-by: Siegfried Weber <mail@siegfriedweber.net>
#3244
> Sign CSRs for kubelet-serving with the server CA

- pkg/nodeconfig/nodeconfig.go
Use config file values in node-args annotation
node annotations
#3289
> Use config file values in node-args annotation

- pkg/agent/run.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/executor.go
Add executor.Bootstrap hook for pre-execution setup.
In RKE2 this will be used as a hook for bootstrapping the runtime image AFTER the configuration has been retrieved from the server. Here in K3s is is a no-op.
* executor API
* No change to K3s - should work as it currently does
rancher/rke2#958 and rancher/rke2#959
> Add executor.Bootstrap hook for pre-execution setup

- .drone.yml
- Dockerfile.test.mod.dapper
- scripts/test-mods
Add CI step to check for proper vendoring 
CI
CI on pull request should have an extra step `validate_go_mods` that errors out when vendoring from a personal fork
https://github.com/k3s-io/k3s/issues/2720
> [release-1.18]Add ci step to validate incorerct replacement fork

- .drone.yml
- Dockerfile.test.mod.dapper
- scripts/test-mods
Signed-off-by: MonzElmasry <menna.elmasry@rancher.com>
Add CI step to check for proper vendoring 
CI
CI on pull request should have an extra step `validate_go_mods` that errors out when vendoring from a personal fork
https://github.com/k3s-io/k3s/issues/2720
> [release-1.19]Add ci step to validate incorerct replacement fork

- .drone.yml
- Dockerfile.test.mod.dapper
- scripts/test-mods
Signed-off-by: MonzElmasry <menna.elmasry@rancher.com>
Add CI step to check for proper vendoring 
CI
CI on pull request should have an extra step `validate_go_mods` that errors out when vendoring from a personal fork
https://github.com/k3s-io/k3s/issues/2720
> [release-1.20]Add ci step to validate incorerct replacement fork

- pkg/agent/config/config.go
Fix passthrough of SystemDefaultRegistry from server config
#3285 did not properly pass through the --system-default-registry flag to agents. It was used in the  fields that are important to k3s agents but was not available for direct use by downstream projects (RKE2) that depend on it being set.
Agent configuration
No change to K3s; will be used downstream by RKE2
rancher/rke2#958 and rancher/rke2#959
> Fix passthrough of SystemDefaultRegistry from server config

- cmd/etcdsnapshot/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- main.go
- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/etcd/etcd.go
This change introduces the ability to perform a prune of etcd snapshots from either local storage or an S3 compatible object store. 
This change will require a documentation update. I will do that when the rest of the etcd snapshot CLI CRUD operations are complete.
Run a prune with the default retention policy of 5.
```sh
k3s etcd-snapshot prune
```
Run a prune with the given retention policy.
```sh
k3s etcd-snapshot prune
```
#3278
> Add the ability to prune etcd snapshots

- .golangci.json
- Dockerfile.dapper
- go.mod
- scripts/build
- scripts/download
- bump the runc version to v1.0.0-rc94
- build runc from its own source tree instead of from ./vendor/
- side-steps incompatibility with upstream kubelet container manager
backport of #3305
addresses #3301
> [backport 1.19] runc: v1.0.0-rc94

- .golangci.json
- go.mod
- scripts/build
- scripts/download
- bump the runc version to v1.0.0-rc94
- build runc from its own source tree instead of from ./vendor/
- side-steps incompatibility with upstream kubelet container manager
backport of #3305
addresses #3302
> [backport 1.18] runc: v1.0.0-rc94

- install.sh
- k3s.service
Add support for multiple env files for systemd unit
Install script
systemd unit
- Place K3s environment files at /etc/default/k3s and/or /etc/sysconfig/k3s
- Install K3s and note that configuration from these files is honored (note that not all K3s CLI flags support passing via environment variable)
- Reinstall K3s with different K3S_ environment variables; note that the new env files are not clobbered by the install and uninstall scripts.
For #3243
> Add support for multiple env files for systemd unit

- cmd/etcdsnapshot/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- main.go
- pkg/cli/cmds/etcd_snapshot.go
This change introduces the ability to perform a save of an etcd snapshot to either local storage or an S3 compatible object store. 
This change will require a documentation update. I will do that when the rest of the etcd snapshot CLI CRUD operations are complete.
Run a prune with the default retention policy of 5.
```sh
k3s etcd-snapshot save
```
#3309
> Add etcd snapshot save subcommand

- go.mod
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/daemons/agent/agent.go
- scripts/download
- vendor/modules.txt
Set nf_conntrack_max for kube-proxy in supervisor agent setup
This will need to be backported to all supported releases, and pulled in to RKE2 as well.
> Set nf_conntrack_max for kube-proxy in supervisor agent setup

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/cmds/server.go
- pkg/etcd/etcd.go
Wire in s3 snapshot purning and adds default value to retention flag help.
```sh
k3s etcd-snapshot prune --s3 --s3-bucket=k3s-snapshots --s3-access-key=<REDACTED> --s3-secret-key=<REDACTED> --snapshot-retention=3
```
#3278 
#3339
> add retention default and wire in s3 prune

- go.mod
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/daemons/agent/agent.go
- scripts/download
- vendor/modules.txt
Handle conntrack-related sysctls in supervisor agent setup
> [release-1.21] Handle conntrack-related sysctls in supervisor agent setup

- go.mod
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/daemons/agent/agent.go
- scripts/download
- vendor/modules.txt
Handle conntrack-related sysctls in supervisor agent setup
> [release-1.20] Handle conntrack-related sysctls in supervisor agent setup

- go.mod
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/daemons/agent/agent.go
- scripts/download
- vendor/modules.txt
Handle conntrack-related sysctls in supervisor agent setup
> [release-1.19] Handle conntrack-related sysctls in supervisor agent setup

- go.mod
- pkg/agent/run.go
- pkg/agent/syssetup/setup.go
- pkg/daemons/agent/agent.go
- scripts/download
Handle conntrack-related sysctls in supervisor agent setup
> [release-1.18] Handle conntrack-related sysctls in supervisor agent setup

- pkg/etcd/etcd.go
Moved defer channel close to the goroutine that was filling it. With this channel remaining open, the library function that consumes from the channel was unable to know it reached the end of the input.
#3240
> Move object channel defer close to goroutine

- pkg/agent/flannel/setup.go
Moves wireguard's privatekey file to flannel's config directory (by default /var/lib/rancher/k3s/agent/etc/flannel). Without this PR the key is deployed in / in the agents
Bugfix of issue: https://github.com/k3s-io/k3s/issues/3031
Use wireguard backend and verify that in the agents, the privatekey is not in / anymore but in /var/lib/rancher/k3s/agent/etc/flannel
> Move wireguard's privatekey to flannel config directory

- go.mod
- go.sum
- vendor/modules.txt
Moves flannel to v0.14.0
Tracked by https://github.com/k3s-io/k3s/issues/3372
(cherry picked from commit d415e413373e1325282aac8eda8f4c32d656fc6f)
> [Backport  1.21] Update flannel version

- pkg/cli/server/server.go
Add a log entry if etcd snapshots are disabled.
Start k3s with etcd snapshots disabled and grep for the log entry: "ETCD snapshots are disabled".
Issue added for RKE2. https://github.com/rancher/rke2/issues/430
> add log message indicating etcd snapshots are disabled

- pkg/agent/flannel/setup.go
Fixes bug https://github.com/k3s-io/k3s/issues/3031
Tracked by https://github.com/k3s-io/k3s/issues/3400
(cherry picked from commit 1576030d6bb4b35b2064c21f285df706af36dafe)
> [Backport 1.21] Add a path for wireguard's privatekey

- cmd/etcdsnapshot/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- main.go
- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/cmds/server.go
- pkg/etcd/etcd.go
Backports the etcd subcommand functionality found in mastser to the release-1.21 branch.
> [ Backport 1.21 ] - etcd subcommands 1.21

- pkg/cluster/https.go
- pkg/daemons/control/deps/deps.go
Add kubernetes.default.svc to serving certs
Bugfix
`echo QUIT | openssl s_client -connect localhost:6444 2>/dev/null | openssl x509 -noout -text | grep DNS`
For #3399
> Add kubernetes.default.svc to serving certs

- contrib/util/check-config.sh
Added additional check in check-config.sh (i.e `k3 check-config`) that complains about iptables being in nf_tables mode only if the version is between 1.8.0 and 1.8.3.
Bugfix
Run on centOS8, it has iptables v1.8.4 in nf_tables mode by default. `k3 check-config` will no longer fail.
https://github.com/k3s-io/k3s/issues/2946
Currently there is a bug in iptables v1.8.2 and v1.8.3 when in nf_tables mode that causes issues.
https://github.com/k3s-io/k3s/issues/3117
> Updated iptables version check

- pkg/deploy/controller.go
- pkg/server/context.go
Use Kubernetes managedFields's manager name string to track the node that last modified a resource. This sets deploy@NODENAME as the field manager on all resources created by the deploy controller, which can be used by other components that might want to know what node created something - due to the deploy controller not using any sort of leader election.
Wrangler's apply library doesn't have any way to set the manager field when applying a DesiredSet, but we can instead rely on the fact that server-side-apply uses everything before the first `/` in the client's user-agent as the manager name if the manager field is empty.
deploy controller
* Install K3s
* `kubectl get service -n kube-system kube-dns -o yaml --show-managed-fields`; note entry in managedFields list showing `manager: …
> Add nodename to UA string for deploy controller

- pkg/deploy/controller.go
- pkg/server/server.go
======
* Addresses issues with visibility (were errors encountered when parsing or applying the manifest) by adding change/failure events viewable via `kubectl get events -n kube-system` or `kubectl describe addon -n kube-system <addon>`. Events are inspired by k/k event behavior for Pods, where Events are created for container pull start, container pull success/failure, etc. They should be meaningful but not spammy.
======
- New feature
Verification
===
Note events when describing AddOn: kubectl describe addon -n kube-system coredns`
Linked Issues
======
For #1337
This is a stripped-down version of #2169 that only adds events; it doesn't attempt to address any of the other issues with tracking who modified the resource, since this can be (minimally) …
> Add events to deploy controller

- pkg/agent/run.go
- pkg/cli/server/server.go
Move the code for when the agent signals systemd to to be the last thing it does before waiting on the blocked context channel.
Verify that kubelet is up and processing before `systemctl start k3s` returns on an agent node.
https://github.com/rancher/rke2/issues/989
> Send systemd notifications for both server and agent

- contrib/util/check-config.sh
Pull in backport of https://github.com/k3s-io/k3s/pull/3425
Only fail if version is between 1.8.0 and 1.8.3 and using nf_tables mode (#3425)
Bug fix
`k3s check-config`
Backport issue: https://github.com/k3s-io/k3s/issues/3453
Original issue: https://github.com/k3s-io/k3s/issues/2946
> [Backport 1.21] Changed iptables version check for failure 

- pkg/agent/containerd/containerd.go
In order to protect air-gapped images from being garbage collected by containerd, the image license is changed from the default of 24h to permanent. On startup, all existing image licenses are deleted.
Enhancement
```
k3s ctr leases ls
ID             CREATED AT                LABELS
642873750-SI8m 2021-06-14T15:12:52-07:00 -
```
Note how the LABEL no longer contains an expiration
https://github.com/k3s-io/k3s/issues/3193
> Change containerd image leases from 24h to permanent

- pkg/agent/run.go
- pkg/cli/server/server.go
Backport previous changes found in #3430
(* update agent to sent systemd notify after everything starts)
Found in original issue. #3430 
#3458
> [Backport 1.21] Send systemd notify to both server and agent

- install.sh
- k3s.service
- package/rpm/install.sh
Even though we are documenting that nm-cloud-setup service breaks the k3s cluster: rancher/docs#3336, it is a good idea to verify this when starting the k3s service and not allow it to start if the user forgot to disable that service. If the OS is not running systemd, it will deploy k3s.
**Required** ==> /bin/sh (which I think is a quite safe assumption)
New Feature. Verifies if nm-cloud-setup is enabled
Deploy RHEL8.4 which use nm-cloud-setup by default and run k3s. It should fail to start with the following log in journactl:
```
sh[1118717]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
sh[1118717]: + exit 1
```
rancher/rke2#1053
> Fail to start k3s if nm-cloud-setup is enabled

- pkg/cli/cmds/server.go
- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/server/server.go
Adds a command-line flag '--disable-helm-controller' that will disable the server's built-in helm controller.
Problem:
Testing installation and uninstallation of the Helm Controller on k3s is
not possible if the Helm Controller is baked into the k3s server.
Solution:
The Helm Controller can optionally be disabled, which will allow users
to manage its installation manually.
Signed-off-by: Joe Kralicky <joe.kralicky@suse.com>
This change will increase the flexibility of testing and development of components that are normally baked into k3s.
New Feature
Running the server with the --disable-helm-controller flag will start the server without the controller. Any Helmchart resources will not be reconciled. 
#1445
This change intentionally does not prevent the installation of the associated …
> Add option to disable the built-in Helm Controller

- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/executor.go
Move the K3s `cloud-controller-manager` from `pkg/daemons/control/server.go` to the more K3s-conventional `pkg/daemons/executor/embed.go`
Server control loop changes. Functionally this is only an optimization, rather than a feature change.
Run K3s and confirm that the embedded `cloud-controller-manager` still functions and sets the `providerID`
https://github.com/k3s-io/k3s/issues/2697
> Move cloud-controller-manager into an embedded executor

- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/executor.go
Backport of https://github.com/k3s-io/k3s/pull/3525
Move the K3s `cloud-controller-manager` from `pkg/daemons/control/server.go` to the more K3s-conventional `pkg/daemons/executor/embed.go`
Server control loop changes. Functionally this is only an optimization, rather than a feature change.
Run K3s and confirm that the embedded `cloud-controller-manager` still functions and sets the `providerID`
https://github.com/k3s-io/k3s/issues/3529
> [Backport 1.21] Move cloud-controller-manager into an embedded executor

- go.mod
- go.sum
- pkg/cluster/storage.go
- vendor/github.com/k3s-io/kine/pkg/client/client.go
- vendor/github.com/k3s-io/kine/pkg/logstructured/sqllog/sql.go
- vendor/modules.txt
Bump kine for #3523
Fix bug (no issue) where deletion of empty-string bootstrap token would always fail due to kine not supporting delete without a transaction.
Bugfix
* Check CI; no failures
* Validate #3422 and rancherlabs/rancher-security#501; note that the old bootstrap key is successfully deleted
#3523
> Bump kine to resolve race condition and unrevisioned delete

- pkg/cli/cmds/server.go
- pkg/etcd/etcd.go
- pkg/etcd/s3.go
Exporting some cli flags to be used in the migration agent directly as well as two function in s3 restoration
> Export cli server flags and etcd restoration functions

- .github/PULL_REQUEST_TEMPLATE.md
Add user-facing change section to PR template
Github
* Open a new PR
* See new template
* Fill out template including user-facing change section
* See contents of PR template show up in release notes
N/A
```release-note
NONE
```
This sets us up to write some automation to scrape release-note sections from PRs for inclusion in release note documents. This is inspired by the upstream PR template and release automation:
https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md.
> Add user-facing change section to PR template

- pkg/agent/containerd/containerd.go
- pkg/cluster/encrypt.go
Allow passing environment variables to containerd
Any K3s environment variable CONTAINERD_FOO=bar will be passed through to containerd as FOO=bar
Containerd environment
Start K3s with CONTAINERD_HTTP_PROXY=x; note that containerd uses the proxy for image pulls
For #3552
I had this in another PR a while back but ended up not using it, happy to bring it back if someone has use for it.
> Allow passing targeted environment variables to containerd

- docker-compose.yml
The default values of ulimits were set to 65536 in EKS, which can be configured in [docker-compose.yml](https://docs.docker.com/compose/compose-file/compose-file-v3/#ulimits) as well. And port 80/443 should be forwarded by default for all ingress controllers.
> Set ulimits in docker-compose.yml

- scripts/dispatch
Add additional steps to dispatch to send a dispatch event to the `rancher/system-agent-installer-k3s` repository to create a tag when a new release is made
CI change
Cut a release, and observe that a corresponding `rancher/system-agent-installer-k3s` tag is created
https://github.com/k3s-io/k3s/issues/3581
```release-note
NONE
```
> Dispatch to rancher/system-agent-installer-k3s when tagged

- go.mod
- go.sum
- pkg/cluster/encrypt.go
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/apis/helm.cattle.io/v1/types.go
- vendor/github.com/k3s-io/helm-controller/pkg/apis/helm.cattle.io/v1/zz_generated_deepcopy.go
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump `k3s-io/helm-controller` to `v0.10.1`
Packaged component version change
Verify that `k3s-io/helm-controller` is `v0.10.1` i.e. `go mod graph | grep helm-controller`
https://github.com/k3s-io/k3s/issues/3427
> [release-1.21] Bump helm-controller to v0.10.1

- pkg/agent/config/config_windows.go
- pkg/agent/templates/templates_windows.go
- pkg/daemons/agent/agent.go
- pkg/daemons/agent/agent_windows.go
- pkg/daemons/agent/agent_windows_test.go
This changes the crictl template for issues with the socket information. It also addresses a typo in the socket address. Last it makes tweaks to configuration that aren't required or had incorrect logic.
This fixes bugs in the containerd socket for windows and a bug related to generating the correct source-vip.
These are all bugfix changes.
The issue in this repo: #3585
This work for Windows enablement: rancher/windows#55
> Fixing various bugs related to windows.

- scripts/dispatch
Backport of https://github.com/k3s-io/k3s/pull/3589
Add additional steps to dispatch to send a dispatch event to the `rancher/system-agent-installer-k3s` repository to create a tag when a new release is made
CI change
Cut a release, and observe that a corresponding `rancher/system-agent-installer-k3s` tag is created
https://github.com/k3s-io/k3s/issues/3582
```release-note
NONE
```
> [release-1.21] Dispatch to rancher/system-agent-installer-k3s when tagged

- pkg/cli/etcdsnapshot/etcd_snapshot.go
Update the error message that is encountered when performing an etcd snapshot operation when K3s is unable to find an initialized etcd database.
UX Change
Run a `k3s etcd-snapshot` on a system that is running K3s at a "global" level using a `non-root` user. Observe that the error message encountered tells you that K3s could not find the etcd database in the local K3s home directory.
https://github.com/k3s-io/k3s/issues/3438
```release-note
Update the error message encountered when running `k3s etcd-snapshot` where K3s cannot find an initialized etcd database to be more informative.
```
> Update etcd snapshot error message to be more informative

- pkg/cli/etcdsnapshot/etcd_snapshot.go
Backport of: https://github.com/k3s-io/k3s/pull/3568
Update the error message that is encountered when performing an etcd snapshot operation when K3s is unable to find an initialized etcd database.
UX Change
Run a `k3s etcd-snapshot` on a system that is running K3s at a "global" level using a `non-root` user. Observe that the error message encountered tells you that K3s could not find the etcd database in the local K3s home directory.
https://github.com/k3s-io/k3s/issues/3591
```release-note
Update the error message encountered when running `k3s etcd-snapshot` where K3s cannot find an initialized etcd database to be more informative.
```
> [release-1.21] Update etcd snapshot error message to be more informative

- scripts/download
Bump the packaged runc binary version
Not bumping runc in go.mod yet, as upstream Kubernetes still requires
runc/libcontainer v1.0.0-rc95
packaged runc
`/var/lib/rancher/k3s/data/current/bin/runc --version`
* #3600
```release-note
Update packaged runc binary version to v1.0.0
```
> Bump the packaged runc binary version

- scripts/download
Bump the packaged runc binary version
Not bumping runc in go.mod yet, as upstream Kubernetes still requires
runc/libcontainer v1.0.0-rc95
packaged runc
`/var/lib/rancher/k3s/data/current/bin/runc --version`
* #3601
```release-note
Update packaged runc binary version to v1.0.0
```
> [release-1.21] Bump the packaged runc binary version

- pkg/daemons/control/server.go
Problem:
Only the client CA is passed to the kube-controller-manager and
therefore CSRs with the signer name "kubernetes.io/kubelet-serving" are
signed with the client CA. Serving certificates must be signed with the
server CA otherwise e.g. "kubectl logs" fails with the error message
"x509: certificate signed by unknown authority".
Solution:
Instead of providing only one CA via the kube-controller-manager
parameter "--cluster-signing-cert-file", the corresponding CA for every
signer is set with the parameters
"--cluster-signing-kube-apiserver-client-cert-file",
"--cluster-signing-kubelet-client-cert-file",
"--cluster-signing-kubelet-serving-cert-file", and
"--cluster-signing-legacy-unknown-cert-file".
Signed-off-by: Siegfried Weber <mail@siegfriedweber.net>
* #3446
> [release-1.20] Sign CSRs for kubelet-serving with the server CA

- pkg/cli/server/server.go
- pkg/cluster/cluster.go
* prevent snapshot save when snapshots are disabled
#3607 
```release-note
```
> [Backport 1.21] - prevent snapshot save when snapshots are disabled (#3475)

- pkg/cli/server/server.go
- pkg/cluster/cluster.go
* prevent snapshot save when snapshots are disabled
#3608 
```release-note
```
> [Backport 1.20] - prevent snapshot save when snapshots are disabled (#3475)

- pkg/deploy/controller.go
- pkg/server/context.go
Use Kubernetes managedFields's manager name string to track the node that last modified a resource. This sets deploy@NODENAME as the field manager on all resources created by the deploy controller, which can be used by other components that might want to know what node created something - due to the deploy controller not using any sort of leader election.
Wrangler's apply library doesn't have any way to set the manager field when applying a DesiredSet, but we can instead rely on the fact that server-side-apply uses everything before the first `/` in the client's user-agent as the manager name if the manager field is empty.
deploy controller
* Install K3s
* `kubectl get service -n kube-system kube-dns -o yaml --show-managed-fields`; note entry in managedFields list showing `manager: …
> [release-1.21] Add nodename to UA string for deploy controller

- pkg/deploy/controller.go
- pkg/server/server.go
======
* Addresses issues with visibility (were errors encountered when parsing or applying the manifest) by adding change/failure events viewable via `kubectl get events -n kube-system` or `kubectl describe addon -n kube-system <addon>`. Events are inspired by k/k event behavior for Pods, where Events are created for container pull start, container pull success/failure, etc. They should be meaningful but not spammy.
======
- New feature
Verification
===
Note events when describing AddOn: kubectl describe addon -n kube-system coredns`
Linked Issues
======
* #3612
This is a stripped-down version of #2169 that only adds events; it doesn't attempt to address any of the other issues with tracking who modified the resource, since this can be (minimally) …
> [release-1.21] Add events to deploy controller

- pkg/cluster/managed.go
A complementary fix to the pr:
https://github.com/k3s-io/k3s/pull/3422
issues:
https://github.com/rancherlabs/rancher-security/issues/501
> fix a runtime core panic

- scripts/download
This PR upgrades the k3s-root version to 0.9.1 which uses buildroot 2021-02. Before this PR we were using k3s-root 0.8.1 using buildroot 2020-11.
Upgrade version of one component
https://github.com/k3s-io/k3s/issues/3625
```
Upgrade k3s-root to 0.9.1
```
> Upgrade k3s-root version

- pkg/etcd/etcd.go
Close the list object channel in thread so that we can fix delete snapshot issue
bug fix
- take  a snapshot using s3
- delete snapshot using etcd-snapshot delete subcommand
- https://github.com/k3s-io/k3s/issues/3646
> Fix delete issue for etcd s3 snapshots

- pkg/cluster/managed.go
Call managed db reset function when cluster reset flag is passed
bug fix
- running k3s server --cluster-reset should work as expected and reset quorum of the cluster
- https://github.com/k3s-io/k3s/issues/3651
> [Release-1.20] Fix cluster reset call

- pkg/cli/cmds/server.go
- pkg/server/server.go
- pkg/server/types.go
The startup hooks where executing after the deploy controller. We needed the deploy controller to wait until the startup hooks had completed.
* https://github.com/k3s-io/k3s/issues/3653
* https://github.com/rancher/rke2/issues/1301
> Adding support for waitgroup to the Startuphooks

- pkg/cli/cmds/server.go
- pkg/server/server.go
- pkg/server/types.go
The startup hooks where executing after the deploy controller. We needed the deploy controller to wait until the startup hooks had completed.
https://github.com/rancher/rke2/issues/1198
```release-note
```
> Adding support for waitgroup to the Startuphooks (#3654)

- scripts/download
Bump k3s-root to 0.9.1
Linked issue: https://github.com/k3s-io/k3s/issues/3633
> [release-1.21] Upgrade k3s-root version

- scripts/download
Bump k3s-root to 0.9.1
Linked issue: https://github.com/k3s-io/k3s/issues/3634
> [release-1.20] Upgrade k3s-root version

- pkg/etcd/etcd.go
- pkg/etcd/s3.go
This removed the hardcoded snapshotPrefix variable in `etcd.go` and instead supplies the `e.config.EtcdSnapshotName` as the  prefix to look for when pruning snapshots.
Bugfix
- Start k3s with: 
`sudo ./dist/artifacts/k3s server --cluster-init --etcd-snapshot-schedule-cron "* * * * *" --etcd-snapshot-name DEADBEEF --etcd-snapshot-retention 2`
- Wait 3 minutes
- Check number of snaphshots, it should be 2
```
sudo ./dist/artifacts/k3s etcd-snapshot ls
DEADBEEF-dinux-compute-1626387000 file:///var/lib/rancher/k3s/server/db/snapshots/DEADBEEF-dinux-compute-1626387000 1835040 2021-07-15T15:10:00-07:00
DEADBEEF-dinux-compute-1626387060 file:///var/lib/rancher/k3s/server/db/snapshots/DEADBEEF-dinux-compute-1626387060 1962016 2021-07-15T15:11:00-07:00 …
```
> Fix to allow prune to correctly cleanup custom named snapshots

- pkg/cli/cmds/server.go
- pkg/server/server.go
- pkg/server/types.go
https://github.com/rancher/rke2/issues/1301
```release-note
```
> adding startup hooks args to access to Disables and Skips

- pkg/etcd/etcd.go
- pkg/etcd/s3.go
- Backported fix for prune to work on custom names snapshots
https://github.com/k3s-io/k3s/issues/3671
Original Issue: https://github.com/k3s-io/k3s/issues/3648
Original PR: https://github.com/k3s-io/k3s/pull/3649
```release-note
NONE
```
> [Backport 1.20] Fix to allow prune to correctly cleanup custom named snapshots (#3649)

- pkg/etcd/etcd.go
- pkg/etcd/s3.go
- Backported fix for prune to work on custom names snapshots
https://github.com/k3s-io/k3s/issues/3670
Original Issue: https://github.com/k3s-io/k3s/issues/3648
Original PR: https://github.com/k3s-io/k3s/pull/3649
```release-note
NONE
```
> [Backport 1.21] Fix to allow prune to correctly cleanup custom named snapshots (#3649)

- pkg/cluster/storage.go
change the return error when multiple keys are found to a warning
loop over the keys and delete the empty string key only
bugfix
* https://github.com/rancher/rke2/issues/1401
```release-note
```
> Fix multiple bootstrap keys found

- pkg/agent/config/config.go
- pkg/agent/run.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
- pkg/server/router.go
* Add a /v1-k3s/readyz endpoint to the server to indicate when runtime.core is available; this occurs after all startup hooks are complete and should be a good checkpoint for having the final system configuration in place.
* Remove KubeProxyDisabled from config.Agent; replace it with a blocking function call that waits for the server readyz to return health before retrieving just this one bit of config.
* Move startKubeProxy into a goroutine that blocks until the server is ready to tell the agent whether or not it should run kube-proxy
bugfix 
Start RKE2 with rke2-kube-proxy HelmChartConfig present; note that the kube-proxy static pod does not start
rancher/rke2#1455
```release-note
```
This feels ugly but I don't see another good way around it.
We need to retrieve MOST of the system …
> Wait until server is ready before configuring kube-proxy

- pkg/daemons/agent/agent.go
- pkg/daemons/agent/agent_linux.go
- pkg/daemons/agent/agent_windows.go
- pkg/util/gates.go
- pkg/util/gates_test.go
This change exports the AddFeatureGate function allowing upstream projects to make use of the same feature for adding feature gates. A unit test was also added to validate the formatting of the feature gate value.
* https://github.com/k3s-io/k3s/issues/3643
> Exporting the AddFeatureGate function and adding a unit test for it.

- pkg/cli/server/server.go
send a notify to systemd for etcd only node
bugfix
- install k3s/rke2 via curl script
- disable api,controller,scheduler and start rke2-server
- systemctl restart/start should work normally
https://github.com/rancher/rke2/issues/1483
> Notify systemd for etcd only node

- .github/stale.yml
Add in a sensible start for stalebot, closing only issues not on the project board, after 180 days of inactivity.  We can start here and pare down pending community response.
Bot yaml config addition
Check that .github/stale.yaml is sensible
https://github.com/k3s-io/k3s/issues/3478
```release-note
NONE
```
> Add in stalebot config, starting with 6mo old stale issues.

- pkg/agent/config/config.go
- pkg/cli/server/server.go
- pkg/server/router.go
- pkg/server/server.go
Sync DisableKubeProxy from cfg into control before sending control to clients, as it may have been modified by a startup hook.
This is a follow-up to #3716 - I missed the fact that the RKE2 startup hooks only have access to cfg.
Bugfix
Normal tests in K3s; not really needed here.
Will need to be tested in RKE2 when pulled through.
* #3725
```release-note
```
Thanks @dweomer for talking this through with me
> Sync DisableKubeProxy into control struct

- pkg/agent/run.go
- pkg/cli/server/server.go
Fix initial start of systemd notify of etcd only nodes
bug fix
https://github.com/rancher/rke2/issues/1483
> Fix initial start of etcd only nodes

- pkg/agent/containerd/containerd.go
Wrap context with lease before importing images
Bugfix
There does not appear to be any way to verify that the image content is reference from the lease using `ctr`. I used [boltbrowser](https://github.com/br0xen/boltbrowser) to ensure that the lease references image content following this change - while k3s is stopped, you can run `boltbrowser -ro /var/lib/rancher/k3s/agent/containerd/io.containerd.metadata.v1.bolt/meta.db` and browse to `v1/k8s.io/leases/k3s/content`.
* #3752 
```release-note
Images imported from airgap tarballs are now properly lease-locked to prevent garbage collection
```
> Wrap context with lease before importing images

- install.sh
If `install.sh` relies on `awk`, `install.sh` malfunctions when run on a device with a limited environment where `awk` is not available. This patch replaces the use of `awk` (in the killall script created by `install.sh`) with built-in shell script functionality.
Bugfix
Run the killall script on a machine that does not have awk installed.
https://github.com/k3s-io/k3s/issues/3737
```release-note
NONE
```
> install.sh: Use built-in shell functionality instead of awk

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump klipper-helm version
version bump
Check image version on running cluster
* #3759
```release-note
The embedded Helm version has been updated to v3.6.3
```
> [release-1.21] Bump helm-controller to v0.10.2

- go.mod
- go.sum
- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/apis/helm.cattle.io/v1/types.go
- vendor/github.com/k3s-io/helm-controller/pkg/apis/helm.cattle.io/v1/zz_generated_deepcopy.go
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump klipper-helm and klipper-lb image versions.
The klipper-lb version bump brings this in line with other branches which were updated as part of the k3s-io move.
version bump
Check image version on running cluster
* #3760
```release-note
The embedded Helm version has been updated to v3.6.3
```
> [release-1.20] Bump helm-controller to v0.10.2

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump klipper-helm version
version bump
Check image version on running cluster
* #3753
```release-note
The embedded Helm version has been updated to v3.6.3
```
> Bump helm-controller to v0.10.2

- pkg/etcd/etcd.go
Add a context timeout for the etcd remove peer function
bug fix
- create cluster with 3 server nodes and etcd backend
- delete one of the nodes using kubectl delete node
node should be deleted normally from the node list
https://github.com/k3s-io/k3s/issues/3773
The issue is not always reproducible
> [Release-1.21] fix Node stuck at deletion

- pkg/etcd/etcd.go
Add a context timeout for the etcd remove peer function
bug fix
- create cluster with 3 server nodes and etcd backend
- delete one of the nodes using kubectl delete node
node should be deleted normally from the node list
https://github.com/k3s-io/k3s/issues/3774
The issue is not always reproducible
> [Release-1.19] fix Node stuck at deletion

- pkg/etcd/etcd.go
Add a context timeout for the etcd remove peer function
bug fix
- create cluster with 3 server nodes and etcd backend
- delete one of the nodes using kubectl delete node
node should be deleted normally from the node list
https://github.com/k3s-io/k3s/issues/3772
The issue is not always reproducible
> [Release-1.20] fix Node stuck at deletion

- pkg/etcd/etcd.go
Additional logic needed to be added to account for the use of folders within AWS S3 buckets in the "list snapshots" routine.
Run the command below and verify that what is listed in the ConfigMap is what's in the AWS folder. 
```sh
kubectl get cm -n kube-system k3s-etcd-snapshots -o yaml 
```
https://github.com/rancher/rke2/issues/1551
```release-note
```
> account for an s3 folder when listing objects

- pkg/daemons/agent/agent_windows.go
Updated the method being called and tweaked the logic.
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
The waitManagementIP function in pkg/daemons/agent/agent_windows.go is calling the incorrect HNS function. It is calling GetHNSEndpointByName instead of calling GetHNSNetworkByName.
Bugfix
Deploy a  windows cluster and ensure that the following doesn't appear in the log files.
```
time="2021-08-10T08:40:17-07:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
```
* https://github.com/k3s-io/k3s/issues/3817
```release-note
```
> Updated the code to use GetNetworkByName and tweaked logic.

- pkg/etcd/etcd_int_test.go
- tests/integration/localstorage_int_test.go
- tests/util/cmd.go
Adds a locking system around launching a k3s server during an integration test. This allows `go test` to compile integration tests in parallel, while ensuring that individual integration tests to not try and start another k3s (or kill k3s) server while one is already active. 
Enhancement
Running all integration tests now pass.
`go test ./pkg/... ./tests/... -run Integration`
The second test will block, waiting for the first test to terminate its k3s server
https://github.com/k3s-io/k3s/issues/3819
```release-note
NONE
```
While the simple solution was to force go test to use 1 thread `go test -p 1`, this greatly slows down build times for the tests. Now tests are built in parallel, but largely run sequentially. 
Future work is to make this …
> Added locking system for integration tests

- pkg/etcd/etcd.go
Problem:
Existing member clientURLs were checked if they contain the joining
node's IP. In some edge cases this would prune valid URLs when the
joining IP is a substring match of the only existing member's IP.
Because of this, it was impossible to e.g. join 10.0.0.2 to an existing
node that has an IP of 10.0.0.2X or 10.0.0.2XX:
level=fatal msg="starting kubernetes: preparing server: start managed database:
joining etcd cluster: etcdclient: no available endpoints"
Solution:
Fixed by properly parsing the URLs and comparing the IPs for equality
instead of substring match.
Signed-off-by: Malte Starostik <info@stellaware.de>
When joining an etcd node, only discard an existing node's clientURL if it's strictly the same address as opposed to a substring match.
Bugfix
Try to join (etcd role) …
> Fix URL pruning when joining an etcd member

- pkg/etcd/etcd.go
Problem:
Existing member clientURLs were checked if they contain the joining
node's IP. In some edge cases this would prune valid URLs when the
joining IP is a substring match of the only existing member's IP.
Because of this, it was impossible to e.g. join 10.0.0.2 to an existing
node that has an IP of 10.0.0.2X or 10.0.0.2XX:
level=fatal msg="starting kubernetes: preparing server: start managed database:
joining etcd cluster: etcdclient: no available endpoints"
Solution:
Fixed by properly parsing the URLs and comparing the IPs for equality
instead of substring match.
Signed-off-by: Malte Starostik <info@stellaware.de>
When joining an etcd node, only discard an existing node's clientURL if it's strictly the same address as opposed to a substring match.
Bugfix
Try to join (etcd role) …
> [release-1.21] Fix URL pruning when joining an etcd member

- pkg/etcd/etcd.go
Problem:
Existing member clientURLs were checked if they contain the joining
node's IP. In some edge cases this would prune valid URLs when the
joining IP is a substring match of the only existing member's IP.
Because of this, it was impossible to e.g. join 10.0.0.2 to an existing
node that has an IP of 10.0.0.2X or 10.0.0.2XX:
level=fatal msg="starting kubernetes: preparing server: start managed database:
joining etcd cluster: etcdclient: no available endpoints"
Solution:
Fixed by properly parsing the URLs and comparing the IPs for equality
instead of substring match.
Signed-off-by: Malte Starostik <info@stellaware.de>
When joining an etcd node, only discard an existing node's clientURL if it's strictly the same address as opposed to a substring match.
Bugfix
Try to join (etcd role) …
> [release-1.20] Fix URL pruning when joining an etcd member

- pkg/etcd/etcd.go
Problem:
Existing member clientURLs were checked if they contain the joining
node's IP. In some edge cases this would prune valid URLs when the
joining IP is a substring match of the only existing member's IP.
Because of this, it was impossible to e.g. join 10.0.0.2 to an existing
node that has an IP of 10.0.0.2X or 10.0.0.2XX:
level=fatal msg="starting kubernetes: preparing server: start managed database:
joining etcd cluster: etcdclient: no available endpoints"
Solution:
Fixed by properly parsing the URLs and comparing the IPs for equality
instead of substring match.
Signed-off-by: Malte Starostik <info@stellaware.de>
When joining an etcd node, only discard an existing node's clientURL if it's strictly the same address as opposed to a substring match.
Bugfix
Try to join (etcd role) …
> [release-1.19] Fix URL pruning when joining an etcd member

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump helm-controller to work around tiller crashes
bugfix
Check klipper-helm image version
* #3843
```release-note
The embedded Helm controller should no longer hang while checking for Helm v2 releases
```
Waiting merge and tag of
* https://github.com/k3s-io/helm-controller/pull/114
> Bump helm-controller to work around tiller crashes

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump helm-controller to work around tiller crashes
bugfix
Check klipper-helm image version
* #3844
```release-note
The embedded Helm controller should no longer hang while checking for Helm v2 releases
```
Waiting merge and tag of
* https://github.com/k3s-io/helm-controller/pull/114
> [release-1.21] Bump helm-controller to work around tiller crashes

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump helm-controller to work around tiller crashes
bugfix
Check klipper-helm image version
* #3845
```release-note
The embedded Helm controller should no longer hang while checking for Helm v2 releases
```
Waiting merge and tag of
* https://github.com/k3s-io/helm-controller/pull/114
> [release-1.20] Bump helm-controller to work around tiller crashes

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump helm-controller to work around tiller crashes
bugfix
Check klipper-helm image version
* #3846
```release-note
The embedded Helm controller should no longer hang while checking for Helm v2 releases
```
Waiting merge and tag of
* https://github.com/k3s-io/helm-controller/pull/114
> [release-1.19] Bump helm-controller to work around tiller crashes

- .github/stale.yml
Adding missing labels to stalebot config.
just a config change.
None needed, or if someone really wanted to, the could verify the labels I added actually exist
No issue, just a bot config change.
None
> Add missing labels to stalebot config

- pkg/agent/loadbalancer/loadbalancer.go
- pkg/cli/server/server.go
Delete local state of internal load balancers during restoration
bug fix
Restoration should work on etcd only node
- https://github.com/k3s-io/k3s/issues/3873
none
> Reset load balancer state during restoraion

- pkg/etcd/etcd_int_test.go
- tests/TESTING.md
- tests/integration/localstorage_int_test.go
- tests/util/cmd.go
The existing integration tests that require a K3s server have been modified. Tests now can run on an existing k3s server via a compile time flag. Tests will skip if the running server is not configured with the flags required of the test.
Documentation change to explain this option.
Changed test util cmd.go to support checks for existing clusters, and exec k3s commands with installed executable.
- Start a k3s cluster without etcd
`k3s server`
Run integration tests
`go test -v -ldflags "-X 'github.com/rancher/k3s/tests/util.existingServer=True'" ./pkg/... ./tests/... -run Integration`
Observe that the tests pass, but each integration testlet skip due to missing flags.
- Start a k3s cluster with etcd
`k3s server --cluster-init`
Run integration tests
`go test -v -ldflags "-X …
> Enable K3s integration test to run on existing cluster

- pkg/etcd/etcd_int_test.go
- tests/TESTING.md
- tests/integration/localstorage_int_test.go
- tests/util/cmd.go
Reverts k3s-io/k3s#3892
Included a typo that causes drone publish to fail on golang lint
> Revert "Enable K3s integration test to run on existing cluster"

- pkg/daemons/agent/agent_linux.go
Fix k 1.22 regression (#3900)
Kubernetes 1.22 requires `KuebletInUserNamespace` feature gate to be set for rootless:
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/#userns-the-hard-way
BugFix
Observe CI
Fix #3900
> Fix rootless regression in 1.22 (Set KubeletInUserNamespace gate)

- pkg/apiaddresses/controller.go
Bug fix
```
apiVersion: v1
kind: Service
metadata:
name: busyb
spec:
selector:
app: busy
ports:
port: 1234
---
metadata:
name: busydep
spec:
replicas: 3
selector:
matchLabels:
app: busy
template:
metadata:
labels:
app: busy
spec:
containers:
command:
- sleep
- "3600"
``` …
> Fix condition for adding kubernetes endpoints

- pkg/apiaddresses/controller.go
Bug fix
```
apiVersion: v1
kind: Service
metadata:
name: busyb
spec:
selector:
app: busy
ports:
port: 1234
---
metadata:
name: busydep
spec:
replicas: 3
selector:
matchLabels:
app: busy
template:
metadata:
labels:
app: busy
spec:
containers:
command:
- sleep
- "3600"
``` …
> [release-1.21] Fix condition for adding kubernetes endpoints 

- pkg/apiaddresses/controller.go
Bug fix
```
apiVersion: v1
kind: Service
metadata:
name: busyb
spec:
selector:
app: busy
ports:
port: 1234
---
metadata:
name: busydep
spec:
replicas: 3
selector:
matchLabels:
app: busy
template:
metadata:
labels:
app: busy
spec:
containers:
command:
- sleep
- "3600"
``` …
> [release-1.19] Fix condition for adding kubernetes endpoints

- pkg/apiaddresses/controller.go
Bug fix
```
apiVersion: v1
kind: Service
metadata:
name: busyb
spec:
selector:
app: busy
ports:
port: 1234
---
metadata:
name: busydep
spec:
replicas: 3
selector:
matchLabels:
app: busy
template:
metadata:
labels:
app: busy
spec:
containers:
command:
- sleep
- "3600"
``` …
> [release-1.20] Fix condition for adding kubernetes endpoints

- pkg/apiaddresses/controller.go
Bug fix
```
apiVersion: v1
kind: Service
metadata:
name: busyb
spec:
selector:
app: busy
ports:
port: 1234
---
metadata:
name: busydep
spec:
replicas: 3
selector:
matchLabels:
app: busy
template:
metadata:
labels:
app: busy
spec:
containers:
command:
- sleep
- "3600"
``` …
> [engine-1.21] Fix condition for adding kubernetes endpoints 

- go.mod
- go.sum
- pkg/cli/server/server.go
- pkg/cluster/cluster.go
- pkg/daemons/control/server.go
- pkg/etcd/etcd.go
- vendor/github.com/google/uuid/null.go
- vendor/github.com/k3s-io/kine/pkg/drivers/generic/generic.go
- vendor/github.com/k3s-io/kine/pkg/drivers/generic/tx.go
- vendor/github.com/k3s-io/kine/pkg/drivers/mysql/mysql.go
- vendor/github.com/k3s-io/kine/pkg/drivers/pgsql/pgsql.go
- vendor/github.com/k3s-io/kine/pkg/drivers/sqlite/sqlite.go
- vendor/github.com/k3s-io/kine/pkg/endpoint/endpoint.go
- vendor/github.com/k3s-io/kine/pkg/endpoint/http.go
- vendor/github.com/k3s-io/kine/pkg/logstructured/logstructured.go
- vendor/github.com/k3s-io/kine/pkg/logstructured/sqllog/sql.go
- vendor/github.com/k3s-io/kine/pkg/server/cluster.go
- vendor/github.com/k3s-io/kine/pkg/server/dbsize.go
- vendor/github.com/k3s-io/kine/pkg/server/kv.go
- vendor/github.com/k3s-io/kine/pkg/server/lease.go
- vendor/github.com/k3s-io/kine/pkg/server/limited.go
- vendor/github.com/k3s-io/kine/pkg/server/maintenance.go
- vendor/github.com/k3s-io/kine/pkg/server/server.go
- vendor/github.com/k3s-io/kine/pkg/server/types.go
- vendor/github.com/k3s-io/kine/pkg/server/watch.go
- vendor/modules.txt
Update kine
version bump
`kubectl get --raw /metrics | grep etcd_db`
* #3952
```release-note
Kine has been updated to v0.8.0, making the `etcd_db_total_size_in_bytes` apiserver metric available to track database size.
```
> Bump kine for metrics/tls changes

- install.sh
When installing k3s on a raspberry Pi one of the nuisances is that the installer looks to have worked just fine:
```
root@datalore:~# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.18.9+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.18.9+k3s1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh …
```
> added raspberry installation hint

- pkg/agent/config/config.go
- pkg/cli/server/server.go
- pkg/cluster/https.go
- pkg/daemons/control/deps/deps.go
- pkg/util/net.go
Add missing node name entry to apiserver SAN list. Also honor node-ip when adding the node address to the SAN list, instead of hardcoding the autodetected IP address.
This converts the agent getHostnameAndIPs function into a utility function, and cleans up some import aliases resolved by moving it out of the agent config module.
bugfix
* `echo QUIT |openssl s_client -connect localhost:6444 2>&1 | openssl x509 -noout -text | grep -A1 Alternative`
* Verify that the list contains the node name IP address; the hostname and private IP should be used by default, or --node-name and --node-ip values if set.
* #3960
This is mostly only visible on RKE2, but...
```release-note
The local kube-apiserver that is available on port 6444 on server nodes now includes the node name in the certificate SAN …
```
> Add missing node name entry to apiserver SAN list

- pkg/agent/config/config.go
- pkg/cli/server/server.go
- pkg/cluster/https.go
- pkg/daemons/control/deps/deps.go
- pkg/util/net.go
Add missing node name entry to apiserver SAN list. Also honor node-ip when adding the node address to the SAN list, instead of hardcoding the autodetected IP address.
This converts the agent getHostnameAndIPs function into a utility function, and cleans up some import aliases resolved by moving it out of the agent config module.
bugfix
* `echo QUIT |openssl s_client -connect localhost:6444 2>&1 | openssl x509 -noout -text | grep -A1 Alternative`
* Verify that the list contains the node name IP address; the hostname and private IP should be used by default, or --node-name and --node-ip values if set.
* #3961
This is mostly only visible on RKE2, but...
```release-note
The local kube-apiserver that is available on port 6444 on server nodes now includes the node name in the certificate SAN …
```
> [release-1.21] Add missing node name entry to apiserver SAN list

- pkg/agent/config/config.go
- pkg/cli/server/server.go
- pkg/cluster/https.go
- pkg/daemons/control/deps/deps.go
- pkg/util/net.go
Add missing node name entry to apiserver SAN list. Also honor node-ip when adding the node address to the SAN list, instead of hardcoding the autodetected IP address.
This converts the agent getHostnameAndIPs function into a utility function, and cleans up some import aliases resolved by moving it out of the agent config module.
bugfix
* `echo QUIT |openssl s_client -connect localhost:6444 2>&1 | openssl x509 -noout -text | grep -A1 Alternative`
* Verify that the list contains the node name IP address; the hostname and private IP should be used by default, or --node-name and --node-ip values if set.
* #3961
This is mostly only visible on RKE2, but...
```release-note
The local kube-apiserver that is available on port 6444 on server nodes now includes the node name in the certificate SAN …
```
> [engine-1.21] Add missing node name entry to apiserver SAN list

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/cmds/server.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/etcd/etcd.go
- pkg/etcd/s3.go
Adds a `--s3-insecure` flag to disable s3 over HTTPS in the etcd-snapshot feature
New feature
- Set up a local minio instance that's only accessable over HTTP.
- Create a etcd snapshot with the new flag. e.g.
```
sudo k3s etcd-snapshot \
--s3 \
--s3-endpoint="192.168.42.60:9000" \
--s3-bucket="etcd-snapshots" \
--s3-access-key="" \
--s3-secret-key="" \
--s3-insecure
```
* https://github.com/k3s-io/k3s/issues/3972
```release-note
```
> Allow option to disable s3 over https when using etcd-snapshot

- pkg/daemons/agent/agent_linux.go
Don't attempt to start the Kubelet with the feature-gate disabled; it's locked on. Just print an error and fail early.
bugfix
Attempt to start K3s on a system without PIDS cgroup support (not sure how to find such a system)
* #3786
```release-note
K3s will no longer attempt to disable the SupportPodPidsLimit FeatureGate on nodes without PIDS cgroup support. PIDS cgroup support is mandatory as of Kubernetes 1.20.
```
> SupportPodPidsLimit is locked to true of 1.20, making pids cgroup support mandatory

- cmd/agent/main.go
- cmd/etcdsnapshot/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/agent/flannel/setup.go
- pkg/cluster/https.go
- pkg/daemons/executor/embed.go
- pkg/daemons/executor/etcd.go
- pkg/daemons/executor/executor.go
- pkg/etcd/etcd.go
- pkg/server/server.go
- vendor/k8s.io/klog/klog.go
- vendor/k8s.io/klog/klog_file.go
- vendor/k8s.io/klog/v2/klog.go
- vendor/modules.txt
Use a forked version of klog where Fatal log messages don't print a full thread dump and then call `os.Exit(255)`. This allows us to recover out of core component failures and do our own error handling.
This PR also properly ignores context cancelation errors, so that k3s cleanly exits when signaled. Currently, K3s treats the context cancelation as an error and always terminates with a fatal message and non-zero exit code.
Bugfix
* run`systemctl stop k3s`, then run `systemctl status k3s` - note that it shows `status=0/SUCCESS` instead of `status=1/FAILURE` to indicate a clean shutdown.
* start k3s server with `--cluster-cidr=10.41.0.0/16,10.42.0.0/26` - note that it exits with a simple error instead of a big stack trace.
* #2624
* #3977
```release-note
Failures within core Kubernetes …
```
> Properly handle fatal errors and context cancelation

- pkg/etcd/etcd.go
When exposing etcd metrics, add an exposed listener instead of replacing the loopback listener
bugfix
Start k3s with --etcd-expose-metrics; note that it is listening on the metrics port on both loopback and the host IP
* #3983
```release-note
Exposing etcd metrics on the host IP no longer disables the localhost metrics listener
```
> Add exposed metrics listener instead of replacing loopback listener

- pkg/etcd/etcd.go
When exposing etcd metrics, add an exposed listener instead of replacing the loopback listener
bugfix
Start k3s with --etcd-expose-metrics; note that it is listening on the metrics port on both loopback and the host IP
* #3984
```release-note
Exposing etcd metrics on the host IP no longer disables the localhost metrics listener
```
> [release-1.21] Add exposed metrics listener instead of replacing loopback listener

- pkg/cluster/managed.go
Call managed db reset function when cluster reset flag is passed
bug fix
- running k3s server --cluster-reset should work as expected and reset quorum of the cluster
https://github.com/k3s-io/k3s/issues/3988
Original Issue:  https://github.com/k3s-io/k3s/issues/3651
Original PR:  https://github.com/k3s-io/k3s/pull/3650
> [Release-1.19] Backport cluster-reset fix

- pkg/etcd/etcd.go
When exposing etcd metrics, add an exposed listener instead of replacing the loopback listener
bugfix
Start k3s with --etcd-expose-metrics; note that it is listening on the metrics port on both loopback and the host IP
* #3984
```release-note
Exposing etcd metrics on the host IP no longer disables the localhost metrics listener
```
> [engine-1.21] Add exposed metrics listener instead of replacing loopback listener

- install.sh
We only package selinux RPMs for EL7 and EL8; treat anything that's doesn't have a VERSION_ID major of 7 as 8.
installer
Install on Fedora
* #3990 
```release-note
```
> Anything not EL7 is EL8

- go.mod
- pkg/agent/run.go
- pkg/daemons/control/server.go
- pkg/util/api.go
Wait for apiserver readyz instead of healthz
bugfix
Upgrade multi-node cluster from 1.21 to 1.22; note that controllers don't start before all the apiserver storageversions stuff has figured itself out.
* #3994 
```release-note
```
This adds a new utility function cribbed from controller-manager:
https://github.com/kubernetes/kubernetes/blob/release-1.22/staging/src/k8s.io/controller-manager/app/helper.go#L31-L32
Deprecation reference: https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health
> Wait for apiserver readyz instead of healthz

- contrib/util/check-config.sh
Problem:
In `check-config.sh` assumptions are made about cgroups v1/v2/hybrid,
causes false-negative on pure V2 system.
Solution:
In `check-config.sh` implement the same validation as found in
`./pkg/agent/run.go` -> `validate()`, `validateCgroupsV1()`, `validateCgroupsV2()`
[ which use `containerd/cgroups:utils.go` -> `Mode()` ]
Signed-off-by: Rowan Thorpe <rowan@rowanthorpe.com>
On a Debian Testing system with cgroups v2 only (not hybrid) `k3s check-config` throws a false-negative. This seems to be just due to the contrib shellscript taking some pragmatic shortcuts to do a quick sanity-check, but on a cgroups v2 only system those shortcuts impact enough to be false. I just replicated in shellscript the validation logic from the core Go files (mentioned in the commit message) to make the …
> Handle cgroup v1/2/hybrid in check-config.sh more explicitly/accurately

- go.mod
- go.sum
- scripts/airgap/image-list.txt
- vendor/github.com/k3s-io/helm-controller/pkg/helm/controller.go
- vendor/modules.txt
Bump helm-controller and klipper-helm image version
*Waiting for merge and tag of https://github.com/k3s-io/helm-controller/pull/118*
bugfix
Upgrade a K3s cluster from 1.21 to 1.22
* #3994 
```release-note
The embedded Helm controller now ensures that deprecated or removed Kubernetes api versions are handled properly during upgrades.
```
> Bump helm-controller and klipper-helm image version

- install.sh
This PR simply modifies the install script to retrieve the environment variables that are prefixed with "CONTAINERD_",thus allowing to configure containerd at installation
Bugfix
Install K3s master node with this change and variables prefixed with "CONTAINERD_"
On the master node, check the content of the /etc/systemd/system/k3s.service.env
https://github.com/k3s-io/k3s/issues/4008
```release-note
NONE
```
> Fixes #4008 by retrieving environment variables prefixed with "CONTAINERD_"

- pkg/containerd/utility_windows.go
Add StargzSupported stub for Windows
RKE2 won't build without this
bugfix
No QA validation needed
* #2918 
```release-note
```
> Add StargzSupported stub for Windows

- pkg/agent/containerd/config_linux.go
- pkg/agent/containerd/nvidia.go
- pkg/agent/containerd/nvidia_test.go
- pkg/agent/templates/templates.go
- pkg/agent/templates/templates_linux.go
This patch updates the default containerd config template with support for adding extra container runtimes, and adds logic to discover nvidia container runtimes installed via the the gpu operator or package manager.
New Feature
`go test -run ^Test_UnitFindNvidiaContainerRuntimes$ github.com/rancher/k3s/pkg/agent/containerd`
A related bugfix has been submitted to the GPU Operator
(update: will be fixed in gpu-operator v1.8.1)
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/288/diffs#d77d1d7e623dc09e3e576662f914bbe1cf2b5226
```release-note
NONE
```
> Nvidia container runtime discovery in containerd config template

- contrib/util/check-config.sh
Problem:
A false-negative in check-config.sh for cgroups v2 systems was fixed but the commit introduced a regression based on a small assumption that content of /sys/fs/cgroup/cgroup.controllers would have the same format as the content of /proc/self/cgroup. It doesn't.
Solution:
This just tweaks the regex to count occurrences of either cgroup subsystem-names on each line (as occurs in the sysfs pseudo-file), or those names with colons either side (as occurs in the procfs pseudo-file).
* #4013
> Fix regression from commit 137e80cd865efe51aa3ef0323fd6b0a014b7b9de

- pkg/daemons/control/server.go
Enable JobTrackingWithFinalizers FeatureGate
Works around issue with Job controller not tracking job pods that are in CrashloopBackoff during upgrade from 1.21 to 1.22.
bugfix
* #3994
```release-note
The JobTrackingWithFinalizers alpha feature-gate is now enabled by default.
```
> Enable JobTrackingWithFinalizers FeatureGate

- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
Use the new klipper-lb image that has newer go and Alpine versions
Dump a new version
Deploy a service with type loadbalancer
https://github.com/k3s-io/k3s/issues/4021
```
klipper-lb upgrade to 0.3.0
```
> Use the newer klipper-lb image

- pkg/cli/server/server.go
- pkg/daemons/config/types.go
- pkg/etcd/etcd.go
- Using node names and not os.Hostname for etcd membership
- making sure there are no duplicates when joining a new etcd node
bug fix
- Start a server with node name node1
- join another server with the same node name
you should get an error stating the following:
```
FATA[0000] starting kubernetes: preparing server: start managed database: joining etcd cluster: Failed to join etcd cluster due to duplicate node names, please use unique node name for the server
```
https://github.com/k3s-io/k3s/issues/2769
There are none, this shouldnt affect the current way we join etcd members, as for current etcd members they wont get affected since they are using the node name that is on file already
> Make sure there are no duplicates in etcd member list

- pkg/servicelb/controller.go
Disable automounting service account token in servicelb pods
They don't need em, don't mount em.
* enhancement
See `kubectl describe` output in linked issue; no tokens should be mounted.
* #4040 
```release-note
servicelb pods no longer mount the kube-system default service account token
```
This wasn't hurting anything but it seems like an easy optimization / reduction in unnecessary privilege.
> Disable automounting service account token in servicelb pods

- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
Reverts k3s-io/k3s#4029
We need to do additional work to bring the armv7l klipper-lb image up to date; will try this again once that's ready.
> Revert "Use the newer klipper-lb image"

- .drone.yml
Prevent CI from publishing artifacts around engine-1.21 tags. We need the tag for other repos to latch onto, but not the artifacts.
Enhancement
```release-note
NONE
```
> Update drone to not publish artifacts for engine tags

- .drone.yml
Fixed ref to refs typo for drone excludes. Prevents drone from building engine release artifacts.
* #4063
> [Engine-1.21] Fix ref typo

- Dockerfile.dapper
- Dockerfile.test.dapper
ci; bugfix
Check CI
* TBD
```release-note
NONE
```
> [engine-1.21] Update build images to python3 for compat with recent gsutil change

- pkg/daemons/agent/agent_linux.go
Drop broken SupportNoneCgroupDriver support
rootless
Run k3s rootless
#3596 
```release-note
Rootless support now requires delegated cgroup v2 support.
```
> Drop broken SupportNoneCgroupDriver support

- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
Upgrades klipper-lb to 0.3.0, which has a newer alpine image base
Version dump
Create a service of type LoadBalancer
https://github.com/k3s-io/k3s/issues/4079
```
Move to klipper-lb 0.3.0
```
> Use the new klipper-lb image that has newer go and Alpine versions

- pkg/agent/syssetup/setup.go
Backport form: https://github.com/k3s-io/k3s/pull/4098
Linked issue: https://github.com/k3s-io/k3s/issues/4060
> [Backport 1.21] Enable the inheritance of settings for ipv6

- pkg/agent/syssetup/setup.go
Backport form: https://github.com/k3s-io/k3s/pull/4098
Linked issue: https://github.com/k3s-io/k3s/issues/4100
> [Backport 1.22] Enable the inheritance of settings for ipv6

- pkg/cli/agent/agent.go
- pkg/cli/cmds/init_default.go
- pkg/cli/cmds/init_linux.go
- pkg/cli/server/server.go
Properly handle operation as init process. This includes both vacating the root cgroup on cgroupv2 systems, and reaping child processes since containerd doesn't clean up after its own shims.
This is a Go adaptation of the behavior proposed in #3237; we rejected doing this in shell and K3d has been using a workaround ever since.
bugfix
* Run K3s in Docker on a system with cgroup v2; note that it works
* Note that there are no `<defunct>` processes inside the Docker container
* #4085
* #2722 
```release-note
The K3s docker image now works on cgroup v2 systems, and properly reaps terminated containerd shim processes.
```
> Properly handle operation as init process

- pkg/cli/agent/agent.go
- pkg/cli/cmds/init_default.go
- pkg/cli/cmds/init_linux.go
- pkg/cli/server/server.go
Properly handle operation as init process. This includes both vacating the root cgroup on cgroupv2 systems, and reaping child processes since containerd doesn't clean up after its own shims.
This is a Go adaptation of the behavior proposed in #3237; we rejected doing this in shell and K3d has been using a workaround ever since.
bugfix
* Run K3s in Docker on a system with cgroup v2; note that it works
* Note that there are no `<defunct>` processes inside the Docker container
* Backport of #4086 
* #4085
* #2722 
```release-note
The K3s docker image now works on cgroup v2 systems, and properly reaps terminated containerd shim processes.
```
> [release-1.22] Properly handle operation as init process

- pkg/cli/agent/agent.go
- pkg/cli/cmds/init_default.go
- pkg/cli/cmds/init_linux.go
- pkg/cli/server/server.go
Properly handle operation as init process. This includes both vacating the root cgroup on cgroupv2 systems, and reaping child processes since containerd doesn't clean up after its own shims.
This is a Go adaptation of the behavior proposed in #3237; we rejected doing this in shell and K3d has been using a workaround ever since.
bugfix
* Run K3s in Docker on a system with cgroup v2; note that it works
* Note that there are no `<defunct>` processes inside the Docker container
* Backport of #4086 
* #4092 
* #4093
```release-note
The K3s docker image now works on cgroup v2 systems, and properly reaps terminated containerd shim processes.
```
> [release-1.21] Properly handle operation as init process

- pkg/cli/agent/agent.go
- pkg/cli/cmds/init_default.go
- pkg/cli/cmds/init_linux.go
- pkg/cli/server/server.go
Properly handle operation as init process. This includes both vacating the root cgroup on cgroupv2 systems, and reaping child processes since containerd doesn't clean up after its own shims.
This is a Go adaptation of the behavior proposed in #3237; we rejected doing this in shell and K3d has been using a workaround ever since.
bugfix
* Build RKE2 with this release and run it in Docker on a system with cgroup v2; note that it works
* Note that there are no `<defunct>` processes inside the Docker container
* Backport of #4086 
* #4092 
* #4093
```release-note
The K3s docker image now works on cgroup v2 systems, and properly reaps terminated containerd shim processes.
```
> [engine-1.21] Properly handle operation as init process

- pkg/cli/cmds/log.go
Send MAINPID to systemd when reexecing for logfile output. This allows the new process to notify systemd when it is ready, instead of having `systemctl start k3s` hang forever because only the first pid is allowed to notify.
bugfix
Add `--log=/var/log/k3s.log` to flags or config file and start K3s systemd unit; note that it completes successfully.
* #1356
* #2277
* #2825
* #3202
```release-note
The k3s systemd unit will no longer hang starting when the `--log` flag is used to redirect output
```
> Send MAINPID to systemd when reexecing for logfile output

- pkg/cli/cmds/init_linux.go
Don't evacuate the root cgroup when rootless; fixes regression introduced by #4086
rootless
* #4085
```release-note
Fixed a regression introduced by #4086 that broke rootless support
```
> Don't evacuate the root cgroup when rootless

- pkg/cli/cmds/init_linux.go
Don't evacuate the root cgroup when rootless; fixes regression introduced by #4088
rootless
* #4085
```release-note
Fixed a regression introduced by #4088 that broke rootless support
```
> [release-1.22] Don't evacuate the root cgroup when rootless

- pkg/cli/cmds/init_linux.go
Don't evacuate the root cgroup when rootless; fixes regression introduced by #4089
rootless
* #4092
```release-note
Fixed a regression introduced by #4089 that broke rootless support
```
> [release-1.21] Don't evacuate the root cgroup when rootless

- pkg/cli/cmds/init_linux.go
Don't evacuate the root cgroup when rootless; fixes regression introduced by #4090
rootless
* #4092
```release-note
Fixed a regression introduced by  #4090 that broke rootless support
```
> [engine-1.21] Don't evacuate the root cgroup when rootless

- pkg/cli/cmds/init_linux.go
Don't evacuate the root cgroup when rootless; fixes regression introduced by #4091
rootless
* #4094
```release-note
Fixed a regression introduced by #4091 that broke rootless support
```
> [release-1.20] Don't evacuate the root cgroup when rootless

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_unix.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_windows.go
- vendor/github.com/containerd/containerd/container_opts.go
- vendor/github.com/containerd/containerd/content/helpers.go
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
- vendor/github.com/containerd/containerd/go.mod
- vendor/github.com/containerd/containerd/go.sum
- vendor/github.com/containerd/containerd/metadata/content.go
- vendor/github.com/containerd/containerd/oci/spec_opts_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/container_create.go
- vendor/github.com/containerd/containerd/pkg/cri/server/container_create_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/helpers.go
- vendor/github.com/containerd/containerd/pkg/cri/server/helpers_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/sandbox_run.go
- vendor/github.com/containerd/containerd/pkg/cri/server/sandbox_run_linux.go
- vendor/github.com/containerd/containerd/runtime/v1/linux/bundle.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle_default.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle_linux.go
- vendor/modules.txt
Bump containerd to v1.5.7+k3s1
CVE
* #4141
```release-note
The embedded containerd has been updated to v1.5.7+k3s1 to address CVE-2021-41103
```
> Bump containerd to v1.5.7+k3s1

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_unix.go
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_windows.go
- vendor/github.com/containerd/containerd/container_opts.go
- vendor/github.com/containerd/containerd/content/helpers.go
- vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
- vendor/github.com/containerd/containerd/go.mod
- vendor/github.com/containerd/containerd/go.sum
- vendor/github.com/containerd/containerd/metadata/content.go
- vendor/github.com/containerd/containerd/oci/spec_opts_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/container_create.go
- vendor/github.com/containerd/containerd/pkg/cri/server/container_create_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/helpers.go
- vendor/github.com/containerd/containerd/pkg/cri/server/helpers_linux.go
- vendor/github.com/containerd/containerd/pkg/cri/server/sandbox_run.go
- vendor/github.com/containerd/containerd/pkg/cri/server/sandbox_run_linux.go
- vendor/github.com/containerd/containerd/runtime/v1/linux/bundle.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle_default.go
- vendor/github.com/containerd/containerd/runtime/v2/bundle_linux.go
- vendor/modules.txt
Bump containerd to v1.5.7+k3s1
CVE
* #4142
```release-note
The embedded containerd has been updated to v1.5.7+k3s1 to address CVE-2021-41103
```
> [release-1.22] Bump containerd to v1.5.7+k3s1

- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
This PR provides dual-stack support in the servicelb controller. There are basically three main changes:
1 - Depending on the value of  "svc.Spec.IPFamilyPolicy", the service will set ipv4, ipv6 or dual-stack externalIPs
2 - Depending on the value of "svc.Spec.IPFamilies[0]", i.e. what class of IP has more priority, either ipv4 or ipv6 addressess will get first
Note that these two points are basically replicating what is explained in the docs https://kubernetes.io/docs/concepts/services-networking/dual-stack/
3 -  klipper-lb daemonset will get the svc.Spec.ClusterIPs as DEST_IPs env variable instead of svc.Spec.ClusterIP. This basically means supporting dual-stack services that have two ip addresses:
```
clusterIP: 10.43.189.134
clusterIPs:
- 10.43.189.134
- 2001:cafe:42:1::51f4
```
New …
> Dual-stack support in serviceLB controller

- pkg/agent/flannel/setup.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/server/context.go
* If using the built-in CCM, wait for it to clear the uninitialized taint before starting the scheduler to ensure that pods can be scheduled immediately.
* Optimize agent startup time by watching the local node instead of getting/sleeping in a loop.
bugfix
* #4340
```release-note
Resolved an issue that would occasionally cause K3s to take more than a minute to schedule initial pods on the first server in a cluster.
```
> Reduce node startup time

- pkg/agent/flannel/setup.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/executor/embed.go
- pkg/server/context.go
* If using the built-in CCM, wait for it to clear the uninitialized taint before starting the scheduler to ensure that pods can be scheduled immediately.
* Optimize agent startup time by watching the local node instead of getting/sleeping in a loop.
bugfix
* https://github.com/k3s-io/k3s/issues/4360
```release-note
Resolved an issue that would occasionally cause K3s to take more than a minute to schedule initial pods on the first server in a cluster.
```
> [release-1.21] Reduce node startup time

- pkg/agent/flannel/setup.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/executor/embed.go
- pkg/server/context.go
* If using the built-in CCM, wait for it to clear the uninitialized taint before starting the scheduler to ensure that pods can be scheduled immediately.
* Optimize agent startup time by watching the local node instead of getting/sleeping in a loop.
bugfix
* https://github.com/k3s-io/k3s/issues/4360
```release-note
Resolved an issue that would occasionally cause K3s to take more than a minute to schedule initial pods on the first server in a cluster.
```
> [engine-1.21] Reduce node startup time

- pkg/agent/flannel/setup.go
- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/daemons/executor/embed.go
- pkg/server/context.go
* If using the built-in CCM, wait for it to clear the uninitialized taint before starting the scheduler to ensure that pods can be scheduled immediately.
* Optimize agent startup time by watching the local node instead of getting/sleeping in a loop.
bugfix
* https://github.com/k3s-io/k3s/issues/4359
```release-note
Resolved an issue that would occasionally cause K3s to take more than a minute to schedule initial pods on the first server in a cluster.
```
> [release-1.22] Reduce node startup time

- .github/workflows/snapshotter.yaml
- Dockerfile.dapper
- go.sum
- pkg/containerd/builtins_linux.go
- scripts/build
- tests/snapshotter/btrfs/opensuse-leap/Vagrantfile
- vendor/github.com/containerd/btrfs/.gitignore
- vendor/github.com/containerd/btrfs/LICENSE
- vendor/github.com/containerd/btrfs/Makefile
- vendor/github.com/containerd/btrfs/README.md
- vendor/github.com/containerd/btrfs/btrfs.c
- vendor/github.com/containerd/btrfs/btrfs.go
- vendor/github.com/containerd/btrfs/btrfs.h
- vendor/github.com/containerd/btrfs/doc.go
- vendor/github.com/containerd/btrfs/go.mod
- vendor/github.com/containerd/btrfs/go.sum
- vendor/github.com/containerd/btrfs/helpers.go
- vendor/github.com/containerd/btrfs/info.go
- vendor/github.com/containerd/btrfs/ioctl.go
- vendor/github.com/containerd/containerd/snapshots/btrfs/btrfs.go
- vendor/github.com/containerd/containerd/snapshots/btrfs/plugin/plugin.go
- vendor/modules.txt
Enable the BTRFS snapshotter in containerd.
Readily available on many Linux systems including SUSE offerings. Seems pretty decent. No good reason not to ship it.
The BTRFS snapshotter is now builtin to the k3s binary and ready for action.
Tested with:
- `vagrant up --provider=libvirt`
- `VAGRANT_EXPERIMENTAL=disks vagrant up --provider=virtualbox`
```shell
cd tests/snapshotter/btrfs/opensuse-leap
vagrant plugin install vagrant-libvirt # if using the libvirt provider
vagrant plugin install vagrant-k3s
VAGRANT_EXPERIMENTAL=disks vagrant up # envvar required for any provider other than libvirt
```
Failure will get you a non-zero exit code. On success you should see output like this:
```
==> snapshotter-btrfs: Running provisioner: k3s-ready (shell)...
snapshotter-btrfs: Running: inline script …
```
> containerd/cri: enable the btrfs snapshotter

- pkg/cli/cmds/log_linux.go
bugfix
* #4189
```release-note
```
> Fix log/reap reexec

- pkg/cli/cmds/log_linux.go
bugfix
* #4195
```release-note
```
> [release-1.22] Fix log/reap reexec

- pkg/cli/cmds/log_linux.go
bugfix
* #4196
```release-note
```
> [engine-1.21] Fix log/reap reexec

- pkg/cli/cmds/log_linux.go
bugfix
* #4196
```release-note
```
> [release-1.21] Fix log/reap reexec

- pkg/cli/cmds/log_linux.go
bugfix
* #4197
```release-note
```
> [release-1.20] Fix log/reap reexec

- pkg/agent/tunnel/tunnel.go
should use a simple channel send/receive instead of select with a single case
code hygiene 
see linked PR
* #4369
```release-note
```
> refactor: Use plain channel send or receive

- install.sh
transactional-update was always under /usr/sbin for SLE Micro
Fix the path used to detect presence of transactional-update system
Correcting  PR: https://github.com/k3s-io/k3s/pull/4331
I've run install.sh on SLE Micro OS 5.1 image
PR: https://github.com/k3s-io/k3s/pull/4331
```release-note
```
openSUSE MicroOS is based on Tumbleweed which has already replaced /bin with just /usr/bin and /bin is symlinked to /usr/bin which could have resulted in the this script working on openSUSE. SLE doesn't have plans to do the same filesystem changes.
> install.sh: fix path detection for sle-micro

- Dockerfile.dapper
- scripts/package-airgap
Replace gzip with pigz
Tests: 
- 6 core, 12 thread machine
- Ubuntu 20.04
Average time of 3 runs of `make` with gzip: 2m 34s
Average time of 3 runs of `make` with pigz: 2m 15s
Enhancement
`make` passes
https://github.com/k3s-io/k3s/issues/4410
```release-note
```
> Replace gzip with pigz for faster builds

- .github/workflows/install.yaml
- install.sh
- tests/install/centos-7/Vagrantfile
- tests/install/centos-8/Vagrantfile
- tests/install/fedora-coreos/Vagrantfile
- tests/install/opensuse-leap/Vagrantfile
- tests/install/ubuntu-focal/Vagrantfile
Fix for sle-micro / microos to use the correct location when attempting to detect for `transactional-update`
installer script
```shell
cd tests/install/opensuse-microos
vagrant plugin install vagrant-reload vagrant-k3s
vagrant up --provider=virtualbox
```
#4402 
#4409 
```release-note
Improved MicroOS support for k3s-uninstall.sh
```
> install: /usr/sbin/transactional-update (and uninstall fix)

- tests/integration/dualstack/dualstack_int_test.go
Fixed checks on dualstack test in CI. Test is currently flaky because depending on how fast/slow the test "skips" through the body, the k3s server may have already crashed from an incorrect startup, causing failures in later tests.
`export CI=true`
`go test -v ./test/integration/dualstack/... -run Integration` properly skips both the test body and startup/teardown
https://github.com/k3s-io/k3s/issues/4339
```release-note
```
> Corrected skip check for dualstack on CI

- Makefile
- go.mod
- go.sum
- pkg/agent/containerd/containerd.go
- pkg/cli/agent/agent.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cli/server/server.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_apply.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_compare.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset_process.go
- vendor/github.com/rancher/wrangler/pkg/signals/signal.go
- vendor/modules.txt
Updates to using wrangler v0.8.8 which includes fixes to the signal handler to give a exported func to cancel the the context by hand. this is useful in windows services and gives us a way to cancel context to kill all sub-processes and exit gracefully when using windows service manager.
vendor update, small code change to align k3s to use library slight different and pass in context to containerd
this will ultimately be used in rke2 windows services, this will be tested by QA when we work on closing the linked issue.
https://github.com/rancher/rke2/issues/1755
none
> [engine-1.21] updating to new signals package in wrangler

- pkg/bootstrap/bootstrap.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cluster/bootstrap.go
- pkg/cluster/cluster.go
- pkg/cluster/storage.go
- pkg/daemons/control/server.go
- pkg/daemons/executor/etcd.go
- pkg/etcd/etcd.go
- pkg/etcd/etcd_test.go
Resolves issue #4335 as well as changes the expected behavior from a 2 way synchronization of data between disk and database to a 1 way with the database being authoritative and disk changes resulting in a processing halt.
**Scenario 2**
Same steps for verifying #4335
**Scenario 2**
Start server 1.
Stop server 1. 
Change the contents of a file in the bootstrap data: client-ca.crt for example.
Start server 1.
Observe a failure indicating that the file has been changed and a suggestion for it to be removed to be subsequently recovered.
A handy means of verifying that the same data exists on any node:
```sh
md5sum /var/lib/rancher/k3s/server/tls/client-ca.crt
```
#4335 
```release-note
```
> update bootstrap logic

- pkg/agent/config/config.go
- pkg/agent/run.go
- pkg/cli/cmds/agent.go
- pkg/cli/server/server.go
- pkg/daemons/agent/agent_linux.go
- pkg/daemons/config/types.go
- pkg/servicelb/controller.go
As explained in the issue, in kernels older than 5.1, the klipper-lb image should set `net.ipv6.conf.all.forwarding` to 1 because the default is 0. When kernels are newer or equal to 5.1, we can inherit that config from the root namespace instead of using the default.
Distros like centos or RHEL use a kernel older than 5.1
We are whitelisting `net.ipv6.conf.all.forwarding` in Kubelet so that pods can change that parameter. Then, starting the svclb pod changing that parameter to one. The whitelisting only happens when svclb is not disabled and we are in dual-stack mode (pod, services and node-ip having both ipv4 and ipv6). svclb adding `net.ipv6.conf.all.forwarding` only happens if the ipFamily of the service contains IPv6 
bug fix
Deploy …
> Allow svclb pod to enable ipv6 forwarding

- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/util/api.go
Since we now start the server's agent sooner and in the background, we
may need to wait longer than 30 seconds for the apiserver to become
ready on downstream projects such as RKE2.
Since this essentially just serves as an analogue for the server's
apiReady channel, there's little danger in setting it to something
relatively high.
bugfix
* Normal CI checks on K3s.
* Should resolve CI failures currently seen when updating K3s in RKE2.
* TBD
```release-note
```
> Increase agent's apiserver ready timeout

- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/util/api.go
Since we now start the server's agent sooner and in the background, we
may need to wait longer than 30 seconds for the apiserver to become
ready on downstream projects such as RKE2.
Since this essentially just serves as an analogue for the server's
apiReady channel, there's little danger in setting it to something
relatively high.
bugfix
* Normal CI checks on K3s.
* Should resolve CI failures currently seen when updating K3s in RKE2.
* TBD
```release-note
```
> [release-1.22] Increase agent's apiserver ready timeout

- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/util/api.go
Since we now start the server's agent sooner and in the background, we
may need to wait longer than 30 seconds for the apiserver to become
ready on downstream projects such as RKE2.
Since this essentially just serves as an analogue for the server's
apiReady channel, there's little danger in setting it to something
relatively high.
bugfix
* Normal CI checks on K3s.
* Should resolve CI failures currently seen when updating K3s in RKE2.
* TBD
```release-note
```
> [engine-1.21] Increase agent's apiserver ready timeout

- pkg/agent/run.go
- pkg/agent/tunnel/tunnel.go
- pkg/daemons/control/server.go
- pkg/util/api.go
Since we now start the server's agent sooner and in the background, we
may need to wait longer than 30 seconds for the apiserver to become
ready on downstream projects such as RKE2.
Since this essentially just serves as an analogue for the server's
apiReady channel, there's little danger in setting it to something
relatively high.
bugfix
* Normal CI checks on K3s.
* Should resolve CI failures currently seen when updating K3s in RKE2.
* TBD
```release-note
```
> [release-1.21] Increase agent's apiserver ready timeout

- pkg/configfilearg/defaultparser_test.go
- pkg/configfilearg/parser.go
- pkg/configfilearg/testdata/defaultdata.yaml
Fix regex to deal with edge case of arguments whose value "contains a equal sign"
Bugfix
Added testlet to unit test.
https://github.com/k3s-io/k3s/issues/4509
```release-note
Fixed an issue where config.yaml arguments with an equal sign would be skipped by server.
```
> Improved parser regex for double equals arguments

- pkg/configfilearg/defaultparser_test.go
- pkg/configfilearg/parser.go
- pkg/configfilearg/testdata/defaultdata.yaml
Backport of https://github.com/k3s-io/k3s/pull/4505
https://github.com/k3s-io/k3s/issues/4511
```release-note
Fixed an issue where config.yaml arguments with an equal sign would be skipped by server.
```
> [Release-1.21] Improved regex for double equals arguments

- pkg/configfilearg/defaultparser_test.go
- pkg/configfilearg/parser.go
- pkg/configfilearg/testdata/defaultdata.yaml
Backport of https://github.com/k3s-io/k3s/pull/4505
https://github.com/k3s-io/k3s/issues/4510
```release-note
Fixed an issue where config.yaml arguments with an equal sign would be skipped by server.
```
> [Release-1.22] Improved regex for double equals arguments

- pkg/configfilearg/defaultparser_test.go
- pkg/configfilearg/parser.go
- pkg/configfilearg/testdata/defaultdata.yaml
Backport of https://github.com/k3s-io/k3s/pull/4505
https://github.com/k3s-io/k3s/issues/4512
```release-note
Fixed an issue where config.yaml arguments with an equal sign would be skipped by server.
```
> [Engine-1.21] Improved regex for double equals arguments

- pkg/servicelb/controller.go
- scripts/airgap/image-list.txt
- scripts/version.sh
To have dual-stack properly working we need to move to `VERSION_CNIPLUGINS="v0.9.1-k3s1` in order to use a flannel and bridge binary that supports dual-stack
To have dual-stack working in arm env, we need to move to klipper-lb 0.3.4
Bugfix
#1405
```release-note
```
> [Release 1.21] Backport new cniplugins and klipper-lb image version

- pkg/agent/config/config.go
- pkg/agent/run.go
- pkg/cli/cmds/agent.go
- pkg/cli/server/server.go
- pkg/daemons/agent/agent.go
- pkg/daemons/config/types.go
- pkg/servicelb/controller.go
Backports: https://github.com/k3s-io/k3s/pull/4437
Issue: https://github.com/k3s-io/k3s/issues/4517
> [Release 1.21] Allow svclb pod to enable ipv6 forwarding

- pkg/cli/server/server.go
Fix a regression bug with cluster reset restore path, where the data dir is not read correctly.
bug fix
- take a snapshot
- try to restore with --cluster-reset and --cluster-reset-restore-path
- https://github.com/k3s-io/k3s/issues/4522
```release-note
```
> Fix regression with cluster reset

- pkg/cli/server/server.go
Fix a regression bug with cluster reset restore path, where the data dir is not read correctly.
bug fix
- take a snapshot
- try to restore with --cluster-reset and --cluster-reset-restore-path
- #4529 
```release-note
```
> [Engine-1.21] Fix regression with cluster reset

- pkg/cli/server/server.go
Fix a regression bug with cluster reset restore path, where the data dir is not read correctly.
bug fix
- take a snapshot
- try to restore with --cluster-reset and --cluster-reset-restore-path
- #4527 
```release-note
```
> [Release-1.22] Fix regression with cluster reset

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
- Dockerfile.test.mod.dapper
- go.mod
- go.sum
- scripts/test-helpers
- vendor/github.com/containerd/containerd/.mailmap
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run.go
- vendor/github.com/containerd/containerd/go.mod
- vendor/github.com/containerd/containerd/go.sum
- vendor/github.com/containerd/containerd/images/image.go
- vendor/github.com/containerd/containerd/pkg/cri/io/helpers_windows.go
- vendor/github.com/containerd/containerd/pkg/cri/opts/container.go
- vendor/github.com/containerd/containerd/pkg/cri/server/helpers.go
- vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- vendor/github.com/containerd/containerd/remotes/docker/httpreadseeker.go
- vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- vendor/github.com/containerd/containerd/task.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Bump golang version
Bump sonobuoy version to v0.55.0
Increase test timeout
Golang change
https://github.com/k3s-io/k3s/issues/4440
```release-note
Bump golang to 1.16.10 and containerd to v1.5.8
```
> [master] Bump golang and containerd

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
- Dockerfile.test.mod.dapper
- go.mod
- go.sum
- scripts/test-helpers
- vendor/github.com/containerd/containerd/.travis.yml
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/images/image.go
- vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Backport https://github.com/k3s-io/k3s/pull/4538
https://github.com/k3s-io/k3s/issues/4441
```release-note
Bump golang to 1.16.10
Bump containerd to v1.4.12-k3s1
```
> [release-1.21] Bump golang and containerd versions

- Dockerfile.dapper
- Dockerfile.manifest
- Dockerfile.test.dapper
- Dockerfile.test.mod.dapper
- go.mod
- go.sum
- scripts/test-helpers
- vendor/github.com/containerd/containerd/.travis.yml
- vendor/github.com/containerd/containerd/Vagrantfile
- vendor/github.com/containerd/containerd/images/image.go
- vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- vendor/github.com/containerd/containerd/version/version.go
- vendor/modules.txt
Backport https://github.com/k3s-io/k3s/pull/4530
golang and containerd bump
https://github.com/k3s-io/k3s/issues/4441
```release-note
Bump golang to 1.16.10
Bump containerd to v1.4.12-k3s1
```
> [engine-1.21] Bump golang and containerd versions

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cluster/cluster.go
- pkg/cluster/managed/drivers.go
- pkg/etcd/etcd.go
- pkg/etcd/etcd_int_test.go
- pkg/etcd/s3.go
Enhance etcd snapshot functionality in K3s
This PR does a couple of things.
Global changes:
1. `etcd snapshot-save` will now attach data from the `k3s-etcd-snapshot-extra-metadata` ConfigMap into the `k3s-etcd-snapshots` configmap under the new key. It will base64 encode the snapshot metadata so as to prevent accidental unmarshaling when the `k3s-etcd-snapshots` configmap is processed by other programs.
2. `etcd snapshot-save` now modifies the `k3s-etcd-snapshots` configmap transactionally, rather than relying on down-the-line reconciliation to populate information. This allows partially-successful attempts to be recorded in the configmap. 
3. If an `etcd snapshot-save` attempt fails, the configmap will be updated with the metadata of the snapshot and the base64 encoded error message …
> [master] etcd snapshot functionality enhancements

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cluster/cluster.go
- pkg/cluster/managed/drivers.go
- pkg/etcd/etcd.go
- pkg/etcd/etcd_int_test.go
- pkg/etcd/s3.go
Backport https://github.com/k3s-io/k3s/pull/4453
Enhance etcd snapshot functionality in K3s
This PR does a couple of things.
Global changes:
1. `etcd snapshot-save` will now attach data from the `k3s-etcd-snapshot-extra-metadata` ConfigMap into the `k3s-etcd-snapshots` configmap under the new key. It will base64 encode the snapshot metadata so as to prevent accidental unmarshaling when the `k3s-etcd-snapshots` configmap is processed by other programs.
2. `etcd snapshot-save` now modifies the `k3s-etcd-snapshots` configmap transactionally, rather than relying on down-the-line reconciliation to populate information. This allows partially-successful attempts to be recorded in the configmap. 
3. If an `etcd snapshot-save` attempt fails, the configmap will be updated with the metadata of the …
> [release-1.22] etcd snapshot functionality enhancements

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cluster/cluster.go
- pkg/cluster/managed/drivers.go
- pkg/etcd/etcd.go
- pkg/etcd/s3.go
Backport https://github.com/k3s-io/k3s/pull/4453
Enhance etcd snapshot functionality in K3s
This PR does a couple of things.
Global changes:
1. `etcd snapshot-save` will now attach data from the `k3s-etcd-snapshot-extra-metadata` ConfigMap into the `k3s-etcd-snapshots` configmap under the new key. It will base64 encode the snapshot metadata so as to prevent accidental unmarshaling when the `k3s-etcd-snapshots` configmap is processed by other programs.
2. `etcd snapshot-save` now modifies the `k3s-etcd-snapshots` configmap transactionally, rather than relying on down-the-line reconciliation to populate information. This allows partially-successful attempts to be recorded in the configmap. 
3. If an `etcd snapshot-save` attempt fails, the configmap will be updated with the metadata of the …
> [release-1.21] etcd snapshot functionality enhancements

- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/etcdsnapshot/etcd_snapshot.go
- pkg/cluster/cluster.go
- pkg/cluster/managed/drivers.go
- pkg/etcd/etcd.go
- pkg/etcd/etcd_int_test.go
- pkg/etcd/s3.go
Backport https://github.com/k3s-io/k3s/pull/4453
Enhance etcd snapshot functionality in K3s
This PR does a couple of things.
Global changes:
1. `etcd snapshot-save` will now attach data from the `k3s-etcd-snapshot-extra-metadata` ConfigMap into the `k3s-etcd-snapshots` configmap under the new key. It will base64 encode the snapshot metadata so as to prevent accidental unmarshaling when the `k3s-etcd-snapshots` configmap is processed by other programs.
2. `etcd snapshot-save` now modifies the `k3s-etcd-snapshots` configmap transactionally, rather than relying on down-the-line reconciliation to populate information. This allows partially-successful attempts to be recorded in the configmap. 
3. If an `etcd snapshot-save` attempt fails, the configmap will be updated with the metadata of the …
> [engine-1.21] etcd snapshot functionality enhancements

- pkg/etcd/etcd_test.go
Improved the cleanup of etcd after test end, Previously several go routines would continue to run for the life of the testing process.
Flaky Test Fix
Stress tested by runnig the test on a 90% CPU utilization to slow things down. Was able to get the test to fail consistently before the patch.
TBD
```release-note
NONE
```
> Improved cleanup for etcd unit test

- pkg/etcd/etcd_test.go
Backport of https://github.com/k3s-io/k3s/pull/4537
Improved the cleanup of etcd after test end, Previously several go routines would continue to run for the life of the testing process.
Flaky Test Fix
Stress tested by running the test on a 90% CPU utilization to slow things down. Was able to get the test to fail consistently before the patch.
Test-only changes, no Issue to track/QA to verify
```release-note
NONE
```
> [Engine-1.21] Improved cleanup for etcd unit test

- pkg/etcd/etcd_test.go
Backport of https://github.com/k3s-io/k3s/pull/4537
Improved the cleanup of etcd after test end, Previously several go routines would continue to run for the life of the testing process.
Flaky Test Fix
Stress tested by runnig the test on a 90% CPU utilization to slow things down. Was able to get the test to fail consistently before the patch.
Test-only changes, no Issue to track/QA to verify
```release-note
NONE
```
> [Release-1.22] Improved cleanup for etcd unit test

- pkg/agent/config/config.go
- pkg/agent/flannel/setup.go
- pkg/agent/flannel/setup_test.go
- pkg/daemons/config/types.go
This PR improves flannel code a bit:
- Swaps `nodeConfig.FlannelConf` to `nodeConfig.FlannelConfFile`, which describes the content of the variable better
- Adds more logging, especially using the debug option of logrus
- Fixes a bug where `createFlannelConf` was returning nil even though there was an error
Bugfix
https://github.com/k3s-io/k3s/issues/4549
```release-note
```
> Improve flannel code and logging

- pkg/configfilearg/defaultparser.go
- pkg/configfilearg/defaultparser_test.go
Enable downstream programs to modify the default parser.
Bugfix
Local testing
https://github.com/rancher/rke2/issues/2130
```release-note
```
> [Engine-1.21] Expose default parser

- cmd/cert/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/cli/cert/cert.go
- pkg/cli/cmds/certs.go
- pkg/cluster/https.go
- scripts/build
- scripts/package-cli
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/copy_namedpipes.go
- vendor/github.com/otiai10/copy/copy_namedpipes_windows.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/github.com/otiai10/copy/options.go
- vendor/github.com/otiai10/copy/preserve_times.go
- vendor/github.com/otiai10/copy/stat_times.go
- vendor/github.com/otiai10/copy/stat_times_darwin.go
- vendor/github.com/otiai10/copy/stat_times_freebsd.go
- vendor/github.com/otiai10/copy/stat_times_windows.go
- vendor/github.com/otiai10/copy/test_setup.go
- vendor/github.com/otiai10/copy/test_setup_windows.go
- vendor/github.com/rancher/dynamiclistener/factory/gen.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
New Feature
- stop k3s
-  
- https://github.com/k3s-io/k3s/issues/2636
> Add cert rotation command

- pkg/agent/config/config.go
- pkg/agent/flannel/setup.go
- pkg/daemons/config/types.go
Signed-off-by: Manuel Buil mbuil@suse.com
Backport: #4550
Issue: https://github.com/k3s-io/k3s/issues/4617
> [Release 1.20] Improve flannel logging

- .gitignore
- tests/e2e/createcluster/Vagrantfile
Replace terraform with vagrant, building on the work @dweomer did.
Testing improvments
- On host install vagrant and virtualbox
- cd into `tests/e2e/createcluster`
- run `vagrant up` 
- SSH into main server `vagrant ssh server-0`
- Verify all nodes connected `kubectl get nodes` should show 3 server (in HA) with 2 agents
https://github.com/k3s-io/k3s/issues/2958
```release-note
```
> Nighlty automation vagrant rework

- cmd/cert/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/cli/cert/cert.go
- pkg/cli/cmds/certs.go
- pkg/cluster/https.go
- scripts/build
- scripts/package-cli
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/copy_namedpipes.go
- vendor/github.com/otiai10/copy/copy_namedpipes_windows.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/github.com/otiai10/copy/options.go
- vendor/github.com/otiai10/copy/preserve_times.go
- vendor/github.com/otiai10/copy/stat_times.go
- vendor/github.com/otiai10/copy/stat_times_darwin.go
- vendor/github.com/otiai10/copy/stat_times_freebsd.go
- vendor/github.com/otiai10/copy/stat_times_windows.go
- vendor/github.com/otiai10/copy/test_setup.go
- vendor/github.com/otiai10/copy/test_setup_windows.go
- vendor/github.com/rancher/dynamiclistener/factory/gen.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
New Feature
- stop k3s
-  
- https://github.com/k3s-io/k3s/issues/4631
> [Engine-1.21] Add cert rotation command

- cmd/cert/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/cli/cert/cert.go
- pkg/cli/cmds/certs.go
- pkg/cluster/https.go
- scripts/build
- scripts/package-cli
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/copy_namedpipes.go
- vendor/github.com/otiai10/copy/copy_namedpipes_windows.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/github.com/otiai10/copy/options.go
- vendor/github.com/otiai10/copy/preserve_times.go
- vendor/github.com/otiai10/copy/stat_times.go
- vendor/github.com/otiai10/copy/stat_times_darwin.go
- vendor/github.com/otiai10/copy/stat_times_freebsd.go
- vendor/github.com/otiai10/copy/stat_times_windows.go
- vendor/github.com/otiai10/copy/test_setup.go
- vendor/github.com/otiai10/copy/test_setup_windows.go
- vendor/github.com/rancher/dynamiclistener/factory/gen.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
New Feature
- stop k3s
-  
- https://github.com/k3s-io/k3s/issues/4630
> [Release-1.20] Add cert rotation command

- cmd/cert/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/cli/cert/cert.go
- pkg/cli/cmds/certs.go
- pkg/cluster/https.go
- scripts/build
- scripts/package-cli
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/copy_namedpipes.go
- vendor/github.com/otiai10/copy/copy_namedpipes_windows.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/github.com/otiai10/copy/options.go
- vendor/github.com/otiai10/copy/preserve_times.go
- vendor/github.com/otiai10/copy/stat_times.go
- vendor/github.com/otiai10/copy/stat_times_darwin.go
- vendor/github.com/otiai10/copy/stat_times_freebsd.go
- vendor/github.com/otiai10/copy/stat_times_windows.go
- vendor/github.com/otiai10/copy/test_setup.go
- vendor/github.com/otiai10/copy/test_setup_windows.go
- vendor/github.com/rancher/dynamiclistener/factory/gen.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
New Feature
- stop k3s
-  
- https://github.com/k3s-io/k3s/issues/4629
> [Release-1.21] Add cert rotation command

- cmd/cert/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- go.mod
- go.sum
- main.go
- pkg/cli/cert/cert.go
- pkg/cli/cmds/certs.go
- pkg/cluster/https.go
- scripts/build
- scripts/package-cli
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/copy_namedpipes.go
- vendor/github.com/otiai10/copy/copy_namedpipes_windows.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/github.com/otiai10/copy/options.go
- vendor/github.com/otiai10/copy/preserve_times.go
- vendor/github.com/otiai10/copy/stat_times.go
- vendor/github.com/otiai10/copy/stat_times_darwin.go
- vendor/github.com/otiai10/copy/stat_times_freebsd.go
- vendor/github.com/otiai10/copy/stat_times_windows.go
- vendor/github.com/otiai10/copy/test_setup.go
- vendor/github.com/otiai10/copy/test_setup_windows.go
- vendor/github.com/rancher/dynamiclistener/factory/gen.go
- vendor/github.com/rancher/dynamiclistener/listener.go
- vendor/modules.txt
New Feature
- stop k3s
-  
- https://github.com/k3s-io/k3s/issues/4628
> [Release-1.22] Add cert rotation command (#4495)

- go.mod
- go.sum
- vendor/github.com/k3s-io/kine/pkg/drivers/generic/generic.go
- vendor/github.com/k3s-io/kine/pkg/drivers/sqlite/sqlite.go
- vendor/github.com/k3s-io/kine/pkg/logstructured/sqllog/sql.go
- vendor/github.com/k3s-io/kine/pkg/server/types.go
- vendor/modules.txt
bump kine to v0.8.1
version bump
normal CI / QA tests
* #3660 
```release-note
K3s will now ensure that the write-ahead log for the embedded sqlite datastore does not grow excessively large.
```
> Update kine to v0.8.1

- pkg/agent/config/config.go
- pkg/util/net.go
- pkg/util/net_test.go
When kube-apiserver is set up to reach kubelet API via ExternalIP it fails because the address is not included into certificate SANs.
Include node-external-ip in serving-kubelet.crt SANs to make sure kubelet API (serving-kubelet.crt) TLS certificate passes validation on kube-apiserver side.
New Feature
* Deploy machine with supplied `--node-external-ip` argument set to machine external IP address.
* Check generated kubelet certificate on the machine: `openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'`. It must include external IP address in the list of SANs.
To verify that the problem is solved you need to create 2 machines with external addresses absent on the local network interfaces, i.e. externalIP provided via NAT, …
> Include node-external-ip in serving-kubelet.crt SANs

- cmd/encrypt/main.go
- cmd/k3s/main.go
- cmd/server/main.go
- main.go
- pkg/cli/cmds/agent.go
- pkg/cli/cmds/etcd_snapshot.go
- pkg/cli/cmds/secrets_encrypt.go
- pkg/cli/cmds/server.go
- pkg/cli/secretsencrypt/secrets_encrypt.go
- pkg/clientaccess/token.go
- pkg/cluster/bootstrap.go
- pkg/cluster/cluster.go
- pkg/cluster/storage.go
- pkg/daemons/config/types.go
- pkg/daemons/control/deps/deps.go
- pkg/daemons/control/server.go
- pkg/deploy/controller.go
- pkg/secretsencrypt/config.go
- pkg/secretsencrypt/controller.go
- pkg/server/router.go
- pkg/server/secrets-encrypt.go
- pkg/server/server.go
- pkg/util/api.go
- scripts/build
- scripts/package-cli
Backport of https://github.com/k3s-io/k3s/pull/4372
Introduces new feature: secrets-encryption keys rotation and enable/disable of encryption. The is all controlled via a new sub command `k3s secrets-encrypt`.
```
NAME:
k3s secrets-encrypt - Control secrets encryption and keys rotation
USAGE:
k3s secrets-encrypt command [command options] [arguments...]
COMMANDS:
status     Print current status of secrets encryption
enable    Enable secrets encryption
disable   Disable secrets encryption
prepare   Prepare for encryption keys rotation
rotate     Rotate secrets encryption keys
reencrypt  Reencrypt all data with new encryption key
```
New Feature
New Integration Test (covers single node) 
Formal documentation to follow:
You can run `k3s …
> [Release-1.21] Secrets-encryption rotation 

- pkg/cluster/bootstrap.go
- pkg/daemons/config/types.go
- pkg/etcd/etcd_test.go
This PR guardrails users of k3s-HA. It verifies if the new member's config is shared across the cluster. If not, it fails and asks to verify the config.
To do so, a few important config parameters:
- ClusterIPRanges
- ServiceIPRanges
- ClusterDNSs
- ClusterDomain
- FlannelBackend
- Disables
- Skips
- DisableCCM
- DisableNPC
- DisableHelmController
- DisableKubeProxy
- NoCoreDNS
- DisableServiceLB
are moved to a struct called CriticalControlArgs. All those fields are anonymous to the current Control struct where they belong, so the change is transparent for the code that uses those fields.
Once a new control plane node tries to join the cluster, fetches the cluster config via `$Cluster-VIP:6443//v1-k3s/config` and compares it with the local …
> Verify new control plane nodes joining the cluster share the same config as cluster members

- pkg/agent/config/config.go
- pkg/util/net.go
- pkg/util/net_test.go
*Backport of #4620*
When kube-apiserver is set up to reach kubelet API via ExternalIP it fails because the address is not included into certificate SANs.
Include node-external-ip in serving-kubelet.crt SANs to make sure kubelet API (serving-kubelet.crt) TLS certificate passes validation on kube-apiserver side.
New Feature
* Deploy machine with supplied `--node-external-ip` argument set to machine external IP address.
* Check generated kubelet certificate on the machine: `openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'`. It must include external IP address in the list of SANs.
To verify that the problem is solved you need to create 2 machines with external addresses absent on the local network interfaces, i.e. externalIP …
> [release-1.22] Include node-external-ip in serving-kubelet.crt SANs

- pkg/agent/config/config.go
- pkg/util/net.go
- pkg/util/net_test.go
*Backport of #4620*
When kube-apiserver is set up to reach kubelet API via ExternalIP it fails because the address is not included into certificate SANs.
Include node-external-ip in serving-kubelet.crt SANs to make sure kubelet API (serving-kubelet.crt) TLS certificate passes validation on kube-apiserver side.
New Feature
* Deploy machine with supplied `--node-external-ip` argument set to machine external IP address.
* Check generated kubelet certificate on the machine: `openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'`. It must include external IP address in the list of SANs.
To verify that the problem is solved you need to create 2 machines with external addresses absent on the local network interfaces, i.e. externalIP …
> [engine-1.21] Include node-external-ip in serving-kubelet.crt SANs

- pkg/agent/config/config.go
- pkg/util/net.go
- pkg/util/net_test.go
*Backport of #4620*
When kube-apiserver is set up to reach kubelet API via ExternalIP it fails because the address is not included into certificate SANs.
Include node-external-ip in serving-kubelet.crt SANs to make sure kubelet API (serving-kubelet.crt) TLS certificate passes validation on kube-apiserver side.
New Feature
* Deploy machine with supplied `--node-external-ip` argument set to machine external IP address.
* Check generated kubelet certificate on the machine: `openssl x509 -in /var/lib/rancher/k3s/agent/serving-kubelet.crt -text -noout | grep -A 3 'Subject Alternative Name'`. It must include external IP address in the list of SANs.
To verify that the problem is solved you need to create 2 machines with external addresses absent on the local network interfaces, i.e. externalIP …
> [release-1.21] Include node-external-ip in serving-kubelet.crt SANs

- pkg/cli/cert/cert.go
> [Release-1.21] Add validation to certificate rotation

- pkg/cli/cert/cert.go
> [Engine-1.21] Add validation to certificate rotation

- pkg/cli/cert/cert.go
> [Release-1.22] Add validation to certificate rotation

- pkg/cli/cert/cert.go
> [master] Add validation to certificate rotation

- pkg/bootstrap/bootstrap.go
- pkg/cluster/bootstrap.go
- pkg/cluster/storage.go
- pkg/etcd/etcd.go
Scenario 1
1. Start cluster
2. Take a snapshot
3. Restore the snapshot
4. Restart cluster
Scenario 2
1. Start cluster
2. Take a snaphsot
3. Stop the cluster
4. Restore to a new node
Scenario 3
1. Start a cluster
2. Take a snapshot
3. Stop the cluster
4. Remove data directory
5. Restore the snapshot
6. Start the server
7. Add node(s)
#4703 
```release-note
Resolve issue preventing successful restore of etcd snapshot due to change in bootstrapping logic.
```
> Resolve restore bootstrap

- docs/adrs/001-record-architecture-decisions.md
Add in first ADR, denoting our decision to use ADRs and to act as a template
Docs changes
Verify that docs/adr dir exists
```release-note
```
> Add in docs/adr to ensure we capture decisions properly 

- pkg/cli/server/server.go
- pkg/cluster/bootstrap.go
- pkg/etcd/etcd.go
- Resetting the api address key in case of cluster restoration
- Closing the agent ready channel in cluster restoration as well
- Fixing an issue with unmigrated bootstrap data 
Bugfix
- test restoration of etcd snapshot on a fresh new node
```release-note
```
> Fix snapshot restoration on fresh nodes

- pkg/cluster/bootstrap.go
Fix to enable cold restarts again, while also making all server nodes perform reconciliation on restart.
This reverts changes made in https://github.com/k3s-io/k3s/commit/1055837e4f292087c0e5b38d4ab20f82d521275e#diff-4dcc46ade478259007245d87cf4eedb63ec9ebf0945746803e724cf1e8ee21a2R197-R198, in favor of a simpler and more correct fix.
Bugfix
- Start 3 k3s servers (1 cluster-init, 2 --server)
- On server 2 run `k3s secrets-encrypt prepare`
- Check that the status has updated only on server 2 `k3s secrets-encrypt status`
- Kill all 3 servers
- Restart only servers 2 and 3. 
- Check that server 3 now has the same status as server 2 `k3s secrets-encrypt status`
https://github.com/k3s-io/k3s/issues/4746
```release-note
```
> Fix cold boot and reconcilation on secondary servers

- docs/adrs/002-add-dual-stack-support-to-netpol-agent.md
Proposal about implementing dual stack in k3s network policy agent,
kube-router and the procedure of that implementation.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
Proposal about implementing dual stack in k3s network policy agent,
kube-router and the procedure of that implementation.
ADR
```release-note
```
> docs: adrs: Dual-stack in network policy agent

- scripts/download
Bump k3s-root to v0.10.1. Doing this helps offset the increase in size from https://github.com/k3s-io/k3s/pull/4757 as the binaries in this release are a fair bit smaller due to recent improvements made by @dweomer.
packaged userspace
run `/var/lib/rancher/k3s/data/current/bin/busybox`
* https://github.com/k3s-io/k3s/issues/4689
```release-note
The embedded userspace binaries have been updated to k3s-root v0.10.1.
```
> Bump k3s-root to v0.10.1

- pkg/daemons/config/types.go
Move Disables, Skips and DisableKubeProxy back to the Config struct. That means, those don't need to be the same in all server nodes joining an HA cluster. We need to do this because in rke2, we are changing the config at runtime and disabling `rke2-kube-proxy` module
Bug fix
https://github.com/k3s-io/k3s/issues/4773
```release-note
```
> [k3s-engine] Remove Disables, Skips and DisableKubeProxy from the critical configs

- pkg/daemons/config/types.go
Move Disables, Skips and DisableKubeProxy back to the Config struct. That means, those don't need to be the same in all server nodes joining an HA cluster. We need to do this because in rke2, we are changing the config at runtime and disabling `rke2-kube-proxy` module
Bug fix
https://github.com/k3s-io/k3s/issues/4780
```release-note
```
> Remove Disables, Skips and DisableKubeProxy from the comparing configs

- pkg/cluster/bootstrap.go
- pkg/cluster/storage.go
If you don't explicitly close the etcd client when you're done with it,
the GRPC connection hangs around in the background. Normally this is
harmelss, but in the case of the temporary etcd we start up on 2399 to
reconcile bootstrap data, the client will start logging errors
afterwards when the server goes away.
bugfix
* #4728
```release-note
K3s no longer leaks etcd client grpc connections
```
> Close etcd clients to avoid leaking GRPC connections

- pkg/cli/server/server.go
Close the agentready channel only in k3s cluster restore
- snapshot restoration on fresh nodes
> Close agentReady channel only in k3s

- pkg/cli/server/server.go
Close the agentready channel only in k3s cluster restore
- snapshot restoration on fresh nodes
> [Engine-1.21] Close agentReady channel only in k3s

- pkg/cli/server/server.go
Close the agentready channel only in k3s cluster restore
- snapshot restoration on fresh nodes
> [Release-1.21] Close agentReady channel only in k3s

- pkg/cli/server/server.go
Close the agentready channel only in k3s cluster restore
- snapshot restoration on fresh nodes
> [Release-1.22] Close agentReady channel only in k3s

- pkg/cluster/bootstrap.go
Adds additional logic to capture all changed files on disk and output them as part of the error message.
Update bootstrap logic to print out all changed files on disk before exiting rather than the first one found in the loop.
Change more than one file on disk that's part of the bootstrap data. E.g. client-ca.crt and client-ca.key
#4797 
```release-note
```
> Update bootstrap logic to output all changed files on disk

- Dockerfile.test.dapper
- scripts/codespell.sh
- scripts/test
- scripts/test-helpers
- scripts/test-run-basics
- scripts/test-run-compat
- scripts/test-run-lazypull
- scripts/test-setup-sonobuoy-etcd
Breaking out multiple CI fixes that were necessary for 1.23:
* More codespell ignores
* Fix previous channel detection
* Add variable to enforce max test concurrency
* Add etcd sonobuoy tests
* Fix an issue where args and hooks from previous test runs were not being reset for subsequent runs.
ci bugfix
* Check CI output; confirm that etcd is tested and everything passes.
* https://github.com/k3s-io/k3s/issues/4689
```release-note
```
> Fix multiple CI issues blocking 1.23 release

- pkg/etcd/etcd.go
Fix panic checking name of uninitialized etcd member
bugfix
* https://github.com/k3s-io/k3s/issues/4785
```release-note
```
> [engine-1.21] Fix panic checking name of uninitialized etcd member

- pkg/etcd/etcd.go
Fix panic checking name of uninitialized etcd member.
bugfix
Not sure how to reproduce; see linked issue.
* #4785 
```release-note
```
> [release-1.21] Fix panic checking name of uninitialized etcd member

- Dockerfile.test.dapper
- pkg/cluster/bootstrap.go
- pkg/cluster/storage.go
- scripts/build
- scripts/codespell.sh
- scripts/download
- scripts/package-cli
- scripts/test
- scripts/test-helpers
- scripts/test-run-basics
- scripts/test-run-compat
- scripts/test-run-lazypull
- scripts/test-setup-sonobuoy-etcd
- scripts/version.sh
* Add etcd sonobuoy tests
* Add variable to enforce max test concurrency
* Fix previous channel detection
* More codespell ignores
* Close etcd clients to avoid leaking GRPC connections
* Build script cleanups
* Bump k3s-root to v0.10.1
CI; Bugfix
* Check for successful CI output
* See linked issues
* https://github.com/k3s-io/k3s/issues/4819
```release-note
```
> [release-1.22] Backport multiple CI fixes from master

- Dockerfile.dapper
- Dockerfile.test.dapper
- pkg/cluster/bootstrap.go
- pkg/cluster/storage.go
- scripts/build
- scripts/codespell.sh
- scripts/download
- scripts/package-cli
- scripts/test
- scripts/test-helpers
- scripts/test-run-basics
- scripts/test-run-compat
- scripts/test-setup-sonobuoy-etcd
- scripts/version.sh
* Add etcd sonobuoy tests
* Add variable to enforce max test concurrency
* Fix previous channel detection
* More codespell ignores
* Close etcd clients to avoid leaking GRPC connections
* Build script cleanups
* Bump k3s-root to v0.10.1
CI; Bugfix
* Check for successful CI output
* See linked issues
* https://github.com/k3s-io/k3s/issues/4818
```release-note
```
> [engine-1.21] Backport multiple CI fixes from master

- Dockerfile.test.dapper
- pkg/cluster/bootstrap.go
- pkg/cluster/storage.go
- scripts/build
- scripts/codespell.sh
- scripts/download
- scripts/package-cli
- scripts/test
- scripts/test-helpers
- scripts/test-run-basics
- scripts/test-run-compat
- scripts/test-setup-sonobuoy-etcd
- scripts/version.sh
* Add etcd sonobuoy tests
* Add variable to enforce max test concurrency
* Fix previous channel detection
* More codespell ignores
* Close etcd clients to avoid leaking GRPC connections
* Build script cleanups
* Bump k3s-root to v0.10.1
CI; Bugfix
* Check for successful CI output
* See linked issues
* https://github.com/k3s-io/k3s/issues/4818
```release-note
```
> [release-1.21] Backport multiple CI fixes from master

- .github/workflows/cgroup.yaml
- tests/vagrant/cgroup/unified/fedora-34/Vagrantfile
Backport of **https://github.com/k3s-io/k3s/pull/4823**
* Fixed control group vagrantfile so running vagrant up doesn't fail locally
> [Release-1.22] Fix cgroup smoke test

- pkg/cli/secretsencrypt/secrets_encrypt.go
- pkg/cluster/bootstrap.go
- pkg/server/router.go
- scripts/package
Fix use of agent creds for secrets-encrypt and config validate
bugfix
```release-note
```
> Fix use of agent creds for secrets-encrypt and config validate

- pkg/cli/secretsencrypt/secrets_encrypt.go
- pkg/cluster/bootstrap.go
- pkg/server/router.go
Fix use of agent creds for secrets-encrypt and config validate
bugfix
```release-note
```
> [release-1.22] Fix use of agent creds for secrets-encrypt and config validate

- pkg/cli/secretsencrypt/secrets_encrypt.go
- pkg/cluster/bootstrap.go
- pkg/server/router.go
Fix use of agent creds for secrets-encrypt and config validate
bugfix
```release-note
```
> [engine-1.21] Fix use of agent creds for secrets-encrypt and config validate
