pkg/agent/config/config.go
pkg/cli/agent/agent.go
pkg/cli/server/server.go
pkg/util/net.go

Add the name of the interface to the error messages to help debugging
Bugfix
Use k3s rootless as querying the interface will fail
https://github.com/k3s-io/k3s/issues/8345
```release-note
```

Include the interface name in the error message

---

pkg/daemons/executor/executor.go
pkg/etcd/etcd.go

Disable HTTP on main etcd client port. Only etcd v2 API used http, all v3 clients (etcdctl and kubernetes) use GRPC.
Fixes performance issue under load, ref: 
* https://github.com/etcd-io/etcd/issues/15402
* https://github.com/kubernetes/kubernetes/pull/118460
Fixes warning in logs on etcd nodes:
```
Sep 22 05:37:58 systemd-node-1 k3s[25599]: {"level":"warn","ts":"2023-09-22T05:37:58.756955Z","caller":"embed/config.go:673","msg":"Running http and grpc server on single port. This is not recommended for production."}
```
bugfix
Check for absence of warning message.
* https://github.com/k3s-io/k3s/issues/8415
```release-note
Embedded etcd no longer serves http requests on the client port, only grpc. This addresses a performance issue that could cause watch stream starvation under load. For …
```

Disable HTTP on main etcd client port

---

docs/adrs/server-token-rotation.md

ADR for Server Token Rotation
https://github.com/rancher/rke2/issues/2141
```release-note
```

[ADR] Server token rotation

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/member_controller.go
pkg/etcd/metadata_controller.go
pkg/server/context.go
pkg/server/server.go

Simplifies etcd member removal annotation handling, and ensures that the removal annotations are cleared following a cluster-reset. Also handles etcd rejecting removal of the only voting member in a cluster.
This changes the managed database driver a bit to enforce proper setup sequencing and enforce use of the Driver interface. This allows us to set the config once, instead of passing in a context and config every time we need to query something.
There are still a lot of bits that directly poke at etcd, since we ended up coding around the Driver interface in a lot of places, but this is a start.
bugfix
**rejects removal of only member**
1. start k3s with embedded etcd
2. run `kubectl annotate node NODENAME etcd.k3s.cattle.io/remove=true`
3. note errors in the logs indicating that the …

Fix issues with etcd member removal after reset

---

pkg/cli/agent/agent.go
pkg/cli/server/server.go

Fix gofmt error. For some reason CI did not notice it :thinking: 
Bugfix
nil
nil
https://github.com/k3s-io/k3s/issues/8345
```release-note
```

Fix gofmt error

---

pkg/cli/cmds/agent.go
pkg/vpn/vpn.go

Allows to pass extra args to vpn provider. These extra args will not be processed or verified, they'll be just added to the end of the "tailscale" execution
New feature
Verify:
* Things are still working when not adding any extraArgs
* Add extraArgs such as: "--accept-dns=false" or "--netfilter-mode=false" or both at the same time: "--accept-dns=false --netfilter-mode=false" and verify tailscale is taking those flags
https://github.com/k3s-io/k3s/issues/8245
```release-note
Allow to pass extra args to the vpn provider
```

Add extraArgs to vpn provider

---

pkg/cli/server/server.go

Backport
Handle when the user tries to  `--cluster-reset` when using the `--server` flag
Backport
Handling Error
```bash
k3s server --server 11.22.33.44 --cluster-reset
```
- https://github.com/rancher/rke2/issues/4805
```release-note
The user will receive a error when --cluster-reset with the --server flag
```

[Release-1.25] Added error when cluster reset while using server flag

---

pkg/cli/server/server.go

Backport
Handle when the user tries to  `--cluster-reset` when using the `--server` flag
Backport
Handling Error
```bash
k3s server --server 11.22.33.44 --cluster-reset
```
- https://github.com/rancher/rke2/issues/4806
```release-note
The user will receive a error when --cluster-reset with the --server flag
```

[Release-1.26] Added error when cluster reset while using server flag

---

pkg/cli/server/server.go

Backport
Handle when the user tries to  `--cluster-reset` when using the `--server` flag
Backport
Handling Error
```bash
k3s server --server 11.22.33.44 --cluster-reset
```
- https://github.com/rancher/rke2/issues/4807
```release-note
The user will receive a error when --cluster-reset with the --server flag
```

[Release-1.27] Added error when cluster reset while using server flag

---

tests/e2e/snapshotrestore/Vagrantfile
tests/e2e/snapshotrestore/snapshotrestore_test.go

Resets all cluster members in the test
- Test
- Backport
```bash
go test -timeout=15m ./tests/e2e/snapshotrestore/... -run E2E
```
* https://github.com/k3s-io/k3s/issues/8448
```release-note
```

[Release-1.26] Cluster reset from non boostrap nodes

---

tests/e2e/snapshotrestore/Vagrantfile
tests/e2e/snapshotrestore/snapshotrestore_test.go

Resets all cluster members in the test
- Test
- Backport
```bash
go test -timeout=15m ./tests/e2e/snapshotrestore/... -run E2E
```
* https://github.com/k3s-io/k3s/issues/8450
```release-note
```

[Release-1.27] Cluster reset from non boostrap nodes

---

pkg/agent/config/config.go
pkg/agent/run_linux.go
pkg/agent/run_windows.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Problem:
External container runtime can be set but image service endpoint is unchanged and also is not exposed as a flag. This is useful for using containerd snapshotters outside of the ones that have built-in support like stargz-snapshotter.
Solution:
Add a flag --image-service-endpoint and also default image service endpoint to container runtime endpoint if set.
The `--image-service-endpoint` flag is a new feature but defaulting image-service-endpoint can be considered a bug fix as that's the behavior in most CRI related tool like `crictl`.
Use `--container-runtime-endpoint` to an external containerd instead of `--snapshotter` for any remote snapshotter setup like `stargz` or `nydus`. Optionally set `--image-service-endpoint` if the snapshotter also supports the image service GRPC …

Add --image-service-endpoint flag

---

cmd/k3s/main.go

Prefer user assets over system assets, if both exist
bugfix
**On old release**
1. install K3s but do not start it.
2. Run `k3s check-config` as unprivileged user; note that assets are extracted out to `$HOME/.rancher/k3s/data` and checked
3. Run `k3s check-config` as root; note that assets are extracted out to `/var/lib/rancher/k3s/data` and checked
4. Run `k3s check-config` as unprivileged user again; note that this time the assets in `/var/lib/rancher/k3s/data` are checked, instead of the user assets.
**On new release**
Perform above steps, but in step 4, note that the assets in the home directory are still checked, even if system-level assets exist.
* https://github.com/k3s-io/k3s/issues/8403
```release-note
```

Don't ignore assets in home dir if system assets exist

---

pkg/agent/templates/templates_linux.go

Pass SystemdCgroup setting through to nvidia runtime options.
This is apparently required by newer versions of the nvidia container runtime; something appears to periodically kill off pods using the nvidia runtime if they are not in the correct cgroup.
Ref: https://github.com/NVIDIA/nvidia-container-toolkit/issues/28#issuecomment-1201243587
bugfix
* #7130
```release-note
Fixed issue that would cause pods using nvidia container runtime to be killed after a few seconds, when using newer versions of nvidia-container-toolkit.
```

Pass SystemdCgroup setting through to nvidia runtime options

---

pkg/cli/cmds/agent.go
pkg/vpn/vpn.go

Backport: https://github.com/k3s-io/k3s/pull/8354
Issue: https://github.com/k3s-io/k3s/issues/8463

[Release-1.25] Add extraArgs to tailscale

---

tests/e2e/snapshotrestore/Vagrantfile
tests/e2e/snapshotrestore/snapshotrestore_test.go

Resets all cluster members in the test
- Test
- Backport
```bash
go test -timeout=15m ./tests/e2e/snapshotrestore/... -run E2E
```
* https://github.com/k3s-io/k3s/issues/8449
```release-note
```

[Release-1.25] Cluster reset from non boostrap nodes 

---

tests/e2e/snapshotrestore/snapshotrestore_test.go

post-merge CI is failing because of a spellcheck problem. This PR fixes it
Bugfix
```release-note
```

Fix spellcheck problem (boostrap ==> bootstrap)

---

install.sh

Include missing variables in /etc/os-release
Bugfix
Install k3s on official slemicro image
- https://github.com/k3s-io/k3s/issues/8519
```release-note
```

Fix slemicro check for selinux

---

pkg/daemons/control/server.go

We are already setting the default networking values:
* clusterCIDR := "10.42.0.0/16" or "fd00:42::/56"
* serviceCIDR := "10.43.0.0/16" or "fd00:43::/112"
* DNS: "utilsnet.GetIndexedIP(svcCIDR, 10)"
in func run of `pkg/cli/server/server.go`. When the execution reaches `pkg/daemons/control/server.go` and executes "defaults", the code that sets the default networking values is never executed because those variables already have a value. Moreover, the latter defaults don't include dual-stack and the DNS address is hardcoded to `10.43.0.10`, regardless of the defined serviceCIDR.
Conclusion: remove that part of the code which is currently useless
Code refactor
Code refactor. Can't be verified
Code refactor. Can't be verified
https://github.com/k3s-io/k3s/issues/8522
```release-note
```

Network defaults are duplicated, remove one

---

pkg/daemons/control/server.go

Backport: https://github.com/k3s-io/k3s/pull/8523
Issue: https://github.com/k3s-io/k3s/issues/8550

[Release 1.25] Network defaults are duplicated, remove one

---

cmd/cert/main.go
cmd/k3s/main.go
cmd/server/main.go
cmd/token/main.go
main.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/token.go
pkg/cli/token/token.go
pkg/cluster/storage.go
pkg/daemons/control/deps/deps.go
pkg/server/router.go
pkg/server/token.go
tests/e2e/token/Vagrantfile
tests/e2e/token/token_test.go

- Adds a new subcommand `k3s token rotate` which enables a user to rotate the initial server token.
- Expands existing E2E token test to include this new command
- Compact CertCommand functions
New Feature
Single node:
- Start k3s with token `1234`
- if root, with access to `/var/lib/rancher/k3s/server/token` run: `k3s token rotate --new-token=6789`
- if not root, or non access, run: `k3s token rotate --token 1234 --new-token=6789`
- Restart k3s with new token `6789`
HA:
- Start k3s servers with token `1234`
- `k3s token rotate --new-token=6789`
- Restart all k3s servers with new token `6789`
New Testlets in E2E test
https://github.com/k3s-io/k3s/issues/8264
```release-note
```

Server Token Rotation

---

cmd/cert/main.go
cmd/k3s/main.go
cmd/server/main.go
cmd/token/main.go
main.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/token.go
pkg/cli/token/token.go
pkg/cluster/storage.go
pkg/daemons/control/deps/deps.go
pkg/server/router.go
pkg/server/token.go
tests/e2e/token/Vagrantfile
tests/e2e/token/token_test.go

Backport https://github.com/k3s-io/k3s/pull/8265
* Consolidate NewCertCommands
* Add support for user defined new token
* Add E2E testlets
* Ensure agent token also changes
https://github.com/k3s-io/k3s/issues/8297
```release-note
Users can now rotate the server token using `k3s token rotate -t <OLD_TOKEN> --new-token <NEW_TOKEN>`. After command succeeds, all server nodes must be restarted with the new token.
```

[Release-1.25] Server Token Rotation

---

cmd/cert/main.go
cmd/k3s/main.go
cmd/server/main.go
cmd/token/main.go
main.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/token.go
pkg/cli/token/token.go
pkg/cluster/storage.go
pkg/daemons/control/deps/deps.go
pkg/server/router.go
pkg/server/token.go
tests/e2e/token/Vagrantfile
tests/e2e/token/token_test.go

Backport https://github.com/k3s-io/k3s/pull/8265
* Consolidate NewCertCommands
* Add support for user defined new token
* Add E2E testlets
* Ensure agent token also changes
https://github.com/k3s-io/k3s/issues/8298
```release-note
Users can now rotate the server token using `k3s token rotate -t <OLD_TOKEN> --new-token <NEW_TOKEN>`. After command succeeds, all server nodes must be restarted with the new token.
```

[Release-1.26] Server Token Rotation

---

cmd/cert/main.go
cmd/k3s/main.go
cmd/server/main.go
cmd/token/main.go
main.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/token.go
pkg/cli/token/token.go
pkg/cluster/storage.go
pkg/daemons/control/deps/deps.go
pkg/server/router.go
pkg/server/token.go
tests/e2e/token/Vagrantfile
tests/e2e/token/token_test.go

Backport https://github.com/k3s-io/k3s/pull/8265
* Consolidate NewCertCommands
* Add support for user defined new token
* Add E2E testlets
* Ensure agent token also changes
https://github.com/k3s-io/k3s/issues/8299
```release-note
Users can now rotate the server token using `k3s token rotate -t <OLD_TOKEN> --new-token <NEW_TOKEN>`. After command succeeds, all server nodes must be restarted with the new token.
```

[Release-1.27] Server Token Rotation

---

.drone.yml

Backport https://github.com/k3s-io/k3s/pull/8579
* Cleanup inactive vm domains
* Have e2e depend on amd64 pipeline
https://github.com/k3s-io/k3s/issues/8379
```release-note
```

[Release-1.27] E2E Domain Drone Cleanup

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/member_controller.go
pkg/etcd/metadata_controller.go
pkg/server/context.go
pkg/server/server.go

Backport https://github.com/k3s-io/k3s/pull/8392
https://github.com/k3s-io/k3s/issues/8431
```release-note
Fixed an issue that could cause k3s to attempt to remove members from the etcd cluster immediately following a cluster-reset/restore, if they were queued for removal at the time the snapshot was taken.
```

[Release-1.26] Clear remove annotations on cluster reset

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/member_controller.go
pkg/etcd/metadata_controller.go
pkg/server/context.go
pkg/server/server.go

Backport https://github.com/k3s-io/k3s/pull/8392
https://github.com/k3s-io/k3s/issues/8430
```release-note
Fixed an issue that could cause k3s to attempt to remove members from the etcd cluster immediately following a cluster-reset/restore, if they were queued for removal at the time the snapshot was taken.
```

[Release-1.27] Clear remove annotations on cluster reset

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cluster/bootstrap.go
pkg/cluster/https.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/member_controller.go
pkg/etcd/metadata_controller.go
pkg/server/context.go
pkg/server/server.go

Backport https://github.com/k3s-io/k3s/pull/8392
https://github.com/k3s-io/k3s/issues/8432
```release-note
Fixed an issue that could cause k3s to attempt to remove members from the etcd cluster immediately following a cluster-reset/restore, if they were queued for removal at the time the snapshot was taken.
```

[Release-1.25] Clear remove annotations on cluster reset

---

scripts/build

This changes the way go embeds versions in the binary. Today, Grype can't determine which k3s version is used in k3s itself because it's built with the file. Here's what a scan looks like:
```
NAME                   INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY
github.com/k3s-io/k3s  (devel)    1.24.17   go-module  GHSA-m4hf-6vgr-75r2  High
```
If you make this switch, the scanner can correctly determine the version instead of (devel).
Bugfix
Build k3s and scan it.
* https://github.com/k3s-io/k3s/issues/8618
```release-note
```

Switch build target from main.go to a package.

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/cli/cmds/server.go
pkg/daemons/agent/agent_linux.go
tests/e2e/dualstack/Vagrantfile

Use always IPv6 when the first configured `node-ip` is IPv6 also in case of dualstack.
This fix also will always use the configured `node-ip` on kubelet to address https://github.com/rancher/rke2/issues/4759
In case of dualstack `node-ip` it adds `CloudDualStackNodeIPs=true` as `feature-gates` configuration to fix https://github.com/k3s-io/k3s/pull/6023 from k8s 1.27 version and it doesn't require to add `node-ip=0.0.0.0` within the kubelet args.
The PR also fix https://github.com/k3s-io/k3s/issues/8467#issuecomment-1749125924 showing the IPv6 when listing pods.
#8467
```release-note
```

Use IPv6 in case is the first configured IP with dualstack

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/daemons/agent/agent_linux.go

Backport: #8581
Issue: #8502
DualStack on Kubelet with an external cloud provider is not fully supported with version prior 1.27

[Release 1.26] Use IPv6 in case is the first configured IP with dualstack

---

pkg/agent/config/config.go
pkg/agent/run.go
pkg/daemons/agent/agent_linux.go

Backport: #8581
Issue: #8503
DualStack on Kubelet with an external cloud provider is not fully supported with version prior 1.27

[Release 1.25] Use IPv6 in case is the first configured IP with dualstack

---

.drone.yml
.github/workflows/cgroup.yaml

Backport https://github.com/k3s-io/k3s/pull/8579
* Cleanup inactive vm domains
* Have e2e depend on amd64 pipeline
https://github.com/k3s-io/k3s/issues/8379
```release-note
```

[Release-1.26] E2E Domain Drone Cleanup

---

scripts/build

Package was changed in version script in bc332ac6671 but we missed changing it here as well.
Both should have been changed when we updated kube-router to v2 for dual-stack support.
bugfix
```
INFO[0016] Starting the netpol controller version v2.0.0-20230925161250-364f994b140b, built on 2023-10-13T19:55:29Z, go1.20.8
```
* https://github.com/k3s-io/k3s/issues/8586
```release-note
```

Update kube-router package in build script

---

scripts/build

Package was changed in version script in bc332ac6671 but we missed changing it here as well.
Both should have been changed when we updated kube-router to v2 for dual-stack support.
bugfix
```
INFO[0016] Starting the netpol controller version v2.0.0-20230925161250-364f994b140b, built on 2023-10-13T19:55:29Z, go1.20.8
```
* https://github.com/k3s-io/k3s/issues/8631
```release-note
```

[release-1.27] Update kube-router package in build script

---

scripts/build

Package was changed in version script in bc332ac6671 but we missed changing it here as well.
Both should have been changed when we updated kube-router to v2 for dual-stack support.
bugfix
```
INFO[0016] Starting the netpol controller version v2.0.0-20230925161250-364f994b140b, built on 2023-10-13T19:55:29Z, go1.20.8
```
* https://github.com/k3s-io/k3s/issues/8632
```release-note
```

[release-1.26] Update kube-router package in build script

---

scripts/build

Package was changed in version script in bc332ac6671 but we missed changing it here as well.
Both should have been changed when we updated kube-router to v2 for dual-stack support.
bugfix
```
INFO[0016] Starting the netpol controller version v2.0.0-20230925161250-364f994b140b, built on 2023-10-13T19:55:29Z, go1.20.8
```
* https://github.com/k3s-io/k3s/issues/8633
```release-note
```

[release-1.25] Update kube-router package in build script

---

pkg/etcd/etcd.go
scripts/test-helpers
scripts/test-run-etcd

Add a test, fix what's broken
bugfix, test
Adds a test
* https://github.com/k3s-io/k3s/issues/8637
* 
```release-note
```

Add etcd-only/control-plane-only server test and fix control-plane-only server crash

---

pkg/etcd/etcd.go
scripts/test-helpers
scripts/test-run-etcd

Add a test, fix what's broken
bugfix, test
Adds a test
* https://github.com/k3s-io/k3s/issues/8639
* 
```release-note
```

[release-1.27] Add etcd-only/control-plane-only server test and fix control-plane-only server crash

---

pkg/etcd/etcd.go
scripts/test-helpers
scripts/test-run-etcd

Add a test, fix what's broken
bugfix, test
Adds a test
* https://github.com/k3s-io/k3s/issues/8640
* 
```release-note
```

[release-1.26] Add etcd-only/control-plane-only server test and fix control-plane-only server crash

---

pkg/etcd/etcd.go
scripts/test-helpers
scripts/test-run-etcd

Add a test, fix what's broken
bugfix, test
Adds a test
* https://github.com/k3s-io/k3s/issues/8641
* 
```release-note
```

[release-1.25] Add etcd-only/control-plane-only server test and fix control-plane-only server crash

---

pkg/daemons/agent/agent_linux.go
pkg/daemons/control/server.go
tests/integration/kubeflags/kubeflags_test.go

Fix CloudDualStackNodeIPs feature-gate inconsistency
Enable the feature-gate for both kubelet and cloud-controller-manager. Enabling it on only one side breaks RKE2, where feature-gates are not shared due to kubelet and ccm running in different processes.
Fixes RKE2 regression introduced by https://github.com/k3s-io/k3s/pull/8581
bugfix
* https://github.com/k3s-io/k3s/issues/8666
```release-note
```

Fix CloudDualStackNodeIPs feature-gate inconsistency

---

pkg/daemons/agent/agent_linux.go
pkg/daemons/control/server.go
tests/integration/kubeflags/kubeflags_test.go

Fix CloudDualStackNodeIPs feature-gate inconsistency
Enable the feature-gate for both kubelet and cloud-controller-manager. Enabling it on only one side breaks RKE2, where feature-gates are not shared due to kubelet and ccm running in different processes.
Fixes RKE2 regression introduced by https://github.com/k3s-io/k3s/pull/8581
bugfix
* https://github.com/k3s-io/k3s/issues/8668
```release-note
```

[release-1.27] Fix CloudDualStackNodeIPs feature-gate inconsistency

---

pkg/agent/config/config.go
pkg/agent/run_linux.go
pkg/agent/run_windows.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Problem:
External container runtime can be set but image service endpoint is unchanged and also is not exposed as a flag. This is useful for using containerd snapshotters outside of the ones that have built-in support like stargz-snapshotter.
Solution:
Add a flag --image-service-endpoint and also default image service endpoint to container runtime endpoint if set.
The `--image-service-endpoint` flag is a new feature but defaulting image-service-endpoint can be considered a bug fix as that's the behavior in most CRI related tool like `crictl`.
Use `--container-runtime-endpoint` to an external containerd instead of `--snapshotter` for any remote snapshotter setup like `stargz` or `nydus`. Optionally set `--image-service-endpoint` if the snapshotter also supports the image service GRPC …

[release-1.27] Add --image-service-endpoint flag (#8279)

---

pkg/agent/config/config.go
pkg/agent/run_linux.go
pkg/agent/run_windows.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Problem:
External container runtime can be set but image service endpoint is unchanged and also is not exposed as a flag. This is useful for using containerd snapshotters outside of the ones that have built-in support like stargz-snapshotter.
Solution:
Add a flag --image-service-endpoint and also default image service endpoint to container runtime endpoint if set.
The `--image-service-endpoint` flag is a new feature but defaulting image-service-endpoint can be considered a bug fix as that's the behavior in most CRI related tool like `crictl`.
Use `--container-runtime-endpoint` to an external containerd instead of `--snapshotter` for any remote snapshotter setup like `stargz` or `nydus`. Optionally set `--image-service-endpoint` if the snapshotter also supports the image service GRPC …

[release-1.26] Add --image-service-endpoint flag (#8279)

---

pkg/agent/config/config.go
pkg/agent/run_linux.go
pkg/agent/run_windows.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Problem:
External container runtime can be set but image service endpoint is unchanged and also is not exposed as a flag. This is useful for using containerd snapshotters outside of the ones that have built-in support like stargz-snapshotter.
Solution:
Add a flag --image-service-endpoint and also default image service endpoint to container runtime endpoint if set.
The `--image-service-endpoint` flag is a new feature but defaulting image-service-endpoint can be considered a bug fix as that's the behavior in most CRI related tool like `crictl`.
Use `--container-runtime-endpoint` to an external containerd instead of `--snapshotter` for any remote snapshotter setup like `stargz` or `nydus`. Optionally set `--image-service-endpoint` if the snapshotter also supports the image service GRPC …

[release-1.25] Add --image-service-endpoint flag (#8279)

---

pkg/etcd/etcd.go

Re-enable etcd endpoint auto-sync
Removing this in 002e6c43ee935583f4533d1347a04b658eee016b regressed control-plane-only nodes, as we rely on the etcd client to update its endpoint list internally so that we can use it to sync the load-balancer address list.
bugfix
* https://github.com/k3s-io/k3s/issues/8672
```release-note
```

Re-enable etcd endpoint auto-sync

---

pkg/etcd/etcd.go
pkg/etcd/snapshot_controller.go

Backports:
* https://github.com/k3s-io/k3s/pull/8675
* https://github.com/k3s-io/k3s/pull/8683
bugfix
* https://github.com/k3s-io/k3s/issues/8684
* https://github.com/k3s-io/k3s/issues/8687
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```

[release-1.27] Backport etcd fixes

---

pkg/etcd/etcd.go
pkg/etcd/snapshot_controller.go

Backports:
* https://github.com/k3s-io/k3s/pull/8675
* https://github.com/k3s-io/k3s/pull/8683
bugfix
* https://github.com/k3s-io/k3s/issues/8685
* https://github.com/k3s-io/k3s/issues/8688
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```

[release-1.26] Backport etcd fixes

---

pkg/etcd/etcd.go
pkg/etcd/snapshot_controller.go

Backports:
* https://github.com/k3s-io/k3s/pull/8675
* https://github.com/k3s-io/k3s/pull/8683
bugfix
* https://github.com/k3s-io/k3s/issues/8686
* https://github.com/k3s-io/k3s/issues/8689
```release-note
Re-enable etcd endpoint auto-sync 
Manually requeue configmap reconcile when no nodes have reconciled snapshots
```

[release-1.25] Backport etcd fixes

---

pkg/etcd/etcd.go
pkg/etcd/s3.go

Don't try to read token hash and cluster id during cluster-reset
These fields are only necessary when saving snapshots to S3, and will block restoration if attempted
bugfix
* https://github.com/k3s-io/k3s/issues/8727
* 
```release-note
```

Fix s3 snapshot restore

---

pkg/etcd/etcd.go
pkg/etcd/s3.go

Don't try to read token hash and cluster id during cluster-reset
These fields are only necessary when saving snapshots to S3, and will block restoration if attempted
bugfix
* https://github.com/k3s-io/k3s/issues/8730
* 
```release-note
```

[release-1.27] Fix s3 snapshot restore

---

pkg/etcd/etcd.go
pkg/etcd/s3.go

Don't try to read token hash and cluster id during cluster-reset
These fields are only necessary when saving snapshots to S3, and will block restoration if attempted
bugfix
* https://github.com/k3s-io/k3s/issues/8731
* 
```release-note
```

[release-1.26] Fix s3 snapshot restore

---

pkg/etcd/etcd.go
pkg/etcd/s3.go

Don't try to read token hash and cluster id during cluster-reset
These fields are only necessary when saving snapshots to S3, and will block restoration if attempted
bugfix
* https://github.com/k3s-io/k3s/issues/8732
* 
```release-note
```

[release-1.25] Fix s3 snapshot restore

---

.drone.yml
.github/workflows/cgroup.yaml
.github/workflows/snapshotter.yaml
docs/adrs/add-dual-stack-support-to-netpol-agent.md

Backport https://github.com/k3s-io/k3s/pull/8579
* Cleanup inactive vm domains
* Have e2e depend on amd64 pipeline
https://github.com/k3s-io/k3s/issues/8379
```release-note
```

[Release-1.25] E2E Domain Drone Cleanup

---

pkg/agent/templates/templates_linux.go

```
Nov 02 10:47:39 QT-vGPU-01 k3s[12570]: time="2023-11-02T10:47:39+08:00" level=info msg="certificate CN=system:node:qt-vgpu-01,O=system:nodes signed by CN=k3s-client-ca@1698840663: notBefore=2023-11-01 12:11:03 +0000 UTC notAfter=2024-11-01 02:47:39 +000
Nov 02 10:47:39 QT-vGPU-01 k3s[12570]: time="2023-11-02T10:47:39+08:00" level=info msg="Module overlay was already loaded"
Nov 02 10:47:39 QT-vGPU-01 k3s[12570]: time="2023-11-02T10:47:39+08:00" level=info msg="Module nf_conntrack was already loaded"
Nov 02 10:47:39 QT-vGPU-01 k3s[12570]: time="2023-11-02T10:47:39+08:00" level=info msg="Module br_netfilter was already loaded"
Nov 02 10:47:39 QT-vGPU-01 k3s[12570]: time="2023-11-02T10:47:39+08:00" level=info msg="Module iptable_nat was already loaded"
Nov 02 10:47:39 QT-vGPU-01 …
```

fix: Access outer scope .SystemdCgroup

---

pkg/etcd/etcd.go

- Add a condition in k3s node resource to track the etcd status 
- ADR PR related to this feature https://github.com/k3s-io/k3s/pull/8355
- New Feature
You can run a two control-planes with etcd and use this command
```bash
kubectl get node {NODE_NAME} -o=jsonpath='Node Name: {.metadata.name}{"\n"}Conditions:{"\n"}{range .status.conditions[*]}- Type: {.type}{"\n"}  Status: {.status}{"\n"}  LastHeartbeatTime: {.lastHeartbeatTime}{"\n"}  LastTransitionTime: {.lastTransitionTime}{"\n"}  Reason: {.reason}{"\n"}  Message: {.message}{"\n\n"}{end}'
```
```release-note
Now the user can see the etcd status from each node in a simple way
```

Add etcd status condition

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/nvidia.go
pkg/agent/containerd/nvidia_test.go
pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go
pkg/agent/containerd/runwasi.go
pkg/agent/containerd/runwasi_test.go

As developers start to experiment building WebAssembly applications, they desire to deploy these workloads on top of Kubernetes, using the same paradigm of "traditional" applications.
The [`containerd/runwasi`](https://github.com/containerd/runwasi) project provides a way to integrate these workloads into Kubernetes.
The WebAssembly workloads require dedicated containerd runtimes to be installed and configured on the node. This PR provides a way to automatically discover the already installed runtimes and properly configure containerd to consume them.
The PR doesn't focus on shipping the pre-built runtimes as part of the k3s installation. I think this should be done by another dedicated PR.
This PR introduces a new feature. It does that by leveraging the same mechanism used to discover …

Wasm shims detection

---

pkg/cli/server/server.go

Remove k3s flag for multiclustercidr
Since the multiclustercidr alpha support has been removed upstream, we need to remove its support from k3s 
- https://github.com/k3s-io/k3s/issues/8563
```release-note
```

Add warning for removal of multiclustercidr flag

---

pkg/agent/flannel/flannel.go

When running dualStack you get the log:
```
level=info msg="The interface eth0 with ipv4 address 10.1.1.10 will be used by flannel"
```
Which can be confusing, especially if you are prioritizing IPv6 family.
This PR combines both log entries when we are in dualStack mode so that we get both IPFamilies in the log 
Bugfix
Deploy with dualStack cidr and you should see the new log
https://github.com/k3s-io/k3s/issues/8797
```release-note
```

Improve dualStack log

---

Dockerfile.dapper

**What this PR does / why we need it**:
Optimizes the Dockerfile for better efficiency and readability.
**Special notes for your reviewer**:
Please pay attention to the Trivy installation simplification.
**Details**:
- Grouped related environment variables to reduce Docker layers.
- Used a case statement for Trivy installation to simplify the process.
- Removed unnecessary commands and combined related ones for efficiency.
- Added comments throughout the Dockerfile for clarity.
**How to test this PR**:
1. Build the Docker image using the updated Dockerfile.
2. Run the container and ensure all functionalities are working as expected.
**Screenshots**:
N/A
**Additional context**:
This optimization aims to make the Dockerfile more maintainable and efficient.

optimize: Simplify and clean up Dockerfile

---

package/Dockerfile

The K3s image is built `FROM scratch`, thus doesn't include a timezone database.
With K8s v1.27, the [timezone field on CronJobs is stable](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones), but cannot really be used with the K3s docker image, since it won't know the timezones except for UTC.
A workaround is to mount the file from the host system.
New Feature
- Run the newly built image (e.g. with k3d) 
- create a CronJob with a timezone set:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
name: my-job
spec:
jobTemplate:
metadata:
name: my-job
spec:
template:
spec:
containers:
- image: busybox
name: my-job
restartPolicy: Never
schedule: '1 1 1 1 *'
timeZone: Europe/Berlin
```
- See that it's applied correctly, whereas it would fail with `unknown time …

add: timezone info in image

---

pkg/agent/config/config.go
pkg/agent/config/config_linux.go
pkg/agent/config/config_windows.go
pkg/agent/templates/templates_linux.go
pkg/daemons/config/types.go

Problem:
Configuring qos-class features in containerd requres a custom containerd configuration template.
Solution:
Look for configuration files in default locations and configure containerd to use them if they exist.
- If `rdt_config.yaml` and/or `blockio_config.yaml` exists, configure containerd to use them by specifying their paths in the generated containerd `config.toml` file.  
- The predefined file locations to check are (same directory as containerd configuration file):
- `/var/lib/rancher/k3s/agent/etc/containerd/rdt_config.yaml`
- `/var/lib/rancher/k3s/agent/etc/containerd/blockio_config.yaml`
- New Feature
1. Ensure generated `config.toml` does not contain any line similar to any of:
`[plugins."io.containerd.service.v1.tasks-service"]`, `rdt_config_file = "..."`, or …

QoS-class resource configuration

---

pkg/etcd/s3.go
pkg/etcd/snapshot_controller.go

Omit snapshot list configmap entries for snapshots without extra metadata; reduce log level of warnings about missing s3 metadata files.
bugfix
* https://github.com/k3s-io/k3s/issues/8834
```release-note
Omit snapshot list configmap entries for snapshots without extra metadata
```

Fix issue with snapshot metadata configmap

---

pkg/cluster/bootstrap.go
pkg/daemons/control/server.go

Skip initial datastore reconcile during cluster-reset
Due to prior refactoring, there are no longer any other callers of `cluster.Bootstrap`, and the `snapshot` flag was unused. It does what we want when resetting/restoring though.
bugfix
* https://github.com/k3s-io/k3s/issues/8497
```release-note
```

Skip initial datastore reconcile during cluster-reset

---

pkg/cloudprovider/servicelb.go
pkg/cloudprovider/servicelb_test.go

Previously, ingress IPs were only string-sorted when returned
Sorted by IP family and string-sorted in each family as part of filterByIPFamily method
Addresses https://github.com/k3s-io/k3s/issues/8704 with adjustment and use of `filterByIPFamily` as part of `servicelb.getStatus`
Bugfix
Added new unit test to `servicelb_test.go`
See above
* https://github.com/k3s-io/k3s/issues/8704
```release-note
Improved ingress IP ordering from ServiceLB
```
Hopefully my first PR of many. Great project

Tweaked order of ingress IPs in ServiceLB

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/server/context.go
pkg/server/server.go

The NewContext package requires config as input which would require all third-party callers to update when the new go module is published.
This change only affects the behaviour of installation of helm CRDs. Existing helm crds installed in a cluster would not be removed when disable-helm-controller flag is set on the server.
Addresses #8701
Disable helm CRD installation for disable-helm-controller
Breaking Change (for sdk) not for k3s service
* #8701 
```release-note
```
Closes #8701

Disable helm CRD installation for disable-helm-controller

---

go.mod
pkg/agent/config/config.go
pkg/node/controller.go
pkg/nodepassword/nodepassword.go
pkg/nodepassword/nodepassword_test.go
pkg/server/router.go

Add jitter to client config retry
Also:
* Replaces labeled for/continue RETRY loops with wait helpers for improved readability
* Pulls secrets and nodes from cache for node password verification
* Migrate nodepassword tests to wrangler mocks for better code reuse
bugfix/enhancement
* https://github.com/k3s-io/k3s/issues/8862
```release-note
```

Add jitter to client config retry to avoid hammering servers when they are starting up

---

pkg/etcd/etcd.go

- Backport from - https://github.com/k3s-io/k3s/pull/8886
- https://github.com/k3s-io/k3s/pull/8724
```release-note
```

[Release-1.25] Handle nil pointer when runtime core is not ready in etcd

---

pkg/agent/flannel/flannel.go

Issue: https://github.com/k3s-io/k3s/issues/8826
Backport: https://github.com/k3s-io/k3s/pull/8798

[Release-1.27] Improve dualStack log

---

pkg/agent/flannel/flannel.go

Backport: https://github.com/k3s-io/k3s/pull/8798
Issue: https://github.com/k3s-io/k3s/issues/8827

[Release-1.26] Improve dualStack log

---

go.mod
go.sum
pkg/etcd/snapshot_controller.go

* Backport of https://github.com/k3s-io/k3s/pull/8894
* Bump dynamiclistener to fix secret sync race
* Reorder snapshot configmap reconcile to reduce log spew during initial startup
bugfix
* https://github.com/k3s-io/k3s/issues/8895
*  https://github.com/k3s-io/k3s/issues/8898
```release-note
Bumped dynamiclistener to address a race condition that could cause a server to fail to sync its certificates into the Kubernetes secret
Reduced etcd snapshot log spam during initial cluster startup
```

[release-1.27] Bump dynamiclistener; reduce snapshot controller log spew

---

.drone.yml
tests/e2e/validatecluster/validatecluster_test.go

* Revert e2e pipeline depends_on change
Reverts part of the change from 7d38b4a3dbd335c155836c4413987589a64e6f3c
Pipeline dependencies are apparently broken, and the e2e pipeline has   been getting skipped whenever any other pipeline fails. Ex:   https://drone-pr.k3s.io/k3s-io/k3s/7853
* Fix flakey dynamic-cert.json in cert rotation e2e test
CI
```release-note
```

Remove depends_on for e2e step; fix cert rotate e2e

---

.drone.yml
tests/e2e/validatecluster/validatecluster_test.go

* Revert e2e pipeline depends_on change
Reverts part of the change from 7d38b4a3dbd335c155836c4413987589a64e6f3c
Pipeline dependencies are apparently broken, and the e2e pipeline has   been getting skipped whenever any other pipeline fails. Ex:   https://drone-pr.k3s.io/k3s-io/k3s/7853
* Fix flakey dynamic-cert.json in cert rotation e2e test
CI
```release-note
```

[release-1.27] Remove depends_on for e2e step; fix cert rotate e2e

---

.drone.yml
go.mod
go.sum
pkg/etcd/snapshot_controller.go
tests/e2e/validatecluster/validatecluster_test.go

* Backport of https://github.com/k3s-io/k3s/pull/8894
* Bump dynamiclistener to fix secret sync race
* Reorder snapshot configmap reconcile to reduce log spew during initial startup
bugfix
* https://github.com/k3s-io/k3s/issues/8896
*  https://github.com/k3s-io/k3s/issues/8899
```release-note
Bumped dynamiclistener to address a race condition that could cause a server to fail to sync its certificates into the Kubernetes secret
Reduced etcd snapshot log spam during initial cluster startup
```

[release-1.26] Bump dynamiclistener; reduce snapshot controller log spew

---

.drone.yml
go.mod
go.sum
pkg/etcd/snapshot_controller.go
tests/e2e/validatecluster/validatecluster_test.go

* Backport of https://github.com/k3s-io/k3s/pull/8894
* Bump dynamiclistener to fix secret sync race
* Reorder snapshot configmap reconcile to reduce log spew during initial startup
bugfix
* https://github.com/k3s-io/k3s/issues/8897
*  https://github.com/k3s-io/k3s/issues/8900
```release-note
Bumped dynamiclistener to address a race condition that could cause a server to fail to sync its certificates into the Kubernetes secret
Reduced etcd snapshot log spam during initial cluster startup
```

[release-1.25] Bump dynamiclistener; reduce snapshot controller log spew

---

pkg/etcd/s3.go
pkg/etcd/snapshot.go

* Don't apply s3 retention if S3 client failed to initialize
* Don't request metadata when listing objects  
While some implementations may support it, it appears that most don't, and some may in fact return an error if it is requested. We already stat the object to get the metadata anyway, so this was unnecessary if harmless on most implementations.
* Print key instead of file path in snapshot metadata log message
bugfix
* https://github.com/k3s-io/k3s/issues/8918
* https://github.com/k3s-io/k3s/issues/8924
* https://github.com/k3s-io/k3s/issues/8925
```release-note
Don't apply S3 retention if S3 client failed to initialize
Don't request metadata when listing S3 snapshots
Print key instead of file path in snapshot metadata log message
```

Fix etcd snapshot S3 issues

---

pkg/etcd/s3.go
pkg/etcd/snapshot.go

*Backport of https://github.com/k3s-io/k3s/pull/8926*
* Don't apply s3 retention if S3 client failed to initialize
* Don't request metadata when listing objects  
While some implementations may support it, it appears that most don't, and some may in fact return an error if it is requested. We already stat the object to get the metadata anyway, so this was unnecessary if harmless on most implementations.
* Print key instead of file path in snapshot metadata log message
bugfix
* https://github.com/k3s-io/k3s/issues/8927
* https://github.com/k3s-io/k3s/issues/8930
* https://github.com/k3s-io/k3s/issues/8933
```release-note
Don't apply S3 retention if S3 client failed to initialize
Don't request metadata when listing S3 snapshots
Print key instead of file path in snapshot …
```

[release-1.27] Fix etcd snapshot S3 issues

---

pkg/etcd/s3.go
pkg/etcd/snapshot.go

*Backport of https://github.com/k3s-io/k3s/pull/8926*
* Don't apply s3 retention if S3 client failed to initialize
* Don't request metadata when listing objects  
While some implementations may support it, it appears that most don't, and some may in fact return an error if it is requested. We already stat the object to get the metadata anyway, so this was unnecessary if harmless on most implementations.
* Print key instead of file path in snapshot metadata log message
bugfix
* https://github.com/k3s-io/k3s/issues/8928
* https://github.com/k3s-io/k3s/issues/8931
* https://github.com/k3s-io/k3s/issues/8934
```release-note
Don't apply S3 retention if S3 client failed to initialize
Don't request metadata when listing S3 snapshots
Print key instead of file path in snapshot …
```

[release-1.26] Fix etcd snapshot S3 issues

---

pkg/etcd/s3.go
pkg/etcd/snapshot.go

*Backport of https://github.com/k3s-io/k3s/pull/8926*
* Don't apply s3 retention if S3 client failed to initialize
* Don't request metadata when listing objects  
While some implementations may support it, it appears that most don't, and some may in fact return an error if it is requested. We already stat the object to get the metadata anyway, so this was unnecessary if harmless on most implementations.
* Print key instead of file path in snapshot metadata log message
bugfix
* https://github.com/k3s-io/k3s/issues/8929
* https://github.com/k3s-io/k3s/issues/8932
* https://github.com/k3s-io/k3s/issues/8935
```release-note
Don't apply S3 retention if S3 client failed to initialize
Don't request metadata when listing S3 snapshots
Print key instead of file path in snapshot …
```

[release-1.25] Fix etcd snapshot S3 issues

---

go.mod
go.sum
pkg/cgroups/cgroups_linux.go

Bump containerd/runc to v1.7.10-k3s1/v1.1.10
version bump
Check version
* https://github.com/k3s-io/k3s/issues/8965
```release-note
```

Bump containerd/runc to v1.7.10-k3s1/v1.1.10

---

go.mod
go.sum
pkg/cgroups/cgroups_linux.go

Bump containerd/runc to v1.7.10-k3s1/v1.1.10
version bump
Check versions
* https://github.com/k3s-io/k3s/issues/8966
```release-note
```

[release-1.27] Bump containerd/runc to v1.7.10-k3s1/v1.1.10

---

go.mod
go.sum
pkg/cgroups/cgroups_linux.go

Bump containerd/runc to v1.7.10-k3s1/v1.1.10
version bump
Check versions
* https://github.com/k3s-io/k3s/issues/8967
```release-note
```

[release-1.26] Bump containerd/runc to v1.7.10-k3s1/v1.1.10

---

pkg/cli/cmds/server.go

Fix missing agent flag on server CLI
bugfix
`k3s server --help`
* https://github.com/k3s-io/k3s/issues/8700
* 
```release-note
```

Allow setting default-runtime on servers

---

pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go
pkg/daemons/control/server.go

Remove KubeletCredentialProviders and JobTrackingWithFinalizers feature-gates, both of which are GA since 1.26 and cannot be disabled.
upstream tracking
* https://github.com/k3s-io/k3s/issues/8941
* https://github.com/k3s-io/k3s/issues/8969
```release-note
```

Remove GA feature-gates

---

pkg/cli/cmds/secrets_encrypt.go

- Due to changes with upstream [K8s KMSv2](https://github.com/kubernetes/kubernetes/issues/117728) we are removing rotate-keys as it currently does not work as intended. This will only be for `1.29.X` as the `1.28.X` branch continues to use the faster inotify system for KMSv2
https://github.com/k3s-io/k3s/issues/9080
```release-note
```

Remove rotate-keys subcommand

---

.drone.yml

Backport https://github.com/k3s-io/k3s/pull/9051 to release-1.27

[Release-1.27] Only publish to code_cov on merged E2E builds

---

.drone.yml

Backport https://github.com/k3s-io/k3s/pull/9051 to release-1.28

[Release-1.28] Only publish to code_cov on merged E2E builds

---

CODE_OF_CONDUCT.md

This commit updates the Code of Conduct to redirect to the latest version of the CNCF Code of Conduct.
Instead of maintaining a separate CoC text, it now link directly to the CNCF CoC for consistency and alignment with industry best practices.
Currently the CoC file has a link to CNCF CoC but also describes the CoC. This becomes an issue in case CNCF CoC is updated and k3s's CoC stays outdated, creating a potetial discrepancy between k3s' CoC and CNCF's CoC. The PR updates the CoC to only redirect to CNCF CoC.
Ref: [Kubernetes CoC](https://github.com/kubernetes/community/blob/master/code-of-conduct.md)
Ref: [Helm CoC](https://github.com/helm/helm/blob/main/code-of-conduct.md)
Document changes
Ref: [Kubernetes CoC](https://github.com/kubernetes/community/blob/master/code-of-conduct.md) …

chore: Update Code of Conduct to Redirect to CNCF CoC

---

go.mod
go.sum
pkg/agent/loadbalancer/servers.go

To me, this is a bugfix as the doc specifies we can use these env variables for k3s: https://docs.k3s.io/advanced#configuring-an-http-proxy.
There is also this documentation that may be misleading as it suggests that in addition to proxies, you should open your network to various URLs, which is incompatible: https://docs.k3s.io/installation/requirements#networking.
You can test the new agent on a airgapped environment, where internet access is only possible through an external proxy.
This was tested in production on such environment on my end.
There are no linked unit tests as this is the first time I'm working on Go.
Linked issue is: https://github.com/k3s-io/k3s/issues/8976
```release-note
HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables are now taken into account by the agent …
```

 Added support for env *_PROXY variables for agent loadbalancer

---

pkg/server/secrets-encrypt.go

- Adds a `retryOnConflict` when attempting to update node annotations for secrets encryption stage.
Bugfix
https://github.com/k3s-io/k3s/issues/9119
https://github.com/rancher/rke2/issues/5127
```release-note
```

Add a retry around updating a secrets-encrypt node annotations

---

install.sh

When k3s is installed with INSTALL_K3S_SKIP_SELINUX_RPM=true or INSTALL_K3S_SKIP_DOWNLOAD=true or INSTALL_K3S_SKIP_DOWNLOAD=selinux, the following message(or similar) is seen on Amazon Linux 2023/Centos
```
[INFO]  Skipping installation of SELinux RPM
[WARN]  Failed to find the k3s-selinux policy, please install:
dnf install -y container-selinux
dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/
[INFO]  Creating /usr/bin/kubectl symlink to k3s
```
whereas now
```
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/bin/kubectl symlink to k3s
```
Silence SELinux warning on INSTALL_K3S_SKIP_SELINUX_RPM
bugfix
See description above
See description
```release-note
```
Closes #8705

Silence SELinux warning on INSTALL_K3S_SKIP_SELINUX_RPM

---

pkg/cloudprovider/servicelb.go
scripts/airgap/image-list.txt

Add ServiceLB support for PodHostIPs FeatureGate
If the feature-gate is enabled, use status.hostIPs for dual-stack externalTrafficPolicy=Local support.
At the moment, we are only able to advertise the address of the primary address family for services with `externalTrafficPolicy=Local`, as the downwards API does not expose both dual-stack host addresses.
Waiting on:
Enhancement
Start dual-stack k3s server with:
```bash
k3s server \
--cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 \
--service-cidr=10.43.0.0/16,2001:cafe:43::/112 \
--kubelet-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \
--kube-apiserver-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \
--controller-manager-arg=feature-gates=CloudDualStackNodeIPs=true,PodHostIPs=true \ …
```

Add ServiceLB support for PodHostIPs FeatureGate

---

Dockerfile.dapper

`$HOME` refers to `$DAPPER_SOURCE`, which is set in the same expression and is thus not visible at the time of substitution.
This problem is not immediately visible with Docker, Inc.'s docker merely because it resets an unset `$HOME` to `/root` (but still breaking the Go cache). Under podman, this problem is immediately visible because an unset `$HOME` remains unset and subsequently breaks the `go generate` invocation.
Bug fix — build system
Run `make generate` under podman
N/A — build system
* #9089
```release-note
NONE
```

Dockerfile.dapper: set $HOME properly

---

pkg/server/secrets-encrypt.go

Backport #9039 to release-1.26
https://github.com/k3s-io/k3s/issues/9120
```release-note
```

[Release-1.26] Add a retry around updating a secrets-encrypt node annotations

---

pkg/etcd/s3.go

Fix the OTHER log message that prints the wrong variable
bugfix
Check log message
* https://github.com/k3s-io/k3s/issues/8925
```release-note
```

Fix the OTHER etcd snapshot s3 log message that prints the wrong variable

---

go.mod
pkg/agent/run.go
pkg/agent/run_test.go

Handle logging flags when parsing kube-proxy args
Also adds a test to ensure this continues to work.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/8915
```release-note
```

Handle logging flags when parsing kube-proxy args

---

pkg/etcd/snapshot_controller.go

If a full reconcile wins the race against sync of an individual snapshot resource, or someone intentionally deletes the configmap, the data map could be nil and cause a crash.
bugfix
* #9047 
```release-note
```

Fix nil map in full snapshot configmap reconcile

---

pkg/agent/containerd/runtimes.go

Add /usr/local/bin and /usr/local/sbin to crun detection. Crun can also be installed manually, without packages, and /usr/local is preferred path when dealing with non-packaged software.
New feature
Drop crun binary to /usr/local/bin or /usr/local/sbin, k3s should detect it and add to containerd config
This is just new path to detection, so i hasn't touched tests
#9112 
```release-note
NONE
```

Add more paths to crun runtime detection

---

Dockerfile.test
pkg/cli/agent/agent.go
pkg/cli/cmds/golang.go
pkg/cli/server/server.go
pkg/version/version.go
scripts/build
scripts/validate
scripts/version.sh

Add runtime checking of golang version.
Forces other groups packaging k3s to intentionally choose to build k3s with an unvalidated golang version, if they wish to do so.
As seen in https://github.com/k3s-io/k3s/issues/8293, there are other teams packaging and distributing K3s using incorrect golang versions. This change will force them to perform validations similar to what we enforce in our build pipeline, and if they fail to do so, make it clear that it is an intentional choice on their part.
enhancement
Build k3s with wrong golang version, skipping CI validation. Confirm that it exits with an error message.
* https://github.com/k3s-io/k3s/issues/8293
```release-note
```

Add runtime checking of golang version

---

.drone.yml
package/Dockerfile
scripts/package-image

Fix OS PRETTY_NAME on tagged releases.
These were always showing up as dev due to the build arg not being set by the drone step.
bugfix
check `OS-IMAGE` in `kubectl get node -o wide`
* https://github.com/k3s-io/k3s/issues/9063
```release-note
```

Fix OS PRETTY_NAME on tagged releases

---

pkg/server/secrets-encrypt.go

Backport #9039 to release-1.27
https://github.com/k3s-io/k3s/issues/9121
```release-note
```

[Release-1.27] Add a retry around updating a secrets-encrypt node annotations

---

go.mod
go.sum
pkg/agent/loadbalancer/servers.go

Backport #9070 to release-1.27
https://github.com/k3s-io/k3s/issues/9114
```release-note
```

[Release-1.27] Added support for env *_PROXY variables for agent loadbalancer

---

pkg/server/server.go

Considering that kube-dns will only be accessed via bare IP addresses, k3s should manually control the `ClusterIPs`, which means its `ipFamilyPolicy` should be set to either `SingleStack` or `RequireDualStack`. I don't think setting `ipFamilyPolicy` to `PreferDualStack` makes much sense for kube-dns, as discussed in https://github.com/k3s-io/k3s/pull/8394#discussion_r1336934121, where the implications of this choice are elaborated.
(Sorry for not mentioning this in #8394 earlier, I was on vacation and it slipped my mind.)
Bug fix
Deploy k3s in dual-stack mode and verify that the kube-dns service's `ipFamilyPolicy` is set to `RequireDualStack`.
#9152 
```release-note
```

Use `ipFamilyPolicy: RequireDualStack` for dual-stack kube-dns

---

pkg/agent/netpol/netpol.go

Backport: https://github.com/k3s-io/k3s/pull/9076
Issue: https://github.com/k3s-io/k3s/issues/9172

[Release-1.28] Wait for taint to be gone in the node before starting the netpol controller

---

pkg/agent/netpol/netpol.go

Backport: https://github.com/k3s-io/k3s/pull/9076
Issue: https://github.com/k3s-io/k3s/issues/9173

[Release-1.27] Wait for taint to be gone in the node before starting the netpol controller

---

pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/servers_test.go
pkg/agent/proxy/apiproxy.go

* Fixes issue where proxy support only honored server address via K3S_URL, not CLI or config.
* Fixes crash when agent proxy is enabled, but proxy env vars do not return a proxy URL for the server address (server URL is in NO_PROXY list).
* Adds tests
bugfix
* https://github.com/k3s-io/k3s/issues/8976
```release-note
```

Move proxy dialer out of init() and fix crash when using `K3S_AGENT_HTTP_PROXY_ALLOWED=true`

---

pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/servers_test.go
pkg/agent/proxy/apiproxy.go

Backport https://github.com/k3s-io/k3s/pull/9219 to release-1.27
* Fixes issue where proxy support only honored server address via K3S_URL, not CLI or config.
* Fixes crash when agent proxy is enabled, but proxy env vars do not return a proxy URL for the server address (server URL is in NO_PROXY list).
* Adds tests
https://github.com/k3s-io/k3s/issues/9114
```release-note
```

[Release-1.27] Move proxy dialer out of init() and fix crash

---

go.mod
go.sum
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/servers_test.go
pkg/agent/proxy/apiproxy.go

Backport #9070 and https://github.com/k3s-io/k3s/pull/9219 to release-1.28
https://github.com/k3s-io/k3s/issues/9115
```release-note
```

[Release-1.28] Added support for env *_PROXY variables for agent loadbalancer

---

pkg/server/server.go

*Backport of https://github.com/k3s-io/k3s/pull/8984*
Considering that kube-dns will only be accessed via bare IP addresses, k3s should manually control the `ClusterIPs`, which means its `ipFamilyPolicy` should be set to either `SingleStack` or `RequireDualStack`. I don't think setting `ipFamilyPolicy` to `PreferDualStack` makes much sense for kube-dns, as discussed in https://github.com/k3s-io/k3s/pull/8394#discussion_r1336934121, where the implications of this choice are elaborated.
(Sorry for not mentioning this in #8394 earlier, I was on vacation and it slipped my mind.)
Bug fix
Deploy k3s in dual-stack mode and verify that the kube-dns service's `ipFamilyPolicy` is set to `RequireDualStack`.
* #9267
```release-note
```

[release-1.27] Use `ipFamilyPolicy: RequireDualStack` for dual-stack kube-dns

---

go.mod
go.sum
pkg/agent/containerd/config_test.go
pkg/server/server.go
scripts/download

Bump runc and helm-controller versions
Also applies `gofmt -s` changes to test file added in https://github.com/k3s-io/k3s/pull/9323. Master has gofmt checks disabled but other branches do not and are failing CI.
version bump
check versions
* https://github.com/k3s-io/k3s/issues/9324
* https://github.com/k3s-io/k3s/issues/9325
```release-note
```
NOTE: This switches to a fork of runc due to https://github.com/opencontainers/runc/commit/0c8e2cc602bab3c8c1127b50aa26fa6f6954e58b breaking Windows platform cross-builds of things that pull in runc/libcontainer. The fix is in https://github.com/k3s-io/runc/commit/7d07dac287da807a624adba7ea7ccc1b3f28c614

Bump runc to v1.1.12 and helm-controller to v0.15.7

---

go.mod
go.sum

Bump helm-controller to fix issue with ChartContent
Deploy a chart with spec.valuesContent
yes, in helm-controller repo
* https://github.com/k3s-io/k3s/issues/9330
```release-note
```

[release-1.27] Bump helm-controller to fix issue with ChartContent

---

pkg/cluster/cluster.go
pkg/etcd/snapshot_controller.go

Fix snapshot reconcile retry
* Fix excessive retry on snapshot configmap reconcile
* Retry startup snapshot reconcile.  
The reconcile may run before the kubelet has created the node object; retry until it succeeds
bugfix
* https://github.com/k3s-io/k3s/issues/9241
```release-note
```

Fix snapshot reconcile retry

---

pkg/etcd/snapshot.go

Add check for etcd-snapshot-dir and fix panic in Walk
bugfix
* https://github.com/k3s-io/k3s/issues/9316
```release-note
```

Add check for etcd-snapshot-dir and fix panic in Walk

---

scripts/version.sh

Bump CNI plugins to v1.4.0
Ref: https://github.com/containernetworking/plugins/compare/v1.3.0...v1.4.0
version bump
check versions
* #9248
* #9224 
```release-note
```

Bump CNI plugins to v1.4.0

---

pkg/node/controller.go

Fix issue with coredns node hosts controller
The nodes controller was reading from the configmaps cache, but doesn't add any handlers, so if no other controller (the helm controller, for example) adds configmap handlers, the cache would remain empty.
We made the embedded helm-controller disableable a while back, but didn't test the secondary effects that disabling might have on other components that are relying on the caches being populated by the configmap and secret caches that the helm controller fills.
bugfix
* https://github.com/k3s-io/k3s/issues/9274
```release-note
fixed issue that could cause coredns pods to fail to start when the embedded helm controller is disabled, due to the configmap not being updated with node hosts entries.
```

Fix issue with coredns node hosts controller

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go

Set up more cluster config for standalone operation so that endpoint selection works properly.
bugfix
* https://github.com/k3s-io/k3s/issues/9214
```release-note
```

Fix on-demand snapshots on ipv6-only nodes

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go

- Since we have hard coded paths for runtimes, this refactor uses the `exec.LookPath` to find the runtimes using the `PATH` variable 
- Refactor
- See the test
- https://github.com/k3s-io/k3s/issues/9411
```release-note
Directories containing runtimes need to be included in the $PATH environment variable for effective runtime detection.
```
- Since this refactor will change the entire search for runtimes, I deleted all the old tests to write a new one

Runtimes refactor using exec.LookPath

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go

- Backport from https://github.com/k3s-io/k3s/pull/9311
- Since we have hard coded paths for runtimes, this refactor uses the `exec.LookPath` to find the runtimes using the `PATH` variable 
- Refactor
- See the test
- https://github.com/k3s-io/k3s/issues/9412
```release-note
Directories containing runtimes need to be included in the $PATH environment variable for effective runtime detection.
```
- Since this refactor will change the entire search for runtimes, I deleted all the old tests to write a new one

[Release-1.28] Runtimes refactor using exec.LookPath

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go

- Backport from https://github.com/k3s-io/k3s/pull/9311
- Since we have hard coded paths for runtimes, this refactor uses the `exec.LookPath` to find the runtimes using the `PATH` variable 
- Refactor
- See the test
- https://github.com/k3s-io/k3s/issues/9413
```release-note
Directories containing runtimes need to be included in the $PATH environment variable for effective runtime detection.
```
- Since this refactor will change the entire search for runtimes, I deleted all the old tests to write a new one

[Release-1.27] Runtimes refactor using exec.LookPath

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go

- Backport from https://github.com/k3s-io/k3s/pull/9311
- Since we have hard coded paths for runtimes, this refactor uses the `exec.LookPath` to find the runtimes using the `PATH` variable 
- Refactor
- See the test
- https://github.com/k3s-io/k3s/issues/9414
```release-note
Directories containing runtimes need to be included in the $PATH environment variable for effective runtime detection.
```
- Since this refactor will change the entire search for runtimes, I deleted all the old tests to write a new one

[Release-1.26] Runtimes refactor using exec.LookPath

---

.github/workflows/integration.yaml

Utilize the code coverage secrets for when running integration tests on Push. Note that PRs do not have access to the secret, which is fine, codecov supports tokenless for PRs. 
Action Bug Fix
https://github.com/k3s-io/k3s/issues/9393

Add codcov secret for integration tests on Push

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/containerd/containerd.go
pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/executor.go

In order to properly address https://github.com/rancher/rke2/issues/2204, the rke2 windows agent needs to be able to define how it reacts to `containerd` exiting. Currently, rke2 uses k3s' implementation for `containerd`, which will call [`os.Exit`](https://github.com/k3s-io/k3s/blob/ac8fe8de2b7f2c7d70e9277eca4e3d7a2d6f3a46/pkg/agent/containerd/containerd.go#L98) if the process stops running. On Windows nodes, this sudden exit prevents the top level context from fully canceling, resulting in supporting processes created with `CommandContext` (`kubelet`, `kube-proxy`, etc.) continuing to run. In the event that the rke2 service is restarted, but those processes are not cleaned up, the service will enter a crash loop which must be manually resolved. 
k3s should provide a way for the rke2 …

Allow executors to define `containerd` and `cridockerd` behavior

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/containerd/containerd.go
pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/executor.go

+ Backport: https://github.com/k3s-io/k3s/pull/9184
https://github.com/rancher/rke2/issues/5290
```release-note
```

[Release-1.26] Allow executors to define containerd and docker behavior

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/containerd/containerd.go
pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/executor.go

+ Backport: https://github.com/k3s-io/k3s/pull/9184
https://github.com/rancher/rke2/issues/5291
```release-note
```

[Release-1.27] Allow executors to define containerd and docker behavior

---

pkg/agent/containerd/config_linux.go
pkg/agent/containerd/config_windows.go
pkg/agent/containerd/containerd.go
pkg/agent/run.go
pkg/daemons/agent/agent.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/executor.go

+ Backport: https://github.com/k3s-io/k3s/pull/9184
https://github.com/rancher/rke2/issues/5292
```release-note
```

[Release-1.28] Allow executors to define containerd and docker behavior

---

.drone.yml
Dockerfile.local
go.mod
pkg/cli/cmds/secrets_encrypt.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/clientaccess/token.go
pkg/daemons/control/deps/deps.go
pkg/daemons/control/server.go
pkg/secretsencrypt/config.go
pkg/secretsencrypt/controller.go
pkg/server/secrets-encrypt.go
pkg/server/server.go
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/secretsencryption/secretsencryption_test.go

- Uses the new automatic reload metrics to correctly wait for apiserver reloading
- Resolve bugs around using the `rotate-keys`  and `disable` commands on non etcd-leader nodes
Feature "Fix"
`go test ./tests/e2e/secretsencryption/secretsencryption_test.go`
Reenabled the E2E test for this feature. 
https://github.com/k3s-io/k3s/issues/9080
```release-note
```

Readd `k3s secrets-encrypt rotate-keys` with correct support for KMSv2 GA

---

pkg/server/router.go

When the agent is disabled, e.g. when k3s image is used in a [vcluster](https://github.com/loft-sh/vcluster), a "NodePasswordValidationFailed" Event is created on every restart. This results in users questioning the state of their cluster, even though there is no impact on functionality.
The proposed change would create a debug log instead of a user-facing event.
enhancment/bug fix?
* https://github.com/k3s-io/k3s/issues/9447
```release-note
The `NodePasswordValidationFailed` Events will no longer be emitted, if the agent is disabled.
```
I am open to discussion and suggestion on better implementation.

Don't create NodePasswordValidationFailed event if agent is disabled

---

pkg/rootless/rootless.go

Currently, the `~/.rancher/k3s/rootless` directory is created but is unused. The directory is passed to the `createParentOpts` but the variable is then overrided by a call to `os.MkdirTemp`. This makes it harder to `nsenter` via rootlesskit's `child_pid` or hit the rootlesskit's API socket.
- When running k3s in rootless mode, expose rootlesskit's state directory as `~/.rancher/k3s/rootless`
- Run k3s in rootless mode
- List files in `~/.rancher/k3s/rootless`
* https://github.com/k3s-io/k3s/issues/9449
```release-note
When running k3s in rootless mode, expose rootlesskit's state directory as `~/.rancher/k3s/rootless`
```

Expose rootless state dir under ~/.rancher/k3s/rootless

---

pkg/rootless/mounts.go

When installing k3s as a rootless systemd user service, it'll have better usability if regular tools like `nerdctl`, `ctr`, and `crictl` can interact with the container runtime embedded in k3s. Due to the rootlesskit setup being embedded in the k3s binary, it's impossible to use `k3s server --rootless` with an external `--container-runtime-endpoint` even with `nsenter` because the embedded kubelet does a healthcheck:
1. kubelet (in k3s) fail to startup due to health check of `containerd-runtime-endpoint`
2. containerd (outside of k3s) fail to startup due to rootlesskit not yet self-exec'd (i.e. `child_pid` not yet available).
Thus, in rootless mode it's better to just leverage the embedded containerd.
- Mount k3s rootless containerd & cri-dockerd socket directories to …

Expose rootless containerd socket directories for external access

---

go.mod
go.sum
pkg/cli/server/server.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go

Bump kine for WatchProgressRequest support and set NotifyInterval to what the apiserver expects
Note upstream says they always test with the notification interval set to 5 seconds. The flag is apparently GA in 3.5 despite being named `experimental`.
https://github.com/kubernetes/kubernetes/issues/122805#issuecomment-1898386268
version bump
upstream compat
Normal release tests
* https://github.com/k3s-io/k3s/issues/9385
```release-note
```

Bump kine and set NotifyInterval to what the apiserver expects

---

go.mod
go.sum
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_controller.go
pkg/node/controller.go
pkg/rootless/mounts.go
pkg/rootless/rootless.go
pkg/server/router.go
scripts/version.sh

Backports:
* https://github.com/k3s-io/k3s/pull/9247
* https://github.com/k3s-io/k3s/pull/9318
* https://github.com/k3s-io/k3s/pull/9249
* https://github.com/k3s-io/k3s/pull/9354
* https://github.com/k3s-io/k3s/pull/9317
* https://github.com/k3s-io/k3s/pull/9312
* https://github.com/k3s-io/k3s/pull/9349
* https://github.com/k3s-io/k3s/pull/9308
* https://github.com/k3s-io/k3s/pull/9309
backports
* https://github.com/k3s-io/k3s/issues/9368
* https://github.com/k3s-io/k3s/issues/9371
* https://github.com/k3s-io/k3s/issues/9377
* https://github.com/k3s-io/k3s/issues/9380
* https://github.com/k3s-io/k3s/issues/9389
* https://github.com/k3s-io/k3s/issues/9450
* https://github.com/k3s-io/k3s/issues/9453
* https://github.com/k3s-io/k3s/issues/9456
* …

[release-1.28] Backports for 2024-02 release cycle

---

go.mod
go.sum
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_controller.go
pkg/node/controller.go
pkg/rootless/mounts.go
pkg/rootless/rootless.go
pkg/server/router.go
scripts/version.sh

Backports:
* https://github.com/k3s-io/k3s/pull/9247
* https://github.com/k3s-io/k3s/pull/9318
* https://github.com/k3s-io/k3s/pull/9249
* https://github.com/k3s-io/k3s/pull/9354
* https://github.com/k3s-io/k3s/pull/9317
* https://github.com/k3s-io/k3s/pull/9312
* https://github.com/k3s-io/k3s/pull/9349
* https://github.com/k3s-io/k3s/pull/9308
* https://github.com/k3s-io/k3s/pull/9309
backports
* https://github.com/k3s-io/k3s/issues/9369
* https://github.com/k3s-io/k3s/issues/9372
* https://github.com/k3s-io/k3s/issues/9378
* https://github.com/k3s-io/k3s/issues/9381
* https://github.com/k3s-io/k3s/issues/9390
* https://github.com/k3s-io/k3s/issues/9451
* https://github.com/k3s-io/k3s/issues/9454
* https://github.com/k3s-io/k3s/issues/9457
* …

[release-1.27] Backports for 2024-02 release cycle

---

go.mod
go.sum
pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_controller.go
pkg/node/controller.go
pkg/rootless/mounts.go
pkg/rootless/rootless.go
pkg/server/router.go
scripts/version.sh

Backports:
* https://github.com/k3s-io/k3s/pull/9247
* https://github.com/k3s-io/k3s/pull/9318
* https://github.com/k3s-io/k3s/pull/9249
* https://github.com/k3s-io/k3s/pull/9354
* https://github.com/k3s-io/k3s/pull/9317
* https://github.com/k3s-io/k3s/pull/9312
* https://github.com/k3s-io/k3s/pull/9349
* https://github.com/k3s-io/k3s/pull/9308
* https://github.com/k3s-io/k3s/pull/9309
backports
* https://github.com/k3s-io/k3s/issues/9370
* https://github.com/k3s-io/k3s/issues/9373
* https://github.com/k3s-io/k3s/issues/9379
* https://github.com/k3s-io/k3s/issues/9382
* https://github.com/k3s-io/k3s/issues/9391
* https://github.com/k3s-io/k3s/issues/9452
* https://github.com/k3s-io/k3s/issues/9455
* https://github.com/k3s-io/k3s/issues/9458
* …

[release-1.26] Backports for 2024-02 release cycle

---

Dockerfile.local
pkg/clientaccess/token.go

Backport a portion of https://github.com/k3s-io/k3s/pull/9340, the parts not related to Secrets Encryption in 1.29
- Enable Timeout modification on a HTTP request
TBD
```release-note
```

[Release-1.28] Enable longer http timeout requests

---

pkg/clientaccess/token.go

Backport a portion of https://github.com/k3s-io/k3s/pull/9340, the parts not related to Secrets Encryption in 1.29
- Enable Timeout modification on a HTTP request
TBD
```release-note
```

[Release-1.26] Enable longer http timeout requests

---

Dockerfile.local
pkg/clientaccess/token.go

Backport a portion of https://github.com/k3s-io/k3s/pull/9340, the parts not related to Secrets Encryption in 1.29
- Enable Timeout modification on a HTTP request
TBD
```release-note
```

[Release-1.27] Enable longer http timeout requests

---

pkg/agent/config/config.go
pkg/agent/config/config_linux.go
pkg/agent/config/config_linux_test.go
pkg/agent/config/config_windows.go

Backport #8945 
https://github.com/k3s-io/k3s/issues/9439
```release-note
```

[Release-1.28] Test_UnitApplyContainerdQoSClassConfigFileIfPresent

---

pkg/agent/config/config.go
pkg/agent/config/config_linux.go
pkg/agent/config/config_linux_test.go
pkg/agent/config/config_windows.go

Backport #8945 
https://github.com/k3s-io/k3s/issues/8843
```release-note
```

[Release-1.27] Test_UnitApplyContainerdQoSClassConfigFileIfPresent

---

pkg/agent/config/config.go
pkg/agent/config/config_linux.go
pkg/agent/config/config_linux_test.go
pkg/agent/config/config_windows.go

Backport #8945 
https://github.com/k3s-io/k3s/issues/8844
```release-note
```

[Release-1.26] Test_UnitApplyContainerdQoSClassConfigFileIfPresent

---

.drone.yml

The `github-release` drone plugin does not support arm (32bit) on the `latest` tag.
Replaced with the properly supported tag.
Ci Fix
Drone Publish Should now pass
https://github.com/k3s-io/k3s/issues/9504
```release-note
```

Fix drone publish for arm

---

.drone.yml

The `github-release` drone plugin does not support arm (32bit) on the `latest` tag.
Replaced with the properly supported tag.
Ci Fix
Drone Publish Should now pass
https://github.com/k3s-io/k3s/issues/9505
```release-note
```

[Release-1.28] Fix drone publish for arm

---

.drone.yml

The `github-release` drone plugin does not support arm (32bit) on the `latest` tag.
Replaced with the properly supported tag.
Ci Fix
Drone Publish Should now pass
https://github.com/k3s-io/k3s/issues/9507
```release-note
```

[Release-1.26] Fix drone publish for arm

---

.drone.yml

The `github-release` drone plugin does not support arm (32bit) on the `latest` tag.
Replaced with the properly supported tag.
Ci Fix
Drone Publish Should now pass
https://github.com/k3s-io/k3s/issues/9506
```release-note
```

[Release-1.27] Fix drone publish for arm

---

pkg/agent/run.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/daemons/agent/agent.go
pkg/daemons/config/types.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
scripts/test-run-etcd
tests/e2e/splitserver/Vagrantfile
tests/e2e/splitserver/splitserver_test.go

- Partial revert of #9184, restoring the orginal order of setting up container runtimes, closing the channel, then running the kubelet.
- Renamed `AgentReady` to `ContainerRuntimeReady` to better reflect what the channel is actually tracking.
- Closed E2E coverage gap around this issue by increasing number of etcd nodes in the split role test.
Bugfix
Manually running split servers (3 etcd, 2 cp, 1 agent), the cluster now initialized all etcd nodes correctly. 
Change is now covered by E2E test, and the docker/drone `test` stage now covers this case.
https://github.com/k3s-io/k3s/issues/9540
```release-note
```
I will not be squashing this, as we want the revert commit to stand alone from the other 2 "new" changes.

Restore original order of agent startup functions

---

pkg/agent/netpol/netpol.go

Fix netpol startup when flannel is disabled.
Don't break out of the poll loop if we can't get the node, RBAC might not be ready yet.
bugfix
tbd
/cc @manuelbuil 
* https://github.com/k3s-io/k3s/issues/9570
```release-note
```

Fix netpol startup when flannel is disabled

---

pkg/agent/netpol/netpol.go

Fix netpol startup when flannel is disabled.
Don't break out of the poll loop if we can't get the node, RBAC might not be ready yet.
bugfix
tbd
/cc @manuelbuil 
* https://github.com/k3s-io/k3s/issues/9575
```release-note
```

[release-1.28] Fix netpol startup when flannel is disabled

---

pkg/agent/netpol/netpol.go

Fix netpol startup when flannel is disabled.
Don't break out of the poll loop if we can't get the node, RBAC might not be ready yet.
bugfix
tbd
/cc @manuelbuil 
* https://github.com/k3s-io/k3s/issues/9576
```release-note
```

[release-1.27] Fix netpol startup when flannel is disabled

---

pkg/agent/netpol/netpol.go

Fix netpol startup when flannel is disabled.
Don't break out of the poll loop if we can't get the node, RBAC might not be ready yet.
bugfix
tbd
/cc @manuelbuil 
* https://github.com/k3s-io/k3s/issues/9577
```release-note
```

[release-1.26] Fix netpol startup when flannel is disabled

---

CONTRIBUTING.md
docs/adrs/testing-2024.md

- Adds Testing in K3s ADR as an update for where testing is headed in 2024.
Docs
https://github.com/k3s-io/k3s/issues/9477
```release-note
```

Testing ADR

---

.github/workflows/unitcoverage.yaml

- Remove the matrix for unit testing, if it passes on ubuntu=latest, its fine, we don't need to waste time testing it on another ubuntu version
- Move to a different debug action: the new action allows a "timeout for non connection", so if you do use the debugging session, the timeout becomes null and void. No longer will a  user have to race against a clock for debugging purposes. 
- Install the version of go given in the go.mod, reduces having to maintain multiple versions of go in infra.
- setup-go@v4 and above enables caching by default, no need to configure it. 
https://github.com/k3s-io/k3s/issues/9478
```release-note
```

Unit Testing Matrix and Actions bump

---

.github/workflows/integration.yaml
tests/integration/flannelnone/flannelnone_int_test.go

Add a new test that verifies cluster starts up correclty up to the point where it needs the CNI plugin to continue
test
```release-note
```

Add an integration test for flannel-backend=none

---

.github/actions/setup-go/actions.yaml
.github/workflows/integration.yaml
.github/workflows/unitcoverage.yaml
.github/workflows/updatecli.yaml

Builds off of https://github.com/k3s-io/k3s/pull/9479 (will be rebased when that merges)
Use a custom caching strategy for GitHub Action `setup-go`, which restricts:
- Only master branch can SAVE caches
- PRs can only RESTORE (ie read) caches
GitHub CI
For now, this PR should not open any new caches
https://github.com/k3s-io/k3s/issues/9494
```release-note
```

Better GitHub CI caching strategy for golang

---

pkg/rootlessports/controller.go

When creating a service, typically the service port is for pod-to-pod access whereas nodePort is used for external access. In non-rootless mode, I was able to access a service of type LoadBalancer via localhost on both its service port and nodePort.
However, in rootless mode, I was only able to access it via localhost on its service port but not its nodePort.
Rootless mode should also bind service nodePort to host for LoadBalancer type, matching UX of rootful mode.
1. `kubectl apply` a simple pod & `LoadBalancer` service with `nodePort`
2. Pod is accessible via service `port` and `nodePort`
* #9511
```release-note
Rootless mode should also bind service nodePort to host for LoadBalancer type, matching UX of rootful mode.
```

Rootless mode also bind service nodePort to host for LoadBalancer type

---

pkg/agent/run.go
pkg/node/controller.go

* Add both dual-stack addresses to the node hosts file
* Add hostname to hosts file as alias for node name to ensure consistent resolution
bugfix
* On a dual-stack cluster, ensure that both addresses are present in the hosts file:
`kubectl get configmap -n kube-system coredns -o template --template '{{.data.NodeHosts}}'`
* https://github.com/k3s-io/k3s/issues/9551
```release-note
```

Fix coredns NodeHosts on dual-stack clusters

---

pkg/agent/netpol/netpol.go

Tweak netpol node wait logs
bugfix; nit
* https://github.com/k3s-io/k3s/issues/9574
```release-note
```

Tweak netpol node wait logs

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go

* Set ServerNodeName in snapshot CLI setup
* Raise error if ServerNodeName ends up empty some other way
* Fix status controller to use etcd node name annotation instead of prefix checking
bugfix
* https://github.com/k3s-io/k3s/issues/9521
* https://github.com/rancher/rke2/issues/5482
```release-note
```

Fix issue with etcd node name missing hostname

---

.github/workflows/integration.yaml
tests/integration/flannelnone/flannelnone_int_test.go

Backport: https://github.com/k3s-io/k3s/pull/9582

[Release 1.28] Add an integration test for flannel-backend=none

---

.github/workflows/integration.yaml
tests/integration/flannelnone/flannelnone_int_test.go

Backport: https://github.com/k3s-io/k3s/pull/9582

[Release 1.27] Add an integration test for flannel-backend=none

---

.github/actions/vagrant-setup/action.yaml
.github/workflows/install.yaml
.github/workflows/integration.yaml
.github/workflows/nightly-install.yaml
.github/workflows/snapshotter.yaml
tests/TESTING.md

- Reenable Install (both PR and Nightly) and Snapshot vagrant testing, now using the ubuntu GitHub Action Runners
- Update Readme
CI and Testing
See https://github.com/dereknola/k3s/pull/19, which has the install and snapshotter GH workflows enabled. I do not want to reenable them on K3s-io until this PR is merged, as other PRs will start running the workflows and fail. 
https://github.com/k3s-io/k3s/issues/8591
```release-note
```

Reenable Install and Snapshotter Testing

---

scripts/build
scripts/version.sh

Use and version flannel/cni-plugin properly
Moves us closer to using the proper upstream for our flannel CNI plugin, instead of the snapshot that is vendored into our plugins fork. In the future, we can drop the flannel plugin from our fork entirely, to better align with the upstream plugins project. It will also ensure that fixes like https://github.com/flannel-io/cni-plugin/pull/46 are no longer accidentally omitted from making it into k3s.
tech debt
Check versions - note that flannel version is no longer the same as the CNI plugins version
```console
/ # flannel --version
CNI Plugin flannel version v1.4.0-flannel1 (linux/amd64) commit HEAD built on 2024-03-04T18:48:37Z
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
/ # cni --version
CNI plugins plugin …
```

Use and version flannel/cni-plugin properly

---

pkg/agent/containerd/runtimes.go
pkg/agent/containerd/runtimes_test.go
tests/e2e/amd64_resource_files/wasm-workloads.yaml
tests/e2e/wasm/Vagrantfile
tests/e2e/wasm/wasm_test.go

Change how containerd configuration is generated with regards to WebAssembly shims.
Use correct binary names and the associated `RuntimeType`. Prior to this, there was quite a mixup between `v1` and `v2` shims.
- Download `spin` and the `slight` shims from [here](https://github.com/deislabs/containerd-wasm-shims/releases/tag/v0.11.1)
- Unpack the tarball and move the files to `/usr/bin/containerd-shim-spin-v2` and `/usr/bin/containerd-shim-slight-v1`
- Install/restart the patched version of k3s
Check the contents of `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`, it should have the following lines:
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."slight"]
runtime_type = "io.containerd.slight.v1"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."slight".opt …
```

fix: use correct wasm shims names

---

pkg/agent/containerd/config_test.go

Thanks @vitorsavian 
Fix test broken by combined changes from https://github.com/k3s-io/k3s/pull/9599 and https://github.com/k3s-io/k3s/pull/9556
One PR added tests, another PR changed the logic; the combination of the two was not tested until both were merged to master.
test
check CI
yes
*
```release-note
NONE
```

Fix wildcard with embbeded registry test

---

contrib/util/check-config.sh

Setting this environment variable will not wrap the text in ANSI color codes, so that we can print a raw output.
This helps us a lot when piping the output to a text file, ANSI color codes make it difficult to read through the output in a text editor.
Introduced a new environment variable called `NO_COLOR`.
`NO_COLOR=1` will disable the wrapping of output text in ANSI color codes.
Default functionality will be maintained if the env var is not set at all.
Ran this suit of tests:
- Default usage:   
- Usage with `NO_COLOR` env var:
NO_COLOR can be set to whatever.
* #9355 
```release-note
To enable raw output for the `check-config` subcommand, run:
NO_COLOR=1 k3s check-config
```
Let me know if the variable name is not suitable, or any other questions/discussions. Will be happy to refactor …

Disable color outputs using `NO_COLOR` env var

---

tests/e2e/tailscale/README.md
tests/e2e/tailscale/Vagrantfile
tests/e2e/tailscale/tailscale_test.go

This PR applies three improvements to the Tailscale e2e test:
1 - Adds `tls-san: #{node_ip4}` to the server config, otherwise, the test fails because it tries to access kube-api via the node-ip. That can work but we must append the node-ip to the kube-apiserver tls-san
2 - Reduce the time limit to 300s. 620s is too much and makes the wait too long when something does not work
3 - Add a "gotchas" section in the README
Test improvement
go test -v -timeout=15m tests/e2e/tailscale/tailscale_test.go
```release-note
```

Improve tailscale e2e test

---

pkg/agent/config/config.go

This PR checks the IP family of the first IP configured as `node-ip` and as `clusterCIDR`. If they differ and the `node-ip` is dualstack it changes the order to prioritize the same family of the `clusterCIDR`. This changes will fix #9435 when no `node-ip` is configured and the auto detected IP is dualstack with always IPv4 as main.
#9435
```release-note
```

Adjust first node-ip based on configured clusterCIDR

---

tests/e2e/tailscale/README.md
tests/e2e/tailscale/Vagrantfile
tests/e2e/tailscale/tailscale_test.go

Backport: https://github.com/k3s-io/k3s/pull/9586

[Release 1.28] Improve tailscale e2e test

---

scripts/build

We actually embed two separate things from the flannel project:
* the flannel controller: https://github.com/flannel-io/flannel/releases/tag/v0.24.2
* the flannel cni plugin: https://github.com/flannel-io/cni-plugin/releases/tag/v1.4.0-flannel1
We were misreporting the flannel controller version as the flannel cni plugin version. That was fixed in https://github.com/k3s-io/k3s/pull/9635, but the QA and release teams were relying on that to look up the flannel controller version embedded in k3s.
Restore the actual flannel controller version as build metadata in the cni plugin version.
enhancement
check the flannel cni plugin version:
```
/ # flannel --version
CNI Plugin flannel version v1.4.0-flannel1+v0.24.2 (linux/amd64) commit HEAD built on 2024-03-05T19:38:31Z
CNI protocol versions …
```

Include flannel version in flannel cni plugin version

---

.github/workflows/integration.yaml
tests/integration/flannelnone/flannelnone_int_test.go

Backport: https://github.com/k3s-io/k3s/pull/9582

[Release 1.26] Add an integration test for flannel-backend=none

---

pkg/agent/containerd/config.go
pkg/agent/containerd/config_test.go

Warn and suppress duplicate registry mirror endpoints
bugfix
See linked issue and test
yes
* https://github.com/k3s-io/k3s/issues/9693
```release-note
K3s will now warn and suppress duplicate entries in the mirror endpoint list for a registry. Containerd does not support listing the same endpoint multiple times as a mirror for a single upstream registry.
```

Warn and suppress duplicate registry mirror endpoints

---

.github/workflows/build-k3s.yaml
.github/workflows/e2e.yaml
.github/workflows/integration.yaml
scripts/test
tests/e2e/btrfs/btrfs_test.go

- Convert a portion of the docker test currently running in Drone to running as part of the E2E GitHub Action
Note: This PR only reduced the drone load for amd64. For arm64/arm architectures the tests will remain as is, as GitHub Actions do not yet exist for those architectures. 
- Fix flaky check on btrfs e2e test
- Fix broken cache name for e2e vagrant boxes
CI/Testing
Takes about 3 minutes off the Drone times... Not much, but every bit counts. Plus now the runners won't need pruning as much.
See https://github.com/dereknola/k3s/actions/runs/8193839495?pr=22, with the new matrices (as this PR won't run the new tests until commited to master for security reasons)
TBD
```release-note
```

Run Subset of Docker tests in GitHub Actions

---

pkg/agent/containerd/config.go
pkg/agent/containerd/config_test.go

The generated config for the wildcard/default entry was missing a top-level `server` entry, so containerd was not falling back to the default upstream endpoint.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9728
```release-note
```

Fix wildcard entry upstream fallback

---

pkg/agent/containerd/config.go
pkg/agent/containerd/config_test.go

The generated config for the wildcard/default entry was missing a top-level `server` entry, so containerd was not falling back to the default upstream endpoint.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9730
```release-note
```

[release-1.28] Fix wildcard entry upstream fallback

---

pkg/agent/containerd/config.go
pkg/agent/containerd/config_test.go

The generated config for the wildcard/default entry was missing a top-level `server` entry, so containerd was not falling back to the default upstream endpoint.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9731
```release-note
```

[release-1.27] Fix wildcard entry upstream fallback

---

pkg/agent/containerd/config.go
pkg/agent/containerd/config_test.go

The generated config for the wildcard/default entry was missing a top-level `server` entry, so containerd was not falling back to the default upstream endpoint.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9732
```release-note
```

[release-1.26] Fix wildcard entry upstream fallback

---

pkg/daemons/control/tunnel.go
pkg/etcd/etcd.go
pkg/server/auth.go
pkg/server/router.go
pkg/util/apierrors.go

* Move error response generation code into util
* Send error response if member list cannot be retrieved
Prevents joining nodes from being stuck with bad initial member list if there is a transient failure, or if they try to join themselves
I am assuming there was some reason we generated a dummy list instead of sending an error, but it's done this since the initial embedded etcd code was bulk-added by Darren in https://github.com/k3s-io/k3s/pull/1770 so I don't know why this was supposed to be a good idea.
bugfix
* Try joining a node that is behind an external load-balancer that includes the new node in its target poor. For example, using the following haproxy config, where `SERVER1` is the existing node, and `SERVER2` is the node attempting to join the cluster:
``` …
```

Send error response if member list cannot be retrieved

---

pkg/cloudprovider/instances.go
pkg/cloudprovider/instances_test.go

Don't clobber the providerID field and instance-type/region/zone labels if provided by the kubelet. This allows the user to set these to the correct values when using the embedded CCM in a real cloud environment.
enhancement
Start k3s server or agent with provider-id, instance-type, region, and zone set:
`k3s server --kubelet-arg=provider-id=aws://i-xxx --node-label=node.kubernetes.io/instance-type=c4.large --node-label=topology.kubernetes.io/region=us-west-2 --node-label=topology.kubernetes.io/zone=us-west-2a`
Check the output of `kubectl get node -o yaml`: k3s should leave these set as requested, and not clobber them with k3s or empty values.
* https://github.com/k3s-io/k3s/issues/9280
```release-note
The k3s stub cloud provider now respects the kubelet's requested provider-id, instance …
```

Respect cloud-provider fields set by kubelet

---

package/Dockerfile

Add /etc/passwd and /etc/group to k3s docker image
Fixes `cannot find name for user ID 0: No such file or directory` errors when checking user info in docker image
```console
~ # PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
@k3s-server-1:/# id
uid=0 gid=0 groups=0
@k3s-server-1:/# groups
groups: cannot find name for group ID 0
0
@k3s-server-1:/# whoami
whoami: cannot find name for user ID 0: No such file or directory
root@k3s-server-1:/# cat /etc/passwd
cat: /etc/passwd: No such file or directory
```
bugfix/enhancement
run the rancher/k3s image in docker, then exec into the running container:
```console
~ # PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
root@k3s-server-1:~# id
uid=0(root) gid=0(root) groups=0(root)
root@k3s-server-1:~# …
```

Add /etc/passwd and /etc/group to k3s docker image

---

pkg/cli/server/server.go
pkg/daemons/config/types.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_controller.go

Fix etcd snapshot reconcile for agentless servers
Disable cleanup of orphaned snapshots and patching of node annotations if running agentless
Fixes regression in agentless etcd behavior introduced by #8064
bugfix
* https://github.com/k3s-io/k3s/issues/9774
```release-note
```

Fix etcd snapshot reconcile for agentless servers

---

pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/servers.go
pkg/agent/proxy/apiproxy.go
pkg/agent/tunnel/tunnel.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/etcd/etcdproxy.go

Add health-check support to loadbalancer
* Adds support for health-checking loadbalancer servers. Servers are now health-checked periodically and before dialing; if the health-check fails, all existing connections to the  server will be closed.
* Wires up a remotedialer tunnel connectivity check as the health check for supervisor/apiserver connections.
* Wires up a simple http request to the supervisor as the health check for etcd connections.
This ensures that any load-balanced connections to a node will be closed when the remotedialer tunnel to that node disconnects. This isn't much of an issue on K3s as the apiserver always exits when the supervisor shuts down, but on RKE2 the apiserver may continue running even when the supervisor stops, but without its load-balanced connection to …

Add health-check support to loadbalancer

---

go.mod
go.sum
pkg/agent/run.go
pkg/agent/run_test.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/cli/token/token.go
pkg/cloudprovider/servicelb.go
pkg/etcd/snapshot.go
pkg/nodepassword/nodepassword.go
pkg/server/secrets-encrypt.go
pkg/spegel/spegel.go

- Move from [deprecated K8s Util Pointer](https://pkg.go.dev/k8s.io/utils/pointer) to Util Ptr library
CI Green, K3s makes
https://github.com/k3s-io/k3s/issues/9819
```release-note
```

Transition from deprecated pointer library to ptr

---

.github/workflows/e2e.yaml
tests/e2e/embeddedmirror/Vagrantfile
tests/e2e/embeddedmirror/embeddedmirror_test.go
tests/e2e/vagrantdefaults.rb
tests/e2e/wasm/Vagrantfile

- Add WASM E2E test to GitHub Actions matrix
- Optimize `vagrant provision` steps, don't install JQ unless we need it. (We don't use it in the PR/local build case, which should slightly improve CI time)
- Fix golang for Embedded Registry test. This PR just addresses issue around the E2E test itself. It does not add the test to the GH matrix yet because an issue was discovered around agents being up before servers that is causing this test to fail, but that is a separate issue that will be fixed in another PR.
Testing/CI
- CI Green
- You can locally run the emedded registry test, but you have to manually bump the sleep times between provisioning of servers and agents to actually get it to pass. 
Testing all the way down …

Several E2E Matrix improvments

---

pkg/agent/templates/templates.go

Add base `[host]` tree to containerd hosts.toml to work around containerd bug
bugfix
* https://github.com/k3s-io/k3s/issues/9839
* https://github.com/containerd/containerd/issues/10027
```release-note
```

Add workaround for containerd hosts.toml bug when passing config for default registry endpoint

---

pkg/cli/cmds/certs.go
pkg/util/services/services.go
pkg/util/services/services_test.go
tests/e2e/validatecluster/validatecluster_test.go

* We added a new cert a while back in https://github.com/k3s-io/k3s/pull/7616, but didn't add it to the rotate list.
bugfix
Yes
* https://github.com/k3s-io/k3s/issues/9831
```release-note
```

Add supervisor cert/key to rotate list

---

channel.yaml

Bump latest to v1.29.3+k3s1
v1.30.0 is coming out next week and we're still serving 1.28 as latest.
channel server version bump
check latest served by install script
```release-note
```

Bump latest to v1.29.3+k3s1

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/etcd/snapshot_handler.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

* Fix on-demand snapshots not honoring folder
Also fix etcd s3 tests to actually check that the files are saved to s3 🙃
* Fix 10 second etcd-snapshot request timeout
The default clientaccess request timeout is too short. Wait longer by default, and add the s3 timeout if s3 is enabled.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9982
* https://github.com/k3s-io/k3s/issues/9985
```release-note
```

Fix on-demand snapshots timing out; not honoring folder

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/etcd/snapshot_handler.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

* *Backport #9984*
* Fix on-demand snapshots not honoring folder
Also fix etcd s3 tests to actually check that the files are saved to s3 🙃
* Fix 10 second etcd-snapshot request timeout
The default clientaccess request timeout is too short. Wait longer by default, and add the s3 timeout if s3 is enabled.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9996
* https://github.com/k3s-io/k3s/issues/9998
```release-note
```

[release-1.28] Fix on-demand snapshots timing out; not honoring folder

---

pkg/cli/etcdsnapshot/etcd_snapshot.go
pkg/etcd/snapshot_handler.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

* *Backport #9984*
* Fix on-demand snapshots not honoring folder
Also fix etcd s3 tests to actually check that the files are saved to s3 🙃
* Fix 10 second etcd-snapshot request timeout
The default clientaccess request timeout is too short. Wait longer by default, and add the s3 timeout if s3 is enabled.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/9997
* https://github.com/k3s-io/k3s/issues/9999
```release-note
```

[release-1.27] Fix on-demand snapshots timing out; not honoring folder

---

tests/e2e/btrfs/Vagrantfile
tests/e2e/btrfs/btrfs_test.go
tests/e2e/token/token_test.go
tests/install/opensuse-leap/Vagrantfile

- Something is broken with the most recently published opensuse leap 15.5 image on vagrant cloud, leading to a failing btrfs test. 
- Moving to recently released 15.6 image resolved this issue. 
Testing
CI is green
```release-note
```

Bump E2E opensuse leap to 15.6, fix btrfs test

---

pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go

- Stops passing pause image to kubelet as a flag (deprecated in v1.29.0)
CLI
Start k3s with `--pause-image=rancher/mirrored-pause:3.5` and check the logs for the kubelet command. Should see no complaints from kubelet. 
https://github.com/k3s-io/k3s/issues/7408
```release-note
```

[1.30] Remove depracated `pod-infra-container-image` kubelet flag

---

tests/e2e/token/token_test.go
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/vagrantdefaults.rb

Update upgradecluster test and minor  fixes
NA

Fix e2e tests

---

tests/e2e/btrfs/Vagrantfile
tests/e2e/dualstack/Vagrantfile
tests/e2e/embeddedmirror/Vagrantfile
tests/e2e/externalip/Vagrantfile
tests/e2e/privateregistry/Vagrantfile
tests/e2e/rootless/Vagrantfile
tests/e2e/rotateca/Vagrantfile
tests/e2e/s3/Vagrantfile
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/secretsencryption_old/Vagrantfile
tests/e2e/snapshotrestore/Vagrantfile
tests/e2e/splitserver/Vagrantfile
tests/e2e/startup/Vagrantfile
tests/e2e/tailscale/Vagrantfile
tests/e2e/token/Vagrantfile
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/wasm/Vagrantfile

`exists` was deprecated since ruby 2.1 and removed in ruby 3.2:
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
Bugfix
```release-note
```
Thanks @mgfritch

Replace deprecated ruby function in e2e tests

---

channel.yaml

Update channels with 1.30

---

.drone.yml
tests/e2e/btrfs/Vagrantfile
tests/e2e/btrfs/btrfs_test.go
tests/e2e/token/token_test.go
tests/e2e/upgradecluster/Vagrantfile
tests/install/opensuse-leap/Vagrantfile

Backport https://github.com/k3s-io/k3s/pull/10057
```release-note
```

[Release-1.28] Bump E2E opensuse leap to 15.6, fix btrfs test

---

.drone.yml
tests/e2e/btrfs/Vagrantfile
tests/e2e/btrfs/btrfs_test.go
tests/e2e/token/token_test.go
tests/e2e/upgradecluster/Vagrantfile
tests/install/opensuse-leap/Vagrantfile

Backport https://github.com/k3s-io/k3s/pull/10057
```release-note
```

[Release-1.27] Bump E2E opensuse leap to 15.6, fix btrfs test 

---

.drone.yml
tests/e2e/upgradecluster/Vagrantfile

- Default to v1.29 for the e2e upgrade test on PRs (so the drone test check going from newest v1.29 -> this PR build)
N/A
```release-note
```

[release-1.29] Set correct release channel for e2e upgrade test

---

tests/e2e/btrfs/Vagrantfile
tests/e2e/dualstack/Vagrantfile
tests/e2e/embeddedmirror/Vagrantfile
tests/e2e/externalip/Vagrantfile
tests/e2e/privateregistry/Vagrantfile
tests/e2e/rotateca/Vagrantfile
tests/e2e/s3/Vagrantfile
tests/e2e/secretsencryption/Vagrantfile
tests/e2e/snapshotrestore/Vagrantfile
tests/e2e/splitserver/Vagrantfile
tests/e2e/startup/Vagrantfile
tests/e2e/tailscale/Vagrantfile
tests/e2e/token/Vagrantfile
tests/e2e/upgradecluster/Vagrantfile
tests/e2e/vagrantdefaults.rb
tests/e2e/validatecluster/Vagrantfile
tests/e2e/wasm/Vagrantfile

Backport: https://github.com/k3s-io/k3s/pull/10084

[Release 1.27] Replace deprecated ruby function

---

pkg/cli/agent/agent.go

When passing the config of tailscale using the config file, Tailscale was not working correctly in the agent. The reason is that we were setting the variable `cmds.AgentConfig.VPNAuth` which is not used by the agent. A few lines before, k3s is doing `cfg := cmds.AgentConfig` and after that, anything set in `cmds.AgentConfig` will get lost. Therefore, we should set the variable `cfg.VPNAuth` instead, which is the one being read by the agent. This PR does exactly that
Bugfix
Deploy k3s+tailscale using the [docs](https://docs.k3s.io/networking/distributed-multicloud#integration-with-the-tailscale-vpn-provider-experimental) and using the `vpn-auth-file` config
https://github.com/k3s-io/k3s/issues/10064
```release-note
Fix bug when using `vpn-auth-file` in the agent
```

Fix bug when using tailscale config by file

---

pkg/agent/containerd/containerd.go

Add WithSkipMissing to not fail import on missing blobs.
Fix an issue where archives produced by `ctr image export` cannot be imported, unless the images are pulled and exported with the `--all-platforms` flag.
enhancement
* https://github.com/k3s-io/k3s/issues/10132
```release-note
```

Add WithSkipMissing to not fail import on missing blobs

---

pkg/agent/cridockerd/cridockerd.go

Use fixed stream server bind address for cri-dockerd
Will now use 127.0.0.1:10010, same as containerd's CRI:
https://github.com/k3s-io/k3s/blob/d973fadbed133cf9c5db64c87ae724b1a80c766f/pkg/agent/templates/templates_linux.go#L16-L18
enhancement
* Check for listener on 127.0.0.1:10010 when using cri-dockerd
* https://github.com/k3s-io/k3s/issues/9965
```release-note
```

Use fixed stream server bind address for cri-dockerd

---

pkg/agent/containerd/config_test.go
pkg/agent/templates/templates_linux.go

Migrate the stargz CRI registry config over to `config_path`, same as the core containerd CRI config.
This should have been done as part of https://github.com/k3s-io/k3s/pull/8973 but I didn't realize stargz already supported it, ref: https://github.com/containerd/stargz-snapshotter/pull/331
tech debt
Note use of `config_path` under `[plugins."io.containerd.snapshotter.v1.stargz".registry]` in config.toml, when stargz snapshotter is enabled.
yes
* https://github.com/k3s-io/k3s/issues/9976
```release-note
```

Switch stargz over to cri registry config_path

---

pkg/cloudprovider/servicelb.go

Fix issue with local traffic policy for single-stack services on dual-stack nodes.
Just enable IP forwarding for all address families regardless of service address families.
Note: I confirmed that this works even on a node with ipv6 disabled via `net.ipv6.conf.all.disable_ipv6=1` sysctl.
bugfix
https://github.com/k3s-io/k3s/issues/9949#issuecomment-2059645672
* https://github.com/k3s-io/k3s/issues/9949
```release-note
```

Fix issue with `externalTrafficPolicy: Local` for single-stack services on dual-stack nodes

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/servicelb.go
pkg/daemons/control/deps/deps.go

Add support for svclb pod PriorityClassName
At this point I would prefer not to add another CLI flag to control the default priorityClassName, but you can override it on a per-service basis via an annotation. The annotation can be set to an empty value if svclb pods for that service should not have a priorityClassName set.
enhancement
* https://github.com/k3s-io/k3s/issues/10033
```release-note
ServiceLB now sets the priorityClassName on svclb pods to `system-node-critical` by default. This can be overridden on a per-service basis via the `svccontroller.k3s.cattle.io/priorityclassname` annotation.
```

Add support for svclb pod PriorityClassName

---

pkg/server/server.go

Drop check for legacy traefik v1 chart
We have been bundling traefik v2 for three years, its time to drop the legacy chart check
tech debt
* https://github.com/k3s-io/k3s/issues/9289
* https://github.com/k3s-io/k3s/issues/1141
```release-note
K3s no longer automatically skips deploying traefik v2 if traefik v1 is present. All clusters should have been upgraded to v2 at some point over the last three years.
```

Drop check for legacy traefik v1 chart

---

pkg/cli/agent/agent.go

Backport: https://github.com/k3s-io/k3s/pull/10074
Issue: https://github.com/k3s-io/k3s/issues/10139

[Release 1.29] Fix bug when using tailscale config by file

---

pkg/cli/agent/agent.go

Backport: https://github.com/k3s-io/k3s/pull/10074
Issue: https://github.com/k3s-io/k3s/issues/10141

[Release 1.28] Fix bug when using tailscale config by file

---

go.mod
go.sum

Bump kine to v0.11.9 to fix pagination
1. Start k3s:
`k3s server --kube-apiserver-arg=feature-gates=WatchList=true --disable=coredns,servicelb,traefik,local-storage,metrics-server --disable-network-policy`
2. Run conformance tests:
`docker run --rm -it -v "$KUBECONFIG:/root/.kube/config" -e "KUBECONFIG=/root/.kube/config" -e "E2E_EXTRA_ARGS=--ginkgo.fail-fast" -e "E2E_FOCUS=sig-api-machinery" -e "E2E_SKIP=StorageVersionAPI|Slow|Flaky" registry.k8s.io/conformance:$(kubectl get --raw /version | grep gitVersion | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+')`
StorageVersionAPI is broken and not graduating beyond alpha. One of the slow tests has a timeout that relies on specific etcd compaction intervals that kine doesn't guarantee, this is fine. The flaky test... …

Bump kine to v0.11.9 to fix pagination

---

tests/e2e/tailscale/Vagrantfile
tests/e2e/tailscale/tailscale_test.go

Adds a test to address changes in #10074 
Test
Adds another node to `tailscale` test that authenticates using a `vpn-auth-file`.
#10064 
```release-note
Fix bug when using `vpn-auth-file` in the agent
```

test: add agent with auth file

---

tests/e2e/testutils.go

As of today, when running k3s e2e tests, we can see how the server-0 is created. For example:
```
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up server-0 &> vagrant.log
```
But we don't see the same log for the rest of VMs which might be confusing. This PR removes that confusion as now the test will print all `vagrant up` commands it runs
Extra logging
Run an e2e test that creates several VMs and you now should see the `vagrant up` command for all nodes, not just server-0
Example:
```
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up server-0 &> vagrant.log
E2E_NODE_ROLES="server-0 agent-0" E2E_NODE_BOXES="generic/ubuntu2310 generic/ubuntu2310"  vagrant up agent-0 &>> vagrant.log
``` …

Add extra log in e2e tests

---

go.mod
go.sum
pkg/agent/flannel/flannel.go

**Proposed Changes**
Update flannel to v0.25.2.
The iptables package was refactored in upstream flannel so we need some changes in flannel.go to keep track of it.
**Types of Changes**
Version Update
Verification
Testing
**Linked Issues**
https://github.com/k3s-io/k3s/issues/9957

Bump flannel version to v0.25.2

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump klipper-helm image for tls secret support
enhancement
* https://github.com/k3s-io/k3s/issues/10124
```release-note
```

Bump klipper-helm image for tls secret support

---

tests/e2e/tailscale/Vagrantfile
tests/e2e/tailscale/tailscale_test.go
tests/e2e/testutils.go

Backports: https://github.com/k3s-io/k3s/pull/10119, https://github.com/k3s-io/k3s/pull/10145

[Release 1.27] Improve tailscale test & add extra log in e2e tests

---

pkg/cluster/managed.go
pkg/etcd/etcd.go
pkg/server/server.go

Fix issue with k3s-etcd informers not starting
Start shared informer caches when k3s-etcd controller wins leader election. Previously, these were only started when the main k3s apiserver controller won an election. If the leaders ended up going to different nodes, some informers wouldn't be started
bugfix
* https://github.com/k3s-io/k3s/issues/10046
```release-note
```

Fix issue with k3s-etcd informers not starting

---

.golangci.json
pkg/agent/config/config.go
pkg/agent/https/https.go
pkg/agent/netpol/netpol.go
pkg/agent/run.go
pkg/certmonitor/certmonitor.go
pkg/cli/agent/agent.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/https.go
pkg/cluster/router.go
pkg/daemons/config/types.go
pkg/daemons/control/tunnel.go
pkg/etcd/etcd.go
pkg/metrics/metrics.go
pkg/profile/profile.go
pkg/server/cert.go
pkg/server/router.go
pkg/server/secrets-encrypt.go
pkg/server/token.go
pkg/spegel/bootstrap.go
pkg/spegel/spegel.go
pkg/util/apierrors.go
pkg/util/net.go
pkg/util/net_unix.go
pkg/util/net_windows.go

* Refactor agent supervisor listener startup and authn/authz to use upstream auth delegators to perform for SubjectAccessReview for access to metrics.
* Convert spegel and pprof handlers over to new structure.
* Promote `--enable-pprof` to agent flag to allow profiling agents. Access to the pprof endpoint now requires client cert auth, similar to the spegel registry api endpoint.
* Add `--supervisor-metrics` server flag that configures all cluster members (both servers and agents) to serve metrics at `0.0.0.0:6443/metrics`. 
* The pprof and metrics endpoints use same listener as spegel. Use of any one of the three features will cause the listener to be enabled.
This is required to expose supervisor metrics on rke2; on k3s the metrics will be the same as those currently available from …

Enable serving supervisor metrics

---

go.mod
go.sum
pkg/agent/netpol/netpol.go
pkg/etcd/metadata_controller.go

Fix netpol crash when node remains tained unintialized
It is concievable that users might take more than 60 seconds to deploy their own cloud-provider. Instead of exiting, we should wait forever, but with more logging to indicate what's being waited on.
The current behavior was added in https://github.com/k3s-io/k3s/pull/9076
bugfix
* https://github.com/k3s-io/k3s/issues/10068
```release-note
```

Fix netpol crash when node remains tained unintialized

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/servers.go
pkg/etcd/etcdproxy.go

Fix issue caused by sole server marked as failed under load.
If health checks are failing for all servers, make a second pass through the server list with health-checks ignored before returning failure.
bugfix
See linked issue - probably hard/impossible to reproduce on demand due to failure conditions
* https://github.com/k3s-io/k3s/issues/10240
```release-note
The embedded load-balancer will now fall back to trying all servers with health-checks ignored, if all servers have been marked unavailable due to failed health checks.
```

Fix issue caused by sole server marked as failed under load

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/config/types.go
pkg/kubectl/main.go
pkg/server/server.go
pkg/util/file.go

Add the flag as discussed in issue #9209 in order to enable configuring of group for writing kubeconfig.
New Feature
Manually run k3s server with the flag `--write-kubeconfig-group` and check if kubeconfig has appropriate groups.
It seems there is no relevant test I found for write-kubeconfig-mode (other than it incidentally being used in some tests. If there is a request for tests please point me in the right direction!
* #9209 
Yes, it creates a new optional flag.
```release-note
New flag in k3s server: --write-kubeconfig-group
```
Unfortunately, my laptop doesn't have Linux on it at the moment (due to some suspend issues with new hardware support I'm procrastinating), and under WSL2 I'm having trouble running the final binary to test whether this commit works. Once I have time again I …

Add write-kubeconfig-group flag to server

---

.github/workflows/e2e.yaml
pkg/agent/https/https.go
tests/e2e/embeddedmirror/Vagrantfile

Fix embedded mirror blocked by SAR RBAC and re-enable test.
The embedded registry mirror was broken by https://github.com/k3s-io/k3s/pull/10019 - requests to the registry API are being run rejected by authz subject access reviews when they should not be. This is due to the AlwaysAllowPaths being incorrectly configured to match specific paths instead of prefixes.
bugfix
* https://github.com/k3s-io/k3s/issues/10256
```release-note
NONE
```

Fix embedded mirror blocked by SAR RBAC and re-enable test

---

pkg/certmonitor/certmonitor.go

Correct the warning message that is generated by the K3s certificate monitor for CA certificates
Bugfix
See issue #10270 for reproducibility
N/A
#10270
```release-note
NONE
```

fix: Use actual warningPeriod in certmonitor

---

pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/proxy/apiproxy.go
pkg/agent/tunnel/tunnel.go

Fix bug that caused agents to bypass local loadbalancer
If proxy.SetAPIServerPort was called multiple times, all calls after the first one would cause the apiserver address to be set to the default server address, bypassing the local load-balancer. This was most likely to occur on RKE2, where the supervisor may be up for a longer period of time before it is ready to manage node password secrets, causing the agent to retry. Also, K3s does not ever take the affected code path due to the apiserver and supervisor always using the same port.
I also added some comments to the code as I was stepping through it trying to figure out what's going on.
bugfix
* https://github.com/k3s-io/k3s/issues/10279
* https://github.com/rancher/rke2/issues/5949
```release-note
```

Fix bug that caused agents to bypass local loadbalancer

---

docs/adrs/etcd-s3-secret.md

new feature
See ADR
* Parent issue for integration with Rancher - should switch to provisioning secret and passing env vars when restoring, instead of writing config to disk:
https://github.com/rancher/rancher/issues/44256
* https://github.com/k3s-io/k3s/issues/10291
```release-note
```

Add ADR for support for etcd s3 config secret

---

pkg/etcd/s3.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

- Certificate that the snapshot key doesn't have the folder in it before add the folder in the key value
- Fix
- Setup k3s with the `etcd-s3-folder` flag and wait for the retention to happen
```yaml
cluster-init: true
etcd-s3: true
etcd-snapshot-schedule-cron: '*/1 * * * *'
etcd-snapshot-retention: 5
etcd-s3-bucket: bucket-name
etcd-s3-folder: bucket-folder
etcd-s3-region: bucket-region
etcd-s3-access-key: s3-access-key
etcd-s3-secret-key: s3-secret-key
```
- https://github.com/k3s-io/k3s/issues/10292
```release-note
```

Add snapshot retention etcd-s3-folder fix

---

.github/actions/setup-go/action.yaml

- After several weeks of running with https://github.com/k3s-io/k3s/pull/9495, our GHA cache looks way better.
There is now enough space in the cache to support an additional golang cache. I have chosen the newest release-1.29. Unit test on backports to this branch will now be faster (uncached its about 7min, cached its 2.5min)
CI Improvements
Pull requests on backports to release-1.29 and commits to release-1.29 should now see a usable go cache.
https://github.com/k3s-io/k3s/issues/9494
```release-note
```

Expand GHA golang caching to includ newest release branch

---

pkg/etcd/s3.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

- Issue: https://github.com/k3s-io/k3s/issues/10312
- Bacport from: https://github.com/k3s-io/k3s/pull/10293

[Release-1.28] Add snapshot retention etcd-s3-folder fix

---

pkg/etcd/s3.go
tests/e2e/s3/Vagrantfile
tests/e2e/s3/s3_test.go

- Issue: https://github.com/k3s-io/k3s/issues/10311
- Bacport from: https://github.com/k3s-io/k3s/pull/10293

[Release-1.29] Add snapshot retention etcd-s3-folder fix

---

pkg/agent/config/config_internal_test.go

(cherry picked from commit 043b1eac5d50861d2f4044d7c543c095f3b19838)
```release-note
```

[Backport 1.28]Add test for `isValidResolvConf` (#10302)

---

pkg/agent/config/config_internal_test.go

(cherry picked from commit 043b1eac5d50861d2f4044d7c543c095f3b19838)
```release-note
```

[backport 1.29] Add test for `isValidResolvConf` (#10302)

---

pkg/agent/config/config_internal_test.go

(cherry picked from commit 043b1eac5d50861d2f4044d7c543c095f3b19838)
```release-note
```

[backport 1.27]Add test for `isValidResolvConf` (#10302)

---

pkg/agent/loadbalancer/servers.go

Fix race condition panic in loadbalancer.nextServer
Multiple goroutines may increment the nextServerIndex field at the same time, after its value has been clamped to the size of the list by another goroutine. This leads to an attempt to reference an item past the end of the list.
bugfix
This may be hard to replicate on k3s, as it requires a large number of goroutines dialing connections using a loadbalancer with multiple failed servers in the list.
* https://github.com/k3s-io/k3s/issues/10320
* https://github.com/rancher/rke2/issues/6130
```release-note
```

[release-1.28] Fix race condition panic in loadbalancer.nextServer

---

pkg/agent/loadbalancer/servers.go

Fix race condition panic in loadbalancer.nextServer
Multiple goroutines may increment the nextServerIndex field at the same time, after its value has been clamped to the size of the list by another goroutine. This leads to an attempt to reference an item past the end of the list.
bugfix
This may be hard to replicate on k3s, as it requires a large number of goroutines dialing connections using a loadbalancer with multiple failed servers in the list.
* https://github.com/k3s-io/k3s/issues/10321
* https://github.com/rancher/rke2/issues/6130
```release-note
```

[release-1.27] Fix race condition panic in loadbalancer.nextServer

---

pkg/agent/config/config.go
pkg/agent/https/https.go
pkg/daemons/config/types.go

Fix agent supervisor port using apiserver port instead
The agent's supervisor listener on RKE2 is using the wrong port. Didn't notice it here because they're the same in k3s.
bugfix
Can only be tested in RKE2
* https://github.com/rancher/rke2/issues/5786#issuecomment-2166690541
```release-note
NONE
```

Fix agent supervisor port using apiserver port instead

---

pkg/agent/config/config.go
pkg/agent/https/https.go
pkg/daemons/config/types.go

Fix agent supervisor port using apiserver port instead
The agent's supervisor listener on RKE2 is using the wrong port. Didn't notice it here because they're the same in k3s.
bugfix
Can only be tested in RKE2
* https://github.com/rancher/rke2/issues/6090#issuecomment-2166778093
```release-note
NONE
```

[release-1.29] Fix agent supervisor port using apiserver port instead

---

pkg/agent/config/config.go
pkg/agent/https/https.go
pkg/daemons/config/types.go

Fix agent supervisor port using apiserver port instead
The agent's supervisor listener on RKE2 is using the wrong port. Didn't notice it here because they're the same in k3s.
bugfix
Can only be tested in RKE2
* https://github.com/rancher/rke2/issues/6091#issuecomment-2166778220
```release-note
NONE
```

[release-1.28] Fix agent supervisor port using apiserver port instead

---

pkg/agent/config/config.go
pkg/agent/https/https.go
pkg/daemons/config/types.go

Fix agent supervisor port using apiserver port instead
The agent's supervisor listener on RKE2 is using the wrong port. Didn't notice it here because they're the same in k3s.
bugfix
Can only be tested in RKE2
* https://github.com/rancher/rke2/issues/6092#issuecomment-2166778368
```release-note
NONE
```

[release-1.27] Fix agent supervisor port using apiserver port instead

---

pkg/etcd/etcd.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_handler.go

Replace 1-weight semaphore on snapshots with simple mutex
Fixes an issue where the semaphore wasn't permanently initialized until a scheduled snapshot was taken, allowing multiple on-demand snapshots to be taken until the first scheduled snapshot was triggered.
bugfix
When fixed, you should see:
```console
root@k3s-server-1:~# k3s etcd-snapshot save & k3s etcd-snapshot save; sleep 5
FATA[0000] see server log for details: Internal error occurred: etcd-snapshot error ID 40905
INFO[0000] Snapshot on-demand-k3s-server-1-1718755362 saved.
[1]+  Done(1)                    k3s etcd-snapshot save
```
server log:
```
INFO[0055] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1718755362
{"level":"info","ts":"2024-06-19T00:02:41.544644Z","logger":"etcd-client", …
```

Fix issue that allowed multiple simultaneous snapshots to be allowed

---

pkg/etcd/etcd.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_handler.go

Replace 1-weight semaphore on snapshots with simple mutex
Fixes an issue where the semaphore wasn't permanently initialized until a scheduled snapshot was taken, allowing multiple on-demand snapshots to be taken until the first scheduled snapshot was triggered.
bugfix
When fixed, you should see:
```console
root@k3s-server-1:~# k3s etcd-snapshot save & k3s etcd-snapshot save; sleep 5
FATA[0000] see server log for details: Internal error occurred: etcd-snapshot error ID 40905
INFO[0000] Snapshot on-demand-k3s-server-1-1718755362 saved.
[1]+  Done(1)                    k3s etcd-snapshot save
```
server log:
```
INFO[0055] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1718755362
{"level":"info","ts":"2024-06-19T00:02:41.544644Z","logger":"etcd-client", …
```

[release-1.29] Fix issue that allowed multiple simultaneous snapshots to be allowed

---

pkg/etcd/etcd.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_handler.go

Replace 1-weight semaphore on snapshots with simple mutex
Fixes an issue where the semaphore wasn't permanently initialized until a scheduled snapshot was taken, allowing multiple on-demand snapshots to be taken until the first scheduled snapshot was triggered.
bugfix
When fixed, you should see:
```console
root@k3s-server-1:~# k3s etcd-snapshot save & k3s etcd-snapshot save; sleep 5
FATA[0000] see server log for details: Internal error occurred: etcd-snapshot error ID 40905
INFO[0000] Snapshot on-demand-k3s-server-1-1718755362 saved.
[1]+  Done(1)                    k3s etcd-snapshot save
```
server log:
```
INFO[0055] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1718755362
{"level":"info","ts":"2024-06-19T00:02:41.544644Z","logger":"etcd-client", …
```

[release-1.28] Fix issue that allowed multiple simultaneous snapshots to be allowed

---

pkg/etcd/etcd.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_handler.go

Replace 1-weight semaphore on snapshots with simple mutex
Fixes an issue where the semaphore wasn't permanently initialized until a scheduled snapshot was taken, allowing multiple on-demand snapshots to be taken until the first scheduled snapshot was triggered.
bugfix
When fixed, you should see:
```console
root@k3s-server-1:~# k3s etcd-snapshot save & k3s etcd-snapshot save; sleep 5
FATA[0000] see server log for details: Internal error occurred: etcd-snapshot error ID 40905
INFO[0000] Snapshot on-demand-k3s-server-1-1718755362 saved.
[1]+  Done(1)                    k3s etcd-snapshot save
```
server log:
```
INFO[0055] Saving etcd snapshot to /var/lib/rancher/k3s/server/db/snapshots/on-demand-k3s-server-1-1718755362
{"level":"info","ts":"2024-06-19T00:02:41.544644Z","logger":"etcd-client", …
```

[release-1.27] Fix issue that allowed multiple simultaneous snapshots to be allowed

---

go.mod
go.sum
pkg/agent/tunnel/tunnel.go
pkg/daemons/control/tunnel.go

Ensure that connections to the kubelet through the egress-selector (either local or via remotedialer) use the correct kubelet bind address.
We have long overridden the kubelet address to the loopback address when dialing via the remotedialer tunnel, and ensured that the kubelet always binds to an ipv4 or ipv6 wildcard address. We broke this in https://github.com/k3s-io/k3s/pull/10019 when we wired the --bind-address flag up to the kubelet --address flag by way of the ListenAddress field.
This is blocked on:
bugfix
1. Set `--bind-address` on a server or agent node
2. Note that `kubectl logs` works properly to retrieve logs from pods on that node
* https://github.com/k3s-io/k3s/issues/10444
```release-note
Fixed an issue where setting the `--bind-address` flag to a non-loopback or wildcard …
```

Ensure remotedialer kubelet connections use kubelet bind address

---

.drone.yml

- Automate the upgrade channel instead of hard-coding it like other PRs: https://github.com/k3s-io/k3s/pull/10106
CI still green
N/A
```release-note
```

For E2E upgrade test, automatically determine the channel to use

---

go.mod
go.sum

Bump kine to v0.11.11
https://github.com/k3s-io/kine/compare/v0.11.9...v0.11.11
version bump
check version
* https://github.com/k3s-io/k3s/issues/10495
* https://github.com/k3s-io/kine/issues/305
* https://github.com/rancher/rke2/issues/6176
```release-note
```

Bump kine to v0.11.11

---

pkg/agent/config/config.go
pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/servers.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go

* Fix reentrant rlock in loadbalancer.dialContext
When I added health-checks in https://github.com/k3s-io/k3s/pull/9757 and promoted the loadbalancer mutex to a rwmutex, I also added a readlock call to dialContext since it is accessing the servers list. As dialContext calls nextServer, which also takes a readlock, this can now deadlock if another goroutine attempts to acquire a writelock while dialContext is in its loop. dialContext will hold a readlock, but the goroutine attempting to acquire a writelock will cause nextServer's readlock to block, which prevents the outer readlock from ever being released.
nextServer is only ever called from dialContext, so it doesn't need to take another lock. I should have removed the lock from nextServer when I added it to dialContext.
* Fix agents …

Fix loadbalancer reentrant rlock

---

pkg/cli/cmds/etcd_snapshot.go
pkg/configfilearg/defaultparser_test.go

Don't use server and token values from config file for etcd-snapshot commands
Fixes an issue where running etcd-snapshot commands on a node that has a server address set in the config will manage snapshots on that server, instead of on the local node as intended.
bugfix
* https://github.com/k3s-io/k3s/issues/10513
```release-note
The `--server` and `--token` flags for the `k3s etcd-snapshot` command have been renamed to `--etcd-server` and `--etcd-token`, to avoid unintentionally running snapshot management commands against a remote node when the cluster join address or token are present in a config file.
```

Don't use server value from config file for etcd-snapshot commands

---

.drone.yml
.github/workflows/e2e.yaml
scripts/test

Backports for:
- https://github.com/k3s-io/k3s/pull/10414
- https://github.com/k3s-io/k3s/pull/10461
N/A Testing only changes
```release-note
```

[Release-1.29] July Test Backports

---

pkg/etcd/snapshot.go
pkg/etcd/snapshot_controller.go
pkg/secretsencrypt/controller.go

Use pagination when listing large numbers of resources
etcd snapshots and secrets are the only thing we bulk list, everything else should either have a selector, or there aren't enough resource of that type to matter.
enhancement
See linked issue - note that this requires a LARGE number of snapshots to make a visible difference in memory - at least 100
* https://github.com/k3s-io/k3s/issues/10450
```release-note
```

Use pagination when listing large numbers of resources

---

pkg/cloudprovider/servicelb.go
pkg/cloudprovider/servicelb_test.go
scripts/airgap/image-list.txt

* Fix handling of long service names
* Fix ipv6 sysctl required by non-ipv6 LoadBalancer service
This is a partial revert of https://github.com/k3s-io/k3s/pull/9963, with the workaround for https://github.com/k3s-io/k3s/issues/9949 moved into klipper-lb.
Waiting on: 
bugfix
yes
* https://github.com/k3s-io/k3s/issues/10537
* https://github.com/k3s-io/k3s/issues/10455
```release-note
Fixed issue that caused ServiceLB to fail to create a daemonset for services with long names
Fixed issue that caused ServiceLB pods to crashloop on nodes with ipv6 disabled at the kernel level
```

Fix multiple issues with servicelb

---

tests/docker/test-run-hardened
tests/e2e/vagrantdefaults.rb

- Remove unnecessary config.yaml options
- Add required `tls-cipher-suites` argument to config.yaml
- Rework default of E2E_HARDENED to accept `true` (psa)
- Auto install kube-bench for easier CIS validation
Testing Enhancements
Manually run multiple times when overhauling the K3s CIS profiles
N/A this is just for manual QA
N/A
```release-note
```

Enhance E2E Hardened option

---

pkg/agent/run.go

- Allow pprof and supervisor metrics to run on servers with agent components disabled
Bug fix
- Run K3s server with `--disable-agent --enable-pprof` 
- Launch  a kubectl proxy instance `kubectl proxy`
- Access the pprof profile `go tool pprof -top https://localhost:8001/debug/pprof/profile`
Manually tested
https://github.com/k3s-io/k3s/issues/10582
```release-note
```

Allow Pprof and Superisor metrics in standalone mode

---

pkg/daemons/control/server.go
pkg/secretsencrypt/controller.go

- Use a separate client go for updating secrets, the default wrangler values strangle the throughput of the secrets encryption controller.
Feature Enhancement
Time to reencrypt 1000 "basic" secrets (secrets are simple strings)
```
echo "this is a file" > file.txt && for i in {1..1000}; do echo test$i >> file.txt; kubectl create secret generic test$i --from-file=file.txt; done
```
| Master | PR | 
| - | - | 
| 207s | 4s |
Time to reencrypt 200 "large" secrets (1000K size, aka the maximum secret size)
```
head -c 1000K </dev/urandom  > file.txt && for i in {1..200}; do echo test$i >> file.txt; kubectl create secret generic test$i --from-file=file.txt; done
```
| Master | PR | 
| - | - | 
| 42s | 17s |
Already Covered
https://github.com/k3s-io/k3s/issues/10581
```release-note
```
This …

Use higher QPS for secrets reencryption

---

cmd/k3s/main.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/dropin-only.yaml.d/01-data.yml
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data-ignore-this.txt
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data.yaml
pkg/configfilearg/testdata/invalid-dropin.yaml.d/01-data.yml
pkg/configfilearg/testdata/invalid.yaml

bugfix
Includes tests
* https://github.com/k3s-io/k3s/issues/10589
```release-note
```

Fix issues loading data-dir value from env vars or dropin config files

---

cmd/k3s/main.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/dropin-only.yaml.d/01-data.yml
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data-ignore-this.txt
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data.yaml
pkg/configfilearg/testdata/invalid-dropin.yaml.d/01-data.yml
pkg/configfilearg/testdata/invalid.yaml

*Backport of #10591*
bugfix
Includes tests
* https://github.com/k3s-io/k3s/issues/10592
```release-note
```

[release-1.30] Fix issues loading data-dir value from env vars or dropin config files

---

cmd/k3s/main.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/dropin-only.yaml.d/01-data.yml
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data-ignore-this.txt
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data.yaml
pkg/configfilearg/testdata/invalid-dropin.yaml.d/01-data.yml
pkg/configfilearg/testdata/invalid.yaml

*Backport of #10591*
bugfix
Includes tests
* https://github.com/k3s-io/k3s/issues/10593
```release-note
```

[release-1.29] Fix issues loading data-dir value from env vars or dropin config files

---

cmd/k3s/main.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/dropin-only.yaml.d/01-data.yml
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data-ignore-this.txt
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data.yaml
pkg/configfilearg/testdata/invalid-dropin.yaml.d/01-data.yml
pkg/configfilearg/testdata/invalid.yaml

*Backport of #10591*
bugfix
Includes tests
* https://github.com/k3s-io/k3s/issues/10594
```release-note
```

[release-1.28] Fix issues loading data-dir value from env vars or dropin config files

---

cmd/k3s/main.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/certs.go
pkg/cli/cmds/root.go
pkg/cli/cmds/server.go
pkg/configfilearg/parser.go
pkg/configfilearg/parser_test.go
pkg/configfilearg/testdata/dropin-only.yaml.d/01-data.yml
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data-ignore-this.txt
pkg/configfilearg/testdata/dropin-only.yaml.d/02-data.yaml
pkg/configfilearg/testdata/invalid-dropin.yaml.d/01-data.yml
pkg/configfilearg/testdata/invalid.yaml

*Backport of #10591*
bugfix
Includes tests
* https://github.com/k3s-io/k3s/issues/10595
```release-note
```

[release-1.27] Fix issues loading data-dir value from env vars or dropin config files

---

go.mod
go.sum
pkg/cloudprovider/servicelb.go
pkg/metrics/metrics.go

Wire lasso metrics up to common registerer/gatherer.
This exposes perf metrics for the Lasso controllers embedded in the supervisor.
Waiting on:
enhancement
`kubectl get --raw /metrics | grep lasso`
* https://github.com/k3s-io/k3s/issues/10606
```release-note
```

Wire lasso metrics up to metrics endpoint

---

pkg/proctitle/proctile.go

(cherry picked from commit bf6e8742415b718d78ccc7ebe8eb4525169680dd)
Fix setproctitle wrapper to not always set title to "agent"
Commit was missed from previous round of backports.
bugfix
* https://github.com/k3s-io/k3s/issues/10620
```release-note
```

[release-1.29] Fixing setproctitle function

---

pkg/proctitle/proctile.go

(cherry picked from commit bf6e8742415b718d78ccc7ebe8eb4525169680dd)
Fix setproctitle wrapper to not always set title to "agent"
Commit was missed from previous round of backports.
bugfix
* https://github.com/k3s-io/k3s/issues/10621
```release-note
```

[release-1.28] Fixing setproctitle function

---

pkg/proctitle/proctile.go

(cherry picked from commit bf6e8742415b718d78ccc7ebe8eb4525169680dd)
Fix setproctitle wrapper to not always set title to "agent"
Commit was missed from previous round of backports.
bugfix
* https://github.com/k3s-io/k3s/issues/10622
```release-note
```

[release-1.27] Fixing setproctitle function

---

go.mod
go.sum

bump docker/docker to v25.0.6
module bump
* https://github.com/k3s-io/k3s/issues/10641
```release-note
```

bump docker/docker to v25.0.6

---

go.mod
go.sum

bump docker/docker to v25.0.6
module bump
* https://github.com/k3s-io/k3s/issues/10643
```release-note
```

[release-1.30] bump docker/docker to v25.0.6

---

go.mod
go.sum

bump docker/docker to v25.0.6
module bump
* https://github.com/k3s-io/k3s/issues/10644
```release-note
```

[release-1.29] bump docker/docker to v25.0.6

---

go.mod
go.sum

bump docker/docker to v24.0.10-0.20240723193628-852759a7df45
No v24 release has been tagged with the authz fix, so we have to use an untagged commit from the v24 release branch.
module bump
* https://github.com/k3s-io/k3s/issues/10645
```release-note
```

[release-1.28] bump docker/docker to v24.0.10-0.20240723193628-852759a7df45

---

go.mod
go.sum

bump docker/docker to v24.0.10-0.20240723193628-852759a7df45
No v24 release has been tagged with the authz fix, so we have to use an untagged commit from the v24 release branch.
module bump
* https://github.com/k3s-io/k3s/issues/10646
```release-note
```

[release-1.27] bump docker/docker to v24.0.10-0.20240723193628-852759a7df45

---

pkg/agent/run.go
pkg/daemons/control/server.go
pkg/secretsencrypt/controller.go
tests/docker/test-run-hardened
tests/e2e/vagrantdefaults.rb

Backports:
- https://github.com/k3s-io/k3s/pull/10558
- https://github.com/k3s-io/k3s/pull/10571
- https://github.com/k3s-io/k3s/pull/10576
https://github.com/k3s-io/k3s/issues/10633
https://github.com/k3s-io/k3s/issues/10637
```release-note
```

[Release-1.30] Backports for August 2024

---

pkg/agent/run.go
pkg/secretsencrypt/controller.go
pkg/server/server.go
tests/docker/test-run-hardened
tests/e2e/vagrantdefaults.rb

Backports:
- https://github.com/k3s-io/k3s/pull/10558
- https://github.com/k3s-io/k3s/pull/10571
- https://github.com/k3s-io/k3s/pull/10576
https://github.com/k3s-io/k3s/issues/10639
https://github.com/k3s-io/k3s/issues/10635
```release-note
```

[Release-1.28] Backports for August 2024

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump helm-controller to v0.16.3 to drop Helm v2 support
CVE reduction
Breaking change
When creating a HelmChart with `spec.helmVersion` set to anything other than v3, notice the warning event and failed condition:
```console
brandond@dev01:~$ kubectl describe helmchart -n kube-system apache
Name:         apache
Namespace:    kube-system
Labels:       <none>
Annotations:  helmcharts.cattle.io/managed-by: helm-controller
API Version:  helm.cattle.io/v1
Kind:         HelmChart
Metadata:
Creation Timestamp:  2024-08-01T17:17:56Z
Finalizers:
wrangler.cattle.io/on-helm-chart-remove
Generation:        3
Resource Version:  731
UID:               ad0fc12c-d820-43c8-bf87-bfe84a851cdb
Spec:
Chart:             apache
Helm Version:      v2
Repo:              https://charts.bitnami.com/bitnami
Target …
```

Bump helm-controller to v0.16.3 to drop Helm v2 support

---

pkg/cloudprovider/servicelb.go

Add toleration support to ServiceLB DaemonSet

---

pkg/cloudprovider/servicelb.go

[release-1.30] Add tolerations support for DaemonSet pods

---

pkg/cloudprovider/servicelb.go

[release-1.29] Add tolerations support for DaemonSet pods

---

pkg/cloudprovider/servicelb.go

[release-1.28] Add tolerations support for DaemonSet pods

---

pkg/bootstrap/bootstrap.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/server/cert.go

Fix rotateca validation failures when not touching default self-signed CAs
Also silences warnings about bootstrap fields that are not intended to be handled by CA rotation
bugfix
* https://github.com/k3s-io/k3s/issues/10689
* 
```release-note
```

Fix rotateca validation failures when not touching default self-signed CAs

---

go.mod
go.sum

Bump runc to v1.1.13
version bump
Check version
* https://github.com/k3s-io/k3s/issues/10736
```release-note
```

Bump runc to v1.1.13

---

.github/workflows/trivy.yaml

Once this is merged, it allows user to comment `/trivy` on a PR to trigger a build of K3s and a trivy report
The report is run on an internal GHA
And eventually, the comment edited and replaced with the report
CI
Verified on https://github.com/dereknola/k3s/pull/25
N/A
```release-note
```

Add trivy scanning to PR reports

---

.drone.yml

When a new minor is being developed, there is not yet a new release channel to pull from for the Upgrade test. Fallback to "latest"
CI Fix
Manual tested with `release-1.31` (which currently does not have a release)
N/A
```release-note
```

Cover edge case when on new minor release for E2E upgrade test

---

.github/workflows/trivy.yaml

Fix /trivy action running against target branch instead of PR branch
Ref: https://github.com/actions/checkout/issues/331#issuecomment-1438220926
ci fix
Trigger the action
```release-note
```

Fix /trivy action running against target branch instead of PR branch

---

tests/e2e/privateregistry/privateregistry_test.go

- Launch the private registry container with `--init` so if it becomes a zombie, the container can be killed on cleanup. 
```release-note
```

[E2E] Launch private registry with init

---

channel.yaml

Add channel for v1.31
channel server
```release-note
```
This is why e2e tests are failing for backports to release-v1.31: https://github.com/k3s-io/k3s/pull/10817
```
==> server-0: Invoking: /vagrant/k3s-provisioner.sh
server-0: [INFO]  Finding release for channel v1.31
server-0: [INFO]  Using v1.31 as release
server-0: [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.31/sha256sum-amd64.txt
server-0: [ERROR]  Download failed
```

Add channel for v1.31

---

go.mod
go.sum
scripts/airgap/image-list.txt

Bump helm-controller for skip-verify/plain-http and updated tolerations
version bump
* https://github.com/k3s-io/k3s/issues/10831
* 
```release-note
```

Bump helm-controller for skip-verify/plain-http and updated tolerations

---

pkg/agent/config/config.go
pkg/agent/flannel/flannel.go
pkg/agent/run.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/cloudprovider/instances.go
pkg/daemons/config/types.go

Add support for setting NodeInternalDNS and NodeExternalDNS addresses via stub cloud provider
enhancement
```
k3s server --node-external-dns node.example.com
```
now yields:
As you can see it correctly sets the ExternalDNS address.
* #10848

add node-internal-dns/node-external-dns address pass-through support

---

.github/workflows/trivy.yaml

- Happy report if no High or Critical CVEs found in trivy scan
CI Improvement
https://github.com/dereknola/k3s/pull/26
```release-note
```

Give good report if no CVEs found in trivy

---

tests/integration/flannelipv6masq/flannelipv6masq_int_test.go
tests/integration/integration.go

Add a new integration test to verify k3s works as expected when deploying with `--flannel-ipv6-masq`.
Adds also a log when running the integration test. Otherwise it seems like we are stuck at `waiting to get test lock` when running the test manually
New test
https://github.com/k3s-io/k3s/issues/10419
```release-note
```

Add int test for flannel-ipv6masq

---

tests/e2e/upgradecluster/Vagrantfile
tests/e2e/validatecluster/Vagrantfile

I suggest to add MariaDB to CI testing. 
Change to CI test. 
```release-note
```
I identified where the database type is checked, and added a section for mariadb, but honestly I don't know how to take it further from here. Can I get some tips on how to work on this?

Add MariaDB to CI

---

cmd/k3s/main.go

Maintain a separate dir for CNI binaries so that additional plugins can be installed in a predictable location that does not change every time k3s is upgraded.
enhancement
1. Note that cni bins are now linked under `/var/lib/rancher/k3s/data/cni`
2. Note that `/var/lib/rancher/k3s/data/cni` is now used as `cni_bin` dir in `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`
3. Note that custom CNI plugins (multus) are still usable after upgrading k3s, as the cni_bin dir no longer changes during upgrades. 
See above
* https://github.com/k3s-io/k3s/issues/10869
* https://github.com/k3s-io/k3s/issues/9710#issuecomment-2338626124
```release-note
K3s now uses a stable directory for CNI binaries, which simplifies the installation of additional CNI plugins.
```

Use static CNI bin dir

---

.github/workflows/trivy.yaml

- Before pull the PR, check that a member of the `k3s-dev` team requested the /trivy scan.
- Breakup the workflow to limit permission scope
CI
```release-note
```

Breakup trivy scan and check comment author

---

go.mod
go.sum

Bump kine to v0.13.0
version bump
check version
* https://github.com/k3s-io/k3s/issues/10936
```release-note
Kine has been bumped to v0.13.0. This release includes changes that should enhance performance when using postgres as an external DB. The updated schema will be automatically used for new databases; to migrate to the new schema on existing databases, K3s can be started with the `KINE_SCHEMA_MIGRATION=2` environment variable set.
```

Bump kine to v0.13.0

---

tests/integration/flannelipv6masq/flannelipv6masq_int_test.go
tests/integration/integration.go

Backport: https://github.com/k3s-io/k3s/pull/10440

[Release 1.29] Add int test for flannel-ipv6masq

---

pkg/agent/containerd/config_linux.go

- Use the runtimes default paths and the user path when searching for the runtimes
- Feature
- https://github.com/k3s-io/k3s/issues/10761
```release-note
Runtimes detection will now use $PATH
```
- I think this will be a good idea, since we will also detect runtimes in the entire user path

Add user path to runtimes search

---

pkg/rootless/rootless.go

In our use-case we are running an K3S Agent in a Rootless environment at the end-user's own workstation. This works well (enough), but we also want to provide access to the local folders (through e.g. HostPath volume mounts). But the Agent runs inside the rootless namespace, disallowing read/write access to the actual file-system.
This PR allows the Agent to setup extra "CopyUpDirs" entries, through an environment variable called "K3S_ROOTLESS_COPYUPDIRS". This environment variable can receive a comma-separated list absolute paths, which will be added to the existing list.
This change is non-breaking, fully backwards compatible. It only adds a new feature and a new environment variable. The setup will not start (with a fatal error) if any of the added folders doesn't exist in the host …

Allow configuration of Rootlesskit's CopyUpDirs through an environment variable

---

pkg/etcd/s3/s3.go
pkg/etcd/snapshot.go

Fix race condition when multiple nodes reconcile S3 snapshots
Don't delete s3 etcdsnapshotfiles if they are missing from s3 but less than a minute old, its possible the other node just finished uploading it and the object key has not yet become visible.
This is most easily reproduced when an on-demand etcd snapshot is requested via Rancher, as it triggers simultaneous snapshots on all etcd nodes, and they will all try to reconcile s3 objects against the etcdsnapshotfile list at the same time despite not necessarily having a consistent view of the bucket.
bugfix
* https://github.com/k3s-io/k3s/issues/10989
* https://github.com/rancher/rancher/issues/47339
```release-note
```

Fix race condition when multiple nodes reconcile S3 snapshots

---

pkg/agent/containerd/config_linux.go

- Issue -> https://github.com/k3s-io/k3s/issues/11000
- Backport -> https://github.com/k3s-io/k3s/pull/10953

[Release-1.29] Add user path to runtimes search

---

.github/workflows/integration.yaml
pkg/server/cert.go
scripts/build-tests-sonobuoy
tests/integration/README.md
tests/integration/cacertrotation/cacertrotation_int_test.go
tests/integration/integration.go

Add ca-cert rotation integration test, and fix ca-cert rotation
bugfix, testing
Rotate self-signed or custom CA certs and restart K3s. You should see the following message in the log before restarting, and K3s should restart successfully.
```
Oct 08 22:49:11 systemd-node-1 k3s[539]: time="2024-10-08T22:49:11Z" level=info msg="Using current data for PasswdFile: /var/lib/rancher/k3s/server/cred/passwd"
Oct 08 22:49:11 systemd-node-1 k3s[539]: time="2024-10-08T22:49:11Z" level=info msg="Using current data for IPSECKey: /var/lib/rancher/k3s/server/cred/ipsec.psk"
Oct 08 22:49:11 systemd-node-1 k3s[539]: time="2024-10-08T22:49:11Z" level=info msg="Using current data for EncryptionConfig: "
Oct 08 22:49:11 systemd-node-1 k3s[539]: time="2024-10-08T22:49:11Z" level=info …
```

Add ca-cert rotation integration test, and fix ca-cert rotation

---

tests/e2e/amd64_resource_files/loadbalancer-extTrafficPol.yaml
tests/e2e/amd64_resource_files/loadbalancer-intTrafficPol.yaml
tests/e2e/svcpoliciesandfirewall/Vagrantfile
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/testutils.go

New e2e test to verify services externaltrafficpolicy, internaltrafficpolicy and loadBalancerSourceRanges
New e2e test
Run go test
```release-note
```

Add e2e test which verifies traffic policies and firewall in services

---

go.mod
go.sum
pkg/agent/loadbalancer/loadbalancer.go

Update tcpproxy for import path change
version bump-ish
check import path
* #11024
```release-note
```

Update tcpproxy for import path change

---

tests/e2e/amd64_resource_files/loadbalancer-extTrafficPol.yaml
tests/e2e/amd64_resource_files/loadbalancer-intTrafficPol.yaml
tests/e2e/svcpoliciesandfirewall/Vagrantfile
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/testutils.go

Backport: https://github.com/k3s-io/k3s/pull/10972

[Release 1.28] Add e2e test for advanced fields in services

---

tests/e2e/amd64_resource_files/loadbalancer-extTrafficPol.yaml
tests/e2e/amd64_resource_files/loadbalancer-intTrafficPol.yaml
tests/e2e/svcpoliciesandfirewall/Vagrantfile
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/testutils.go

Backport: https://github.com/k3s-io/k3s/pull/10972

[Release 1.29] Add e2e test for advanced fields in services

---

pkg/rootless/rootless.go

Backport https://github.com/k3s-io/k3s/pull/10386
https://github.com/k3s-io/k3s/issues/11009
```release-note
```

[Release-1.28] Allow additional Rootless CopyUpDirs through K3S_ROOTLESS_COPYUPDIRS

---

go.mod
go.sum

Bump containerd to v1.7.22
version bump
check version
* https://github.com/k3s-io/k3s/issues/11069
```release-note
```

[release-1.30] Bump containerd to v1.7.22

---

go.mod
go.sum

Bump containerd to v1.7.22
version bump
check version
* https://github.com/k3s-io/k3s/issues/11070
```release-note
```

[release-1.29] Bump containerd to v1.7.22

---

go.mod
go.sum

Bump containerd to v1.7.22
version bump
check version
* https://github.com/k3s-io/k3s/issues/11071
```release-note
```

[release-1.28] Bump containerd to v1.7.22

---

pkg/agent/containerd/runtimes.go

Add the nvidia runtime cdi, so that pods can use the GPU with the full functionality
Bugfix
In an env with a GPU and the OS drivers correctly installed, deploy the gpu operator:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
name: gpu-operator
namespace: kube-system
spec:
repo: https://helm.ngc.nvidia.com/nvidia
chart: gpu-operator
targetNamespace: gpu-operator
createNamespace: true
valuesContent: |-
toolkit:
env:
- name: CONTAINERD_SOCKET
value: /run/k3s/containerd/containerd.sock
```
And after some minutes, check that `/var/lib/rancher/rke2/agent/etc/containerd/config.toml` includes the nvidia runtimes at the bottom (both nvidia and nvidia-cdi).
Then create a pod including:
```
runtimeClassName: nvidia
containers:
- image: xxxxxxx
name: xxxxxxx
resources:
limits: …
```

Add the nvidia runtime cdi

---

pkg/agent/containerd/runtimes.go

Backport: https://github.com/k3s-io/k3s/pull/11065
Issue: https://github.com/k3s-io/k3s/issues/11089

[Release 1.30] Add the nvidia runtime cdi

---

pkg/agent/containerd/runtimes.go

Backport: https://github.com/k3s-io/k3s/pull/11065
Issue: https://github.com/k3s-io/k3s/issues/11088

[Release 1.31] Add the nvidia runtime cdi

---

pkg/agent/containerd/runtimes.go

Backport: https://github.com/k3s-io/k3s/pull/11065
Issue: https://github.com/k3s-io/k3s/issues/11090

[Release 1.29] Add the nvidia runtime cdi

---

pkg/agent/containerd/runtimes.go

Backport: https://github.com/k3s-io/k3s/pull/11065
Issue: https://github.com/k3s-io/k3s/issues/11091

[Release 1.28] Add the nvidia runtime cdi

---

.github/workflows/e2e.yaml
.github/workflows/unitcoverage.yaml
docs/adrs/remove-svclb-daemonset.md
pkg/cloudprovider/servicelb.go
scripts/airgap/image-list.txt
updatecli/updatecli.d/klipper-lb.yaml
updatecli/values.yaml

Revert "Make svclb as simple as possible"

---

.github/workflows/e2e.yaml
.github/workflows/unitcoverage.yaml
pkg/cloudprovider/servicelb.go
scripts/airgap/image-list.txt
updatecli/updatecli.d/klipper-lb.yaml
updatecli/values.yaml

Backport https://github.com/k3s-io/k3s/pull/11109
```release-note
```

[Release-1.31] Revert "Make svclb as simple as possible"

---

.github/workflows/e2e.yaml
.github/workflows/unitcoverage.yaml
pkg/cloudprovider/servicelb.go
scripts/airgap/image-list.txt
updatecli/updatecli.d/klipper-lb.yaml
updatecli/values.yaml

Backport https://github.com/k3s-io/k3s/pull/11109
```release-note
```

[Release-1.30] Revert "Make svclb as simple as possible"

---

.drone.yml
.github/actions/vagrant-setup/action.yaml
.github/workflows/e2e.yaml
.github/workflows/unitcoverage.yaml
pkg/flock/flock_unix.go
pkg/flock/flock_unix_test.go

- Fix lsof output for flock utility function. Ubuntu 24.04 moved to a new(ish) version of `lsof` which included https://github.com/lsof-org/lsof/pull/158.
| Old lsof | Newish lsof |
| - | - |
| ![image](https://github.com/user-attachments/assets/c0052630-fbe4-4640-845a-fb39d94c01da) | ![image](https://github.com/user-attachments/assets/ec700b8d-47a2-4cfc-a4b8-5b93ea7cbb45) |
- Fix composite action for libvirt/vagrant installation. Now works on ubuntu-24.04
- Pinned e2e and unit test workflows to ubuntu-24.04 to prevent future disruption (in 2 years I can manually open PRs for ubuntu-26.04) 
```release-note
```

Fix Github Actions for Ubuntu-24.04

---

tests/e2e/scripts/latest_commit.sh

- Check the last 10 commits on a branch when looking for a valid aws commit build. When code freeze comes up, the number of PRs merged causes long build queues, meaning that the last 5 commits may not be available for E2E testing.
- Rework script to use bash array rather than edit a file one line at a time
E2E
N/A internal improvement
```release-note
```

[E2E] Check the last 10 commits for upgrade E2E test

---

cmd/k3s/main.go

Fixes "file exists" error from CNI bins when upgrading k3s

---

cmd/k3s/main.go

bugfix
* https://github.com/k3s-io/k3s/issues/10929
```release-note
```

[release-1.30] Fixes "file exists" error from CNI bins when upgrading k3s

---

cmd/k3s/main.go

bugfix
* https://github.com/k3s-io/k3s/issues/10930
```release-note
```

[release-1.29] Fixes "file exists" error from CNI bins when upgrading k3s

---

cmd/k3s/main.go

bugfix
* https://github.com/k3s-io/k3s/issues/10931
```release-note
```

[release-1.28] Fixes "file exists" error from CNI bins when upgrading k3s

---

tests/e2e/scripts/latest_commit.sh
tests/e2e/scripts/run_tests.sh
tests/e2e/vagrantdefaults.rb

Nightly E2E suite is seeing failures due to limits on GH api calls for the "latest commit". This PR attempts to address this in several ways:
- Allow E2E_RELEASE_VERSION=<commit_SHA> to install a specific commit SHA
- For the nightly test suite. run the `latest_commit.sh` script before all the tests, then pass that commit into each test (reduces API calls from I nodes x J tests to a single API call)
- Allow for an optional authenticated commits request via GH_TOKEN
E2E, CI
Running on the nightly nodes by hand. 
```release-note
```

Reduce the number of GH api request for E2E nightly

---

.github/actions/vagrant-setup/action.yaml

Latest version of vagrant suffers from https://github.com/hashicorp/vagrant/issues/13527, this is affecting all our E2E tests. Pin to 2.4.1 for now.
CI
CI Green
```release-note
```

Pin vagrant to older version to avoid known issue 13527

---

pkg/cli/server/server.go
scripts/build

Set kine EmulatedETCDVersion from embedded etcd version
Fixes issue where kine's reported etcd version was left unset.
bugfix
See linked issue for log messages to check
* https://github.com/k3s-io/k3s/issues/11220
```release-note
```

Set kine EmulatedETCDVersion from embedded etcd version

---

pkg/agent/config/config.go
pkg/agent/containerd/config_linux.go
pkg/agent/templates/templates.go
pkg/agent/templates/templates_linux.go
pkg/cli/cmds/agent.go
pkg/cli/cmds/server.go
pkg/daemons/config/types.go

Add new flag that is passed through to the `device_ownership_from_security_context` parameter in the containerd CRI config. This is not possible to change without providing a complete custom containerd.toml template so we should add a flag for it.
enhancement
* Set flag, verify that param is set in containerd config.
* Verify that feature documented upstream at https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/#see-non-root-containers-using-devices-after-the-fix works when this param is set.
* https://github.com/k3s-io/k3s/issues/11168
```release-note
`device_ownership_from_security_context` can now be enabled in the containerd CRI config by setting the `--nonroot-devices` flag or config key.
```

Add nonroot-devices flag to agent CLI

---

go.mod
go.sum

bump runc to v1.2
version bump
check runc version
* https://github.com/k3s-io/k3s/issues/11211
```release-note
```

Bump runc to v1.2

---

cmd/k3s/main.go
pkg/configfilearg/defaultparser.go
pkg/configfilearg/defaultparser_test.go

Fix MustFindString returning override flags on external CLI commands
External CLI actions cannot short-circuit on --help or --version, so we cannot skip loading the config file if these flags are present when running these wrapped commands. The behavior of just returning the override flag name instead of the requested flag value was breaking data-dir lookup when running wrapped commands.
This was introduced in https://github.com/k3s-io/k3s/pull/7683 - which did not account for some subcommands/wrapped commands needing to be unconditionally extracted out.
bugfix
yes
* https://github.com/k3s-io/k3s/issues/11235
```release-note
```

Fix MustFindString returning override flags on external CLI commands

---

go.mod
go.sum

* Bump containerd to v1.7.23
* Fix repository rewrites not being reflected in auth token scopes
* Rework of rewrites: https://github.com/k3s-io/containerd/commit/c18a4212c76eed6dc52d94c5f48fc6598e140712
* version bump
* bugfix
* Check version
* https://github.com/k3s-io/k3s/issues/11239
```release-note
```

Bump containerd to v1.7.23-k3s1 to fix registry rewrite token scopes

---

pkg/kubectl/main.go

Currently K3s fails to work with the "standalone mode" of oidc-login, where the kube.config file contains an Auth-provider section for the users. Trying to use any subcommand that requires a valid login will fail with the error: 
'error: no Auth Provider found for name "oidc"'
This PR fixes this, and allows the usage of this oidc-login mode for the embedded kubectl library in K3s.
For background info on that oidc-login mode: https://github.com/int128/kubelogin/blob/master/docs/standalone-mode.md
This is a simple one-liner bugfix copied from the upstream kubectl-cli implementation.
Source of the fix: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/kubectl.go#L25
Use an example kube.config like described in the kubelogin documentation:
```
- name: keycloak
user: …
```

Fix the "Standalone"-mode of oidc-login in the wrapped kubectl library

---

scripts/version.sh
tests/e2e/testutils.go

Made with ❤️️ by updatecli
Backport https://github.com/k3s-io/k3s/pull/11282
https://github.com/k3s-io/k3s/issues/11296
https://github.com/k3s-io/k3s/issues/11292
```release-note
```

[Release-1.30]  Bump to latest k3s-root version in scripts/version.sh

---

pkg/configfilearg/defaultparser.go
pkg/configfilearg/defaultparser_test.go

Fix handling of wrapped subcommands when run with a path
https://github.com/k3s-io/k3s/pull/11237 fixed `k3s kubectl --help` and `kubectl --help` but not `/usr/local/bin/k3s kubectl --help` or `/usr/local/bin/kubectl --help`
bugfix
* https://github.com/k3s-io/k3s/issues/11235
```release-note
```

Fix handling of wrapped subcommands when run with a path

---

updatecli/updatecli.d/klipper-helm-and-controller.yaml

Modify the updatecli config so that it updates the version based on latest tag and not based on date
Bugfix
Wait for the script to be executed by updatecli in the next run
```release-note
```

Fix updatecli config for klipper and helm-controller

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/util/apierrors.go

bugfix
yes
* https://github.com/k3s-io/k3s/issues/11311
* https://github.com/k3s-io/k3s/issues/10505
* https://github.com/rancher/rancher/issues/48050
```release-note
```

Fix issue with loadbalancer failover to default server

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/util/apierrors.go

bugfix
yes
* https://github.com/k3s-io/k3s/issues/11320
```release-note
```

[release-1.31] Fix issue with loadbalancer failover to default server

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/util/apierrors.go

bugfix
yes
* https://github.com/k3s-io/k3s/issues/11321
```release-note
```

[release-1.30] Fix issue with loadbalancer failover to default server

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/util/apierrors.go

bugfix
yes
* https://github.com/k3s-io/k3s/issues/11322
```release-note
```

[release-1.29] Fix issue with loadbalancer failover to default server

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/agent/loadbalancer/loadbalancer_test.go
pkg/agent/loadbalancer/servers.go
pkg/agent/loadbalancer/utility.go
pkg/util/apierrors.go

bugfix
yes
* https://github.com/k3s-io/k3s/issues/11323
```release-note
```

[release-1.28] Fix issue with loadbalancer failover to default server

---

tests/integration/README.md

Small PR - fixes the `localstorage_int_test.go` reference in `tests/integration/README.md`.
Docs
Check the document
```release-note
Update `localstorage_int_test.go` reference in `tests/integration/README.md`
```

Update `localstorage_int_test.go` reference

---

go.mod

We introduced the `go toolchain` line in https://github.com/k3s-io/k3s/pull/11277, however this line causes issues with the GHA go install action and introduces another level of confusion. 
Everything is still green across CI and manual testing. 
```release-note
```

Remove the go toolchain line

---

tests/e2e/README.md

- Add a shell command for install necessary dependencies for vagrant in ubuntu 24.04
- Docs enhancement 
- try installing qemu
```shell
sudo apt install qemu
```
- now install qemu with the right package
```shell
sudo apt install qemu-kvm
```
```release-note
```

Add ubuntu 24.04 apt command for e2e test

---

.github/workflows/e2e.yaml
go.mod
scripts/test
tests/docker/basics/basics_test.go
tests/docker/bootstraptoken/bootstraptoken_test.go
tests/docker/cacerts/cacerts_test.go
tests/docker/etcd/etcd_test.go
tests/docker/lazypull/lazypull_test.go
tests/docker/resources/snapshot-test.yaml
tests/docker/resources/volume-test.yaml
tests/docker/skew/skew_test.go
tests/docker/test-helpers.go
tests/docker/upgrade/upgrade_test.go

The current [docker tests ](https://github.com/k3s-io/k3s/tree/master/tests/docker) use a complex series of bash function hooks to construct k3s cluster out of docker containers, using the `rancher/k3s` image we publish. These tests are difficult to read, difficult to write, and do not match the ginkgo/gomega centric BDD testing frameworks we have constructed for integration and E2E tests.
- Convert the old docker tests to use Ginkgo/Gomega BDD testing framework. This framework is currently similar but separate from E2E and Integration frameworks. Future work is to potentially combine all 3 frameworks where it makes sense. 
- Precompile Go tests binaries during a separate build job to speed of the actual running of the tests. This runs in parallel with the Building of the k3s binary and …

Convert legacy docker tests from bash to golang

---

.github/workflows/e2e.yaml
tests/docker/etcd/etcd_test.go
tests/docker/test-helpers.go

- Add more logic and checks around determining parent branch name for Docker Upgrade and Skew tests.
- Extend timeout for etcd split role docker test, 5 nodes takes more than 60s
CI Test Fix
CI is green. 
Note that this branch is specifically prefixed with `dependabot` to simulate a typical dependabot branch name. 
Additionally, this PR is from a branch on k3s-io not from my personal fork, just like the bots make.
https://github.com/k3s-io/k3s/actions/runs/12039503425
https://github.com/k3s-io/k3s/issues/11374
```release-note
```

Fix Branch Name logic for Dependabot and UpdateCLI pushes to k3s-io

---

pkg/cluster/managed.go
tests/e2e/snapshotrestore/snapshotrestore_test.go

This PR does two things:
1 - Fixes the e2e test doing backup/restore from a snapshot. It was failing with:
```
FATA[0000] cannot perform cluster-reset while server URL is set - remove server from configuration before resetting
```
When comparing the steps it was following and the documentation, it was indeed wrong. The rest of the servers don't have to run `--cluster-reset`. When removing the step `Resets non bootstrap nodes`, the e2e test works again
2 - I must confess that I wasted an hour trying to use `k3s etcd-snapshot` in a k3s cluster that was not using etcd. When doing that, the error we get is super confusing:
```
FATA[0000] see server log for details: Unauthorized
```
However, there is nothing in the logs. The problem is that we are treating a 404 (url does not exist) as …

Fix etcd backup/restore test and add guardrail for etcd-snapshot

---

go.mod
go.sum
tests/e2e/privateregistry/Vagrantfile
tests/e2e/privateregistry/privateregistry_test.go

Bump containerd to fix rewrites
* The container bump in https://github.com/k3s-io/k3s/pull/11238 did not handle all cases where registry references needed to be rewritten - this is fixed in https://github.com/k3s-io/containerd/commit/d157daba6497d98750949b4f77747b96dde92f91
version bump / bugfix / ci
* Check e2e test results
Yes
```release-note
```

Bump containerd to -k3s2 to fix rewrites

---

go.mod
go.sum
tests/e2e/privateregistry/Vagrantfile
tests/e2e/privateregistry/privateregistry_test.go

Bump containerd to fix rewrites
* The container bump in https://github.com/k3s-io/k3s/pull/11238 did not handle all cases where registry references needed to be rewritten - this is fixed in https://github.com/k3s-io/containerd/commit/d157daba6497d98750949b4f77747b96dde92f91
version bump / bugfix / ci
* Check e2e test results
Yes
* https://github.com/k3s-io/k3s/issues/11256
```release-note
```

[release-1.31] Bump containerd to -k3s2 to fix rewrites

---

go.mod
go.sum
tests/e2e/privateregistry/Vagrantfile
tests/e2e/privateregistry/privateregistry_test.go

Bump containerd to fix rewrites
* The container bump in https://github.com/k3s-io/k3s/pull/11238 did not handle all cases where registry references needed to be rewritten - this is fixed in https://github.com/k3s-io/containerd/commit/d157daba6497d98750949b4f77747b96dde92f91
version bump / bugfix / ci
* Check e2e test results
Yes
* https://github.com/k3s-io/k3s/issues/11257
```release-note
```

[release-1.30] Bump containerd to -k3s2 to fix rewrites

---

go.mod
go.sum
tests/e2e/privateregistry/Vagrantfile
tests/e2e/privateregistry/privateregistry_test.go

Bump containerd to fix rewrites
* The container bump in https://github.com/k3s-io/k3s/pull/11238 did not handle all cases where registry references needed to be rewritten - this is fixed in https://github.com/k3s-io/containerd/commit/d157daba6497d98750949b4f77747b96dde92f91
version bump / bugfix / ci
* Check e2e test results
Yes
* https://github.com/k3s-io/k3s/issues/11258
```release-note
```

[release-1.29] Bump containerd to -k3s2 to fix rewrites

---

tests/install/opensuse-leap/Vagrantfile

- Around 2 months ago, nightly started failing for opensuse leap 15.6. For some reason newer images of this VM don't come with `procps` package installed, which is needed for basic utilities like `ps`.
Test fix
opensuse-leap install test now passes
N/A internal CI fix
```release-note
```

Fix opensuse-leap install test

---

pkg/server/secrets-encrypt.go
tests/e2e/splitserver/Vagrantfile

- When running `k3s secrets-encrypt reencrypt`, once the `reencrypt-active` annotation has been written, run the actual secrets updates in a go routine, allowing the http statusOK response to return in the 10s window. 
- Fixed missing OS definitions for agents in split-role vagrantfile. Found while trying to replicate above issue. 
Either have a slow cluster, or use large secrets. Either way, you need to have reencryption take more than 10 seconds.
I used  1000, 100k size secrets on a single node and could hit the 10s limit (4vcpu, 4GB)
```
head -c 100K </dev/urandom  > file.txt && for i in {1..1000}; do echo test$i >> file.txt; kubectl create secret generic test$i --from-file=file.txt; done
```
With this change, `k3s secrets-encrypt reencrypt` should return with no errors within 1-3 …

Fix secrets-encrypt reencrypt timeout error

---

pkg/server/secrets-encrypt.go
tests/e2e/splitserver/Vagrantfile

Backport https://github.com/k3s-io/k3s/pull/11385
https://github.com/k3s-io/k3s/issues/11439
```release-note
```

[Release-1.29] Fix secrets-encrypt reencrypt timeout error

---

pkg/server/secrets-encrypt.go
tests/e2e/splitserver/Vagrantfile

Backport https://github.com/k3s-io/k3s/pull/11385
https://github.com/k3s-io/k3s/issues/11437
```release-note
```

[Release-1.31] Fix secrets-encrypt reencrypt timeout error

---

pkg/server/secrets-encrypt.go
tests/e2e/splitserver/Vagrantfile

Backport https://github.com/k3s-io/k3s/pull/11385
https://github.com/k3s-io/k3s/issues/11438
```release-note
```

[Release-1.30] Fix secrets-encrypt reencrypt timeout error

---

pkg/cli/cmds/server.go

- Move Spegel (embedded-registry) to GA status in CLI. Docs will be update according to note it went GA in December 2024 releases.
CLI
k3s server --help shows `embedded-registry` no longer has the `experimental` tag
TBD
```release-note
```

Remove experimental from embedded-registry flag

---

pkg/cli/cmds/server.go

Backport https://github.com/k3s-io/k3s/pull/11443
- Move Spegel (embedded-registry) to GA status in CLI. Docs will be update according to note it went GA in December 2024 releases.
CLI
k3s server --help shows `embedded-registry` no longer has the `experimental` tag
TBD
```release-note
```

[Release-1.31] Remove experimental from embedded-registry flag

---

pkg/cli/cmds/server.go

Backport https://github.com/k3s-io/k3s/pull/11443
- Move Spegel (embedded-registry) to GA status in CLI. Docs will be update according to note it went GA in December 2024 releases.
CLI
k3s server --help shows `embedded-registry` no longer has the `experimental` tag
TBD
```release-note
```

[Release-1.30]  Remove experimental from embedded-registry flag

---

pkg/cli/cmds/server.go

Backport https://github.com/k3s-io/k3s/pull/11443
- Move Spegel (embedded-registry) to GA status in CLI. Docs will be update according to note it went GA in December 2024 releases.
CLI
k3s server --help shows `embedded-registry` no longer has the `experimental` tag
TBD
```release-note
```

[Release-1.29] Remove experimental from embedded-registry flag

---

pkg/agent/tunnel/tunnel.go
pkg/cli/cmds/server.go
tests/e2e/startup/startup_test.go
tests/e2e/testutils.go

Fix issue where rke2 tunnel was trying to connect to apiserver port instead of supervisor:
Note the incorrect port for the tunnel connection in RKE2 where the apiserver and supervisor are on different ports:
```
time="2024-12-06T20:35:57Z" level=info msg="Started tunnel to 172.17.0.2:6443"
time="2024-12-06T20:35:57Z" level=info msg="Stopped tunnel to 127.0.0.1:9345"
time="2024-12-06T20:35:57Z" level=info msg="Connecting to proxy" url="wss://172.17.0.2:6443/v1-rke2/connect"
time="2024-12-06T20:35:57Z" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:9345/v1-rke2/connect"
time="2024-12-06T20:35:57Z" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
time="2024-12-06T20:35:57Z" level=error msg="Failed to …
```

Fix agent tunnel address with dedicated supervisor port

---

cmd/agent/main.go
cmd/k3s/main.go
cmd/server/main.go
go.mod
pkg/agent/config/config.go
pkg/daemons/agent/agent.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go
pkg/daemons/config/types.go
pkg/etcd/etcd.go
tests/e2e/s3/s3_test.go
tests/e2e/startup/startup_test.go
tests/integration/integration.go
tests/integration/startup/startup_int_test.go

Switch to using kubelet config file for all supported flags
enhancement / tech debt
* https://github.com/k3s-io/k3s/issues/2116
```release-note
```
Currently using a hacky string replace when marshaling the config file to work around an upstream issue:
* https://github.com/kubernetes/kubernetes/issues/79421

Switch to using kubelet config file for all supported flags

---

pkg/cli/cmds/server.go

This update is based on the related PR/MR: [rancher/rke2-docs#303](https://github.com/rancher/rke2-docs/pull/303).
While the RKE2/K3s clusterDNS variable (cluster-dns) supports both IPv4 and IPv6, the current documentation does not explicitly mention the option to use an IPv6 address for the cluster DNS. Users can configure the cluster DNS to use an IPv4, IPv6, or dual-stack address, as supported by the [relevant script logic](https://github.com/rancher/rke2/blob/9255fd8fa411695fc93573a6e6dfa9470e13e938/scripts/validate-charts#L54).
Add explicit documentation for IPv6 support in the ClusterDNS usage section, highlighting its capability to handle IPv6 addresses.
The ClusterDNS can be configured to use IPv4/IPv6 addresses based on the CIDRs specified in config.yaml. By default, the IPv4 …

add IPv6 to cluster-dns Usage Docs

---

pkg/agent/syssetup/setup.go

Issue: https://github.com/k3s-io/k3s/issues/11525
```release-note
```

Load nft modules at startup

---

.github/workflows/e2e.yaml
tests/e2e/btrfs/btrfs_test.go
tests/e2e/embeddedmirror/embeddedmirror_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/s3/s3_test.go
tests/e2e/startup/startup_test.go
tests/e2e/testutils.go
tests/e2e/wasm/wasm_test.go

- Upload journald logs of each node as a GHA artifact on E2E test failure. An improvement over just dumping it into the output.
- Improved logic for forks when running the go docker tests in determining the "parent" branch that a PR comes from.
See this run, where WASM and Private registry E2E tests were purposely failed. Note the available log artifacts
https://github.com/dereknola/k3s/actions/runs/12602264364
Its all testing
```release-note
```

Upload E2E logs on failure as GHA artifacts

---

pkg/cli/cert/cert.go
pkg/cli/cmds/certs.go
tests/integration/certrotation/certrotation_int_test.go

- Adds coverage of the `k3s certificate check` CLI in testing. 
- Adds "--output table" format for cert check
```
derek@degion:~/rancher/k3s$ sudo ./dist/artifacts/k3s certificate check -o table
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/028414f76580c17e66747d4743a4ad51a705efcdc49cb61e619bdfb975acdb01 
INFO[0000] Server detected, checking agent and server certificates 
CERTIFICATE                      SUBJECT                                    STATUS  EXPIRES
-----------                      -------                                    ------  -------
client-admin.crt                 CN=system:admin,O=system:masters           OK      2025-12-20T19:55:36Z
client-admin.crt                 CN=k3s-client-ca@1734724536 …
```

Add "k3s certificate check" clause for better test coverage

---

tests/docker/skew/skew_test.go

- Release-1.32 tests now skip as intended
- Semver for older release branches now correct finds previous version
Test fix
Tests pass when run manually with older branches
Seen in https://github.com/k3s-io/k3s/actions/runs/12643149990/job/35264904033
```release-note
```

Fix skew semver for release-XX branches

---

.github/workflows/e2e.yaml
docs/adrs/add-auto-import-containerd.md
docs/adrs/add-auto-import-embedded-registry.md
go.mod
pkg/agent/containerd/containerd.go
pkg/agent/containerd/watcher.go
tests/e2e/autoimport/Vagrantfile
tests/e2e/autoimport/autoimport_test.go

- ADR
- Auto import images form .txt files and tar files
- New Feature
- run a k3s server
```shell
k3s server
```
- create the images folder
```shell
mkdir /var/lib/rancher/k3s/agent/images
```
- create a .txt file and add a docker.io image path to the .txt file
```shell
docker.io/library/mysql:latest
```
- move the file to /var/lib/rancher/k3s/agent/images
```shell
cp example.txt /var/lib/rancher/k3s/agent/images
```
- then see if the file was imported in the containerd image store
```shell
k3s ctr images list | grep "mysql"
```
- you can also change the file inside var/lib/rancher/k3s/agent/images
```shell
nano /var/lib/rancher/k3s/agent/images/example.txt
```
- then you can add 
```shell
docker.io/library/redis:latest
```
- the controller will see the change and then import the redis …

Auto import images for containerd image store

---

go.mod
go.sum

bump runc to v1.2.4
version bump
* Check version
* Look for log messages to be absent
* https://github.com/k3s-io/k3s/issues/11503
```release-note
```

Bump runc to v1.2.4

---

pkg/cluster/managed.go
tests/e2e/snapshotrestore/snapshotrestore_test.go

Backport: https://github.com/k3s-io/k3s/pull/11314
Issue: https://github.com/k3s-io/k3s/issues/11390
FOR JANUARY RELEASE

[Release 1.30] Add guardrail for etcd-snapshot

---

pkg/cluster/managed.go
tests/e2e/snapshotrestore/snapshotrestore_test.go

Backport: https://github.com/k3s-io/k3s/pull/11314
Issue: https://github.com/k3s-io/k3s/issues/11391
FOR JANUARY RELEASE

[Release 1.29] Add a guardrail for etcd-snapshot

---

pkg/agent/flannel/setup.go
pkg/util/api.go

Only wait for k3s-controller RBAC when AuthorizeNodeWithSelectors blocks kubelet from listing nodes.
This allows agents to use whichever client allows flannel to list/watch nodes. If the feature-gate does not block access to nodes, then the kubelet kubeconfig will be used as in older releases. If it does block access, then we will wait for k3s-controller RBAC to be created and use that instead.
This is a forward-port of the compat changes being made to the  <= v1.31 branches, where agents will need to support servers that may or may not have the updated k3s-controller RBAC.
compat fix
see compat tests in CI
yes
```release-note
```

Improve flannel RBAC changes

---

pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go

The CLI documentation (i.e. `--help` output) should be a reliable source of truth for the end user. This PR ensures that the default etcd snapshot location matches the expectations that are being set by the CLI. It updates the `--etcd-snapshot-dir` option's description to match the effective default snapshot path (one that will be used by the `server`).
Bugfix, a simple update to the `--etcd-snapshot-dir` option descriptions for the `server` and `etcd-snapshot` commands.
This section is mostly based on the reproduction steps from https://github.com/k3s-io/k3s/issues/11570
1. Run `k3s server --help | grep '\-dir'`.
2. Ensure the reported default value for `--etcd-snapshot-dir` matches `${data-dir}/server/db/snapshots`. That's been confirmed to be the actual path in the issue's analysis.
3. …

Align etcd-snapshot-dir default path description

---

.github/workflows/e2e.yaml
pkg/cli/cert/cert.go
pkg/cli/cmds/certs.go
tests/e2e/btrfs/btrfs_test.go
tests/e2e/embeddedmirror/embeddedmirror_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/s3/s3_test.go
tests/e2e/startup/startup_test.go
tests/e2e/testutils.go
tests/e2e/wasm/wasm_test.go
tests/integration/certrotation/certrotation_int_test.go

Backports of 
- https://github.com/k3s-io/k3s/pull/11485
- https://github.com/k3s-io/k3s/pull/11514
https://github.com/k3s-io/k3s/issues/11575
https://github.com/k3s-io/k3s/issues/11579
```release-note
```

[Release-1.32] 2025 January Backports

---

.github/workflows/e2e.yaml
Dockerfile.local
Dockerfile.test
go.mod
pkg/cli/cert/cert.go
pkg/cli/cmds/certs.go
scripts/test
tests/docker/basics/basics_test.go
tests/docker/bootstraptoken/bootstraptoken_test.go
tests/docker/cacerts/cacerts_test.go
tests/docker/etcd/etcd_test.go
tests/docker/lazypull/lazypull_test.go
tests/docker/resources/snapshot-test.yaml
tests/docker/resources/volume-test.yaml
tests/docker/skew/skew_test.go
tests/docker/test-helpers.go
tests/docker/upgrade/upgrade_test.go
tests/e2e/btrfs/btrfs_test.go
tests/e2e/embeddedmirror/embeddedmirror_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/s3/s3_test.go
tests/e2e/startup/startup_test.go
tests/e2e/testutils.go
tests/e2e/wasm/wasm_test.go
tests/install/opensuse-leap/Vagrantfile
tests/integration/certrotation/certrotation_int_test.go

Backports of 
- https://github.com/k3s-io/k3s/pull/11357
- https://github.com/k3s-io/k3s/pull/11379
- https://github.com/k3s-io/k3s/pull/11474
- https://github.com/k3s-io/k3s/pull/11485
- https://github.com/k3s-io/k3s/pull/11514
- https://github.com/k3s-io/k3s/pull/11531
https://github.com/k3s-io/k3s/issues/11580
https://github.com/k3s-io/k3s/issues/11585
https://github.com/k3s-io/k3s/issues/11576
```release-note
```

[Release-1.31] 2025 January Backports

---

pkg/agent/syssetup/setup.go

[release-1.30] Load kernel modules for nft in agent setup

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

bugfix
* go test
Yes
* https://github.com/k3s-io/k3s/issues/11477
* https://github.com/rancher/security-team/issues/1097 …

Fix local password validation when bind-address is set

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

* Backport https://github.com/k3s-io/k3s/pull/11607
bugfix
* go test
Yes
* https://github.com/k3s-io/k3s/issues/11539
* …

[release-1.32] Fix local password validation when bind-address is set

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

* Backport https://github.com/k3s-io/k3s/pull/11607
bugfix
* go test
Yes
* https://github.com/k3s-io/k3s/issues/11540
* …

[release-1.31] Fix local password validation when bind-address is set

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

* Backport https://github.com/k3s-io/k3s/pull/11607
bugfix
* go test
Yes
* https://github.com/k3s-io/k3s/issues/11541
* …

[release-1.30] Fix local password validation when bind-address is set

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

* Backport https://github.com/k3s-io/k3s/pull/11607
bugfix
* go test
Yes
* https://github.com/k3s-io/k3s/issues/11542
* …

[release-1.29] Fix local password validation when bind-address is set

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

Remove local restriction for deferred node password validation
Restricting deferred node password validation to only requests from the local node is not possible without breaking split-role cluster cold start. There are too many cases where node password secrets may not yet be available due to the apiserver not being up.
This was added in response to https://github.com/rancher/security-team/issues/1097#issuecomment-2575374965 but turns out to not be something we can actually lock down without breaking things.
regression fix
TODO - need to add a split-role test that mimics rancher's order of operations. For split-role clusters, rancher waits for all etcd nodes to start containerd, kubelet, and etcd before joining control-plane nodes.
Tracking this in: …

Remove local restriction for deferred node password validation

---

pkg/nodepassword/validate.go
pkg/server/handlers/handlers_test.go

Remove local restriction for deferred node password validation
Restricting deferred node password validation to only requests from the local node is not possible without breaking split-role cluster cold start. There are too many cases where node password secrets may not yet be available due to the apiserver not being up.
This was added in response to https://github.com/rancher/security-team/issues/1097#issuecomment-2575374965 but turns out to not be something we can actually lock down without breaking things.
regression fix
TODO - need to add a split-role test that mimics rancher's order of operations. For split-role clusters, rancher waits for all etcd nodes to start containerd, kubelet, and etcd before joining control-plane nodes.
Tracking this in: …

[release-1.30] Remove local restriction for deferred node password validation

---

pkg/etcd/s3/s3.go

Disable s3 transport transparent compression/decompression
bugfix
Cannot really verify this one as the issue only occurs on a specific vendor's S3 implementation, and there is no free version available. We can verify that it doesn't regress other users though.
https://github.com/k3s-io/k3s/issues/11603
```release-note
```

Disable s3 transport transparent compression/decompression

---

pkg/cli/cmds/token.go

The `k3s token` CLI has 5 verbs. 4 relate to bootstrap tokens and 1 is about server tokens (rotate). Based on that, this PR removes some potential confusion in the CLI help by:
* Removing the word "bootstrap" from the general usage description of the tool
* Replacing "bootstrap" by "server" in the description of the "rotate" verb
Bugfix
Execute `k3s token` command and verify that the help description has this PR' changes
https://github.com/k3s-io/k3s/issues/11674
```release-note
```

Correct the k3s token command help

---

go.mod
go.sum
pkg/cli/cmds/etcd_snapshot.go
pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/daemons/config/types.go
pkg/etcd/s3/config_secret.go
pkg/etcd/s3/s3.go
pkg/etcd/snapshot/types.go

Add support for AWS shared credentials file
Also adds a CLI flag and fields for session token, which must be passed alongside the access key and secret when using temporary credentials. Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list-AWS_SESSION_TOKEN
enhancement
Use shared credentials file (`~/.aws/credentials`) for S3:
1. Run `aws configure` as root
2. Enter access and secret key
3. Confirm that values are written to default profile in /root/.aws/credentials
4. Start K3s and save snapshots to S3 - you will need to specify the bucket and folder but NOT the access or secret key.
* https://github.com/k3s-io/k3s/issues/11609
```release-note
etcd snapshot backup/restore now supports loading s3 credentials from an AWS SDK shared credentials file. …
```

Add support for AWS shared credentials file

---

Dockerfile.test

- Implement workaround to handle ttps://github.com/vagrant-libvirt/vagrant-libvirt/issues/1840 and  https://github.com/hashicorp/vagrant/issues/13571. For now we will manually download and install the ubuntu boxes used for E2E testing
CI fixes
Drone E2E passes again
```release-note
```

Fix e2e pipeline due to vagrant cloud infra issues

---

.github/workflows/build-k3s.yaml
.github/workflows/e2e.yaml
scripts/test
tests/docker/skew/skew_test.go
tests/docker/upgrade/upgrade_test.go

- Build both arm64 and amd64 versions of k3s artifacts in GHA
-  Implement Docker Go Tests as a matrix of both Arm64 and Amd64 architectures. 
- Consolidate Drone tests down to only be PR for arm (32bit) and tagging events (for publishing).
- Reduce failures for Skew and Upgrade tests on forks by moving away from git branch to a channel based flag (git history is too inconsistent on GHA runners and just source ./script/version.sh is easier)
Testing Overhaul
CI is green
**THIS ALL RUNS IN 5m 38s**
Its all testing
https://github.com/k3s-io/k3s/issues/11704
```release-note
```

Run Docker test on Github Actions arm64 runners

---

scripts/test
tests/docker/conformance/conformance_test.go
tests/docker/test-helpers
tests/docker/test-helpers.go
tests/docker/upgrade/upgrade_test.go
tests/e2e/btrfs/btrfs_test.go

- Convert the sonobuoy docker bash tests into the new go docker framework. Replaced sonobuoy with [hydrophone](https://github.com/kubernetes-sigs/hydrophone). Hydrophone has the advantage of being a ginkgo wrapper around the compiled suite of upstream tests, so we can pipe its output directly into our `GinkgoWriter`, effectively giving us both our BDD level of `It/Context` statements and the conformance `It/Context` statements at a single output level. 
- Replace ONLY the etcd and sqlite versions of sonobuoy for now, and only on the CRON Drone events, I tested these manually, but it takes a long time and I want to see consistent nightly conformance pass before all of the tests. I also am not touching the TAG events, I don't want to break releases.
- Replace more of the old docker tests in …

Convert docker conformance test to go test framework

---

tests/e2e/testutils.go
tests/e2e/wasm/wasm_test.go

Fix e2e ingress IP helper
Fix the helper to return an error if the ingress doesn't have any IPs yet, and add an Eventually in the test to avoid race condition. Just because the ingress has been deployed doesn't mean that traefik has sync'd it yet.
e2e bugfix
Check CI
```release-note
```

Fix e2e ingress IP helper

---

package/Dockerfile

Static bin dir is first in search path and is on /var/lib/rancher/k3s volume, which can be persisted by users. If the volume is empty it will just fall back to the legacy /bin dir.
enhancement
* Check config.toml when running k3s docker image:
```
[plugins.'io.containerd.cri.v1.runtime'.cni]
bin_dir = "/var/lib/rancher/k3s/data/cni"
```
Covered by docker tests
* https://github.com/k3s-io/k3s/issues/11497
```release-note
```

Add static bin dir support to k3s docker image

---

pkg/agent/loadbalancer/loadbalancer.go
pkg/etcd/snapshot.go
pkg/etcd/snapshot_metrics.go
pkg/metrics/metrics.go
pkg/util/metrics/metrics.go

Add etcd snapshot metrics:
```
```
Note that the total number of ETCDSnapshotFile resources present does NOT have a metric here - that can already be queried from apiserver storage object count metrics:
`apiserver_storage_objects{resource="etcdsnapshotfiles.k3s.cattle.io"} 1`
enhancement
Check metrics on etcd node:
```console
brandond@dev01:~$ kubectl get --raw /metrics | grep 'etcd_snapshot_.*_count'
k3s_etcd_snapshot_reconcile_duration_seconds_count{status="success"} 9
k3s_etcd_snapshot_reconcile_local_duration_seconds_count{status="success"} 11
k3s_etcd_snapshot_reconcile_s3_duration_seconds_count{status="error"} 9
k3s_etcd_snapshot_save_duration_seconds_count{status="success"} 1
k3s_etcd_snapshot_save_local_duration_seconds_count{status="success"} 1 …
```

Add etcd snapshot metrics

---

pkg/agent/templates/templates.go
tests/e2e/dualstack/dualstack_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/splitserver/splitserver_test.go
tests/e2e/startup/startup_test.go
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/validatecluster_test.go
tests/e2e/wasm/wasm_test.go

* Render CNI dir config whenever vars are set
* Fix registry auth plugin name in containerd v2.0 config template
Was missed when migrating plugin names, and apparently we don't have a test that covers authenticated image pulls.
regression fix
* Test pulling images from a mirror that requires auth
* Test RKE2 in Windows.
* https://github.com/k3s-io/k3s/issues/11826
* https://github.com/rancher/rke2/issues/7793
* …

Render CNI dir config whenever vars are set

---

pkg/agent/templates/templates.go
tests/e2e/dualstack/dualstack_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/splitserver/splitserver_test.go
tests/e2e/startup/startup_test.go
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/validatecluster_test.go
tests/e2e/wasm/wasm_test.go

* Render CNI dir config whenever vars are set
* Fix registry auth plugin name in containerd v2.0 config template
Was missed when migrating plugin names, and apparently we don't have a test that covers authenticated image pulls.
regression fix
* Test pulling images from a mirror that requires auth
* Test RKE2 in Windows.
* https://github.com/k3s-io/k3s/issues/11826
* https://github.com/rancher/rke2/issues/7793
* …

[release-1.32] Render CNI dir config whenever vars are set

---

pkg/agent/templates/templates.go
tests/e2e/dualstack/dualstack_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/splitserver/splitserver_test.go
tests/e2e/startup/startup_test.go
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/validatecluster_test.go
tests/e2e/wasm/wasm_test.go

* Render CNI dir config whenever vars are set
* Fix registry auth plugin name in containerd v2.0 config template
Was missed when migrating plugin names, and apparently we don't have a test that covers authenticated image pulls.
rke2 windows regression fix
* Test pulling images from a mirror that requires auth
* Test RKE2 in Windows.
* https://github.com/k3s-io/k3s/issues/11826
* …

[release-1.31] Render CNI dir config whenever vars are set

---

pkg/agent/templates/templates.go
tests/e2e/dualstack/dualstack_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/splitserver/splitserver_test.go
tests/e2e/startup/startup_test.go
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/validatecluster_test.go
tests/e2e/wasm/wasm_test.go

Render CNI dir config whenever vars are set
rke2 windows regression fix
Test RKE2 in Windows.
TODO on rke2 side.
https://github.com/rancher/rke2/issues/7793
```release-note
```

[release-1.30] Render CNI dir config whenever vars are set

---

pkg/agent/templates/templates.go
tests/e2e/dualstack/dualstack_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/privateregistry/privateregistry_test.go
tests/e2e/splitserver/splitserver_test.go
tests/e2e/startup/startup_test.go
tests/e2e/svcpoliciesandfirewall/svcpoliciesandfirewall_test.go
tests/e2e/upgradecluster/upgradecluster_test.go
tests/e2e/validatecluster/validatecluster_test.go
tests/e2e/wasm/wasm_test.go

Render CNI dir config whenever vars are set
rke2 windows regression fix
Test RKE2 in Windows.
TODO on rke2 side.
https://github.com/rancher/rke2/issues/7793
```release-note
```

[release-1.29] Render CNI dir config whenever vars are set

---

go.mod
go.sum

Bump containerd for go-cni deadlock fix
Version bump / bugfix
Not currently reproducible with embedded flannel, does seem to affect other slower CNIs though.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```

Bump containerd for go-cni deadlock fix

---

go.mod
go.sum

Bump containerd for go-cni deadlock fix
Version bump / bugfix
Not currently reproducible with embedded flannel, does seem to affect other slower CNIs though.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```

[release-1.32] Bump containerd for go-cni deadlock fix

---

go.mod
go.sum

Bump containerd for go-cni deadlock fix
Version bump / bugfix
Not currently reproducible with embedded flannel, does seem to affect other slower CNIs though.
* https://github.com/rancher/rke2/issues/7808
* https://github.com/containerd/containerd/pull/11269
* https://github.com/containerd/go-cni/pull/126
```release-note
```

[release-1.31] Bump containerd for go-cni deadlock fix

---

.github/workflows/e2e.yaml
pkg/bootstrap/bootstrap.go
pkg/clientaccess/token.go
pkg/cluster/bootstrap.go
pkg/cluster/cluster.go
pkg/cluster/storage.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/etcd/etcd.go
pkg/server/handlers/handlers.go
pkg/server/handlers/secrets-encrypt.go
tests/docker/autoimport/autoimport_test.go
tests/docker/basics/basics_test.go
tests/docker/bootstraptoken/bootstraptoken_test.go
tests/docker/cacerts/cacerts_test.go
tests/docker/conformance/conformance_test.go
tests/docker/etcd/etcd_test.go
tests/docker/hardened/hardened_test.go
tests/docker/lazypull/lazypull_test.go
tests/docker/secretsencryption/secretsencryption_test.go
tests/docker/skew/skew_test.go
tests/docker/snapshotrestore/snapshotrestore_test.go
tests/docker/test-helpers.go
tests/docker/token/token_test.go
tests/docker/upgrade/upgrade_test.go

* Serve HTTP bootstrap data from datastore before disk
Fixes issue where CA rotation would fail on servers with join URL set due to using old data from disk on other server.
* Control-plane-only nodes try bootstrapping via etcd load-balancer if they have client certs, to avoid a dependency on the server URL
Fixes issue where control-plane-only nodes could not come up if the server they were joined against is not up, despite other servers being available.
bugfix
* https://github.com/k3s-io/k3s/issues/11233
* https://github.com/k3s-io/k3s/issues/11333
```release-note
```

Fix bootstrapping on non-init servers

---

pkg/agent/flannel/setup.go

This reverts commit 8643576985bb0863b42ae0eeb64cdd4e20953907.
Backport #11783
Issue: [#11797](https://github.com/k3s-io/k3s/issues/11797)

[Release 1.30] Revert "Add ability to pass configuration options to flannel backend"

---

pkg/cli/cmds/server.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/daemons/config/types.go
pkg/etcd/etcd_linux_test.go

Add periodic background snapshot reconcile
Interval is configurable with new etcd-snapshot-reconcile-interval flag
new feature
Start K3s with embedded etcd; note that snapshots are reconciled automatically at the configured interval - any files added/removed from disk/s3 are reflected in the ETCDSnapshotFiles present in the cluster
* https://github.com/k3s-io/k3s/issues/11817
```release-note
```

Add periodic background snapshot reconcile

---

tests/docker/skew/skew_test.go

- Backports are now in 1.31 and older, so we can reenable skew test in CI for master/release-1.32
CI is green
https://github.com/k3s-io/k3s/issues/11554
```release-note
```

Reenable skew test for 1.32/master

---

tests/e2e/rootless/rootless_test.go

- E2E Rootless test is flaky because AllPodsUp only says that "All current pods are ready" which on startup may not yet include Traefik and Metric server Deployments. Replace with `CheckDefaultDeployments` which is more reliable  and correct to what we consider "k3s ready".
Test fix
Rootless should fail less often
N/A
```release-note
```
Similar fix was applied to the E2E WASM test

Fix flaky rootless E2E test

---

go.mod
go.sum

Bump containerd to v2.0.4
Includes backported commit from https://github.com/containerd/containerd/pull/11576: https://github.com/k3s-io/containerd/commit/2879c0790c5c8e3a26e67f19e37a8c73d7ccf0ec
version bump
bugfix
check version
* https://github.com/k3s-io/k3s/issues/12002
```release-note
```

[release-1.31] Bump to containerd v2.0.4

---

scripts/test
tests/docker/basics/basics_test.go
tests/docker/bootstraptoken/bootstraptoken_test.go
tests/docker/cacerts/cacerts_test.go
tests/docker/conformance/conformance_test.go
tests/docker/etcd/etcd_test.go
tests/docker/lazypull/lazypull_test.go
tests/docker/skew/skew_test.go
tests/docker/test-helpers.go
tests/docker/upgrade/upgrade_test.go

- Updates image name transformation to be correct when more than one dash is present. 
- Bump timeouts for skew test, flaky on `arm` Drone CI, our slowest runner
- Ensure proper cleanup of Docker containers for all docker tests (currently only half had proper cleanup  checks). Should stop `arm` Drone runner from becoming unresponsive.
Testing fixes
CI is green
Its all testing
https://github.com/k3s-io/k3s/issues/11971
```release-note
```

Fix upgrade test container version

---

pkg/agent/cri/cri.go
pkg/agent/cri/cri_linux.go
pkg/agent/cri/cri_windows.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/cli/agent/agent.go
pkg/cli/cert/cert.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_linux_test.go
pkg/server/handlers/cert.go
pkg/server/server.go
pkg/util/api.go
tests/mock/executor.go
tests/unit.go

This PR eliminates the scattered creation of ready channels that are passed around via struct fields. Ready channels for all components started by the Executor are now exposed by the Executor, providing a consistent interface that different portions of the codebase can use to wait for components to be available.
* Add context to agent token validation error
Makes the error message nice when agents are retrying retrieval of cacerts from cluster
* Increase log output while waiting for apiserver ready.
We were never actually logging anything here, as we would always take the `result.Error()` path whenever the apiserver isn't ready - and log nothing.
* Move apiserver ready wait into common channel
Splits server startup into prepare/start phases. Server's agent is now started after server is …

Improve readiness polling on node startup

---

.drone.yml

- In light of dockerhubs reduced rate limits for users, we should consider dual publishing the k3s image to ghcr.io and dockerhub.
CI/Release
Ran by hand with `dereknola` replacing `k3s-io` on my personal k3s fork
```
DRONE_TAG=v1.32.2-ds1 drone exec --trusted --pipeline=amd64 --event tag --secret-file=/home/derek/tmp/secrets.txt --instance=drone-publish.k3s.io --include=ghcr-publish
```
See it at https://github.com/dereknola/k3s/pkgs/container/k3s
```release-note
The k3s image in now published to `ghcr.io` in addition to dockerhub. You can `docker pull ghcr.io/k3s-io/k3s:<TAG>` 
```

Publish k3s image to Github Container Registry

---

pkg/agent/cri/cri.go
pkg/agent/cri/cri_linux.go
pkg/agent/cri/cri_windows.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/cli/agent/agent.go
pkg/cli/cert/cert.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_linux_test.go
pkg/server/handlers/cert.go
pkg/server/server.go
pkg/util/api.go
tests/mock/executor.go
tests/unit.go

* **Backport https://github.com/k3s-io/k3s/pull/11878**
This PR eliminates the scattered creation of ready channels that are passed around via struct fields. Ready channels for all components started by the Executor are now exposed by the Executor, providing a consistent interface that different portions of the codebase can use to wait for components to be available.
* Add context to agent token validation error
Makes the error message nice when agents are retrying retrieval of cacerts from cluster
* Increase log output while waiting for apiserver ready.
We were never actually logging anything here, as we would always take the `result.Error()` path whenever the apiserver isn't ready - and log nothing.
* Move apiserver ready wait into common channel
Splits server startup into prepare/start …

[Release-1.32] Improve readiness polling on node startup

---

pkg/agent/cri/cri.go
pkg/agent/cri/cri_linux.go
pkg/agent/cri/cri_windows.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/cli/agent/agent.go
pkg/cli/cert/cert.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_linux_test.go
pkg/server/handlers/cert.go
pkg/server/server.go
pkg/util/api.go
tests/mock/executor.go
tests/unit.go

* **Backport https://github.com/k3s-io/k3s/pull/11878**
This PR eliminates the scattered creation of ready channels that are passed around via struct fields. Ready channels for all components started by the Executor are now exposed by the Executor, providing a consistent interface that different portions of the codebase can use to wait for components to be available.
* Add context to agent token validation error
Makes the error message nice when agents are retrying retrieval of cacerts from cluster
* Increase log output while waiting for apiserver ready.
We were never actually logging anything here, as we would always take the `result.Error()` path whenever the apiserver isn't ready - and log nothing.
* Move apiserver ready wait into common channel
Splits server startup into prepare/start …

[Release-1.30] Improve readiness polling on node startup

---

pkg/agent/cri/cri.go
pkg/agent/cri/cri_linux.go
pkg/agent/cri/cri_windows.go
pkg/agent/run.go
pkg/agent/tunnel/tunnel.go
pkg/cli/agent/agent.go
pkg/cli/cert/cert.go
pkg/cli/cmds/agent.go
pkg/cli/server/server.go
pkg/cluster/cluster.go
pkg/cluster/managed.go
pkg/cluster/managed/drivers.go
pkg/daemons/config/types.go
pkg/daemons/control/server.go
pkg/daemons/executor/embed.go
pkg/daemons/executor/etcd.go
pkg/daemons/executor/executor.go
pkg/etcd/etcd.go
pkg/etcd/etcd_linux_test.go
pkg/server/handlers/cert.go
pkg/server/server.go
pkg/util/api.go
tests/mock/executor.go
tests/unit.go

* **Backport https://github.com/k3s-io/k3s/pull/11878**
This PR eliminates the scattered creation of ready channels that are passed around via struct fields. Ready channels for all components started by the Executor are now exposed by the Executor, providing a consistent interface that different portions of the codebase can use to wait for components to be available.
* Add context to agent token validation error
Makes the error message nice when agents are retrying retrieval of cacerts from cluster
* Increase log output while waiting for apiserver ready.
We were never actually logging anything here, as we would always take the `result.Error()` path whenever the apiserver isn't ready - and log nothing.
* Move apiserver ready wait into common channel
Splits server startup into prepare/start …

[Release-1.31] Improve readiness polling on node startup

---

pkg/etcd/etcd_linux_test.go

Increase etcd shutdown delay to avoid `bind: address already in use` errors seen in CI. Also uses test TempDir to ensure dir is cleaned up between tests.
This was flaking noticeably in the backports of https://github.com/k3s-io/k3s/pull/12018 
CI
check CI
yes, is a test
* https://github.com/k3s-io/k3s/issues/12017
```release-note
```

[ci] Fix flakey etcd startup tests

---

pkg/etcd/etcd_linux_test.go

* *Backport https://github.com/k3s-io/k3s/pull/12046 - missed commit from https://github.com/k3s-io/k3s/pull/12042*
Increase etcd shutdown delay to avoid `bind: address already in use` errors seen in CI. Also uses test TempDir to ensure dir is cleaned up between tests.
This was flaking noticeably in the backports of https://github.com/k3s-io/k3s/pull/12018 
CI
check CI
yes, is a test
* https://github.com/k3s-io/k3s/issues/12039
```release-note
```

[release-1.32] Fix flakey etcd startup tests

---

pkg/cli/cmds/secrets_encrypt.go
pkg/cli/cmds/server.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/control/deps/deps.go
pkg/secretsencrypt/config.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/handlers/token.go
tests/docker/secretsencryption/secretsencryption_test.go

- Adds a new server configuration flag: `secrets-encryption-provider` with valuse of `aescbc` (default and original) and `secretbox`.
- Supports migration between key types. Only allowed with the newer `k3s secrets-encrypt rotate-keys` command. Not supported on the older (eventually will be deprecated) `prepare` `rotate` and `reencrypt` subcommands.
New Feature
Manually tested through various configurations:
NEW CLUSTER:
- Add `secrets-encryption: true` and `secrets-encryption-provider: secretbox` to the config.yaml
- Start the cluster
- Check `k3s secrets-encrypt status` you will see a new `XSalsa20-POLY1305` type as the active key
MIGRATING CLUSTER
- Add `secrets-encryption-provider: secretbox` to the config.yaml. `secrets-encryption` should already be there
- Restart all servers
- Run …

Add support for secretbox encryption provider with the `k3s secrets-encrypt` command

---

.drone.yml
Dockerfile.dapper
Dockerfile.local
Dockerfile.test

- Update gopls version
- Update go version used for `go test`
- Simplify E2E binary building, slightly faster (20-30s) E2E pipeline times
CI
E2E Drone still green
```release-note
```

Bump Drone E2E components

---

tests/docker/cacerts/cacerts_test.go
tests/docker/test-helpers.go

Cleanup anonymous volumes associated with the server and agent nodes for docker tests. Be double sure and cleanup the named volumes as well. 
Test/CI
Run the basic go docker test
`go test -v ./tests/docker/basics/basics_test.go -k3sImage=rancher/k3s:v1.32.3-k3s1-amd64`
Check the volumes left behind, should see no new volumes added
```
docker volume ls
```
All testing
https://github.com/k3s-io/k3s/issues/12068
```release-note
```

Cleanup anonymous and named volumes for docker tests

---

pkg/daemons/executor/executor.go
pkg/etcd/etcd.go

Addresses flakes in etcd CI due to the port still being in TIME_WAIT after the server is shut down between tests. Ref:
* https://github.com/etcd-io/etcd/pull/12702
* https://github.com/k3s-io/k3s/pull/12046
ci fix
Check CI
yes
* https://github.com/k3s-io/k3s/issues/12017
```release-note
```

Add ReusePort/ReuseAddr flags to etcd config

---

.github/workflows/install.yaml
.github/workflows/nightly-install.yaml
tests/e2e/splitserver/splitserver_test.go
tests/e2e/testutils.go

Add --no-tty flag to all `vagrant up` commands to silence the printing of box loading progress. Ref:
* https://github.com/hashicorp/vagrant/pull/11465
CI improvement
Check CI output, for example: https://github.com/k3s-io/k3s/actions/runs/14322117288/job/40140912631
yes
```release-note
```

Silence vagrant progress output

---

pkg/cli/cmds/secrets_encrypt.go
pkg/cli/cmds/server.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/control/deps/deps.go
pkg/secretsencrypt/config.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/handlers/token.go
tests/docker/secretsencryption/secretsencryption_test.go

Backport https://github.com/k3s-io/k3s/pull/12021
```release-note
Users can now configure secrets encryption to use `secretbox` provider by setting the `secrets-encryption-provider` flag.
```

[Release-1.30] Add support for secretbox encryption provider with the `k3s secrets-encrypt` command

---

pkg/cli/cmds/secrets_encrypt.go
pkg/cli/cmds/server.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/control/deps/deps.go
pkg/secretsencrypt/config.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/handlers/token.go
tests/docker/secretsencryption/secretsencryption_test.go

Backport https://github.com/k3s-io/k3s/pull/12021
```release-note
Users can now configure secrets encryption to use `secretbox` provider by setting the `secrets-encryption-provider` flag.
```

[Release-1.31] Add support for secretbox encryption provider with the `k3s secrets-encrypt` command

---

pkg/cli/cmds/secrets_encrypt.go
pkg/cli/cmds/server.go
pkg/cli/secretsencrypt/secrets_encrypt.go
pkg/cli/server/server.go
pkg/cluster/bootstrap.go
pkg/daemons/config/types.go
pkg/daemons/control/deps/deps.go
pkg/secretsencrypt/config.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/handlers/token.go
tests/docker/secretsencryption/secretsencryption_test.go

Backport https://github.com/k3s-io/k3s/pull/12021
```release-note
Users can now configure secrets encryption to use `secretbox` provider by setting the `secrets-encryption-provider` flag.
```

[Release-1.32] Add support for secretbox encryption provider with the `k3s secrets-encrypt` command

---

.github/workflows/install.yaml
.github/workflows/integration.yaml
pkg/agent/cri/cri.go
tests/integration/startup/testdata/agnhost.yaml

* Move Windows test out of Install Script workflow
Placing this in the install script workflow, which only runs when specific files are changed, was preventing it from being run on code changes.
In addition to moving this into the integration workflow, fix codecov for Windows and upload data after running a test pod.
* Fix containerd socket path on Windows
This was broken by https://github.com/k3s-io/k3s/pull/11878 but it went undetected because the windows test wasn't getting run
CI
Check CI
yes
* https://github.com/k3s-io/k3s/issues/11896
* https://github.com/k3s-io/k3s/issues/11865
```release-note
```

Move Windows test out of Install Script workflow

---

pkg/cli/cert/cert.go

If there is a problem when running "k3s certificate check" and getting information from the certificate, it is impossible to understand what is going on. This PR prints  the error when using `--debug`. I thought about printing it always as an error but in that case, there will always be error lines because the current algorithm reads over all files in the directory, keys included.
Imagine running k3s without being root
Before (no error & no output):
```
azureuser@terraform-mbuil-vm0:~$ k3s certificate check --debug
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/f4fcc0d3214aa5b93214da39de2fc1bde3f8cdabcdd9c245c2599ce46ce3b78a 
DEBU[0000] Running /var/lib/rancher/k3s/data/f4fcc0d3214aa5b93214da39de2fc1bde3f8cdabcdd9c245c2599ce46ce3b78a/bin/k3s-certificate [k3s certificate check --debug] …
```

Add error in certificate check

---

pkg/server/handlers/handlers.go

This uses the correct key when signing a key for the kubelet.
I assume this was a mistake when copying and the kubelet key should have been used here.
This bug was introduced in #11471.
Bugfix
I'm actually not sure, I noticed this when looking through the code, but I'm not familiar with K3s enough to fully understand the impact of this change.
I don't think a test is necessary.
* https://github.com/k3s-io/k3s/issues/12012
```release-note
NONE
```

fix: Use proper key when signing kubelet certificate

---

.drone.yml
tests/e2e/scripts/cleanup_vms.sh
tests/e2e/scripts/drone_registries.sh
tests/e2e/scripts/registry.sh

An updated take on https://github.com/k3s-io/k3s/pull/11448:
- Run specific tests in parallel blocks in Drone, 2 groups (validatecluster, splitserver + upgradecluster)
- Be explicit about VM cleanup, removing any similar named VMs before a E2E test runs. This works because we continue to operate with only 1 amd64 pipeline active at any time. This should better handle edge cases by being more agressive on VM cleanup than the previous 2H time limited system.
- Running only 2 E2E tests at one time should still fit within the IO constraints of the Drone runner
- Rework the registries in E2E tests to work more like the old docker tests, registries end up as long running containers on the drone host, enabling better caching over multiple reruns of similar e2e tests.
| Before | After |
| - | - | …

Split E2E Drone pipeline into matrix

---

.drone.yml
.github/workflows/unitcoverage.yaml

- Move the small `test-mods` pipeline from Drone to GHA, set as a "Unit Test" because it really what it us, we don't need to build K3s, and it just a sanity check that we match correct use the k3s-io fork of k8s dependencies.
- Don't run `amd64` and `arm64` Drone pipelines on PR anymore. As you can see from [this example run](https://drone-pr.k3s.io/k3s-io/k3s/11033), these pipelines don't run any tests anymore on PR, they just build the binary and exit. Our new CI in GHA covers builds and test on both these platforms.
| OLD | NEW |
|  - | - |
| ![image](https://github.com/user-attachments/assets/edb89162-d1ea-49ab-9a1d-8f3b5bd27d25) |  ![image](https://github.com/user-attachments/assets/99bd9794-c680-4de7-88a8-fa66863fe365)|
CI
New CI is green …

Migrate test-mods from Drone to GHA

---

.drone.yml
tests/docker/cacerts/cacerts_test.go

During backports of https://github.com/k3s-io/k3s/pull/12069 and https://github.com/k3s-io/k3s/pull/12086, two additional commits were added to cover issues found at scale with the CI. This "forward-ports" these two commits to master.
CI/Testing
No more k3s-pause volumes left behind on Drone arm runner
E2E Drone tests past more consistently
```release-note
```

[master] Stagger E2E Drone and Delete k3s pause in cacerts test

---

pkg/daemons/agent/agent.go
pkg/daemons/agent/agent_linux.go
pkg/daemons/agent/agent_windows.go

* Set kubelet read-only-port via CLI flag
Set kubelet read-only-port via cli flag due to inability to marshal the config struct with value set to 0.
bugfix
* https://github.com/k3s-io/k3s/issues/12164
```release-note
```

Set kubelet read-only-port via CLI flag

---

tests/docker/skew/skew_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/rootless/rootless_test.go
tests/e2e/startup/startup_test.go

Our top three E2E test failures are: `startup`, `rootless`, and `externalIP`:
- Add better error logging around why `kubectl top node` is failing on Rootless and Startup. Hopefully this help root cause this inconsistent failure.
- Better handling around clientIP checks in ExternalIP. Removed duplicate calls and check more edge cases to prevent the follow on error of ip.IPv4 being empty (which cause curl to fail)
Our top docker test failure is `skew`:
- Increase deployment timeout on the 1 older server and 2 newer servers from 180s to 240s. This particular scenario seems to take a bit more time than all same version servers.
Tests
CI still green. Hopefully see a decrease in test flakiness over the next several weeks. 
All testing
N/A
```release-note
```

Address top flaky tests

---

pkg/agent/https/https.go
pkg/server/auth/auth.go
pkg/server/handlers/router.go
pkg/spegel/bootstrap.go
pkg/spegel/spegel.go

* Fix handler panic when bootstrapper returned empty peer list
Panic gets rescued by the http server, and was only visible when running in debug mode, but should be handled properly.
Found when load testing master following merge of https://github.com/k3s-io/k3s/pull/12154
<details><summary>Stack Trace</summary>
```
INFO[0026] Cluster-Http-Server 2025/04/18 07:36:18 http: panic serving 172.17.0.10:54992: runtime error: invalid memory address or nil pointer dereference
INFO[0026] goroutine 25337 [running]:
INFO[0026] net/http.(*conn).serve.func1()
INFO[0026] 	/usr/local/go/src/net/http/server.go:1947 +0xbe
INFO[0026] panic({0x5f6a3a0?, 0xb5ae5e0?})
INFO[0026] 	/usr/local/go/src/runtime/panic.go:785 +0x132
INFO[0026] github.com/k3s-io/k3s/pkg/spegel.(*Config).Start.(*Config).peerInfo.func13( …
```

Fix handler panic when bootstrapper returns empty peer list

---

pkg/agent/https/https.go
pkg/server/auth/auth.go
pkg/server/handlers/router.go
pkg/spegel/bootstrap.go
pkg/spegel/spegel.go

* Fix handler panic when bootstrapper returned empty peer list
Panic gets rescued by the http server, and was only visible when running in debug mode, but should be handled properly.
Found when load testing master following merge of https://github.com/k3s-io/k3s/pull/12154
<details><summary>Stack Trace</summary>
```
INFO[0026] Cluster-Http-Server 2025/04/18 07:36:18 http: panic serving 172.17.0.10:54992: runtime error: invalid memory address or nil pointer dereference
INFO[0026] goroutine 25337 [running]:
INFO[0026] net/http.(*conn).serve.func1()
INFO[0026] 	/usr/local/go/src/net/http/server.go:1947 +0xbe
INFO[0026] panic({0x5f6a3a0?, 0xb5ae5e0?})
INFO[0026] 	/usr/local/go/src/runtime/panic.go:785 +0x132
INFO[0026] github.com/k3s-io/k3s/pkg/spegel.(*Config).Start.(*Config).peerInfo.func13( …
```

[release-1.32] Fix handler panic when bootstrapper returns empty peer list

---

pkg/agent/https/https.go
pkg/server/auth/auth.go
pkg/server/handlers/router.go
pkg/spegel/bootstrap.go
pkg/spegel/spegel.go

* Fix handler panic when bootstrapper returned empty peer list
Panic gets rescued by the http server, and was only visible when running in debug mode, but should be handled properly.
Found when load testing master following merge of https://github.com/k3s-io/k3s/pull/12154
<details><summary>Stack Trace</summary>
```
INFO[0026] Cluster-Http-Server 2025/04/18 07:36:18 http: panic serving 172.17.0.10:54992: runtime error: invalid memory address or nil pointer dereference
INFO[0026] goroutine 25337 [running]:
INFO[0026] net/http.(*conn).serve.func1()
INFO[0026] 	/usr/local/go/src/net/http/server.go:1947 +0xbe
INFO[0026] panic({0x5f6a3a0?, 0xb5ae5e0?})
INFO[0026] 	/usr/local/go/src/runtime/panic.go:785 +0x132
INFO[0026] github.com/k3s-io/k3s/pkg/spegel.(*Config).Start.(*Config).peerInfo.func13( …
```

[release-1.30] Fix handler panic when bootstrapper returns empty peer list

---

pkg/agent/https/https.go
pkg/server/auth/auth.go
pkg/server/handlers/router.go
pkg/spegel/bootstrap.go
pkg/spegel/spegel.go

* Fix handler panic when bootstrapper returned empty peer list
Panic gets rescued by the http server, and was only visible when running in debug mode, but should be handled properly.
Found when load testing master following merge of https://github.com/k3s-io/k3s/pull/12154
<details><summary>Stack Trace</summary>
```
INFO[0026] Cluster-Http-Server 2025/04/18 07:36:18 http: panic serving 172.17.0.10:54992: runtime error: invalid memory address or nil pointer dereference
INFO[0026] goroutine 25337 [running]:
INFO[0026] net/http.(*conn).serve.func1()
INFO[0026] 	/usr/local/go/src/net/http/server.go:1947 +0xbe
INFO[0026] panic({0x5f6a3a0?, 0xb5ae5e0?})
INFO[0026] 	/usr/local/go/src/runtime/panic.go:785 +0x132
INFO[0026] github.com/k3s-io/k3s/pkg/spegel.(*Config).Start.(*Config).peerInfo.func13( …
```

[release-1.29] Fix handler panic when bootstrapper returns empty peer list

---

scripts/test

See [failures on the nightly runs ](https://drone-publish.k3s.io/k3s-io/k3s/4365/1/3)around 
```
sonobuoy run --config=scripts/sonobuoy-config.json --plugin-env=e2e.E2E_USE_GO_RUNNER=true --kubernetes-version= --wait=90 '--e2e-focus=\[Serial\].*\[Conformance\]'
[SERIAL-mysql] Error: invalid argument "" for "--kubernetes-version" flag: version "" is invalid: Malformed version: 
```
At some point the VERSION_K8S stopped getting passed correctly down the script layers to the actual sonobuoy call. 
We just need to properly export this so its available to the subprocess.
Manually run locally and SERIAL and PARALLEL tests now correctly launch.
```release-note
```
We can't move forward with GHA migration until we are in a stable place with the old …

Fix sonobuoy conformance testing

---

.drone.yml

- Fix specific for release in drone
- Fix
```release-note
```

Remove ghcr from drone

---

tests/e2e/rootless/rootless_test.go
tests/e2e/startup/startup_test.go

Follow on to https://github.com/k3s-io/k3s/pull/12163, both `rootless` and `startup` E2E commonly fail around calls to metrics (either pods or nodes). Implement longer timeouts and pull more logs in the event of this failure to help rootcause this flakiness. 
Testing improvements
CI is Green (But even if its red, we get more logs :)
N/A
```release-note
```

Better logging on E2E tests around metrics availability

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Add anonymous-auth to flags gated on empty authorization-config value
Also warn if default flags are not set due to user provided config
bugfix
See issue
yes
* https://github.com/k3s-io/k3s/issues/12245
```release-note
```

Add anonymous-auth to flags gated on empty authorization-config value

---

pkg/agent/containerd/containerd.go
pkg/agent/containerd/watcher.go

Normally K3s will import all tarballs in the image dir on startup, and re-import any tarballs that are created or changed while it is running.
This change allows users to opt into only importing tarballs that have changed since they were last imported, even across restarts.
This behavior is opted into by touching a `.cache.json` file in the images dir. This file is used to track across restarts the size and mtime of the image files when they are imported.
enhancement
1. `mkdir -p /var/lib/rancher/k3s/agent/images/;  touch /var/lib/rancher/k3s/agent/images/.cache.json`
2. Copy images into images dir
3. Start k3s; note that images are imported
4. Restart k3s; note that images are NOT imported again.
5. Touch image tarball or replace it with a different file; note that it is imported again. …

Add support for conditional image tarball imports

---

scripts/test
tests/docker/skew/skew_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/rootless/rootless_test.go
tests/e2e/startup/startup_test.go

Backports the following PRs:
- https://github.com/k3s-io/k3s/pull/12163
- https://github.com/k3s-io/k3s/pull/12214
- https://github.com/k3s-io/k3s/pull/12198
Testing fixes
CI still green (with more logs)
```release-note
```

[Release-1.32] Testing backports for 2025 May

---

scripts/test
tests/docker/skew/skew_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/rootless/rootless_test.go
tests/e2e/startup/startup_test.go

Backports the following PRs:
- https://github.com/k3s-io/k3s/pull/12163
- https://github.com/k3s-io/k3s/pull/12214
- https://github.com/k3s-io/k3s/pull/12198
Testing fixes
CI still green (with more logs)
```release-note
```

[Release-1.31] Testing backports for 2025 May

---

scripts/test
tests/docker/skew/skew_test.go
tests/e2e/externalip/externalip_test.go
tests/e2e/rootless/rootless_test.go
tests/e2e/startup/startup_test.go

Backports the following PRs:
- https://github.com/k3s-io/k3s/pull/12163
- https://github.com/k3s-io/k3s/pull/12214
- https://github.com/k3s-io/k3s/pull/12198
Testing fixes
CI still green (with more logs)
```release-note
```

[Release-1.30] Testing backports for 2025 May

---

go.mod
pkg/certmonitor/certmonitor.go
pkg/cli/cert/cert.go
pkg/cli/cmds/certs.go
pkg/util/cert.go

This PR implements a certificate check feature that:
- Adds `USAGES` field to distinguish between `CertSign`/`ServerAuth`/`ClientAuth`
- Changes `CERTIFICATE` column to `FILENAME` for clarity
- Supports multiple output formats (text, table, json, yaml)
New Feature
``` sh
FILENAME              SUBJECT                    USAGES       EXPIRES                  RESIDUAL TIME   STATUS
--------              -------                    ------       -------                  -------------   ------
client-kubelet.crt    system:node:ubuntu         ClientAuth   May 07, 2026 02:31 UTC   1 year          OK
client-kubelet.crt    k3s-client-ca@1746585073   CertSign     May 05, 2035 02:31 UTC   10 years        OK
serving-kubelet.crt   ubuntu                     ServerAuth   May 07, 2026 02:31 UTC   1 year …
```

Implement certificate check with file-oriented view and usage types

---

pkg/daemons/config/types.go
pkg/daemons/control/deps/deps.go
pkg/daemons/control/server.go
pkg/util/services/services.go
pkg/util/services/services_test.go

- Generate Serving Certs for kube-scheduler and kube-controller-manager
- New Feature
- Run k3s
- Go in the tls folder
```bash
cd /var/lib/rancher/k3s/server/tls
```
- Verify if the cert are signed by CA
```bash
root@test:/var/lib/rancher/k3s/server/tls# openssl verify -CAfile server-ca.crt $PWD/kube-controller-manager/kube-controller-manager.crt
/var/lib/rancher/k3s/server/tls/kube-controller-manager/kube-controller-manager.crt: OK
root@test:/var/lib/rancher/k3s/server/tls# openssl verify -CAfile server-ca.crt $PWD/kube-scheduler/kube-scheduler.crt
/var/lib/rancher/k3s/server/tls/kube-scheduler/kube-scheduler.crt: OK
```
- https://github.com/k3s-io/k3s/issues/12172
```release-note
```

Add generation for kube-scheduler and kube-controller-manager certs

---

pkg/agent/flannel/flannel.go
pkg/agent/flannel/setup.go
pkg/agent/flannel/setup_test.go

Move the `ipv4` and `ipv6` constants to their own constant declaration.  This ensures that the `iota` expression for the `ipv4` constant evaluates to 0, not some arbitrary value.  (`iota` evaluates to N for the Nth constant in the constant declaration; see <https://go.dev/ref/spec#Iota>.)  This is also more idiomatic, which improves readability.
Also switch from incremental integers to bit flags, and use bitwise operators for checking.  This is more idiomatic (the integer is treated like a set of booleans), it avoids some code duplication, and it is necessary to avoid ambiguity.  Consider the following:
const (
ipv4 = iota
ipv6
)
In the above, `ipv4` would have the value 0 and `ipv6` would have the value 1.  This would make it impossible to distinguish an IPv6-only stack from a dual-stack …

flannel: Use custom type for network mode (IPv4, IPv6, dual-stack)

---

docs/contrib/development.md

The Vagrantfile was removed from the repository in 2022 (PR #6395), 
but the development documentation still referenced it. This PR updates the documentation to:
- Remove outdated Vagrantfile references
- Clarify that Docker with Dapper is the recommended build environment for non-Linux systems
Documentation

docs: Remove references to deprecated Vagrantfile

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Bugfix
Yes
* https://github.com/k3s-io/k3s/issues/12245
```release-note
```

Fix authorization-config/authentication-config handling

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Bugfix
Yes
* https://github.com/k3s-io/k3s/issues/12276
```release-note
```

[release-1.33] Fix authorization-config/authentication-config handling

---

pkg/cli/server/server.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/server.go

bugfix
* https://github.com/k3s-io/k3s/issues/12339
* https://github.com/rancher/rke2/issues/8236
```release-note
```

Fix secretsencrypt race conditions

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Bugfix
Yes
* https://github.com/k3s-io/k3s/issues/12279
```release-note
```

[release-1.30] Fix authorization-config/authentication-config handling

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Bugfix
Yes
* https://github.com/k3s-io/k3s/issues/12277
```release-note
```

[release-1.32] Fix authorization-config/authentication-config handling

---

pkg/daemons/control/server.go
pkg/daemons/control/server_test.go

Bugfix
Yes
* https://github.com/k3s-io/k3s/issues/12278
```release-note
```

[release-1.31] Fix authorization-config/authentication-config handling

---

pkg/cli/server/server.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/server.go

bugfix
* https://github.com/k3s-io/k3s/issues/12340
* https://github.com/rancher/rke2/issues/8249
```release-note
```

[release-1.33] Fix secretsencrypt race conditions

---

pkg/cli/server/server.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/server.go

bugfix
* https://github.com/k3s-io/k3s/issues/12341
* https://github.com/rancher/rke2/issues/8250
```release-note
```

[release-1.32] Fix secretsencrypt race conditions

---

pkg/cli/server/server.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/server.go

bugfix
* https://github.com/k3s-io/k3s/issues/12342
* https://github.com/rancher/rke2/issues/8251
```release-note
```

[release-1.31] Fix secretsencrypt race conditions

---

pkg/cli/server/server.go
pkg/server/handlers/secrets-encrypt.go
pkg/server/server.go

bugfix
* https://github.com/k3s-io/k3s/issues/12343
* https://github.com/rancher/rke2/issues/8252
```release-note
```

[release-1.30] Fix secretsencrypt race conditions

---

pkg/secretsencrypt/config.go

Increases the timeout for encryption config reload from 60 seconds to 120 seconds during secrets encryption key rotation to ensure sufficient time for the apiserver to reload the configuration.
Bugfix
https://github.com/k3s-io/k3s/issues/12373

Fix secrets encryption rotation timeout causing false failures

---

scripts/test
tests/docker/test-helpers

- Convert remaining NIGHTLY (not tag) sonobuoy conformance tests to golang test framework
- Implement similar `[LABEL]` prefix to test output to match existing sonobuoy tests
Tested manually, will need to wait for nightly cron in Drone CI
```release-note
```
Future PR will convert the tag conformance testing found [here](https://github.com/k3s-io/k3s/blob/master/scripts/test#L60-L66) to the new golang framework, once nightly conformance has proven to be stable.

Convert all nightly conformance to golang test framework

---

docs/adrs/multus.md

I worked for a while in the integration of k3s and Multus but it was pretty complicated. This ADR tries to explain what was tried and why I finally gave up
New feature
```release-note
```

Add ADR about failed multus integration

---

pkg/etcd/etcd.go
tests/e2e/rootless/rootless_test.go
tests/e2e/scripts/setup_rootless.sh

* Fix sqlite-etcd migration
Forgot to add new config to temporary kine in #12293
* Fix rootless e2e flake
Rootless test was restarting the service unnecessarily, which caused flakiness.
bugfix
Needs a test
* https://github.com/k3s-io/k3s/issues/12478
```release-note
```

Fix sqlite-etcd migration

---

tests/e2e/startup/startup_test.go
tests/e2e/testutils.go

This PR adds a new e2e test to verify SQLite to etcd datastore migration functionality. The test:
1. Starts K3s with SQLite datastore
2. Creates test resources to verify data persistence
3. Migrates to etcd datastore
4. Verifies all nodes, pods, and resources remain functional after migration
New Feature
https://github.com/k3s-io/k3s/issues/12507
```release-note
NONE
```

Add etcdmigration e2e test

---

.clomonitor.yml

Add .clomonitor.yml file so we can exclude the Artifact Hub check and others in the future
https://clomonitor.io/projects/cncf/k3s
https://clomonitor.io/docs/topics/checks/#artifact-hub-badge
https://clomonitor.io/docs/topics/checks/#exemptions
https://github.com/k3s-io/k3s/issues/12090

Add .clomonitor.yml file so we can exclude the Artifact Hub check

---

pkg/cli/cmds/etcd_snapshot.go

Add a description of the command etcd-snapshot. It's currently the only command which has no description:
Love to etcd-snapshot
Run `k3s` and see the help description
https://github.com/k3s-io/k3s/issues/12558
```release-note
```

Add usage description for etcd-snapshot

---

.github/workflows/codeql.yml
pkg/authenticator/hash/scrypt_test.go

- Adds a basic fuzz test on the `VerifyHash` function
- Enables CodeQL static code analysis on our GitHub Actions 
New Unit test
CI Still green
N/A
```release-note
```

Add basic fuzz test + Enable codeql on GHA

---

cmd/completion/main.go
cmd/k3s/main.go
cmd/server/main.go
main.go
pkg/cli/cmds/completion.go
pkg/cli/completion/completion.go

- better structure for shell completion command, this new structure for this command is to avoid unnecessary problems specially related to verify input from the user
```bash
k3s completion --help
```
```bash
k3s completion bash --help
```
```bash
k3s completion zsh --help
```
- Fix
- you can see that the two of them are separated commands by
```bash
k3s completion --help
```
- the verification to test if it's working as expected is
```bash
k3s completion bash -i
```
- and then
```bash
source ~/.bashrc
```
- the issue that came to that was from rke2, since rke2 uses the same structure for shell completion as k3s
https://github.com/rancher/rke2/issues/8495
```release-note
k3s completion shell command will now be separate to specific subcommands for bash and zsh
```

Refac shell completion to a better command structure

---

cmd/completion/main.go
cmd/k3s/main.go
cmd/server/main.go
main.go
pkg/cli/cmds/completion.go
pkg/cli/completion/completion.go

- better structure for shell completion command, this new structure for this command is to avoid unnecessary problems specially related to verify input from the user
```bash
k3s completion --help
```
```bash
k3s completion bash --help
```
```bash
k3s completion zsh --help
```
- Fix
- you can see that the two of them are separated commands by
```bash
k3s completion --help
```
- the verification to test if it's working as expected is
```bash
k3s completion bash -i
```
- and then
```bash
source ~/.bashrc
```
```release-note
k3s completion shell command will now be separate to specific subcommands for bash and zsh
```

[Release-1.32] Refac shell completion to a better command structure

---

cmd/completion/main.go
cmd/k3s/main.go
cmd/server/main.go
main.go
pkg/cli/cmds/completion.go
pkg/cli/completion/completion.go

- better structure for shell completion command, this new structure for this command is to avoid unnecessary problems specially related to verify input from the user
```bash
k3s completion --help
```
```bash
k3s completion bash --help
```
```bash
k3s completion zsh --help
```
- Fix
- you can see that the two of them are separated commands by
```bash
k3s completion --help
```
- the verification to test if it's working as expected is
```bash
k3s completion bash -i
```
- and then
```bash
source ~/.bashrc
```
```release-note
k3s completion shell command will now be separate to specific subcommands for bash and zsh
```

[Release-1.33] Refac shell completion to a better command structure

---

go.mod
go.sum

Adds backports of 
* containerd/containerd#11588
* containerd/containerd#12053
version bump
* check version
* see linked issues
* https://github.com/rancher/rancher/issues/50823
* https://github.com/k3s-io/k3s/issues/12561
```release-note
```

Bump containerd to v2.0.5-k3s2

---

manifests/metrics-server/metrics-server-deployment.yaml
scripts/airgap/image-list.txt

Backport: https://github.com/k3s-io/k3s/pull/12726
Issue: https://github.com/k3s-io/k3s/issues/12738

[Release-1.33] - Bump metrics-server to v0.8.0

---

manifests/metrics-server/metrics-server-deployment.yaml
scripts/airgap/image-list.txt

Backport: https://github.com/k3s-io/k3s/pull/12726
Issue: https://github.com/k3s-io/k3s/issues/12739

[Release-1.32] - Bump metrics-server to v0.8.0

---

manifests/metrics-server/metrics-server-deployment.yaml
scripts/airgap/image-list.txt

Backport: https://github.com/k3s-io/k3s/pull/12726
Issue: https://github.com/k3s-io/k3s/issues/12740

[Release-1.31] - Bump metrics-server to v0.8.0

---

pkg/certmonitor/certmonitor.go

Follow up to
* https://github.com/k3s-io/k3s/pull/12645
* https://github.com/k3s-io/k3s/pull/12744
Ensure that cert checks don't run until after the apiserver is ready to receive events
enhancement
Check for event on startup, when all certs are OK.
* https://github.com/k3s-io/k3s/issues/12646
```release-note
```

[release-1.33] Fix cert startup check events

---

pkg/certmonitor/certmonitor.go

Follow up to
* https://github.com/k3s-io/k3s/pull/12645
* https://github.com/k3s-io/k3s/pull/12744
Ensure that cert checks don't run until after the apiserver is ready to receive events
enhancement
Check for event on startup, when all certs are OK.
* https://github.com/k3s-io/k3s/issues/12648
```release-note
```

[release-1.31] Fix cert startup check events

---

pkg/agent/config/config.go
pkg/agent/cridockerd/cridockerd.go
pkg/daemons/config/types.go

Wire cri-dockerd `--log-level=debug` up to k3s `--debug` flag
Fixes issue caused by cri-dockerd reseting the logrus log-level during startup.
Bugfix
* https://github.com/k3s-io/k3s/issues/12749
```release-note
```

Wire cri-dockerd `--log-level=debug` up to k3s `--debug` flag

---

pkg/server/context.go
pkg/server/server.go

Retry CRD creation in case of conflict
Also cleans up some of the `server.Context` factory creation stuff to eliminate unused code paths and avoid registering the Helm controller when helm is disabled.
As of fe465cc83253fbc9139418f8a2a6254d24af1888 we no longer call `NewContext` outside `pkg/server`, so the `isServer` bool flag to use the supervisor kubeconfig and create an event recorder is unnecessary.
bugfix
tech debt
See linked issue - this is difficult to reproduce due to tight timing; multiple control-plane nodes need to be at the exact same spot in the startup sequence at the exact same time.
* https://github.com/k3s-io/k3s/issues/12813
```release-note
```

 Retry CRD creation in case of conflict

---

pkg/cli/server/server.go

Wire up kine metrics
Set metrics registrar in kine datastore config so that metrics are registered to the correct registry.
enhancement
`kubectl get --raw /metrics | grep kine`
* https://github.com/k3s-io/k3s/issues/12595
```release-note
```

Wire up kine metrics

---

pkg/etcd/etcd.go

Fix for incorrect error used in
* https://github.com/k3s-io/k3s/pull/12815
Error is deadline exceeded, not cancelled.
bugfix
Yes, error was seen in CI tests
* https://github.com/k3s-io/k3s/issues/12794
```release-note
```

Fix etcd join timeout handling

---

go.mod

Add opencontainers/runc pin
We no longer depend on this as a module any more, but need to keep it pinned for build-time version selection.
version bump/pin
check runc version
* https://github.com/k3s-io/k3s/issues/12865
```release-note
```

Add opencontainers/runc pin to v1.3.1

---

manifests/coredns.yaml

Default `forward . /etc/resolv.conf` after override imports to ensure we'll be able to partially and fully override the `forward` statement.
Bugfix #12979 
See #12979 
NA
* #12979 
```release-note
NONE
```

fix: default forward after override imports

---

pkg/server/handlers/token.go

Fix ability to rotate server token to an invalid format
bugfix
* https://github.com/k3s-io/k3s/issues/12982
```release-note
```
We should probably also tweak the docs to better note that server token rotation cannot use agent bootstrap tokens...

Fix ability to rotate server token to an invalid format
